// content/astronomy_amateur.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: constellations, scope
//
// NOTE: Separate from `astronomy` (the hard science). This subject is the
// amateur / stargazing angle — constellations, equipment, and observing.

window.CONTENT = window.CONTENT || {};
window.CONTENT.astronomy_amateur = {
  subjectId: 'astronomy_amateur',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    constellations: {
      id: 'constellations',
      name: 'Constellations',
      level: 'Beginner',
      dek: 'Eighty-eight patterns older than the pyramids — and the seasonal clock that let half the civilizations we remember know when to plant.',
      readTime: '11 min',

      sections: ['An older sky than any of ours', 'The IAU\'s 88', 'Seasonal constellations', 'Star-hopping', 'Light pollution and what the dark still shows'],
      body: [
        { type: 'lead', text: 'On a winter night in Mesopotamia around 3,200 BCE, a Sumerian astronomer-priest looked up at a pattern of seven stars near the celestial equator and drew a bull. Four and a half thousand years later that same pattern is still called Taurus. The names change — Greek catalogues replacing Babylonian, Latin replacing Greek, IAU abbreviations layered over the Latin — but the patterns are remarkably persistent. Human eyes organize the same set of stars into the same shapes, across cultures and millennia, because nothing else can lend memory to the sky.' },
        { type: 'figure', src: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Orion_constellation_map.svg',
          alt: 'Map of the constellation Orion',
          caption: 'Orion, as drawn in the IAU constellation map. The three stars of the belt and the Orion Nebula below are the best-known winter objects in the northern sky.',
          credit: 'IAU and Sky &amp; Telescope · Wikimedia Commons · CC BY 3.0' },
        { type: 'h2', text: 'The IAU\'s eighty-eight' },
        { type: 'p', text: 'In 1922 the International Astronomical Union, meeting in Rome, adopted a list of 88 constellations that partitions the entire celestial sphere. The Belgian astronomer Eugène Delporte drew the boundaries, which were published in 1930 and have not been changed since. Forty-eight of the 88 come from Ptolemy\'s second-century Almagest and trace back through Greek to Babylonian sky catalogues. Forty were added by European astronomers of the sixteenth through eighteenth centuries to fill the southern gaps the Mediterranean sailors could not see. Every constellation now has a three-letter IAU code — Ori for Orion, UMa for Ursa Major — that serves roughly the same function as the state postal abbreviations on a weather map.' },
        { type: 'h2', text: 'The seasonal clock' },
        { type: 'p', text: 'The night sky rotates because the Earth does, and it changes month by month because the Earth is also moving around the Sun. The constellations visible after dinner in January — Orion, Taurus, Canis Major, Gemini — are invisible in July, because they lie in the same part of the sky as the Sun in July. Learn six winter, six summer, and six spring and fall constellations, and you can name any overhead star in the mid-northern sky within a minute. The classical version of this knowledge, carried by every Mediterranean navigator from the Phoenicians to Columbus, is how you found north before a compass.' },
        { type: 'h2', text: 'Star-hopping' },
        { type: 'p', text: 'The practical skill of amateur astronomy is star-hopping — using the bright, memorable constellations as signposts to find the dimmer things that matter. The pointer stars of the Big Dipper find Polaris. Orion\'s belt leads down-left to Sirius and up-right to Aldebaran. The arc of the Dipper\'s handle, extended, "arcs to Arcturus and speeds to Spica." These chains are memorized by every working amateur and they let you find the Andromeda Galaxy, the Pleiades, the Orion Nebula, and a hundred other objects with nothing more than a pair of binoculars and a planisphere.' },
        { type: 'callout', text: 'Red light only. Once your eyes have adapted to dark — twenty to thirty minutes — a single glance at a white phone screen resets the process. A red-filtered flashlight (or a phone in red-screen mode) keeps your pupils wide and preserves the faint stars you came out to see.' },
        { type: 'h2', text: 'What the city still shows' },
        { type: 'p', text: 'Nine out of ten people on Earth now live under a sky so light-polluted they cannot see the Milky Way. A Manhattan rooftop on a clear night shows fewer than fifty stars; a Bortle Class 1 site in rural Utah shows about 4,500. But the bright constellations — Orion, Ursa Major, Cassiopeia, Scorpius — cut through all but the worst skyglow, and the planets are unaffected. A city beginner can learn the sky; the rural sky becomes the reward. DarkSky International tracks protected sites, and the U.S. National Park Service operates more than thirty International Dark Sky Parks where the Milky Way returns at full strength.' },
      ],

      keyTerms: ['asterism', 'celestial sphere', 'ecliptic', 'zodiac', 'magnitude', 'planisphere', 'Bortle scale', 'circumpolar', 'IAU boundary'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@AstroBackyard',
            title: 'AstroBackyard — full channel (Trevor Jones)',
            channel: 'AstroBackyard', duration: 'variable',
            why: 'Trevor Jones\'s backyard astronomy videos are the best general-purpose amateur-astronomy series in English. Strong on the beginner arc from naked eye through scope.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@LearntheSky',
            title: 'Learn the Sky — full channel',
            channel: 'Learn the Sky', duration: 'variable',
            why: 'Janine Myszka\'s weekly "What\'s in the sky this week" videos are the calmest teacher available for learning the seasonal constellations.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@EdTingsAstronomy',
            title: 'Ed Ting\'s Astronomy — full channel',
            channel: 'Ed Ting', duration: 'variable',
            why: 'Ed Ting reviews every major amateur telescope and eyepiece; his beginner-sky videos are the practical companion to the gear reviews.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@ScottAstronomy',
            title: 'Scott Astronomy / Cosmic Pursuits',
            channel: 'Scott Astronomy', duration: 'variable',
            why: 'Brian Ventrudo\'s Cosmic Pursuits and its companion channel. Especially good on the Messier catalog and seasonal deep-sky targets.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@crashcourseastronomy',
            title: 'Crash Course Astronomy (Phil Plait)',
            channel: 'Crash Course', duration: 'variable',
            why: 'Phil Plait\'s 46-episode Crash Course series. Broader than constellations, but the naked-eye and night-sky episodes are the right starting ground.' },
        ],
        books: [
          { title: 'Turn Left at Orion',
            author: 'Guy Consolmagno and Dan Davis', year: 2018,
            url: '',
            why: 'The standard introduction to amateur telescopic observing — fifth edition, in print continuously since 1989. Guy Consolmagno is a Jesuit astronomer who directs the Vatican Observatory; the book is authoritative and warm.' },
          { title: 'NightWatch: A Practical Guide to Viewing the Universe',
            author: 'Terence Dickinson', year: 2006,
            url: '',
            why: 'The other classic. Large-format, seasonal star charts, equipment guide — the book to put on the kitchen table for a family.' },
          { title: 'The Backyard Astronomer\'s Guide',
            author: 'Terence Dickinson and Alan Dyer', year: 2021,
            url: '',
            why: 'The equipment-and-technique counterpart to NightWatch. Fourth edition in 2021, fully updated for GOTO mounts and astrophotography.' },
          { title: 'The Cambridge Star Atlas',
            author: 'Wil Tirion', year: 2011,
            url: '',
            why: 'The best affordable printed star atlas — 900 objects, Moon maps, and the Tirion chart style every working amateur knows by sight.' },
          { title: 'Stars and Planets (Collins Field Guide)',
            author: 'Ian Ridpath and Wil Tirion', year: 2017,
            url: '',
            why: 'The pocket reference. Every one of the 88 constellations drawn twice — a labeled chart and a photograph — and Tirion\'s charts are the gold standard.' },
        ],
        articles: [
          { title: 'Constellation', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Constellation',
            why: 'A patient history — Ptolemy, Hevelius, Lacaille, Delporte — with the full IAU boundary story.' },
          { title: 'IAU designated constellations', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/IAU_designated_constellations',
            why: 'The canonical list of 88 with abbreviations, Latin names, origin dates, and sky coverage.' },
          { title: 'Amateur astronomy', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Amateur_astronomy',
            why: 'The field\'s own entry — tools, contributions, famous amateurs. A useful map of what the hobby touches.' },
        ],
        courses: [
          { title: 'Crash Course Astronomy (46 episodes)',
            provider: 'Phil Plait / Crash Course',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtPAJr1ysd5yGIyiSFuh0mIL',
            free: true,
            why: 'A full 46-episode introductory astronomy course, free, led by the author of "Bad Astronomy."' },
          { title: 'Open Yale — Frontiers and Controversies in Astrophysics',
            provider: 'Yale OpenCourseWare',
            url: 'https://oyc.yale.edu/astronomy/astr-160',
            free: true,
            why: 'Charles Bailyn\'s undergraduate lectures. Far beyond constellations, but the right next step for a curious beginner.' },
        ],
        tools: [
          { title: 'Stellarium Web (planetarium)',
            url: 'https://stellarium-web.org/',
            why: 'A free browser-based planetarium — enter your location and see exactly what is up, labeled. No sign-in required.' },
          { title: 'Stellarium (desktop)',
            url: 'https://stellarium.org/',
            why: 'The free open-source desktop planetarium. Every amateur astronomer has it installed.' },
          { title: 'SkySafari (mobile)',
            url: 'https://skysafariastronomy.com/',
            why: 'The best-regarded paid mobile planetarium. Excellent for star-hopping from a phone held up at the sky.' },
          { title: 'DarkSky International — Dark Sky Place finder',
            url: 'https://darksky.org/places/',
            why: 'The nonprofit\'s certified-dark-sky site directory. Start with a nearby park and drive out for a new-moon weekend.' },
        ],
        primarySources: [
          { title: 'Ptolemy\'s Almagest (ca. 150 CE)',
            url: 'https://en.wikipedia.org/wiki/Almagest',
            why: 'The ancient catalogue of 48 constellations that seeded everything later. Wikipedia has the best free summary.' },
        ],
        images: [
          { src: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Orion_constellation_map.svg',
            alt: 'Map of Orion',
            caption: 'The IAU-bounded constellation of Orion, showing the belt, nebula, and the major stars.',
            credit: 'IAU and Sky &amp; Telescope · Wikimedia Commons · CC BY 3.0' },
        ],
      },

      interactive: null,
      seeAlso: ['scope', 'astronomy', 'cartography'],
      prereqs: [],
      leadsTo: ['scope'],

      chapterActivity: 'A moonless-night walk with the Amateur Astronomers Association of New York on the Great Lawn in Central Park — they set up scopes every clear weekend in season.',

      sources: [
        'https://en.wikipedia.org/wiki/Constellation',
        'https://en.wikipedia.org/wiki/IAU_designated_constellations',
        'https://stellarium-web.org/',
      ],
      verifiedAt: '2026-04-23',
    },

    scope: {
      id: 'scope',
      name: 'Using a Telescope',
      level: 'Intermediate',
      dek: 'Aperture beats magnification — and a cheap six-inch Dobsonian will show you more than an expensive four-inch refractor ever will.',
      readTime: '12 min',

      sections: ['The first principle', 'The three families of amateur scope', 'Eyepieces and magnification', 'Mounts and what they actually do', 'Your first night with a telescope', 'A small dark patch of sky'],
      body: [
        { type: 'lead', text: 'In a Tucson parking lot in 1965, an amateur astronomer named John Dobson nailed together a telescope from plywood, a piece of cardboard, and a pair of phonograph bearings. It was six inches across, weighed forty pounds, and could be set up in ninety seconds. He took it to a sidewalk in San Francisco and let people look at Saturn through it. The Dobsonian telescope, which cost roughly a twentieth of the commercial equivalents of its time, is still — sixty years later — the single telescope that has introduced the most people to the night sky.' },
        { type: 'h2', text: 'Aperture beats magnification' },
        { type: 'p', text: 'The single most important number on a telescope is not its magnification — which is adjustable and, past a point, counterproductive — but its aperture, the diameter of the light-gathering lens or mirror. Double the aperture and you gather four times the light; past about 60× magnification the air itself becomes the limit on resolution. Every experienced amateur would rather have an 8-inch $400 Dobsonian than a 4-inch $2,000 refractor, and for visual observing she is right. The terrible word for what a shop may try to sell a beginner is "525-power magnification!" — on a two-inch tube. Do not buy that scope.' },
        { type: 'h2', text: 'Three families' },
        { type: 'p', text: 'Refractors use lenses; reflectors use mirrors; catadioptrics use both. A refractor has a long tube, a lens at the front, and the classic spyglass form. A Newtonian reflector (invented by Newton in 1668) uses a concave primary mirror to fold the light up to a small secondary that sends it out the side. A Dobsonian is a Newtonian on a simple alt-azimuth base. A Schmidt-Cassegrain or Maksutov (catadioptric) folds the light twice using a corrector lens and two mirrors, producing a short, portable tube. Refractors give the sharpest views but cost more per inch; Dobsonians give the most aperture per dollar; SCTs pack the most focal length into the most luggable format.' },
        { type: 'h2', text: 'Eyepieces, plural' },
        { type: 'p', text: 'Magnification is focal-length-of-telescope divided by focal-length-of-eyepiece. A scope with a 1200mm focal length and a 10mm eyepiece gives 120×; swap in a 25mm eyepiece and it drops to 48×. Most observing is done at lower magnification — more field of view, more forgiving of atmosphere — and the eyepiece is the place to spend money after the scope itself. A trio of a 25mm, a 15mm, and a 7mm eyepiece, plus a 2× Barlow, covers everything a beginner will ever want. "Good enough" eyepieces from TeleVue or Explore Scientific are indistinguishable from expensive ones for visual use; the beginner kit bundled with a scope almost never is.' },
        { type: 'h2', text: 'Mounts' },
        { type: 'p', text: 'A telescope on a shaky mount is a telescope that shows nothing. Alt-azimuth mounts — up-down, left-right, like a camera tripod — are simple and intuitive; Dobsonians and most entry refractors use them. Equatorial mounts are tilted to match Earth\'s axis so that a single slow-motion knob tracks the sky. GOTO computerized mounts do the aiming for you from a database of thousands of objects. Each choice has a trade-off: alt-az is the fastest to set up; equatorial is better for photography; GOTO is easier but more expensive and takes more setup each night. For beginners, an 8-inch Dobsonian with no computer at all is still the most-recommended first telescope, and it probably always will be.' },
        { type: 'callout', text: 'The rule for a beginner\'s first scope is a four-sentence test: can you carry it outside in one trip? Can you set it up in under ten minutes? Can you point it at the Moon without reading a manual? If yes to all three, you will use it; if no, you will not.' },
        { type: 'h2', text: 'Your first night' },
        { type: 'p', text: 'Start with the Moon. Every crater a week old has a shadow that moves hour by hour. Move to Jupiter — four pinprick moons arranged on either side, rearranging themselves nightly. Saturn\'s rings are the single sight that has hooked more astronomers than any other. Then find the Orion Nebula, the Andromeda Galaxy, the Pleiades — the Messier catalogue was written for exactly this curriculum, and Guy Consolmagno\'s Turn Left at Orion walks you through it object by object. Plan for cold. Plan for dew. Plan for patience.' },
        { type: 'h2', text: 'A small dark patch of sky' },
        { type: 'p', text: 'The amateur\'s real reward is not a Hubble image — the scope cannot compete — but the direct line of photons from the object to your retina. An Andromeda photon in your eye left that galaxy 2.5 million years ago. The relationship is oddly intimate, and every working amateur knows it. Carl Sagan\'s phrase for the pale blue dot applies here too. Whatever else a telescope does, it humbles the viewer, and then it gives her back the night.' },
      ],

      keyTerms: ['aperture', 'focal length', 'magnification', 'eyepiece', 'Dobsonian', 'refractor', 'reflector', 'catadioptric', 'alt-azimuth', 'equatorial', 'GOTO', 'Barlow'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@AstroBackyard',
            title: 'AstroBackyard — telescope and setup videos',
            channel: 'Trevor Jones', duration: 'variable',
            why: 'The single best practical-scope channel for beginners. Trevor Jones has done everything from a $200 starter kit to a high-end rig, and is patient about the trade-offs.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@EdTingsAstronomy',
            title: 'Ed Ting — scope and eyepiece reviews',
            channel: 'Ed Ting', duration: 'variable',
            why: 'Ed Ting has reviewed practically every amateur telescope made since 1990. The buying-decision channel.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@AstronomyWithSymon',
            title: 'Symon Hill — Astronomy With Symon',
            channel: 'Astronomy With Symon', duration: 'variable',
            why: 'A UK amateur who runs a calm first-telescope series. Good for overcoming equipment anxiety.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@DeepSkyDetail',
            title: 'Deep Sky Detail — Robert Glassel',
            channel: 'Robert Glassel', duration: 'variable',
            why: 'Deep-sky imaging tutorials and observing walkthroughs. Useful once a first scope is in hand and the question is where to point it.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@crashcourseastronomy',
            title: 'Crash Course Astronomy — Phil Plait',
            channel: 'Crash Course', duration: 'variable',
            why: 'The optics and telescopes episodes (9 and 10) are the clearest free primer on how a telescope actually works.' },
        ],
        books: [
          { title: 'Turn Left at Orion',
            author: 'Guy Consolmagno and Dan Davis', year: 2018,
            url: '',
            why: 'The indispensable first book of telescopic observing. Every object drawn the way it actually looks in a modest scope, with finder charts and descriptions.' },
          { title: 'The Backyard Astronomer\'s Guide',
            author: 'Terence Dickinson and Alan Dyer', year: 2021,
            url: '',
            why: 'Fourth edition. The equipment, eyepiece, mount, and photography reference. Authoritative and cheerful.' },
          { title: 'Star-Hopping for Backyard Astronomers',
            author: 'Alan MacRobert', year: 1994,
            url: '',
            why: 'The classic on using a low-power eyepiece to hop from bright star to faint target. Written by a long-time Sky &amp; Telescope editor.' },
          { title: 'Seeing in the Dark',
            author: 'Timothy Ferris', year: 2002,
            url: '',
            why: 'The literary companion. Timothy Ferris\'s account of amateur astronomy\'s quiet renaissance at the end of the twentieth century.' },
          { title: 'NightWatch',
            author: 'Terence Dickinson', year: 2006,
            url: '',
            why: 'Large format, seasonal sky charts, and the best introductory reference for families. Still the single most-given beginner\'s astronomy book in North America.' },
        ],
        articles: [
          { title: 'Telescope', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Telescope',
            why: 'A broad history from the Dutch spectacle-makers through Galileo, Newton, and modern mirror figuring.' },
          { title: 'Dobsonian telescope', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Dobsonian_telescope',
            why: 'The backstory on John Dobson, the Sidewalk Astronomers, and the most-recommended beginner scope on earth.' },
          { title: 'Amateur astronomy', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Amateur_astronomy',
            why: 'The community, the tools, the citizen-science contributions, and a list of famous amateurs worth looking up.' },
        ],
        courses: [
          { title: 'Sky &amp; Telescope — Let\'s Go Stargazing (free guide)',
            provider: 'Sky &amp; Telescope',
            url: 'https://skyandtelescope.org/lets-go-stargazing/',
            free: true,
            why: 'The magazine\'s free beginner portal. Weekly sky-at-a-glance, equipment basics, and the evergreen "astronomy for beginners" pages.' },
          { title: 'Crash Course Astronomy (full playlist)',
            provider: 'Phil Plait / Crash Course (YouTube)',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtPAJr1ysd5yGIyiSFuh0mIL',
            free: true,
            why: '46 free episodes. Not a telescope course per se, but the physics the telescope reveals.' },
        ],
        tools: [
          { title: 'Stellarium (desktop) and Stellarium Web',
            url: 'https://stellarium.org/',
            why: 'Free open-source planetarium. Shows exactly what you can see from your coordinates at any moment, and will print finder charts for objects.' },
          { title: 'Astronomy League — club finder',
            url: 'https://www.astroleague.org/',
            why: 'The umbrella federation for 240+ North American amateur clubs. Most run public star parties and loan scopes to members.' },
          { title: 'AAVSO — American Association of Variable Star Observers',
            url: 'https://www.aavso.org/',
            why: 'The amateur-science organization par excellence. Contribute real variable-star data that feeds professional astronomy.' },
          { title: 'Clear Outside / Clear Dark Sky',
            url: 'https://www.cleardarksky.com/',
            why: 'Forecasting clouds, seeing, transparency, and dark hours for thousands of North American sites. An observer\'s weather report.' },
        ],
        primarySources: [
          { title: 'Galileo, Sidereus Nuncius (1610)',
            url: 'https://archive.org/details/siderealmessenge00gali',
            why: 'Galileo\'s dispatch announcing the moons of Jupiter, the craters of the Moon, and the stars of the Milky Way — all from the telescope he had built six months earlier. The Internet Archive has scans.' },
        ],
      },

      interactive: null,
      seeAlso: ['constellations', 'astronomy', 'solar'],
      prereqs: ['constellations'],
      leadsTo: [],

      chapterActivity: 'A monthly scope night at Floyd Bennett Field with the Amateur Astronomers Association — Dobsonians set up in a line, strangers passing each other coffee and Saturn.',

      sources: [
        'https://en.wikipedia.org/wiki/Telescope',
        'https://en.wikipedia.org/wiki/Dobsonian_telescope',
        'https://stellarium.org/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
