// content/birding.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: id, calls

window.CONTENT = window.CONTENT || {};
window.CONTENT.birding = {
  subjectId: 'birding',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    id: {
      id: 'id',
      name: 'Identification',
      level: 'Beginner',
      dek: 'GISS — general impression, size, shape — and how a good birder reads a silhouette before the color.',
      readTime: '11 min',

      sections: ['A bird is first a shape', 'The four keys', 'Habitat, the hidden field mark', 'Merlin, Sibley, and the old hands', 'The life list as a diary'],
      body: [
        { type: 'lead', text: 'A warbler flickers at the top of a bare tree in Prospect Park on the last Saturday in April, and a veteran birder calls it a Blackburnian without lifting her binoculars. She has not seen the throat. What she has seen is the jizz — an old British birders\' word for the way a bird carries itself — and forty years of paying attention have turned that glimpse into a name.' },
        { type: 'h2', text: 'The four keys' },
        { type: 'p', text: 'Roger Tory Peterson, the Bronx-born illustrator whose 1934 A Field Guide to the Birds turned birding from Victorian list-making into an American pastime, taught a generation to look for field marks — a dark eye-ring, a white wing-bar, a notched tail. Cornell\'s modern Merlin app, trained on the Macaulay Library\'s millions of recordings and photos, asks its four keys in the same order a good birder\'s eye does: size and shape, color pattern, behavior, habitat. Size and shape tell you the family. Color narrows to species. Behavior and habitat decide the last few coin-flips.' },
        { type: 'h2', text: 'Habitat, the hidden field mark' },
        { type: 'p', text: 'Where the bird is matters almost as much as what it looks like. A chickadee-sized bird climbing headfirst down a tree trunk is a nuthatch; one hitching upward in short bursts is a brown creeper or a woodpecker. A small brown bird skulking in a marsh is probably not a sparrow. Pete Dunne, the longtime New Jersey Audubon man, writes that the first question a birder should ask is not "what is it?" but "what could it plausibly be, here, right now?" The answer collapses the guide by ninety percent.' },
        { type: 'h2', text: 'The tools, modest and otherwise' },
        { type: 'p', text: 'An eight-by-forty-two binocular, a field guide — Sibley for the careful, Kaufman for the patient, the Peterson for the sentimental — and a willingness to be wrong are the whole kit. Merlin and eBird, both free from the Cornell Lab of Ornithology, have changed the hobby more than any other single development since Peterson. Merlin will name a bird from a photo or, more startlingly, from its song; eBird turns every casual outing into citizen science that feeds back into the continent\'s maps of bird distribution.' },
        { type: 'callout', text: 'Do not trust the first app ID. Merlin is spectacular and also wrong, in ways that matter, maybe one time in twenty. A life list built on uncorrected Merlin guesses is a fiction. Verify with a second clue.' },
        { type: 'h2', text: 'The life list as a diary' },
        { type: 'p', text: 'Most birders keep a life list — every species seen, with date and place. Kenn Kaufman, who hitch-hiked around North America at sixteen trying to see seven hundred species in a year, wrote Kingbird Highway about that trip thirty years later, and the book is the most honest thing in American nature writing about what the list actually is: not a scoreboard but a diary, crowded with old parking lots and specific April afternoons. The bird you learn best is the one you had to work to find.' },
      ],

      keyTerms: ['GISS (jizz)', 'field mark', 'habitat', 'silhouette', 'field guide', 'life list', 'pishing', 'plumage'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube', url: 'https://www.youtube.com/@LesleytheBirdNerd/videos',
            title: 'Lesley the Bird Nerd — full channel',
            channel: 'Lesley the Bird Nerd', duration: 'variable',
            why: 'A Newfoundland birder whose patient, slow-paced videos on individual species (Pileated Woodpecker, Snowy Owl, Northern Saw-whet Owl) are the most humane beginner introduction on YouTube.' },
          { id: null, featured: true, source: 'other',
            url: 'https://academy.allaboutbirds.org/product/basics-of-bird-id/',
            title: 'Basics of Bird ID (free mini-course)',
            channel: 'Cornell Bird Academy', duration: '~1 hour',
            why: 'Cornell\'s own introduction to the four keys — size and shape, color, behavior, habitat — taught by the people who built Merlin.' },
          { id: null, featured: true, source: 'other',
            url: 'https://merlin.allaboutbirds.org/',
            title: 'Merlin Bird ID (photo, sound, and step-by-step ID)',
            channel: 'Cornell Lab of Ornithology', duration: 'on-demand',
            why: 'The single tool that has done more for beginner birding than any field guide since Peterson. Free, offline-capable, and startling when it works.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@CornellBirds',
            title: 'Cornell Lab of Ornithology — full channel',
            channel: 'Cornell Lab of Ornithology', duration: 'variable',
            why: 'The Lab\'s own shorts and lectures — everything from the Macaulay Library recording process to seasonal identification primers.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@BadgerlandBirding',
            title: 'Badgerland Birding — full channel',
            channel: 'Badgerland Birding', duration: 'variable',
            why: 'Wisconsin-based big-year chases and patch birding. A window into how serious hobbyists actually bird a region.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@Audubon',
            title: 'National Audubon Society — full channel',
            channel: 'Audubon', duration: 'variable',
            why: 'Short, well-produced species features and conservation reporting from the oldest bird-focused organization in the country.' },
        ],
        books: [
          { title: 'The Sibley Guide to Birds (Second Edition)',
            author: 'David Allen Sibley', year: 2014,
            url: 'https://www.sibleyguides.com/book/the-sibley-guide-to-birds-second-edition/',
            why: 'The standard for North American identification since its 2000 first edition. Sibley illustrates every plumage and pose, and the quiet text tells you what matters.' },
          { title: 'Kaufman Field Guide to Birds of North America',
            author: 'Kenn Kaufman', year: 2005, url: '',
            why: 'The friendliest first guide, using retouched photographs in place of paintings. The book to keep in the glove box.' },
          { title: 'A Field Guide to the Birds (Peterson, 5th Edition)',
            author: 'Roger Tory Peterson', year: 2002, url: '',
            why: 'The 1934 original, in its last revised edition. The book that invented the field-mark system every later guide uses.' },
          { title: 'Pete Dunne on Bird Watching',
            author: 'Pete Dunne', year: 2003, url: '',
            why: 'A working New Jersey birder explains what good binoculars feel like in hand, why you miss the bird you are staring at, and how to find one anyway.' },
          { title: 'Kingbird Highway',
            author: 'Kenn Kaufman', year: 1997, url: '',
            why: 'A teenage hitch-hiker\'s 1973 big-year memoir — the most honest thing ever written about what the life list actually is.' },
        ],
        articles: [
          { title: 'Birdwatching', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Birdwatching',
            why: 'A sober, well-referenced history of the hobby from its 1712 origins through the iPhone.' },
          { title: 'All About Birds (species accounts)',
            source: 'Cornell Lab of Ornithology',
            url: 'https://www.allaboutbirds.org/',
            why: 'The authoritative free species guide — range maps, sounds, photos, life history — for every North American bird.' },
          { title: 'Audubon Bird Guide',
            source: 'National Audubon Society',
            url: 'https://www.audubon.org/bird-guide',
            why: 'Audubon\'s parallel guide, strong on conservation status and climate-driven range change.' },
        ],
        courses: [
          { title: 'Bird Academy — free webinars and mini-courses',
            provider: 'Cornell Lab of Ornithology',
            url: 'https://academy.allaboutbirds.org/',
            free: true,
            why: 'A running series of free webinars (several a month) plus the paid Be a Better Birder series for the ones that take a weekend.' },
          { title: 'eBird Essentials',
            provider: 'Cornell Lab of Ornithology',
            url: 'https://academy.allaboutbirds.org/course/ebird-essentials/',
            free: true,
            why: 'Three hours, free, and by the end you know how to submit checklists that become data.' },
        ],
        tools: [
          { title: 'Merlin Bird ID',
            url: 'https://merlin.allaboutbirds.org/',
            why: 'Photo, sound, and step-by-step ID, trained on Macaulay Library recordings. Free; offline packs downloadable.' },
          { title: 'eBird',
            url: 'https://ebird.org/',
            why: 'The world\'s largest citizen-science bird database. Every checklist becomes data; every hotspot map is fed by yours.' },
          { title: 'Macaulay Library',
            url: 'https://www.macaulaylibrary.org/',
            why: 'Cornell\'s archive of bird photos, video, and sound recordings — the largest in the world, and the training set behind Merlin.' },
        ],
        primarySources: [
          { title: 'A Field Guide to the Birds (1934 — Internet Archive)',
            url: 'https://archive.org/details/fieldguidetobird00pete',
            why: 'Roger Tory Peterson\'s original, scanned by the Internet Archive. The book that turned birding American.' },
        ],
        images: [
          { src: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Setophaga_fusca_male.jpg',
            alt: 'Male Blackburnian Warbler',
            caption: 'A male Blackburnian Warbler — the flame-throated migrant that passes through New York parks in late April and early May.',
            credit: 'Dan Pancamo · Wikimedia Commons · CC BY-SA 2.0' },
        ],
      },

      interactive: null,
      seeAlso: ['calls', 'ecology', 'biomes'],
      prereqs: [],
      leadsTo: ['calls'],

      chapterActivity: 'A dawn spring-migration walk in Prospect Park on the first Saturday in May, led by whichever chapter member has the biggest life list — bring binoculars, a field guide, and nothing else.',

      sources: [
        'https://en.wikipedia.org/wiki/Birdwatching',
        'https://www.allaboutbirds.org/',
        'https://merlin.allaboutbirds.org/',
        'https://www.sibleyguides.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    calls: {
      id: 'calls',
      name: 'Birdsong',
      level: 'Intermediate',
      dek: 'The ear does more work than the eye — and the language of dawn is learnable, one phrase at a time.',
      readTime: '12 min',

      sections: ['The ear-first birder', 'Song, call, and the difference', 'How a bird sings', 'Learning by phrase, not by list', 'The Macaulay archive and Merlin Sound ID'],
      body: [
        { type: 'lead', text: 'In a Tennessee oak woods in 1928, the ornithologist Arthur Allen set down a cylinder recorder and captured a Song Sparrow — the first usable field recording of an American bird. Everything now in the Macaulay Library at Cornell, every song identified by Merlin, every data point in the continental map of declining thrushes, descends from that afternoon. A good birder in the field today identifies nine tenths of what she finds before she sees it.' },
        { type: 'h2', text: 'Song and call' },
        { type: 'p', text: 'The terms are not interchangeable. A song is a long, learned, elaborate vocalization — almost always by a male songbird on territory during breeding season, as a combined claim and advertisement. A call is shorter, usually given year-round by both sexes, and does a single job: contact, alarm, flight note, begging. The chip of a warbler in fall and its ringing spring song are the same bird; a birder who can tell them apart has doubled her effective field season.' },
        { type: 'h2', text: 'The syrinx, not the larynx' },
        { type: 'p', text: 'A bird sings from an organ no mammal has — the syrinx, sitting where the trachea splits into the two bronchi. Two separate membranes, each with its own muscles, let some species sing two notes at once. Donald Kroodsma\'s *The Singing Life of Birds* walks patiently through the physiology and the behavior; nothing else in the popular literature is as good on why a Hermit Thrush\'s song seems to come from inside a cathedral.' },
        { type: 'h2', text: 'Learn by phrase, not by list' },
        { type: 'p', text: 'The beginner\'s mistake is to try to memorize two hundred songs at once. The working method, taught in Cornell\'s Bird Academy courses, is to learn one phrase a week — a chipping-on-a-typewriter trill is a Chipping Sparrow; a clear tea-KETtle, tea-KETtle is a Carolina Wren; a lazy sweet-sweet, I\'m-so-lazy is a Yellow Warbler. Mnemonic beats muscle memory. By a third summer the whole dawn chorus has names.' },
        { type: 'callout', text: 'Merlin Sound ID is the biggest change to ear-birding since magnetic tape. It listens through your phone and suggests species in real time. Trust it the way you trust a tide chart — useful, sometimes wrong, never final.' },
        { type: 'h2', text: 'The archive and the phone' },
        { type: 'p', text: 'The Macaulay Library now holds over a million hours of bird audio, almost all of it free to stream. Every species page on allaboutbirds.org carries sample recordings; every phone with Merlin installed carries a live classifier trained on them. None of this substitutes for hearing the bird itself. It shortens the distance between not knowing and knowing, which is what a good teacher does.' },
      ],

      keyTerms: ['song', 'call', 'syrinx', 'dawn chorus', 'flight call', 'mnemonic', 'Macaulay Library', 'Sound ID'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@LesleytheBirdNerd/videos',
            title: 'Lesley the Bird Nerd — full channel',
            channel: 'Lesley the Bird Nerd', duration: 'variable',
            why: 'Lesley\'s species profiles almost always include a long, clean audio segment of the bird singing. The best patient teacher for ear-birding.' },
          { id: null, featured: true, source: 'other',
            url: 'https://www.macaulaylibrary.org/',
            title: 'Macaulay Library — stream any species',
            channel: 'Cornell Lab of Ornithology', duration: 'on-demand',
            why: 'Search a species, press play. The largest bird audio archive ever assembled, free, with spectrograms alongside.' },
          { id: null, featured: true, source: 'other',
            url: 'https://merlin.allaboutbirds.org/sound-id/',
            title: 'Merlin Sound ID (live classifier)',
            channel: 'Cornell Lab of Ornithology', duration: 'on-demand',
            why: 'The pocket tool that names the singer as you walk. Built on Macaulay recordings; gets better every release.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@CornellBirds',
            title: 'Cornell Lab of Ornithology — full channel',
            channel: 'Cornell Lab of Ornithology', duration: 'variable',
            why: 'The Lab\'s public lectures and shorts include whole series on song learning and the neurobiology of the singing zebra finch.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@thewildzoneca',
            title: 'The Wild Zone — Canadian bird-song walks',
            channel: 'The Wild Zone', duration: 'variable',
            why: 'Slow-paced, on-location recordings from Ontario forests. Good for training the ear before the April migrants arrive.' },
        ],
        books: [
          { title: 'The Singing Life of Birds',
            author: 'Donald Kroodsma', year: 2005, url: '',
            why: 'The field\'s best popular book — by the Hampshire College ornithologist who has spent forty years listening. Includes a CD of recordings keyed to each chapter.' },
          { title: 'Birdsong: A Natural History',
            author: 'Don Stap', year: 2005, url: '',
            why: 'A journalist\'s chronicle of Kroodsma\'s fieldwork and the history of bioacoustics — the best narrative introduction.' },
          { title: 'Why Birds Sing',
            author: 'David Rothenberg', year: 2005, url: '',
            why: 'A philosopher-musician asks why songs are as elaborate as they are — and plays clarinet duets with a white-crested laughingthrush.' },
          { title: 'The Peterson Field Guide to Bird Sounds of Eastern North America',
            author: 'Nathan Pieplow', year: 2017, url: '',
            why: 'The book that finally reduced bird song to a writable notation. A reference as useful as the visual field guide.' },
        ],
        articles: [
          { title: 'Bird vocalization', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Bird_vocalization',
            why: 'The best free overview of the anatomy, learning, and function of song.' },
          { title: 'All About Birds — sound pages',
            source: 'Cornell Lab of Ornithology',
            url: 'https://www.allaboutbirds.org/',
            why: 'Every species page carries annotated audio — song, call, flight note — drawn from the Macaulay Library.' },
        ],
        courses: [
          { title: 'Be a Better Birder: Sound ID',
            provider: 'Cornell Bird Academy',
            url: 'https://academy.allaboutbirds.org/',
            free: true,
            why: 'A mix of paid deep-dives and free webinars on learning song. Start with the free lectures; graduate to the paid modules when the backyard dawn chorus is solved.' },
        ],
        tools: [
          { title: 'Merlin Sound ID',
            url: 'https://merlin.allaboutbirds.org/sound-id/',
            why: 'The live in-the-field classifier. Indispensable, imperfect, free.' },
          { title: 'Macaulay Library',
            url: 'https://www.macaulaylibrary.org/',
            why: 'The archive itself. Listen and compare without leaving the browser.' },
          { title: 'Spectrograms on eBird checklists',
            url: 'https://ebird.org/explore',
            why: 'Every sound recording uploaded to eBird now renders as a spectrogram. Read the shape before you trust the ear.' },
        ],
        primarySources: [
          { title: 'Arthur Allen and Peter Paul Kellogg field recordings (1929 onward)',
            url: 'https://www.macaulaylibrary.org/about/our-history/',
            why: 'The Cornell pioneers who invented sound-recording ornithology, and built the archive that became Macaulay.' },
        ],
      },

      interactive: null,
      seeAlso: ['id', 'ecology', 'neuro'],
      prereqs: ['id'],
      leadsTo: [],

      chapterActivity: 'A May dawn chorus walk in the Brooklyn Botanic Garden — phones in airplane mode, Merlin open on one, the rest of us guessing first.',

      sources: [
        'https://en.wikipedia.org/wiki/Bird_vocalization',
        'https://www.macaulaylibrary.org/',
        'https://merlin.allaboutbirds.org/sound-id/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
