// content/chess.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: openings, endgame
//
// NOTE: No chess_board interactive widget exists in the registry. Per batch
// instructions, we omit the interactive and link to lichess Studies.

window.CONTENT = window.CONTENT || {};
window.CONTENT.chess = {
  subjectId: 'chess',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    openings: {
      id: 'openings',
      name: 'Openings',
      level: 'Beginner',
      dek: 'Development, the center, and king safety — the three principles that let you stop memorizing lines and start playing chess.',
      readTime: '11 min',

      sections: ['The three principles', 'The living repertoire', 'A system for each color', 'The Oxford Companion\'s 1,327 names', 'Where the clock really lives'],
      body: [
        { type: 'lead', text: 'On June 12, 1889, in the second round of the Sixth American Chess Congress in New York, a twenty-two-year-old Emanuel Lasker sat opposite the veteran Harry Nelson Pillsbury and, playing Black, answered 1. e4 with the modest move c5. The Sicilian Defense was already three centuries old by then, but Lasker\'s game — quiet, positional, eventually drawn — was the kind of steady resistance that would in six years make him world champion. A hundred and thirty-five years later, the Sicilian is the single most-played opening in top-level chess. There is nothing fashionable about it. Chess openings are among the most stable pieces of human knowledge.' },
        { type: 'h2', text: 'The three principles' },
        { type: 'p', text: 'The schoolteacher\'s three are control the center, develop your pieces, and castle. Past the thousandth game of a modest career, they hold. Pawns on e4 and d4 (or e5 and d5 for Black) fight for the four central squares from which knights and bishops reach the most terrain. Knights before bishops, because knights have fewer good squares. Do not move the same piece twice before everything else is developed. Do not bring the queen out early — she is expensive and the opponent can gain tempo by attacking her. Castle by the tenth move. These rules are not absolute, but the opening in which a beginner breaks them is almost always the opening she loses.' },
        { type: 'h2', text: 'A living repertoire, not a memorized one' },
        { type: 'p', text: 'Top-level players know thousands of moves of opening theory; club players cannot, should not, and will not. What a serious amateur actually builds is a repertoire — one or two openings for White, two or three responses for Black — that she plays often enough to understand, not memorize. The difference matters: the player who has memorized the first fifteen moves of the Italian Game loses her way on move sixteen; the player who understands why those fifteen moves were chosen keeps playing good moves when the theory runs out.' },
        { type: 'h2', text: 'A workable first system' },
        { type: 'p', text: 'For White, a beginner repertoire of the Italian Game (1. e4 e5 2. Nf3 Nc6 3. Bc4) after 1... e5, and the Open Sicilian with Be2 or g3 after 1... c5, covers most of what the rest of the playing world will throw at you and teaches the core principles in the sharpest way. For Black against 1. e4, either 1... e5 (entering the Italian or the Ruy Lopez) or 1... c5 (the Sicilian); against 1. d4, the Queen\'s Gambit Declined with 1... d5 2... e6 is the workhorse line the world champion Magnus Carlsen has been playing for twenty years, and it has never been refuted.' },
        { type: 'callout', text: 'The line of your life as a chess player will be crossed not by what your opponent plays but by how long you keep playing the same thing. Three openings, mastered, beat thirty openings, memorized. Repetition is how chess positions stop being diagrams and start being landscapes.' },
        { type: 'h2', text: 'The Oxford Companion\'s 1,327 names' },
        { type: 'p', text: 'The Oxford Companion to Chess lists 1,327 named opening variations. The names are almost entirely the work of nineteenth- and twentieth-century analysts who, like taxonomists, wanted a label for every leaf. A beginner need learn about fifteen of them. The names — Italian, Ruy Lopez, Queen\'s Gambit, King\'s Indian, Sicilian — are the trellis on which the whole theory of the subject hangs, but the thing you are learning is not the names. It is how to make reasonable moves in positions nobody has ever had before.' },
        { type: 'h2', text: 'Where the clock really lives' },
        { type: 'p', text: 'A serious chess game is lost by the player who spends too much time in the opening. The Swedish grandmaster Jonny Hector used to tell his students that every minute a beginner spends thinking about opening move 7 is a minute she will not have for the real problem of middlegame move 25. A reasonable target: twelve minutes for the first fifteen moves of any classical game. That is fifty seconds per move — enough to choose intelligently, not enough to try to calculate ten moves ahead. The ten-move calculation is saved for the position it actually decides.' },
      ],

      keyTerms: ['tempo', 'development', 'center', 'castling', 'gambit', 'pin', 'fianchetto', 'initiative', 'theory', 'novelty'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@GothamChess',
            title: 'GothamChess — full channel (Levy Rozman)',
            channel: 'GothamChess', duration: 'variable',
            why: 'The biggest chess channel on YouTube. Rozman\'s beginner-guides-by-opening series and his "How to Win at Chess" companion videos are the on-ramp for most new players in 2026.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@agadmator',
            title: 'agadmator\'s Chess Channel — classical game analysis',
            channel: 'agadmator (Antonio Radić)', duration: 'variable',
            why: 'Croatian former tournament player whose single-game analyses of classical and modern games are the best free chess storytelling on the internet.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@DanielNaroditskyGM',
            title: 'Daniel Naroditsky — full channel',
            channel: 'Daniel Naroditsky', duration: 'variable',
            why: 'Grandmaster and teacher. His speed-run series explaining chess through graduated opponents is the best free structured curriculum on YouTube.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@JohnBartholomewChess',
            title: 'John Bartholomew — Chess Fundamentals',
            channel: 'John Bartholomew', duration: 'variable',
            why: 'International Master with patient, club-player-focused explainers. His "Chess Fundamentals" series is the steady companion to flashier channels.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@HangingPawns',
            title: 'Hanging Pawns — full channel',
            channel: 'Hanging Pawns', duration: 'variable',
            why: 'Stjepan Tomić\'s methodical opening surveys. When you want to understand what an opening is really about, start here.' },
        ],
        books: [
          { title: 'My System',
            author: 'Aron Nimzowitsch', year: 1925, url: '',
            why: 'The classic of positional chess. Nimzowitsch\'s hypermodern principles — control the center with pieces, not only pawns — rewrote the opening. A hundred years later the book is still in print and still argued about.' },
          { title: 'How to Win at Chess',
            author: 'Levy Rozman', year: 2023, url: '',
            why: 'The current best-selling first book for true beginners. Rozman\'s writing has the same patient cadence as his videos.' },
          { title: 'Logical Chess: Move by Move',
            author: 'Irving Chernev', year: 1957, url: '',
            why: 'A seventy-year-old book that is still the best beginner explanation of why each move in thirty-three complete games is played. The book many teachers recommend first.' },
          { title: 'Modern Chess Openings (15th Edition)',
            author: 'Nick de Firmian', year: 2008, url: '',
            why: '"MCO" — the pocket reference every tournament player has carried since 1911. Not to be read; to be consulted.' },
          { title: 'The Oxford Companion to Chess',
            author: 'David Hooper and Kenneth Whyld', year: 1996, url: '',
            why: 'The reference book — history, biography, and the catalogue of 1,327 opening names.' },
        ],
        articles: [
          { title: 'Chess opening', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Chess_opening',
            why: 'A well-referenced overview of the principles, the naming conventions, and the major families.' },
          { title: 'Chess', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Chess',
            why: 'The general article. Essential background — rules, history, notation, competitive structure.' },
          { title: 'List of chess openings', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/List_of_chess_openings',
            why: 'The catalog by ECO code. Useful when you want to see where an opening sits in the taxonomy.' },
        ],
        courses: [
          { title: 'Lichess — free learning modules',
            provider: 'lichess.org',
            url: 'https://lichess.org/learn',
            free: true,
            why: 'The free, open-source chess server\'s own introductory modules. No sign-up. The right place to start before any book.' },
          { title: 'Chess.com Lessons — free tier',
            provider: 'chess.com',
            url: 'https://www.chess.com/lessons',
            free: true,
            why: 'Chess.com\'s beginner lessons are free; the advanced courses are paid. A solid complementary curriculum to Lichess.' },
        ],
        tools: [
          { title: 'Lichess (play and study boards)',
            url: 'https://lichess.org/',
            why: 'Free, open-source, ad-free, and better than the commercial alternatives in almost every respect. The Study tool lets you annotate and share full games.' },
          { title: 'Lichess Studies — directory',
            url: 'https://lichess.org/study',
            why: 'A directory of user-created studies on openings, tactics, and endgames. The closest thing to a free open chess curriculum.' },
          { title: 'Chess.com',
            url: 'https://www.chess.com/',
            why: 'The largest chess platform. Paid premium features are extensive; the free tier is still very usable.' },
          { title: 'Chessgames.com — historical game database',
            url: 'https://www.chessgames.com/',
            why: 'Over 900,000 searchable master games. The free archive that lets you follow any opening through a century of practice.' },
        ],
        primarySources: [
          { title: 'Ruy López de Segura, Libro de la invención liberal y arte del juego del Axedrez (1561)',
            url: 'https://en.wikipedia.org/wiki/Ruy_L%C3%B3pez_de_Segura',
            why: 'The Spanish priest whose opening treatise gave us the Ruy Lopez. Wikipedia\'s article is the best free portal.' },
        ],
      },

      interactive: null,
      seeAlso: ['endgame', 'algorithms', 'ai'],
      prereqs: [],
      leadsTo: ['endgame'],

      chapterActivity: 'A Sunday afternoon beginner-friendly tournament at the Marshall Chess Club on West 10th Street — $10 entry, clocks provided, four rounds, home by six.',

      sources: [
        'https://en.wikipedia.org/wiki/Chess_opening',
        'https://lichess.org/',
        'https://www.chess.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    endgame: {
      id: 'endgame',
      name: 'Endgame',
      level: 'Intermediate',
      dek: 'Where concrete skill lives — the phase of the game that separates the dedicated amateur from the tourist.',
      readTime: '12 min',

      sections: ['Capablanca\'s rule', 'King and pawn: the kingdom of rules', 'Rook endings, which are always drawn', 'Bishop versus knight', 'Tablebases and the shape of truth', 'A reading plan'],
      body: [
        { type: 'lead', text: 'In 1921, in the third game of his World Championship match against Emanuel Lasker, the Cuban José Raúl Capablanca emerged from a quiet Queen\'s Gambit middlegame with a tiny positional edge — half a pawn\'s worth of space and a slightly better-placed rook. Over the next fifty moves, with all the pieces except the rooks traded off, he converted the edge into a won king-and-pawn endgame. The game was played at thirty-five moves per two and a half hours. Capablanca had not calculated the winning line; he had seen its shape. "A good endgame player," he wrote, "is a good chess player." Nothing in the sport has changed since.' },
        { type: 'h2', text: 'Capablanca\'s rule' },
        { type: 'p', text: 'The ratio of improvement per hour of study is, almost uniquely in chess, highest in the endgame. A beginner who spends her first year on openings will be a stronger player in principle; one who spends it on endgames will actually win more games. This is because the endgame is where the smallest material or positional edge can be converted to a full point, and where the skill is most concretely teachable. Bobby Fischer, who as a teenager studied nothing but Capablanca for a year, played the endgame at a depth none of his peers matched.' },
        { type: 'h2', text: 'King and pawn: the foundation' },
        { type: 'p', text: 'Every endgame reduces, in principle, to king-and-pawn. So start there. The opposition — two kings facing each other with one empty square between — is the central concept. The player who must move in opposition often loses ground. The rule of the square tells you whether a lone king can catch a running pawn: draw an imaginary square from the pawn to its promotion rank; if the king can step inside it, the pawn falls. Passed pawns must be pushed. Jeremy Silman\'s Complete Endgame Course teaches these ideas by rating — read only the section at your current rating, re-read it every six months. Three or four returns, and the foundation is there.' },
        { type: 'h2', text: 'Rook endings, which are almost always drawn' },
        { type: 'p', text: 'Rook endings are the most common pawn-reduced endgame in tournament practice, and the Soviet grandmaster Savielly Tartakower\'s old joke — "all rook endings are drawn" — is only half a joke. The techniques are structural: get your rook behind your passed pawn; active the king as a fighting piece; build a bridge to promote. Philidor\'s defensive formation (defending third rank with your rook, then checking from behind once the enemy king advances) and the Lucena position (winning a queen-versus-rook conversion) are the two reference positions every serious player memorizes. These are not exotica; you will face them.' },
        { type: 'h2', text: 'Bishop versus knight' },
        { type: 'p', text: 'Bishops prefer open positions with pawns on both flanks. Knights prefer closed positions with pawns fixed on one color. An opposite-colored bishops endgame is usually drawn even with a two-pawn deficit, because the defending bishop can prevent passed-pawn promotion on its own color. A same-colored bishops ending with a space edge is often won. Two bishops versus bishop-and-knight is measurably better for the two-bishops side across the Carlsbad and Karlsbad database results. These are not opinions; they are statistical patterns you can verify on a tablebase.' },
        { type: 'callout', text: 'Seven-piece tablebases — endgame databases that solve every position with seven or fewer men on the board — are complete. They are the first case in human history where a class of problem has been solved for all time. In the occasional long-study endgame, tablebase answers sometimes diverge startlingly from grandmaster intuition.' },
        { type: 'h2', text: 'A reading plan' },
        { type: 'p', text: 'Silman\'s Complete Endgame Course, by rating, for the first lap. Dvoretsky\'s Endgame Manual, the uncompromising second book, once you are a club player with a regular game. Capablanca\'s Chess Fundamentals (1921), free in multiple editions and easily in the public domain, for the instinct. Fischer\'s My 60 Memorable Games, for the endgames as Fischer saw them. Finally, a tablebase — Syzygy, or the Lomonosov seven-piece database, both freely queryable online. Check your intuition against the truth once a week, and your endgame instincts will sharpen faster than any other part of your game.' },
      ],

      keyTerms: ['opposition', 'rule of the square', 'passed pawn', 'Lucena', 'Philidor', 'opposite-colored bishops', 'Zugzwang', 'tablebase', 'fortress', 'triangulation'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@DanielNaroditskyGM',
            title: 'Daniel Naroditsky — endgame series',
            channel: 'Daniel Naroditsky', duration: 'variable',
            why: 'The grandmaster explainer. His "Endgame Fundamentals" playlist is the single best free endgame course on YouTube.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@HangingPawns',
            title: 'Hanging Pawns — endgame principles',
            channel: 'Hanging Pawns', duration: 'variable',
            why: 'Stjepan Tomić\'s methodical endgame explainers pair each principle with a complete master-level example. Quiet, useful teaching.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@agadmator',
            title: 'agadmator\'s Chess Channel — classical endgame annotations',
            channel: 'agadmator', duration: 'variable',
            why: 'agadmator\'s annotations of Capablanca, Smyslov, and Karpov endgames are the best free exposure to endgame artistry on the internet.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@GothamChess',
            title: 'GothamChess — endgame lessons',
            channel: 'Levy Rozman', duration: 'variable',
            why: 'Rozman\'s endgame series is noisier than Naroditsky\'s but covers the essentials at a beginner-friendly level.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@SaintLouisChessClub',
            title: 'Saint Louis Chess Club — lectures',
            channel: 'Saint Louis Chess Club', duration: 'variable',
            why: 'The free archived lectures from Yasser Seirawan, Ben Finegold, and others. The Finegold endgame lectures are the cheerfully blunt standard.' },
        ],
        books: [
          { title: 'My 60 Memorable Games',
            author: 'Bobby Fischer', year: 1969, url: '',
            why: 'Fischer\'s own annotations of 60 of his games. Unusual for including draws and losses. The book every serious student returns to.' },
          { title: 'Silman\'s Complete Endgame Course',
            author: 'Jeremy Silman', year: 2007, url: '',
            why: 'The uncommon endgame book organized by playing rating — read only the section you need now. The best structured first book on the subject in English.' },
          { title: 'Dvoretsky\'s Endgame Manual',
            author: 'Mark Dvoretsky', year: 2003, url: '',
            why: 'The uncompromising second book. Mark Dvoretsky trained a generation of Soviet grandmasters; his standards show. The reference you graduate into.' },
          { title: 'Capablanca\'s Chess Fundamentals',
            author: 'José Raúl Capablanca', year: 1921,
            url: 'https://www.gutenberg.org/ebooks/33870',
            why: 'The most elegantly-written chess book in the public domain. Capablanca wrote for the patient amateur. Free on Project Gutenberg.' },
          { title: 'My System',
            author: 'Aron Nimzowitsch', year: 1925, url: '',
            why: 'Not an endgame book, but its treatment of pawn structure and blockade is the missing layer under any serious endgame understanding.' },
        ],
        articles: [
          { title: 'Chess endgame', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Chess_endgame',
            why: 'A careful, well-referenced catalogue of all major endgame types with worked examples.' },
          { title: 'José Raúl Capablanca', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Jos%C3%A9_Ra%C3%BAl_Capablanca',
            why: 'Biography and career of the twentieth century\'s best endgame player.' },
          { title: 'Bobby Fischer', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Bobby_Fischer',
            why: 'Context for My 60 Memorable Games and for Fischer\'s Capablanca-like endgame sensibility.' },
        ],
        courses: [
          { title: 'Lichess Practice',
            provider: 'lichess.org',
            url: 'https://lichess.org/practice',
            free: true,
            why: 'Built-in tutorials and practice drills, including the core endgame positions (king-and-pawn, rook-and-pawn, Lucena, Philidor). Free, no sign-up.' },
          { title: 'Lichess Studies — endgame directory',
            provider: 'lichess.org',
            url: 'https://lichess.org/study/all/newest/search?q=endgame',
            free: true,
            why: 'User-created endgame studies, many of them excellent. A rotating free curriculum.' },
        ],
        tools: [
          { title: 'Syzygy tablebase (via Lichess analysis)',
            url: 'https://syzygy-tables.info/',
            why: 'Free online seven-piece tablebase. Type a position; get the objective answer. Use sparingly — calculation is a muscle.' },
          { title: 'Lichess Analysis Board',
            url: 'https://lichess.org/analysis',
            why: 'Free analysis with a strong engine, tablebase access, and unlimited position setup. The working tool of most serious amateurs.' },
          { title: 'Stockfish (engine)',
            url: 'https://stockfishchess.org/',
            why: 'The world\'s strongest open-source chess engine. Free, runs on any modern phone or laptop, used under the hood by every major platform.' },
        ],
        primarySources: [
          { title: 'José Raúl Capablanca, Chess Fundamentals (1921)',
            url: 'https://www.gutenberg.org/ebooks/33870',
            why: 'Public-domain edition of Capablanca\'s instructional classic. The source of the endgame section most modern teachers draw from.' },
        ],
      },

      interactive: null,
      seeAlso: ['openings', 'algorithms', 'ai'],
      prereqs: ['openings'],
      leadsTo: [],

      chapterActivity: 'A Saturday endgame drill at the Marshall Chess Club — two-player clocks on every board, a printed Lucena diagram in front of each pair, and a mentor walking the floor.',

      sources: [
        'https://en.wikipedia.org/wiki/Chess_endgame',
        'https://en.wikipedia.org/wiki/Bobby_Fischer',
        'https://lichess.org/practice',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
