// content/cooking.js
// Batch: B09-kitchen-arts
// Last updated: 2026-04-23 by BATCH B09-kitchen-arts
//
// Topics this subject must cover (from data.js):
//   Technique: knife, heat_transfer, seasoning, stocks

window.CONTENT = window.CONTENT || {};
window.CONTENT.cooking = {
  subjectId: 'cooking',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B09-kitchen-arts',
  topics: {

    knife: {
      id: 'knife',
      name: 'Knife Skills',
      level: 'Beginner',
      dek: 'The first technique and the one every other depends on — a sharp edge, two hands, and the patience to go slow.',
      readTime: '11 min',

      sections: ['The grip', 'The claw', 'Three cuts worth mastering', 'A sharp knife is a safe knife', 'The long apprenticeship'],
      body: [
        { type: 'lead', text: 'In a Tokyo workshop lit by fluorescent tubes, a blacksmith named Masamoto folds carbon steel against iron at 1,200 degrees Celsius, hammers it out, folds it again, and grinds an edge so fine it splits a hair lengthwise. The knife he makes is not a tool. It is a bargain between the steel and the hand: if you learn to use it properly, it will last a lifetime, and you will be faster and safer than any cook with a dull blade.' },
        { type: 'h2', text: 'The grip that professionals use' },
        { type: 'p', text: 'The pinch grip — thumb and forefinger on the blade just above the bolster, three remaining fingers wrapped around the handle — is the grip every culinary school teaches on the first day. It puts the hand close enough to the edge that the knife pivots on the cutting board like a seesaw, the wrist locked, the elbow doing most of the work. Beginners hold the handle like a tennis racket, which is why their wrists hurt after ten minutes and their cuts drift off line.' },
        { type: 'h2', text: 'The claw that keeps your fingertips' },
        { type: 'p', text: 'The guiding hand curls into a claw: fingertips tucked under knuckles, the flat of the middle phalanges pressed against the blade\'s side. The blade rides up and down the knuckles; the fingertips are never in the path. Every professional cook has scars on their thumbs from learning this the wrong way first, which is why the advice from culinary school instructors is almost religious in its repetition: watch your fingertips, watch your fingertips, watch your fingertips.' },
        { type: 'h2', text: 'Three cuts worth mastering' },
        { type: 'p', text: 'The rock chop, pivoting the tip on the board while the heel rises and falls, is for onions and herbs — anything you want fine and fast. The push cut, driving the blade forward and down in a single motion, is for firm vegetables and most meat. The slice, drawing the blade through delicate proteins without pressing, is for fish, tomatoes, and the soft summer fruit that a dull knife will crush. Learn these three and you have ninety percent of what a kitchen asks of you.' },
        { type: 'h2', text: 'A sharp knife is a safe knife' },
        { type: 'p', text: 'The single most common kitchen injury — a deep slice across the top of a finger — is almost always caused by a dull knife slipping off a tomato\'s skin or a squash\'s rind. A sharp blade bites instantly and goes where you point it. A dull blade requires force, and force without control is how hospital visits begin. A cheap whetstone and five minutes a week are enough to keep a home knife sharper than most restaurant kitchens manage.' },
        { type: 'h2', text: 'The long apprenticeship' },
        { type: 'p', text: 'In a Japanese professional kitchen, the new cook is handed an onion and a board, and told to keep cutting until told to stop. Nobody teaches them. They watch, they imitate, and they improve by the thousand repetitions the first year asks of them. A home cook does not need the same discipline, but the principle is the same: knife skills get better only with bored, repetitive practice, and they plateau the moment you stop practicing.' },
        { type: 'callout', text: 'The damp kitchen towel under the cutting board is not superstition. It keeps the board from sliding, which keeps the knife from jumping, which keeps your fingers attached. Every serious kitchen does it and no one writes it down.' },
      ],

      keyTerms: ['pinch grip', 'claw grip', 'rock chop', 'push cut', 'bolster', 'whetstone', 'mise en place', 'honing steel'],

      resources: {
        videos: [
          {
            id: 'XyS915RynEQ',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=XyS915RynEQ',
            title: 'Knife Skills: How to Chop',
            channel: 'Serious Eats (J. Kenji López-Alt)',
            duration: '3:00',
            featured: true,
            why: 'Kenji\'s original Serious Eats tutorial — the grip, the claw, the rock chop, in three minutes. The shortest good introduction on the internet.',
          },
          {
            id: 'LQO76nUscjc',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=LQO76nUscjc',
            title: 'Knife Skills: How to Rock Chop',
            channel: 'Serious Eats (J. Kenji López-Alt)',
            duration: '2:30',
            featured: true,
            why: 'The rock chop shown slowly, from the side and from above. The companion piece to the first video.',
          },
          {
            id: 'ixCnCvDUKQ8',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=ixCnCvDUKQ8',
            title: 'How to Sharpen a Knife with a Whetstone',
            channel: 'J. Kenji López-Alt',
            duration: '18:50',
            featured: true,
            why: 'Kenji\'s patient, first-person whetstone tutorial, filmed in his home kitchen. The best sharpening video for someone who has never done it before.',
          },
          {
            id: 'G-Fg7l7G1zw',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=G-Fg7l7G1zw',
            title: '4 Knife Skills Techniques Every Home Cook Should Know',
            channel: 'America\'s Test Kitchen',
            duration: '8:35',
            featured: false,
            why: 'Bridget Lancaster walks through four cuts on-camera. A calmer, slower pace than most YouTube tutorials, which is what the subject needs.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@JKenjiLopezAlt',
            title: 'J. Kenji López-Alt — full channel',
            channel: 'J. Kenji López-Alt',
            duration: 'variable',
            featured: false,
            why: 'First-person cooking videos filmed with a GoPro strapped to his forehead. No edits, no music, the rhythm of a real kitchen. His knife-use is unconscious, which is the point.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@aragusea',
            title: 'Adam Ragusea — full channel',
            channel: 'Adam Ragusea',
            duration: 'variable',
            featured: false,
            why: 'A journalism professor who cooks with honest economy — his knife work is unfussy and practical, aimed at someone with a weeknight and a cutting board.',
          },
        ],
        books: [
          {
            title: 'On Food and Cooking: The Science and Lore of the Kitchen',
            author: 'Harold McGee',
            year: 1984,
            url: 'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
            why: 'The standard reference on what is happening to the food in front of you. First published 1984, revised in 2004. Every serious cook has a copy.',
          },
          {
            title: 'Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking',
            author: 'Samin Nosrat',
            year: 2017,
            url: 'https://www.saltfatacidheat.com/',
            why: 'The modern primer on the four fundamentals. Nosrat, a Chez Panisse alumna, teaches cooking as a set of principles rather than a list of recipes.',
          },
          {
            title: 'The Professional Chef',
            author: 'The Culinary Institute of America',
            year: 1962,
            url: 'https://www.ciachef.edu/the-professional-chef/',
            why: 'The CIA\'s textbook, now in its ninth edition. The chapter on knife skills is what American culinary students are taught on day one.',
          },
          {
            title: 'The Food Lab: Better Home Cooking Through Science',
            author: 'J. Kenji López-Alt',
            year: 2015,
            url: 'https://www.kenjilopezalt.com/the-food-lab',
            why: 'Six hundred recipes and a thousand pages of why-it-works, from the former chief editor of Serious Eats. The knife-skills chapter shows the grip in full-page photographs.',
          },
        ],
        articles: [
          {
            title: 'Chef\'s knife',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Chef%27s_knife',
            why: 'The history and geometry of the tool. Good diagrams of German versus French versus Japanese blade shapes.',
            year: null,
          },
          {
            title: 'Knife Skills Illustrated: A User\'s Manual',
            source: 'Peter Hertzmann (archived)',
            url: 'https://www.hertzmann.com/articles/2004/knives/',
            why: 'A patient, illustrated, non-commercial guide by a longtime culinary writer. Includes cutting grids and a sharpening primer.',
            year: 2004,
          },
          {
            title: 'How to Sharpen Kitchen Knives',
            source: 'Cook\'s Illustrated',
            url: 'https://www.americastestkitchen.com/cooksillustrated/how_tos/6262-how-to-sharpen-kitchen-knives',
            why: 'The America\'s Test Kitchen version — sharpening angles, stone grits, and why the pull-through gadgets will eat your edge.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Culinary Techniques (free auditable course)',
            provider: 'Rouxbe',
            url: 'https://rouxbe.com/courses/culinary-techniques',
            free: false,
            why: 'The online culinary school that restaurants use to certify line cooks. The Knife Skills module is often available as a free preview.',
          },
          {
            title: 'Serious Eats Knife Skills Guide',
            provider: 'Serious Eats',
            url: 'https://www.seriouseats.com/knife-skills',
            free: true,
            why: 'A free, open index of Kenji\'s written knife tutorials paired with the Serious Eats video library. The equivalent of a week of culinary school, for nothing.',
          },
        ],
        tools: [
          {
            title: 'A single good chef\'s knife',
            url: 'https://en.wikipedia.org/wiki/Chef%27s_knife',
            why: 'A Victorinox Fibrox eight-inch costs under fifty dollars and outperforms blocks of knives that cost ten times more. Buy one. Learn it.',
          },
          {
            title: 'A combination whetstone (1000/6000 grit)',
            url: 'https://en.wikipedia.org/wiki/Sharpening_stone',
            why: 'Fifteen minutes, three times a year, is all a home knife needs. A single two-sided whetstone does both coarse repair and a finishing polish.',
          },
          {
            title: 'A honing steel',
            url: 'https://en.wikipedia.org/wiki/Honing_steel',
            why: 'Not for sharpening — for straightening. Three passes per side before every session keep the edge aligned between whetstone visits.',
          },
        ],
      },

      seeAlso: ['heat_transfer', 'seasoning', 'primals'],
      prereqs: [],
      leadsTo: ['heat_transfer', 'stocks', 'primals'],

      chapterActivity: 'A monthly "five-onions" knife-skills drop-in at a Cobble Hill community kitchen — a chef brings a case of onions, a stack of boards, and two hours.',

      sources: [
        'https://en.wikipedia.org/wiki/Chef%27s_knife',
        'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
        'https://www.saltfatacidheat.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    heat_transfer: {
      id: 'heat_transfer',
      name: 'Heat Transfer',
      level: 'Intermediate',
      dek: 'Everything that happens to food in a hot pan is one of four things — and knowing which is which is what separates a cook from an assembler.',
      readTime: '13 min',

      sections: ['Four modes, one stove', 'The dry heat of a sear', 'Water\'s ceiling', 'Why fat is a better conductor than air', 'The carry-over'],
      body: [
        { type: 'lead', text: 'In 1912, a young French chemist named Louis Camille Maillard noticed that when he warmed a solution of amino acids and sugar, it turned brown and started to smell like toast. He was trying to understand protein synthesis. He stumbled, instead, onto the reaction responsible for the flavor of a roast chicken, a coffee bean, a seared steak, and the crust of every loaf of bread ever baked. A hundred years later, nobody has written down all the molecules the reaction can produce. There are thousands.' },
        { type: 'h2', text: 'Four modes, one stove' },
        { type: 'p', text: 'Heat moves by conduction (touch), convection (a moving fluid), radiation (photons, mostly infrared), and evaporation (which removes heat, so it is cooling rather than heating). A covered pot of soup uses all four at once: the burner radiates to the pan, the pan conducts to the broth, the broth convects the heat through itself, and steam evaporates from the surface carrying heat out of the pot. A good cook thinks in these four modes without naming them.' },
        { type: 'h2', text: 'The dry heat of a sear' },
        { type: 'p', text: 'A steak on a dry cast-iron skillet at 230°C browns through the Maillard reaction, which requires temperatures above 140°C and an absence of liquid water. Water, at sea level, cannot rise above 100°C — it boils off first. This is why a damp pan will not sear: the meat\'s surface cools the iron below browning temperature until the water has evaporated, and by the time the pan recovers, the meat is gray and overcooked. Dry the meat first. Let the pan get hot. Do not crowd it.' },
        { type: 'h2', text: 'Water\'s ceiling and the 100°C problem' },
        { type: 'p', text: 'Any wet cooking — boiling, poaching, steaming, braising — is capped at water\'s boiling point. You cannot brown a thing underwater. This is why every braise begins with a sear: the flavor of the finished dish depends on the brown crust you build before the liquid goes in. A stew that skips this step tastes like boiled meat. Which is what it is.' },
        { type: 'h2', text: 'Why fat is a better conductor than air' },
        { type: 'p', text: 'A film of oil in the pan does more than keep the food from sticking. It fills the microscopic valleys between the food and the metal, giving heat a direct path. Oil conducts heat about fifteen times faster than air, which is why food cooked in a dry pan browns unevenly and food cooked in a thin layer of oil browns across its entire surface. The same logic governs deep frying: the oil is a thermal coupling medium, and its temperature sets the cooking rate.' },
        { type: 'h2', text: 'The carry-over cook' },
        { type: 'p', text: 'A roast chicken taken from a 220°C oven at an internal temperature of 70°C will continue to rise for another ten minutes — the outer layers are hotter than the inside, and their heat conducts inward as the bird rests. A cook who ignores carry-over overcooks everything they roast. A cook who learns to pull things ten degrees early, and lets the rest finish off the heat, never overcooks anything again.' },
        { type: 'callout', text: 'A digital probe thermometer costs about fifteen dollars and replaces a lifetime of guessing. The food\'s internal temperature is the only number that matters; the oven\'s set point is mostly a suggestion.' },
      ],

      keyTerms: ['Maillard reaction', 'conduction', 'convection', 'radiation', 'evaporation', 'carry-over cooking', 'caramelization', 'braising', 'searing'],

      resources: {
        videos: [
          {
            id: 'zCrFNZbI36Y',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=zCrFNZbI36Y',
            title: 'Maillard Reaction — Why does food brown?',
            channel: 'Reactions (American Chemical Society)',
            duration: '4:10',
            featured: true,
            why: 'The clearest four-minute animation of the Maillard reaction on YouTube. From the American Chemical Society\'s educational series.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@aragusea',
            title: 'Adam Ragusea — cooking science playlists',
            channel: 'Adam Ragusea',
            duration: 'variable',
            featured: true,
            why: 'Ragusea\'s "why do we flip the steak" and "why do we let meat rest" videos walk through heat transfer with honest skepticism about conventional wisdom.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@JKenjiLopezAlt',
            title: 'Kenji López-Alt — reverse-sear and sous-vide explainers',
            channel: 'J. Kenji López-Alt',
            duration: 'variable',
            featured: true,
            why: 'The reverse-sear method Kenji popularized is a lesson in heat transfer disguised as a technique: first convection at low temperature, then brief high-conduction sear.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@foodwishes',
            title: 'Chef John — Food Wishes full channel',
            channel: 'Food Wishes',
            duration: 'variable',
            featured: false,
            why: 'Fifteen years of patient weekly recipes explaining why each step matters. Chef John has the most quietly educational cooking channel on the internet.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@bingingwithbabish',
            title: 'Babish Culinary Universe — Basics with Babish',
            channel: 'Babish Culinary Universe',
            duration: 'variable',
            featured: false,
            why: 'Andrew Rea\'s "Basics" series is the most visually careful fundamentals course on YouTube — each episode is one technique, cleanly shot.',
          },
        ],
        books: [
          {
            title: 'On Food and Cooking: The Science and Lore of the Kitchen',
            author: 'Harold McGee',
            year: 1984,
            url: 'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
            why: 'The Heat chapter is the clearest plain-English account of what fire does to food anywhere in print. The standard reference since 1984.',
          },
          {
            title: 'Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking',
            author: 'Samin Nosrat',
            year: 2017,
            url: 'https://www.saltfatacidheat.com/',
            why: 'The Heat chapter is its own short course — when to go high and fast, when to go low and slow, and how to tell the two apart.',
          },
          {
            title: 'Modernist Cuisine: The Art and Science of Cooking',
            author: 'Nathan Myhrvold, Chris Young, Maxime Bilet',
            year: 2011,
            url: 'https://modernistcuisine.com/books/modernist-cuisine/',
            why: 'The five-volume technical reference. Volume 2 is almost entirely about heat transfer — with thermal imaging, cross-sections of roasts, and equations that a working cook will skim and a curious cook will love.',
          },
          {
            title: 'The Science of Good Cooking',
            author: 'America\'s Test Kitchen',
            year: 2012,
            url: 'https://www.americastestkitchen.com/books/the-science-of-good-cooking',
            why: 'Fifty principles, each tested in the ATK kitchen and explained in a page. The modern bench companion to McGee.',
          },
        ],
        articles: [
          {
            title: 'Maillard reaction',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Maillard_reaction',
            why: 'Good coverage of the chemistry, with temperature ranges and the acrylamide controversy at the high end.',
            year: null,
          },
          {
            title: 'Heat transfer',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Heat_transfer',
            why: 'The physics article — conduction, convection, radiation — grounded in the equations a cooking article never shows you.',
            year: null,
          },
          {
            title: 'The Food Lab: The Reverse-Sear Is the Best Way to Cook a Steak',
            source: 'Serious Eats',
            url: 'https://www.seriouseats.com/the-food-lab-complete-guide-to-sous-vide-steak',
            why: 'Kenji\'s long-form column on why low-then-hot cooks a better steak than hot-alone. An applied lesson in heat transfer.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Science and Cooking: From Haute Cuisine to Soft Matter Science',
            provider: 'Harvard / edX',
            url: 'https://www.edx.org/learn/food-science/harvard-university-science-and-cooking-from-haute-cuisine-to-soft-matter-science-chemistry',
            free: true,
            why: 'The Harvard course that opened chef demonstrations to undergraduate physics students. Ferran Adrià, David Chang, and physicists Michael Brenner and Pia Sörensen alternate weeks.',
          },
        ],
        tools: [
          {
            title: 'A digital probe thermometer',
            url: 'https://en.wikipedia.org/wiki/Meat_thermometer',
            why: 'A Thermoworks Dot or a ThermoPop is under thirty dollars, accurate within a degree, and the single biggest upgrade to a home cook\'s output.',
          },
          {
            title: 'A heavy cast-iron skillet',
            url: 'https://en.wikipedia.org/wiki/Cast-iron_cookware',
            why: 'Mass matters. A twelve-inch cast-iron pan holds enough heat to sear a steak without cooling, and costs a tenth what a comparable stainless pan does.',
          },
        ],
      },

      seeAlso: ['knife', 'seasoning', 'stocks', 'bread'],
      prereqs: ['knife'],
      leadsTo: ['stocks', 'smoke', 'bread'],

      chapterActivity: 'Quarterly "Maillard night" at a Queens community kitchen — five cooks, one ribeye each, five pans at five different temperatures, and a thermometer.',

      sources: [
        'https://en.wikipedia.org/wiki/Maillard_reaction',
        'https://en.wikipedia.org/wiki/Heat_transfer',
        'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
      ],
      verifiedAt: '2026-04-23',
    },

    seasoning: {
      id: 'seasoning',
      name: 'Salt & Seasoning',
      level: 'Beginner',
      dek: 'Seasoning is less about courage than timing — the difference between a good cook and a great one is usually when the salt went on.',
      readTime: '10 min',

      sections: ['What salt actually does', 'The timing question', 'Acid, fat, and the other pillars', 'Why a kitchen needs four salts', 'The last ten percent'],
      body: [
        { type: 'lead', text: 'In the 1960s, a New York food writer named James Beard watched a French chef season a chicken in his restaurant kitchen. The chef took a pinch of salt, held it a foot above the bird, and let it fall. Beard thought it was showmanship. It was not. The height let the salt distribute evenly across the skin, rather than piling up where the fingers opened. Decades later, when Samin Nosrat wrote a book arguing that salt was the first and most important pillar of good cooking, chefs recognized the argument as obvious and home cooks as a revelation.' },
        { type: 'h2', text: 'What salt actually does' },
        { type: 'p', text: 'Salt does three things. It seasons, meaning it wakes up flavors you already have. It draws water out of cells through osmosis, which is how a dry brine works on a turkey. And it unfolds proteins, which is why a salted steak, left overnight, develops a tacky skin that browns beautifully in a pan. All three effects depend on time. A pinch at the table seasons. A tablespoon the day before seasons, brines, and transforms.' },
        { type: 'h2', text: 'The timing question' },
        { type: 'p', text: 'Salt meat early — an hour before for thin cuts, a day before for thick ones — and the surface is dry when it hits the pan, which is what browning needs. Salt meat at the moment it meets the heat, and the salt will sit on top, bead out water, and steam rather than sear. Salt greens early and they weep; salt them late and they stay crisp. Every cooking mistake that tastes "under-seasoned" is often, in fact, under-timed.' },
        { type: 'h2', text: 'Acid, fat, and the other pillars' },
        { type: 'p', text: 'Nosrat\'s argument in Salt, Fat, Acid, Heat is that four elements explain almost every dish that works: enough salt, the right fat, the right acid to cut the fat, and the right kind of heat. A vinaigrette is oil plus vinegar plus salt. A braise is fat plus acid plus salt plus low heat. The grammar of cooking, once you see it, is small.' },
        { type: 'h2', text: 'Why a kitchen needs four salts' },
        { type: 'p', text: 'Diamond Crystal kosher, for almost everything — its flakes stick to food, dissolve quickly, and a tablespoon weighs about half what a tablespoon of Morton\'s does, which matters more in a recipe than anyone admits. Fine sea salt for baking, where gram weights matter. Maldon or a similar flake for the finish, when a salty crunch at the last second is the point. Fleur de sel for the occasional special thing. Four salts, one shelf, and everything a home kitchen needs.' },
        { type: 'h2', text: 'The last ten percent' },
        { type: 'p', text: 'A dish seasoned exactly enough is a dish you do not think about seasoning. You taste it and reach for the next bite. A dish under-seasoned is a dish you reach for the salt shaker on, because your tongue is telling you something is missing. The fastest way to close the last ten percent of a recipe is to taste, add a quarter teaspoon, taste again, and stop when you stop thinking about it.' },
        { type: 'quote', text: 'Salt has a greater impact on flavor than any other ingredient.', cite: 'Samin Nosrat, Salt Fat Acid Heat' },
      ],

      keyTerms: ['kosher salt', 'sea salt', 'dry brine', 'wet brine', 'osmosis', 'seasoning in layers', 'finishing salt', 'umami'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://www.netflix.com/title/80198288',
            title: 'Salt Fat Acid Heat (four-part series)',
            channel: 'Netflix',
            duration: '4 × 50:00',
            featured: true,
            why: 'Samin Nosrat travels to Italy, Japan, Mexico, and California — one episode for each pillar. The Salt episode is in Japan, at a soy-sauce brewery.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@JKenjiLopezAlt',
            title: 'Kenji López-Alt — salt-related videos',
            channel: 'J. Kenji López-Alt',
            duration: 'variable',
            featured: true,
            why: 'Kenji\'s dry-brine-a-turkey, salt-your-steak-early, and measure-salt-by-weight videos are the single best argument for cooking by feel with a kitchen scale.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@aragusea',
            title: 'Adam Ragusea — salt and seasoning videos',
            channel: 'Adam Ragusea',
            duration: 'variable',
            featured: true,
            why: 'Ragusea\'s "why I salt my pasta water," "why I don\'t brine anymore," and "why your soup is under-seasoned" are honest, low-production explanations of first-principle seasoning.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@foodwishes',
            title: 'Food Wishes — salt-focused recipes',
            channel: 'Chef John',
            duration: 'variable',
            featured: false,
            why: 'Chef John\'s phrase "you are after all the season tuner of your own salt" has become a running joke. It is also the whole lesson.',
          },
        ],
        books: [
          {
            title: 'Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking',
            author: 'Samin Nosrat',
            year: 2017,
            url: 'https://www.saltfatacidheat.com/',
            why: 'The canonical modern argument. Illustrated by Wendy MacNaughton; the world salt map on page 12 is worth the price of the book.',
          },
          {
            title: 'Salt: A World History',
            author: 'Mark Kurlansky',
            year: 2002,
            url: 'https://www.penguinrandomhouse.com/books/121059/salt-by-mark-kurlansky/',
            why: 'The classic popular history of the mineral that started wars and ran empires. A meditation on why salt mattered before refrigerators.',
          },
          {
            title: 'On Food and Cooking',
            author: 'Harold McGee',
            year: 1984,
            url: 'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
            why: 'The Seasoning and the Chemistry of Flavor chapters explain why salt does what it does at the molecular level.',
          },
          {
            title: 'The Flavor Bible',
            author: 'Karen Page, Andrew Dornenburg',
            year: 2008,
            url: 'https://www.karenandandrew.com/books',
            why: 'A cross-reference of ingredient pairings drawn from interviews with dozens of American chefs. Not a cookbook — a dictionary of affinities.',
          },
        ],
        articles: [
          {
            title: 'Salt',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Salt',
            why: 'History, production, chemistry, and the public-health debate. A good place to start before the Kurlansky book.',
            year: null,
          },
          {
            title: 'The Trick to Seasoning Food Perfectly, Every Time',
            source: 'Serious Eats',
            url: 'https://www.seriouseats.com/how-to-properly-season-food',
            why: 'Sho Spaeth\'s plain-English breakdown of when to salt, by what weight, and what the common mistakes look like on the plate.',
            year: null,
          },
          {
            title: 'How Umami Became the 5th Taste',
            source: 'Smithsonian Magazine',
            url: 'https://www.smithsonianmag.com/arts-culture/what-is-umami-180982127/',
            why: 'The century-long story of a Tokyo chemist, a dashi broth, and a molecule that the West took a hundred years to recognize.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Samin Nosrat Teaches Home Cooking',
            provider: 'MasterClass',
            url: 'https://www.masterclass.com/classes/samin-nosrat-teaches-home-cooking',
            free: false,
            why: 'The MasterClass version of Salt Fat Acid Heat, taught by Nosrat herself with live demos. Paid — but public libraries sometimes offer free access.',
          },
        ],
        tools: [
          {
            title: 'A kitchen scale (gram-accurate)',
            url: 'https://en.wikipedia.org/wiki/Kitchen_scale',
            why: 'Diamond Crystal kosher salt weighs about 3 grams per teaspoon; Morton\'s weighs almost double. A recipe that says "one teaspoon kosher salt" is a recipe that assumes you read the side of the box.',
          },
          {
            title: 'A small pinch bowl',
            url: 'https://en.wikipedia.org/wiki/Pinch_bowl',
            why: 'Keeping an open bowl of salt at arm\'s length is the single habit that separates cooks who season well from cooks who do not.',
          },
        ],
      },

      seeAlso: ['heat_transfer', 'stocks', 'bread', 'primals'],
      prereqs: [],
      leadsTo: ['stocks', 'bread', 'smoke'],

      chapterActivity: 'A "taste the difference" salt-tasting hour at a Park Slope community kitchen — four salts, one tomato, one slice of bread, and a blindfold.',

      sources: [
        'https://www.saltfatacidheat.com/',
        'https://en.wikipedia.org/wiki/Salt',
        'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
      ],
      verifiedAt: '2026-04-23',
    },

    stocks: {
      id: 'stocks',
      name: 'Stocks & Sauces',
      level: 'Intermediate',
      dek: 'Every serious kitchen in the Western tradition rests on a short pantry of sauces, and all five of them rest on a good stock.',
      readTime: '13 min',

      sections: ['What a stock really is', 'The five mother sauces', 'The brown-versus-white fork in the road', 'The small-sauce tree', 'A gallon on the back burner'],
      body: [
        { type: 'lead', text: 'Auguste Escoffier arrived at the Savoy Hotel in London in 1890 at the invitation of César Ritz, and spent the next decade rewriting how Western restaurants worked. He broke the kitchen into stations with a single chef in charge of each, a system called the brigade. He wrote Le Guide Culinaire, a five-thousand-recipe reference that doubled as a curriculum. And he declared — though really he inherited the claim from Marie-Antoine Carême — that every serious French sauce is a variation on one of five. A hundred and twenty years later, every culinary student in the world learns these five in their first month.' },
        { type: 'h2', text: 'What a stock really is' },
        { type: 'p', text: 'Stock is water that has spent six to twelve hours with bones, mirepoix, and patience. Collagen in the bones dissolves into gelatin, which gives the liquid body. The vegetables — traditionally a two-to-one-to-one mix of onion, carrot, and celery — add sweetness and backbone. A proper stock, cooled, should wobble on a spoon like loose gelatin dessert. That wobble is the proof that it will thicken a sauce without any help from flour.' },
        { type: 'h2', text: 'The five mother sauces' },
        { type: 'p', text: 'Béchamel is milk thickened with a white roux. Velouté is a light stock — chicken, fish, or veal — thickened the same way. Espagnole is a brown stock thickened with a brown roux and deepened with tomato. Tomato sauce is, canonically, a tomato sauce. Hollandaise is an emulsion of clarified butter into egg yolks, held together by lecithin. Escoffier codified the first four; the modern list of five replaces mayonnaise with hollandaise and has stayed put since roughly 1907.' },
        { type: 'h2', text: 'The brown-versus-white fork in the road' },
        { type: 'p', text: 'A white stock starts with raw bones and clear vegetables; the liquid stays pale and the flavor stays clean. A brown stock starts with roasted bones and caramelized mirepoix; the Maillard reaction in the roasting pan gives the finished stock its color and a deeper, meatier dimension. White for lighter sauces, cream soups, and poultry velouté. Brown for beef sauces, demi-glace, and the long game.' },
        { type: 'h2', text: 'The small-sauce tree' },
        { type: 'p', text: 'From béchamel: mornay (add cheese), soubise (onion), nantua (crayfish butter). From velouté: suprême (cream), allemande (egg yolks), bercy (shallots and wine). From espagnole: demi-glace (reduced by half), bordelaise (red wine and marrow), robert (mustard and onion). The pattern is the same everywhere: a mother sauce is a platform; a small sauce is what you build on it for this plate. The system is elegant the first time you see it.' },
        { type: 'h2', text: 'A gallon on the back burner' },
        { type: 'p', text: 'A home cook does not need five mother sauces. A home cook needs one good stock, made on a Sunday, cooled overnight, and frozen in pint containers. Chicken is the best default — it builds anything, it stores well, and it makes the worst weeknight soup into a competent one. Save the bones from every roast bird. Save the vegetable ends. Simmer, strain, cool, freeze. The home version of Escoffier\'s system is two hours of work a month and a freezer that transforms every meal after.' },
        { type: 'callout', text: 'Never boil a stock. A rolling boil emulsifies the fat back into the liquid and produces a cloudy, greasy result. Barely-moving surface ripples are the sign the pot has been set right.' },
      ],

      keyTerms: ['stock', 'mirepoix', 'roux', 'béchamel', 'velouté', 'espagnole', 'hollandaise', 'demi-glace', 'emulsion', 'collagen'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@JKenjiLopezAlt',
            title: 'Kenji López-Alt — roast-chicken and pressure-cooker stock videos',
            channel: 'J. Kenji López-Alt',
            duration: 'variable',
            featured: true,
            why: 'Kenji\'s pressure-cooker-stock method turns twelve hours of simmering into ninety minutes with no measurable loss. The single best modernization of the technique.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@foodwishes',
            title: 'Chef John — mother-sauce series',
            channel: 'Food Wishes',
            duration: 'variable',
            featured: true,
            why: 'Chef John\'s béchamel, velouté, and hollandaise episodes are ten-minute, first-person, voice-over demonstrations. The calmest teacher on the internet.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@aragusea',
            title: 'Adam Ragusea — stocks, gravies, and sauces',
            channel: 'Adam Ragusea',
            duration: 'variable',
            featured: true,
            why: 'Ragusea\'s pragmatic "do I really need to do this" approach is a good counter to classical orthodoxy — he makes a case for thirty-minute chicken stock that is honest about the tradeoff.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@bingingwithbabish',
            title: 'Binging with Babish — Basics: Stocks',
            channel: 'Babish Culinary Universe',
            duration: 'variable',
            featured: false,
            why: 'Andrew Rea\'s Basics series includes a patient half-hour on building white and brown stocks from scratch. Good for first-timers.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.youtube.com/watch?v=tlK5nt1aTmY',
            title: 'Jacques Pépin — Classic Chicken Stock',
            channel: 'KQED',
            duration: '3:45',
            featured: false,
            why: 'Jacques Pépin, ninety years old in the clip, making stock the way he was taught in 1950s Paris. Every gesture is economical.',
          },
        ],
        books: [
          {
            title: 'Le Guide Culinaire',
            author: 'Auguste Escoffier',
            year: 1903,
            url: 'https://en.wikipedia.org/wiki/Le_Guide_culinaire',
            why: 'The book. Five thousand recipes, the origin of the five-sauce system, and the still-standard cross-reference for classical French cuisine. The Crane-Davies English translation is the one to own.',
          },
          {
            title: 'The Professional Chef',
            author: 'The Culinary Institute of America',
            year: 1962,
            url: 'https://www.ciachef.edu/the-professional-chef/',
            why: 'The CIA\'s textbook. The stocks-and-sauces chapters are how American culinary students are taught the system Escoffier codified.',
          },
          {
            title: 'Ratio: The Simple Codes Behind the Craft of Everyday Cooking',
            author: 'Michael Ruhlman',
            year: 2009,
            url: 'https://ruhlman.com/ratio-2/',
            why: 'Ruhlman\'s argument that all the mother sauces, and almost everything else in the kitchen, reduce to a handful of ingredient ratios. Once you see them, you stop needing recipes.',
          },
          {
            title: 'Sauces: Classical and Contemporary Sauce Making',
            author: 'James Peterson',
            year: 1991,
            url: 'https://www.jamespetersonbooks.com/sauces',
            why: 'The modern reference. Peterson teaches Escoffier\'s system from the top of the tree down to the small sauces, with photographs of each step. The saucier\'s standard since 1991.',
          },
          {
            title: 'On Food and Cooking',
            author: 'Harold McGee',
            year: 1984,
            url: 'https://en.wikipedia.org/wiki/On_Food_and_Cooking',
            why: 'McGee\'s chapter on gravies and sauces explains the emulsion chemistry (hollandaise, mayonnaise) and the gelatin extraction (stock) at a level no cookbook bothers with.',
          },
        ],
        articles: [
          {
            title: 'Mother sauce',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Mother_sauce',
            why: 'The lineage from Carême to Escoffier to the modern five. A good first orientation before opening Le Guide Culinaire.',
            year: null,
          },
          {
            title: 'Stock (food)',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Stock_(food)',
            why: 'Covers fond blanc, fond brun, dashi, master stock, and the stock-versus-broth debate. Well-cited, with pointers to the classical references.',
            year: null,
          },
          {
            title: 'Auguste Escoffier',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Auguste_Escoffier',
            why: 'The life. The brigade system, Le Guide Culinaire, the Savoy, and the 1898 kickback scandal that eventually cost him his job.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Stocks & Sauces (free module)',
            provider: 'Rouxbe',
            url: 'https://rouxbe.com/cooking-school/',
            free: false,
            why: 'Rouxbe\'s professional track runs through Escoffier\'s sauces in order. Modules are sometimes free to audit; the full certification is paid.',
          },
          {
            title: 'Science and Cooking',
            provider: 'Harvard / edX',
            url: 'https://www.edx.org/learn/food-science/harvard-university-science-and-cooking-from-haute-cuisine-to-soft-matter-science-chemistry',
            free: true,
            why: 'The Harvard free course. The unit on emulsions (hollandaise, mayonnaise) is the cleanest explanation of why egg yolks hold clarified butter together.',
          },
        ],
        tools: [
          {
            title: 'A tall narrow stockpot (12 qt or larger)',
            url: 'https://en.wikipedia.org/wiki/Stockpot',
            why: 'A narrow, tall pot minimizes evaporation and keeps bones submerged. A shallow pot is for soup; a stockpot is for stock.',
          },
          {
            title: 'A fine-mesh chinois',
            url: 'https://en.wikipedia.org/wiki/Chinois',
            why: 'The conical strainer is the difference between a finished stock and a cloudy one. Line it with a double layer of cheesecloth for the final strain.',
          },
          {
            title: 'An immersion blender',
            url: 'https://en.wikipedia.org/wiki/Immersion_blender',
            why: 'Builds an emulsified hollandaise or mayonnaise in thirty seconds, with no risk of breaking. The tool that made the technique safe for a weeknight.',
          },
        ],
      },

      seeAlso: ['heat_transfer', 'seasoning', 'primals', 'bread'],
      prereqs: ['knife', 'heat_transfer'],
      leadsTo: ['smoke', 'aged', 'classics'],

      chapterActivity: 'A "Sunday stock pot" at the Greenpoint chapter kitchen: bring a bag of bones, leave with a quart of pressure-cooker stock and a recipe for what to do with it Monday.',

      sources: [
        'https://en.wikipedia.org/wiki/Mother_sauce',
        'https://en.wikipedia.org/wiki/Stock_(food)',
        'https://en.wikipedia.org/wiki/Auguste_Escoffier',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
