// content/datascience.js
// Owned by batch: B06-tech-and-code
// Last updated: 2026-04-23 by BATCH B06-tech-and-code
//
// Topics this subject covers (from data.js):
//   Core: cleaning, viz

window.CONTENT = window.CONTENT || {};
window.CONTENT.datascience = {
  subjectId: 'datascience',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B06-tech-and-code',
  topics: {

    cleaning: {
      id: 'cleaning',
      name: 'Data Cleaning',
      level: 'Intermediate',
      dek: 'The unglamorous two-thirds of the job — turning a real-world mess into something you can analyze without lying.',
      readTime: '14 min',

      sections: ['The survey that started the cliché', 'What "messy" actually means', 'Tidy data, a simple idea', 'Imputation, or: be honest about what you changed', 'Cleaning as reproducible code', 'A working pipeline in 2026'],
      body: [
        { type: 'lead', text: 'In 2014 the New York Times ran a story with a line that has been quoted in every data-science curriculum since: working analysts told the reporter they spent "50 to 80 percent of their time" cleaning data. Nobody who has done the job disputes the number. The cleaning is not preamble. It is the job. Every real-world dataset arrives with missing values, inconsistent formats, duplicate rows, timezone confusions, and columns that mean two different things in different years. Analysis cannot begin until these are resolved, and how they are resolved is almost always the thing that makes the analysis honest or dishonest.' },
        { type: 'h2', text: 'What actually breaks' },
        { type: 'p', text: 'Names spelled three ways. Dates as strings, as Unix timestamps, as Excel serial numbers. A column called "revenue" that switched from dollars to cents in 2022 when accounting changed systems. Integer zeros that mean the measurement failed and floating-point zeros that mean the measurement was zero. A customer record that shows up twice because the email was re-capitalized. None of these are exotic. All of them will corrupt a naive analysis quietly.' },
        { type: 'p', text: 'The practical move is to profile the data before you do anything else. Count rows. Count nulls. Histogram every numeric column and show it to yourself. Sample ten random rows of every string column and read them. Look for "NULL" and "N/A" and "-" as string values; for dates in the year 1900 and 1970 (defaults for missing); for a column that is 80% the mode. Every oddity is a conversation with a data engineer you have not yet had, and it is better to have it now than after the chart is printed.' },
        { type: 'h2', text: 'Tidy data: one row, one observation' },
        { type: 'p', text: 'In 2014 Hadley Wickham published a paper called Tidy Data in the Journal of Statistical Software. It laid out a simple structure: each variable is a column, each observation is a row, each type of observational unit is a table. The paper sounds obvious and is not. Most of what cleaning code does is shaping data into that form, because once data is tidy, a surprising amount of the rest of analysis becomes easy. The tidyverse in R and the pandas and Polars libraries in Python all build on this shape.' },
        { type: 'animation',
          youtubeId: '4FlQlY2_MtU',
          caption: 'Alex The Analyst — a live pandas cleaning walkthrough on a real messy file. The actual moves.',
          credit: 'Alex The Analyst, YouTube.',
        },
        { type: 'h2', text: 'Imputation, or: be honest about what you changed' },
        { type: 'p', text: 'A hard case: a column with missing values. Dropping the row throws away information. Filling with the mean, or the last observation, or a model-predicted value changes the distribution. There is no universally correct answer, and the wrong move is pretending the problem is not there. Record the rule you used, apply it reproducibly, and make sure the downstream model knows which values were imputed. Donald Rubin\'s multiple-imputation framework, from 1987, is still the rigorous baseline.' },
        { type: 'callout', text: 'A dataset is never "clean" in the abstract. It is clean enough for a particular question. Writing down the question first is what keeps cleaning from becoming infinite.' },
        { type: 'h2', text: 'Cleaning is reproducible code, not one-off Excel' },
        { type: 'p', text: 'The professional move is to write the cleaning as code — a pipeline that takes raw files in and produces clean tables out, every time, the same way. Next quarter\'s data has the same problems as last quarter\'s, plus new ones. Hand-editing a spreadsheet makes the result unverifiable, irreproducible, and impossible to redo at scale. The rule in working data teams since the 2010s: every transformation is a commit, every dataset is versioned, every decision is in the script.' },
        { type: 'p', text: 'The payoff compounds. A cleaning pipeline that ran in five minutes on last quarter\'s data will run in five minutes on this quarter\'s too. A cleaning session that required two days in Excel will require two days again, and the second time you will not remember what you did the first. Every senior data person has watched a junior re-do, by hand, work the junior already did. The cure is code.' },
        { type: 'h2', text: 'A working pipeline in 2026' },
        { type: 'p', text: 'The modern stack: Polars or pandas for small-to-medium tabular work; DuckDB for SQL against local files; dbt for transformations in a warehouse; Great Expectations or Pandera for data contracts and tests; Git for version control; a notebook (Jupyter, Marimo, Observable) for exploration; a pipeline tool (Prefect, Dagster, Airflow, or just a Makefile) to run the whole thing end to end. None of this is exotic. A competent data engineer can assemble it in a week. A team that treats cleaning as code rather than as a pre-step ships reliably, forever.' },
        { type: 'aside', label: 'The Reinhart–Rogoff mistake', text: 'In 2013 Thomas Herndon, a U-Mass graduate student, tried to reproduce Reinhart and Rogoff\'s influential 2010 debt-and-growth paper. He found three errors — including a spreadsheet cell that skipped five countries — that changed the headline finding. The paper had influenced European austerity policy. The lesson: check the cleaning, and if the analysis will influence anyone, let someone else check it too.' },
      ],

      keyTerms: ['tidy data', 'missing value', 'imputation', 'dedup', 'normalization', 'schema', 'ETL', 'reproducibility', 'pandas', 'data contract'],

      examples: [
        {
          title: 'Tidy vs. untidy',
          problem: 'Untidy:\n  country | 2020 | 2021 | 2022\n  France  | 100  | 110  | 120\n  Germany | 90   | 95   | 100',
          steps: [
            { text: 'In the untidy form, the years are columns. Each ROW is a country, and each COLUMN is a year.' },
            { text: 'The fix: make each row a single (country, year, value) observation.' },
            { text: 'Tidy:\n  country | year | value\n  France  | 2020 | 100\n  France  | 2021 | 110\n  France  | 2022 | 120\n  Germany | 2020 | 90\n  Germany | 2021 | 95\n  Germany | 2022 | 100' },
            { text: 'Now: filter by year, group by country, plot with ggplot — all one-liners. The untidy form forces a reshape for almost every operation.' },
          ],
          answer: 'Each row one observation; each column one variable.',
        },
        {
          title: 'Counting nulls in pandas',
          problem: 'import pandas as pd\ndf = pd.read_csv("data.csv")\ndf.isnull().sum()',
          steps: [
            { text: 'df.isnull() returns a DataFrame of Booleans — True where the cell is null.' },
            { text: '.sum() sums each column. True = 1, False = 0, so the sum is the count of nulls per column.' },
            { text: 'Printed output looks like:\n  name        0\n  email      12\n  age       301\n  dtype: int64' },
            { text: 'age has 301 nulls. That is your signal to investigate — why? Missing, never-collected, or a sentinel value like -1?' },
          ],
          answer: 'A one-liner that surfaces the missing-value profile.',
        },
      ],

      practice: [
        { q: 'Who formalized the "tidy data" framework, and in what year?',
          a: 'Hadley Wickham in 2014', acceptable: ['wickham', '2014', 'wickham 2014'],
          difficulty: 'medium', hint: 'Published in the Journal of Statistical Software.',
          solution: 'Hadley Wickham, 2014. The paper is the ideological foundation of tidyverse and pandas-style work.' },
        { q: 'What fraction of a typical data scientist\'s time goes to cleaning?',
          a: '50-80%', acceptable: ['50 to 80', '50–80', 'most', 'majority', '60%', '70%', '80%'],
          difficulty: 'easy', hint: 'The 2014 NYT figure.',
          solution: '50 to 80 percent, per the 2014 NYT "janitor work" article. No working analyst disputes the number.' },
        { q: 'Which tool lets you query a CSV with SQL in two lines of Python?',
          a: 'DuckDB', acceptable: ['duckdb', 'duck db'],
          difficulty: 'medium', hint: 'Embeddable analytical database, 2020s.',
          solution: 'DuckDB. Install, point at a file, run SELECT. One of the most popular tools in data teams in 2026.' },
      ],

      subtopics: [
        {
          id: 'cleaning.tidy_data',
          name: 'Tidy data',
          summary: 'One row per observation, one column per variable, one table per kind of thing.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'The paper is three pages long and reshapes how you think about data forever. The rule: each variable in a column, each observation in a row, each kind of observational unit in its own table. A dataset that obeys these three rules is tidy.' },
            { type: 'p', text: 'Why it matters: once the data is tidy, an enormous fraction of the work you want to do becomes one-liners. Filtering, grouping, summarizing, plotting. The verbs in dplyr (R) and the methods in pandas (Python) all assume tidy shape.' },
          ],
          practice: [
            { q: 'A spreadsheet has columns Jan, Feb, Mar (monthly sales). Is it tidy?',
              a: 'no', acceptable: ['n', 'false', 'untidy', 'not tidy'],
              difficulty: 'easy', hint: 'Months are values of a variable, not variables themselves.',
              solution: 'No. The months are values of a "month" variable. Tidy form: two columns, month and sales, with a row per month.' },
          ],
          keyTerms: ['tidy', 'long format', 'wide format', 'pivot', 'reshape'],
        },
        {
          id: 'cleaning.imputation',
          name: 'Imputation — what to do about missing values',
          summary: 'Drop, fill, predict, or flag. There is no universally correct answer.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'Real data has gaps. Dropping rows throws away information; filling with the mean shifts distributions; filling with the last value assumes stability. The wrong move is not choosing — letting missing values default-propagate will produce subtle, hard-to-find bugs downstream.' },
            { type: 'p', text: 'Donald Rubin\'s 1987 multiple-imputation framework is still the rigorous baseline. Generate several plausible filled-in datasets, run the analysis on each, pool the results with a known variance correction. In practice, simpler techniques (mean/median/mode, indicator columns for "was missing") handle most business-grade work.' },
          ],
          practice: [
            { q: 'If you fill missing ages with the mean, what happens to the age distribution\'s variance?',
              a: 'decreases', acceptable: ['shrinks', 'reduces', 'smaller', 'decrease'],
              difficulty: 'hard', hint: 'More values exactly at the mean.',
              solution: 'Variance decreases. You have added values exactly at the mean, which lowers the spread. This can distort downstream analyses.' },
          ],
          keyTerms: ['missing at random', 'imputation', 'multiple imputation', 'indicator', 'missingness'],
        },
      ],

      resources: {
        videos: [
          { id: '4FlQlY2_MtU', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=4FlQlY2_MtU',
            title: 'Data Cleaning in Pandas — Python Tutorial',
            channel: 'Alex The Analyst', duration: '38:35',
            why: 'A live, line-by-line pandas cleaning walkthrough on a real file.' },
          { id: 'ZOX4R_M2JNM', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=ZOX4R_M2JNM',
            title: 'StatQuest — What is a Histogram?',
            channel: 'StatQuest with Josh Starmer', duration: '4:03',
            why: 'Josh Starmer\'s channel is the friendliest intro to statistics on YouTube. Start with histograms.' },
          { id: 'vmEHCJofslg', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=vmEHCJofslg',
            title: 'Pandas for Data Science in 20 Minutes',
            channel: 'Programming with Mosh', duration: '24:16',
            why: 'A short, current introduction to the library most cleaning code is written in.' },
          { id: 'CGx-jaqV0PQ', source: 'youtube', url: 'https://www.youtube.com/watch?v=CGx-jaqV0PQ',
            title: 'Polars — A Faster Pandas',
            channel: 'Ritchie Vink (Polars creator)', duration: '30:00',
            why: 'The 2020s successor to pandas, by the person who wrote it. Why and how it is different.' },
          { id: 'dR4Mz6hP1y8', source: 'youtube', url: 'https://www.youtube.com/watch?v=dR4Mz6hP1y8',
            title: 'DuckDB — The Database Every Analyst Needs',
            channel: 'DuckDB Conference 2024', duration: '22:00',
            why: 'The analytical database that has swept through data teams in 2024–25.' },
          { id: 'htp7FMFIuB4', source: 'youtube', url: 'https://www.youtube.com/watch?v=htp7FMFIuB4',
            title: 'What Is dbt and Why Is Everyone Using It?',
            channel: 'Mehdi Ouazza', duration: '11:00',
            why: 'The transformation tool most modern data teams standardized on, explained.' },
        ],
        books: [
          { title: 'R for Data Science (2nd edition)',
            author: 'Hadley Wickham, Mine Çetinkaya-Rundel, Garrett Grolemund', year: 2023,
            url: 'https://r4ds.hadley.nz/',
            why: 'The standard free online textbook for doing data work in R.' },
          { title: 'Python for Data Analysis (3rd edition)',
            author: 'Wes McKinney', year: 2022,
            url: 'https://wesmckinney.com/book/',
            why: 'By the creator of pandas. Free online, third edition.' },
          { title: 'Storytelling with Data',
            author: 'Cole Nussbaumer Knaflic', year: 2015, url: '',
            why: 'A short, practical book on the handoff between cleaning and communication.' },
          { title: 'Fundamentals of Data Engineering',
            author: 'Joe Reis and Matt Housley', year: 2022, url: '',
            why: 'The book every data engineer in 2026 has on the shelf. The way data actually moves in modern organizations.' },
        ],
        articles: [
          { title: 'Tidy Data',
            source: 'Hadley Wickham, Journal of Statistical Software',
            url: 'https://www.jstatsoft.org/article/view/v059i10',
            why: 'The paper that named the framework most modern data tools are built around.', year: 2014 },
          { title: 'pandas documentation — Working with missing data',
            source: 'pandas.pydata.org',
            url: 'https://pandas.pydata.org/docs/user_guide/missing_data.html',
            why: 'The practical reference on imputation strategies in the library most people use.' },
          { title: 'For Big-Data Scientists, "Janitor Work" Is Key Hurdle to Insights',
            source: 'New York Times (Steve Lohr, 2014)',
            url: 'https://www.nytimes.com/2014/08/18/technology/for-big-data-scientists-hidden-work-hurdle-to-insights.html',
            why: 'The article that produced the 50–80% statistic every data-science course uses.', year: 2014 },
          { title: 'Does High Public Debt Consistently Stifle Economic Growth? A Critique of Reinhart and Rogoff',
            source: 'Herndon, Ash, Pollin (U-Mass Amherst)',
            url: 'https://www.peri.umass.edu/publication/item/download/634_6a5cb7f7fe55c68d13dce21d27ea0f4c',
            why: 'The paper that caught a famous spreadsheet mistake. Required reading on why your cleaning matters.', year: 2013 },
        ],
        courses: [
          { title: 'CS109 — Data Science (Harvard)',
            provider: 'Harvard University',
            url: 'https://harvard-iacs.github.io/2021-CS109A/', free: true,
            why: 'A full Harvard data-science course. Lectures, notebooks, homework.' },
          { title: 'Data Science Specialization',
            provider: 'Johns Hopkins (Coursera)',
            url: 'https://www.coursera.org/specializations/jhu-data-science', free: true,
            why: 'The original ten-course Coursera specialization. Pragmatic, R-based, still the most widely-taken data-science program on the internet.' },
        ],
        tools: [
          { title: 'pandas', url: 'https://pandas.pydata.org/',
            why: 'The Python library most cleaning code is written in.' },
          { title: 'Polars', url: 'https://pola.rs',
            why: 'A modern Rust-based alternative to pandas. Much faster on large files.' },
          { title: 'OpenRefine', url: 'https://openrefine.org/',
            why: 'An open-source GUI tool for cleaning messy spreadsheets — clustering similar values, splitting columns, tracing a history of transformations.' },
          { title: 'DuckDB', url: 'https://duckdb.org',
            why: 'SQL against a CSV in two lines. The analytical engine data engineers have standardized on.' },
          { title: 'Great Expectations', url: 'https://greatexpectations.io',
            why: 'Tests for data. Declare what the data should look like; fail loudly when it does not.' },
        ],
        primarySources: [
          { title: 'Wickham, Tidy Data paper (2014)',
            url: 'https://www.jstatsoft.org/article/view/v059i10',
            why: 'The founding paper of the modern data-shaping toolkit.' },
          { title: 'Codd, A Relational Model of Data (1970)',
            url: 'https://www.seas.upenn.edu/~zives/03f/cis550/codd.pdf',
            why: 'Tidy data is in a direct line from Codd\'s normalization rules. Read them together.' },
        ],
        images: [],
        animations: [
          { youtubeId: '4FlQlY2_MtU',
            title: 'Data Cleaning in Pandas',
            channel: 'Alex The Analyst',
            why: 'Watch the actual moves on a real file.' },
        ],
      },

      interactive: null,
      seeAlso: ['viz', 'stats', 'databases'],
      prereqs: ['programming'],
      leadsTo: ['viz'],

      chapterActivity: 'A Wednesday-evening "bring your messiest CSV" workshop at a Chinatown public-library computer lab — pair up, clean one file each, present the hardest decision you made.',

      sources: [
        'https://www.jstatsoft.org/article/view/v059i10',
        'https://r4ds.hadley.nz/',
        'https://wesmckinney.com/book/',
      ],
      verifiedAt: '2026-04-23',
    },

    viz: {
      id: 'viz',
      name: 'Visualization',
      level: 'Intermediate',
      dek: 'Drawing numbers so the eye learns what the spreadsheet is hiding.',
      readTime: '15 min',

      sections: ['Snow, Playfair, Minard', 'Tufte and the integrity principle', 'The grammar of graphics', 'Perception hierarchies', 'Pick the chart the question wants', 'Tools for the working analyst'],
      body: [
        { type: 'lead', text: 'In 1854 a London doctor named John Snow was trying to convince an unconvinced city that cholera was waterborne. He walked door to door, plotted each death as a black bar on a map of Soho, and discovered that the bars clustered on the Broad Street pump. The map did not prove his theory — that came later — but it was the first piece of evidence anyone could see without having to think like an epidemiologist. Data visualization, done well, does that: it turns a claim into something the eye is willing to believe.' },
        { type: 'figure',
          src: 'content/images/snow_cholera.jpg',
          alt: 'John Snow\'s 1854 map of cholera deaths in Soho, London.',
          caption: 'John Snow\'s original 1854 map. Each black bar is a death; the cluster around the Broad Street pump changed how London thought about water, sewers, and epidemic disease.',
          credit: 'Public domain, via Wikimedia Commons.',
        },
        { type: 'h2', text: 'A short lineage of great charts' },
        { type: 'p', text: 'William Playfair, a Scottish engineer, invented the line graph, the bar chart, and the pie chart in the 1780s while working on the British budget. Florence Nightingale drew her famous polar-area diagrams in 1858 to argue that more British soldiers in the Crimea were dying of infection than of bullets, and got the army hospitals reformed. Charles Joseph Minard\'s 1869 map of Napoleon\'s Russian campaign — the single best-known infographic in the world — shows the army\'s size, its path, the temperature, and the retreat in one image. None of them had the word "visualization." All of them knew what they were doing.' },
        { type: 'figure',
          src: 'content/images/minard_napoleon.png',
          alt: 'Charles Joseph Minard\'s map of Napoleon\'s 1812 Russian campaign.',
          caption: 'Minard\'s 1869 map of the 1812 Russian campaign. Size of army (band width), path, temperature on the retreat — all in one image. Tufte called it "the best statistical graphic ever drawn."',
          credit: 'Public domain, via Wikimedia Commons.',
        },
        { type: 'h2', text: 'Tufte: do not lie with ink' },
        { type: 'p', text: 'Edward Tufte self-published The Visual Display of Quantitative Information in 1983 and changed the field. His rules are strict: maximize the data-ink ratio, label directly instead of with a legend, avoid chartjunk, never use 3D when 2D will do, keep the axes honest. The book is a genuine work of design — Tufte typeset it himself — and the principles it names have since become invisible infrastructure in every serious newsroom graphic and every good scientific paper.' },
        { type: 'figure',
          src: 'content/images/nightingale_rose.jpg',
          alt: 'Florence Nightingale\'s rose/polar-area diagram of mortality in the Crimean War.',
          caption: 'Florence Nightingale\'s 1858 diagram. Blue: deaths from infection. Red: deaths from wounds. Black: other. She used it to argue for sanitary reform in military hospitals, and got it.',
          credit: 'Public domain, via Wikimedia Commons.',
        },
        { type: 'h2', text: 'The grammar of graphics' },
        { type: 'p', text: 'In 1999 Leland Wilkinson published The Grammar of Graphics, arguing that every statistical chart can be broken into a small set of composable parts — data, aesthetics (what color, what shape, what position), geometries (points, lines, bars), scales, facets. Hadley Wickham implemented that grammar as the R package ggplot2 in 2005, and most modern plotting libraries (plotnine, Altair, Vega-Lite, Observable Plot) are descendants. Once you see a chart as a grammar, you stop picking from a menu of chart types and start composing.' },
        { type: 'animation',
          youtubeId: 'hVimVzgtD6w',
          caption: 'Hans Rosling, "The best stats you\'ve ever seen" — twenty minutes that changed how a generation thought about what a chart can do.',
          credit: 'TED, 2006.',
        },
        { type: 'h2', text: 'Perception hierarchies' },
        { type: 'p', text: 'William Cleveland and Robert McGill, in 1984, did careful experiments on how accurately people can read different visual encodings. The ranking they produced has held up. Position along a common axis is read most accurately. Then position along identical non-aligned axes. Then length, then angle, then area, then color intensity. Pie charts fail early in this ranking. The reason a bar chart is "boring" is the reason a bar chart works — position on a common axis is what the eye measures best.' },
        { type: 'callout', text: 'Above all else, show the data. Then make it hard to lie about.' },
        { type: 'h2', text: 'Pick the chart the question wants' },
        { type: 'p', text: 'Comparing categories: bar chart. Showing change over time: line chart. Showing a distribution: histogram, box plot, violin. Showing two variables: scatter. Showing geography: map. Showing part-of-whole: not a pie chart, despite tradition — a stacked bar or a small multiple almost always communicates better. The discipline is matching the question to the encoding, and saying out loud what question the chart is meant to answer before you draw.' },
        { type: 'h2', text: 'Tools for the working analyst' },
        { type: 'p', text: 'The 2026 toolkit: matplotlib or seaborn for quick Python; Altair for the grammar-of-graphics experience in Python; Observable Plot or Vega-Lite for publication-quality interactive charts; Datawrapper for newsroom-speed charts; d3.js for genuinely custom work; ggplot2 for the R world. A working chart usually lives in a notebook first; a shipping chart usually lives in Datawrapper, Vega-Lite, or a custom d3 build. The tools matter less than the discipline.' },
        { type: 'aside', label: 'The Upshot', text: 'Most of the best chart work in American journalism since 2014 has come out of the New York Times\' data team — The Upshot. Worth subscribing just for the charts. The Economist, Financial Times, Bloomberg Graphics, and The Pudding round out the working canon. Save the ones you love; you will refer to them.' },
        { type: 'quote', text: 'Above all else, show the data.', cite: 'Edward Tufte, The Visual Display of Quantitative Information' },
      ],

      keyTerms: ['chart', 'encoding', 'data-ink', 'small multiple', 'grammar of graphics', 'ggplot', 'histogram', 'scatter plot', 'chartjunk', 'chart literacy'],

      examples: [
        {
          title: 'Choosing a chart',
          problem: 'You have: state, population. 50 rows. What chart?',
          steps: [
            { text: 'Comparing values across a handful of categories is a bar chart. A pie chart would be terrible at 50 slices.' },
            { text: 'Sort the bars by population. Sorted bars communicate rank; alphabetical bars communicate nothing.' },
            { text: 'If you must show all 50, a horizontal bar chart fits labels better than vertical.' },
            { text: 'If you only want the top 10, slice — and add "+ 40 more" to tell the reader what was cut.' },
          ],
          answer: 'Sorted horizontal bar chart. Optionally truncate to top-N.',
        },
        {
          title: 'Why pie charts fail',
          problem: 'A pie chart with 8 similar-sized slices.',
          steps: [
            { text: 'Humans read position along a common axis (the bar) much more accurately than angle or area (the pie).' },
            { text: 'With slices of similar size, the eye cannot reliably rank them. Which is biggest? You cannot say without labels.' },
            { text: 'A sorted bar chart with the same data lets the reader see the ranks at a glance.' },
            { text: 'Cleveland and McGill proved this experimentally in 1984 and no one has overturned them. Use pie charts only for 2-3 slices where the proportion is the whole message.' },
          ],
          answer: 'Position-on-axis beats angle. Use bars, not pies.',
        },
      ],

      practice: [
        { q: 'Who made the 1854 Soho cholera map?',
          a: 'John Snow', acceptable: ['snow'],
          difficulty: 'easy', hint: 'A London doctor.',
          solution: 'John Snow. The map clustered deaths around the Broad Street pump and helped end the outbreak.' },
        { q: 'Whose 1869 map shows Napoleon\'s 1812 Russian campaign?',
          a: 'Charles Joseph Minard', acceptable: ['minard'],
          difficulty: 'medium', hint: 'French civil engineer.',
          solution: 'Charles Joseph Minard. Tufte called it "the best statistical graphic ever drawn."' },
        { q: 'In the Cleveland-McGill perception ranking, which is read most accurately?',
          a: 'position along a common axis', acceptable: ['position', 'position on common axis', 'common axis'],
          difficulty: 'medium', hint: 'Where bar charts win.',
          solution: 'Position along a common axis. Why bar charts and dot plots beat pie charts at almost every job.' },
      ],

      subtopics: [
        {
          id: 'viz.chart_choice',
          name: 'Choosing the right chart',
          summary: 'Bar, line, scatter, histogram, small multiple. Start here.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'Comparing categories: bar. Showing change over time: line. Distribution of a single variable: histogram or box plot. Relationship between two numeric variables: scatter. A single scalar "part of whole" with 2-3 slices: reluctantly, pie. Anything spatial: map. Small multiples everywhere — they are almost always better than layered lines.' },
            { type: 'p', text: 'The discipline is matching the question to the encoding. If you cannot say the question in one sentence before choosing the chart, choosing the chart is premature.' },
          ],
          practice: [
            { q: 'You want to show the relationship between a country\'s GDP and its life expectancy, for 200 countries. What chart?',
              a: 'scatter plot', acceptable: ['scatter'],
              difficulty: 'easy', hint: 'Two numeric variables, many observations.',
              solution: 'A scatter plot. Each country is a dot. Add a regression line or LOESS smooth if you want to hint at the trend.' },
          ],
          keyTerms: ['bar', 'line', 'scatter', 'histogram', 'box plot', 'small multiple', 'choropleth'],
        },
        {
          id: 'viz.grammar_of_graphics',
          name: 'The grammar of graphics',
          summary: 'Data + aesthetic mappings + geoms + scales. The language behind ggplot.',
          level: 'Advanced', readTime: '8 min',
          body: [
            { type: 'lead', text: 'Leland Wilkinson\'s 1999 book argued that every chart decomposes into a handful of layers: data, aesthetic mappings (what maps to x, y, color, size), geometric objects (points, lines, bars), scales (how data values become visual values), facets (small multiples), coordinate systems. Compose, not pick from a menu.' },
            { type: 'p', text: 'Hadley Wickham\'s ggplot2 (R, 2005) implemented the grammar and changed statistical graphics forever. Altair (Python/Vega), Observable Plot (JavaScript), and plotnine (Python) are all descendants. Once you can think in layers, you stop asking "what chart do I want" and start asking "what mappings do I want?"' },
          ],
          practice: [
            { q: 'In ggplot2 grammar, what does "geom" stand for?',
              a: 'geometric object', acceptable: ['geometry', 'geometric', 'geom'],
              difficulty: 'medium', hint: 'Points, lines, bars.',
              solution: 'Geometric object — the visible mark (point, line, bar, area) that represents each data record.' },
          ],
          keyTerms: ['geom', 'aesthetic', 'scale', 'facet', 'layer', 'coordinate system'],
        },
      ],

      resources: {
        videos: [
          { id: 'hVimVzgtD6w', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=hVimVzgtD6w',
            title: 'The best stats you\'ve ever seen',
            channel: 'Hans Rosling (TED)', duration: '19:50',
            why: 'Rosling on the Gapminder data, in 2006. Twenty minutes that changed how a generation thought about what a chart can do.' },
          { id: 'fPz-i1rxiyc', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=fPz-i1rxiyc',
            title: 'Edward Tufte on Data Visualization',
            channel: 'Susquehanna International Group', duration: '35:49',
            why: 'Tufte himself, in a recorded talk.' },
          { id: 'h4pPSQFS9To', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=h4pPSQFS9To',
            title: 'Data Visualization — Computerphile',
            channel: 'Computerphile', duration: '9:55',
            why: 'A short, working-engineer\'s take on the basics.' },
          { id: 'v5gxlKLvZKk', source: 'youtube', url: 'https://www.youtube.com/watch?v=v5gxlKLvZKk',
            title: 'Data Visualization and D3.js Course',
            channel: 'freeCodeCamp.org / Shirley Wu', duration: '4:04:28',
            why: 'A four-hour free course in d3.js from one of the genuinely great practitioners.' },
          { id: '4EXNedimDMs', source: 'youtube', url: 'https://www.youtube.com/watch?v=4EXNedimDMs',
            title: 'A Graphic Look at Graphics — Alberto Cairo',
            channel: 'The Functional Art', duration: '34:00',
            why: 'Alberto Cairo, journalist and data-viz author, on principles and examples.' },
          { id: 'Yyzg6fUczOU', source: 'youtube', url: 'https://www.youtube.com/watch?v=Yyzg6fUczOU',
            title: 'The Beauty of Data Visualization',
            channel: 'David McCandless / TED', duration: '17:54',
            why: 'A classic, accessible talk on beautiful-and-useful charts.' },
          { id: 'hpLj3nB3YIc', source: 'youtube', url: 'https://www.youtube.com/watch?v=hpLj3nB3YIc',
            title: 'How to Lie with Statistics — in Charts',
            channel: 'How To Lie with Statistics / Digestible Media', duration: '12:00',
            why: 'The cautionary companion to Tufte. The tricks to look out for in charts you did not make.' },
        ],
        books: [
          { title: 'The Visual Display of Quantitative Information',
            author: 'Edward Tufte', year: 2001,
            url: 'http://www.edwardtufte.com/books/',
            why: 'The classic. Second edition, 2001, still in print. The book every other visualization book is arguing with.' },
          { title: 'The Grammar of Graphics',
            author: 'Leland Wilkinson', year: 2005, url: '',
            why: 'Second edition. The theoretical foundation under ggplot2 and half the modern plotting libraries.' },
          { title: 'The Truthful Art',
            author: 'Alberto Cairo', year: 2016, url: '',
            why: 'The best modern introduction. Cairo is a journalist and a designer.' },
          { title: 'Storytelling with Data',
            author: 'Cole Nussbaumer Knaflic', year: 2015, url: '',
            why: 'The most practical book on charts-as-communication. What to cut, how to annotate, where the reader\'s eye goes.' },
          { title: 'Better Data Visualizations',
            author: 'Jonathan Schwabish', year: 2021, url: '',
            why: 'A 2021 reference on chart types — when each works, when it fails, how to improve the common ones.' },
        ],
        articles: [
          { title: 'The Pudding — visual essays',
            source: 'The Pudding', url: 'https://pudding.cool/',
            why: 'A data-journalism publication whose whole output is a master class.' },
          { title: 'The Upshot',
            source: 'The New York Times', url: 'https://www.nytimes.com/section/upshot',
            why: 'The Times\' data and analysis vertical.' },
          { title: 'Data visualization', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Data_visualization',
            why: 'A reasonable survey with a usable bibliography; the Minard section alone is worth the visit.' },
          { title: 'Cleveland & McGill — Graphical Perception (1984)',
            source: 'JASA', url: 'https://www.cs.ubc.ca/~tmm/courses/cpsc533c-04-spr/readings/cleveland.pdf',
            why: 'The foundational perception paper. Every modern viz course quotes its ranking of encodings.', year: 1984 },
          { title: 'Financial Times Visual Vocabulary',
            source: 'Financial Times',
            url: 'https://ft-interactive.github.io/visual-vocabulary/',
            why: 'A one-page poster of every chart type worth knowing, with when each works. Print it.' },
        ],
        courses: [
          { title: 'Data Visualization — University of Illinois (Coursera)',
            provider: 'University of Illinois',
            url: 'https://www.coursera.org/learn/datavisualization', free: true,
            why: 'Professor John C. Hart\'s course, auditable for free.' },
          { title: 'D3 in Depth (free book + course)',
            provider: 'Peter Cook',
            url: 'https://www.d3indepth.com/', free: true,
            why: 'The clearest free introduction to d3.js in 2026. Project-based.' },
        ],
        tools: [
          { title: 'Observable Plot',
            url: 'https://observablehq.com/plot/',
            why: 'A modern JavaScript plotting library in the Wilkinson grammar, from the team that made D3. Fast, expressive, current as of 2026.' },
          { title: 'Vega-Lite',
            url: 'https://vega.github.io/vega-lite/',
            why: 'A high-level declarative grammar for statistical graphics. JSON specs compile to D3.' },
          { title: 'Datawrapper',
            url: 'https://www.datawrapper.de/',
            why: 'Used by the New York Times, The Guardian, and most newsrooms. Free tier is generous.' },
          { title: 'Altair',
            url: 'https://altair-viz.github.io/',
            why: 'The Python port of Vega-Lite. The shortest path from a DataFrame to a publishable chart.' },
          { title: 'ggplot2',
            url: 'https://ggplot2.tidyverse.org/',
            why: 'The R library that defined the modern grammar-of-graphics experience.' },
        ],
        primarySources: [
          { title: 'John Snow, Broad Street pump map (1854)',
            url: 'https://en.wikipedia.org/wiki/1854_Broad_Street_cholera_outbreak',
            why: 'The Wikipedia page with the original map, in context.' },
          { title: 'Minard, 1869 map of Napoleon\'s 1812 campaign',
            url: 'content/images/minard_napoleon.png',
            why: 'The image itself, high resolution.' },
          { title: 'Playfair, Commercial and Political Atlas (1786)',
            url: 'content/images/playfair_timeseries.png',
            why: 'One of the first line charts in history, drawn for a British Treasury report.', year: 1786 },
        ],
        images: [
          { src: 'content/images/snow_cholera.jpg',
            caption: 'John Snow\'s 1854 cholera map — the founding document of public-health visualization.',
            credit: 'Public domain, Wikimedia Commons.' },
          { src: 'content/images/minard_napoleon.png',
            caption: 'Minard\'s map of Napoleon\'s 1812 campaign — "the best statistical graphic ever drawn" (Tufte).',
            credit: 'Public domain, Wikimedia Commons.' },
          { src: 'content/images/nightingale_rose.jpg',
            caption: 'Florence Nightingale\'s 1858 polar-area diagram — the chart that reformed British army hospitals.',
            credit: 'Public domain, Wikimedia Commons.' },
          { src: 'content/images/playfair_timeseries.png',
            caption: 'William Playfair\'s 1786 time-series — the first modern line chart.',
            credit: 'Public domain, Wikimedia Commons.' },
        ],
        animations: [
          { youtubeId: 'hVimVzgtD6w',
            title: 'The best stats you\'ve ever seen',
            channel: 'Hans Rosling',
            why: 'The talk that made Gapminder famous.' },
        ],
      },

      interactive: null,
      seeAlso: ['cleaning', 'stats', 'design'],
      prereqs: ['cleaning', 'stats'],
      leadsTo: [],

      chapterActivity: 'A monthly "chart critique" at a Williamsburg coffee shop — each attendee brings a chart they made or hated, everyone redraws one on paper.',

      sources: [
        'http://www.edwardtufte.com/books/',
        'https://en.wikipedia.org/wiki/Data_visualization',
        'https://pudding.cool/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
