// content/economics.js
// Owned by batch: B05-social-world
// Last updated: 2026-04-23 by BATCH B05-social-world
//
// Topics this subject must cover (from data.js):
//   Core: micro, macro, behavioral_econ
//
// Expansion pass 2026-04-23: deeper lesson bodies, ~10 videos per topic,
// 7+ books, 5+ articles, podcasts + interactive tools where available.

window.CONTENT = window.CONTENT || {};
window.CONTENT.economics = {
  subjectId: 'economics',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B05-social-world',
  topics: {

    // ——— MICROECONOMICS ———
    micro: {
      id: 'micro',
      name: 'Microeconomics',
      level: 'Beginner',
      dek: 'The study of how households and firms decide, and of the prices that emerge when their decisions meet.',
      readTime: '17 min',

      sections: ['Smith\'s butcher', 'Supply and demand', 'The marginal revolution', 'Elasticity', 'When markets fail', 'Why the simple story is still useful'],
      body: [
        { type: 'lead', text: 'In Edinburgh in 1776, the year the American colonies declared their independence, a Scottish moral philosopher named Adam Smith published a thousand-page book he had been writing for most of a decade. The Wealth of Nations is the founding text of the discipline, and its most famous sentence is still its best: "It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest."' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/AdamSmith.jpg?width=900', caption: 'Adam Smith (1723–1790), Scottish moral philosopher. He held that his earlier book, The Theory of Moral Sentiments (1759), was the better of his two — a corrective worth remembering before quoting The Wealth of Nations.', credit: 'Public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'The two curves that organize everything' },
        { type: 'p', text: 'The first thing a microeconomics course teaches is the demand curve — how the quantity of a good that buyers want falls as its price rises — and the supply curve, which does the opposite. Drawn on the same axes, they cross once, and the point where they cross is the equilibrium: the price at which the market clears. Alfred Marshall formalized the picture in Principles of Economics (1890). It is still the workhorse diagram of the field.' },
        { type: 'p', text: 'The diagram is idealized in a dozen ways. Real buyers have imperfect information, real sellers have fixed costs, real goods are heterogeneous. And yet, the prediction that a binding price ceiling produces shortages, that a quota produces higher prices and lower quantities, that a tax gets split between buyer and seller according to the relative elasticity of each — these predictions hold up in the data again and again. The model works because it captures the core of an enormous amount of behavior with very few moving parts.' },
        { type: 'h2', text: 'The marginal revolution' },
        { type: 'p', text: 'In the 1870s, three economists in three countries — William Stanley Jevons in England, Carl Menger in Austria, Léon Walras in Switzerland — independently had the same insight: value comes not from total usefulness but from the usefulness of the next unit. A glass of water is priceless in the desert and worthless in the rain, not because water changed but because the marginal glass did. The "marginal revolution" ended the classical puzzle about why diamonds cost more than water and set up almost every piece of modern economic reasoning.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Supply-demand-equilibrium.svg?width=900', caption: 'The supply-and-demand diagram as Alfred Marshall drew it in 1890: two curves crossing once, producing the equilibrium price and quantity. Still the workhorse image of introductory economics.', credit: 'Paweł Zdziarski (faxe), CC BY-SA 3.0, via Wikimedia Commons' },
        { type: 'h2', text: 'Elasticity' },
        { type: 'p', text: 'Elasticity measures how much quantity responds to a change in price. Gasoline is inelastic in the short run (you drive roughly the same amount whether gas is three dollars or five) and more elastic in the long run (you eventually buy a smaller car). Cigarettes are famously inelastic — which is why taxing them raises revenue without reducing smoking much. Luxury goods tend to be elastic — small price cuts can generate big volume gains. Most of what gets called "strategy" in a business school case is an argument about elasticity in disguise.' },
        { type: 'h2', text: 'When markets fail' },
        { type: 'p', text: 'Microeconomics does not claim that markets always work; it is, in fact, mostly a theory of when they do and when they don\'t. Externalities (a factory pumping smoke at its neighbors), public goods (a lighthouse, a national defense), information asymmetry (George Akerlof\'s famous 1970 paper on the market for used cars), and market power (a monopoly) each break the first-week story. Most policy economics is an argument about how badly, and whether the cure is worse than the disease.' },
        { type: 'p', text: 'The twentieth century invented an impressive toolkit for each of these failures. Pigouvian taxes (named for Arthur Pigou) try to put a price on pollution. Mechanism design, the field for which Leonid Hurwicz, Eric Maskin, and Roger Myerson shared the 2007 Nobel, engineers markets where none would emerge naturally — kidney matching, spectrum auctions, school choice. A good microeconomics course spends as much time on the failures as on the ideal.' },
        { type: 'h2', text: 'Why the simple story is still useful' },
        { type: 'p', text: 'For most of human history, famines were caused by poor harvests. Since about 1970, almost every famine has been caused by a breakdown of exchange — war, blockade, hyperinflation — not a shortfall of food. That observation, Amartya Sen\'s, is microeconomics at its best: unglamorous curves that turn out to describe something morally urgent. The subject is easy to mock as "the dismal science"; it is harder to see that the same frame illuminates something as mundane as grocery pricing and as terrible as starvation, and that it does so without much rhetorical effort.' },
        { type: 'quote', text: 'It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest.', cite: 'Adam Smith, The Wealth of Nations (1776)' },
        { type: 'callout', text: 'Elinor Ostrom\'s 2009 Nobel was, in part, a rebuke to the assumption that common-pool resources must be either privatized or nationalized. Her fieldwork in Nepali irrigation systems and Swiss alpine meadows showed that local communities, left alone, often evolve their own micro-economic institutions for managing a shared resource — and that those institutions work.' },

        { type: 'h2', text: 'Learn it: a worked example (price ceilings in apartments)' },
        { type: 'p', text: 'Set up the model. Suppose the monthly rental market in a small city has a demand curve Q_d = 10,000 – 5·P (quantity demanded falls by 5 apartments for every additional dollar of monthly rent) and a supply curve Q_s = –2,000 + 5·P (landlords supply more units as the price rises). In a free market, equilibrium is where Q_d = Q_s. Solve: 10,000 – 5P = –2,000 + 5P, so 12,000 = 10P, and P* = $1,200 per month. At that price, 4,000 apartments clear the market. Nobody is in a queue; nobody is vacant.' },
        { type: 'p', text: 'Now impose a rent ceiling at P = $900 (below equilibrium). At $900, Q_d = 10,000 – 5·900 = 5,500 apartments demanded. Q_s = –2,000 + 5·900 = 2,500 apartments supplied. The shortage is Q_d – Q_s = 3,000 apartments. The 2,500 people who do get one pay less; the other 3,000 find nothing. In the long run, owners convert to condos or let buildings deteriorate — supply shrinks further. This is roughly what happened in New York, Berlin, and Stockholm under hard price controls, and the stylized mechanism is the reason most economists distrust ceilings even when the politics are sympathetic.' },
        { type: 'p', text: 'What the example shows: the supply-and-demand diagram is not a rule about what prices *should* be. It is a prediction about what happens when you block adjustment. The prediction is robust enough that two generations of empirical housing research have largely confirmed the story — with sharper nuance about long-run supply elasticity and about the distribution of who ends up with scarce units.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. A café sells 200 coffees per day at $4. It raises the price to $5 and sales fall to 170. Compute the own-price elasticity of demand, using the midpoint formula. Is demand elastic or inelastic over this range?' },
        { type: 'p', text: 'Answer: %ΔQ = (170 – 200) / ((170+200)/2) = –30/185 ≈ –16.2%. %ΔP = (5 – 4) / 4.50 ≈ 22.2%. Elasticity = –16.2 / 22.2 ≈ –0.73. |ε| < 1, so demand is inelastic in this range — the café earns more total revenue at $5 than at $4. Revenue at $4 = $800; at $5 = $850. The price increase was a good move.' },
        { type: 'p', text: 'Problem 2. A factory pollutes a river. Each unit of output produces $3 of downstream damage to local fishermen not paid for by the factory. The factory currently makes 1,000 units per month; the private marginal cost curve intersects marginal revenue at P = $10. What size Pigouvian tax would restore the socially efficient output, and which direction would output move?' },
        { type: 'p', text: 'Answer: The tax should equal the marginal external cost, $3 per unit. After the tax, the factory\'s effective marginal cost shifts up by $3 at every quantity. Output falls to the quantity where the new (higher) marginal cost equals marginal revenue. The policy point: the tax does not eliminate output; it aligns private and social cost, so the factory keeps producing the units that are still worth more than the total damage.' },
        { type: 'p', text: 'Problem 3. Two sellers in a small market: Alice has marginal cost $4, Bob has marginal cost $7. If the market price falls to $5, who sells and who stops? What does this tell you about supply curves being upward-sloping?' },
        { type: 'p', text: 'Answer: Alice sells (MC < price); Bob stops (MC > price). The market supply at $5 is Alice\'s output alone. Raise the price to $8 and both sell. The supply curve slopes up because the marginal seller at any given price is the one with the lowest cost still above that price — every price increase brings in another marginal seller.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) Why do price controls produce shortages rather than just lower prices? (2) Give one example each of an externality, a public good, information asymmetry, and market power. (3) Why are cigarettes inelastic and restaurant meals elastic? (4) What does "marginal" mean in "marginal cost"? (5) If the supply curve shifts right, what happens to equilibrium price and quantity? (6) Name one real-world case where Ostrom\'s design principles for common-pool resources apply.' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new to economics? Watch MRU\'s first ten micro videos, then sketch a supply-and-demand diagram from memory — label axes, both curves, equilibrium, surplus and shortage. When you can do that cold, you know the basic model. Once you\'ve got the basics? Read Marshall Book V (market equilibrium) and work through the first problem set of MIT 14.01SC. To go further? Study the chapters on market failures in any intermediate micro textbook (Perloff, Nicholson) and then pick one market failure and read three empirical papers that try to quantify it — labor-monopsony studies, emission-trading program evaluations, the used-car "lemons" literature. Serious students then take graduate micro (Mas-Colell, Whinston, and Green) or do a field course in industrial organization, labor, or development.' },
      ],

      keyTerms: ['supply', 'demand', 'equilibrium', 'marginal utility', 'elasticity', 'externality', 'public good', 'information asymmetry', 'market failure', 'Pigouvian tax', 'monopoly', 'mechanism design'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://mru.org/principles-economics-microeconomics',
            title: 'Principles of Economics: Microeconomics',
            channel: 'Marginal Revolution University',
            duration: '101 videos',
            why: 'Tyler Cowen and Alex Tabarrok\'s free microeconomics course. Short, clear, and written by two working academic economists with a popular audience.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://ocw.mit.edu/courses/14-01sc-principles-of-microeconomics-fall-2011/',
            title: 'MIT 14.01 Principles of Microeconomics — video lectures',
            channel: 'MIT OpenCourseWare',
            duration: '26 lectures',
            why: 'Jonathan Gruber\'s full MIT undergraduate course, recorded in lecture hall. Click into any session to watch. The gold standard for a university first course.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@marginalrevolutionuniversity',
            title: 'Marginal Revolution University (channel)',
            channel: 'Marginal Revolution University',
            duration: 'variable',
            why: 'Single-concept videos — elasticity, monopoly, rent control, price gouging — all under ten minutes. The cleanest free resource for microeconomic intuition.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/tim_harford_a_powerful_way_to_unleash_your_natural_creativity',
            title: 'Tim Harford — on markets and creative problem-solving',
            channel: 'TED2018',
            duration: '16:14',
            why: 'The Undercover Economist himself. A humane, readable economist explaining what his subject is actually for.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/alvin_roth_on_matching_and_markets',
            title: 'Alvin Roth on matching markets (recorded lecture)',
            channel: 'Nobel / TED',
            duration: 'variable',
            why: 'Alvin Roth, 2012 Nobel laureate, on mechanism design and the real-world design of kidney-exchange markets and medical-residency matching. Microeconomics in the wild.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — economics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Full-length public lectures by Nick Stern, Paul Krugman, Esther Duflo, Abhijit Banerjee, and others. Working economists at length.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/esther_duflo_social_experiments_to_fight_poverty',
            title: 'Social experiments to fight poverty',
            channel: 'TED2010',
            duration: '16:30',
            why: 'Esther Duflo, 2019 Nobel laureate, on randomized controlled trials in development economics. The applied side of modern micro.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardUniversity',
            title: 'Harvard Kennedy School — economics talks',
            channel: 'Harvard University',
            duration: 'variable',
            why: 'Recent lectures by Raj Chetty, Claudia Goldin, Larry Summers, and Gregory Mankiw. Search the channel for the topic.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/daniel_kahneman_the_riddle_of_experience_vs_memory',
            title: 'The Riddle of Experience vs Memory',
            channel: 'TED2010',
            duration: '20:34',
            why: 'Kahneman on the limits of the rational-actor assumption at the heart of classical micro. A door into the behavioral critique covered in the next topic.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@khanacademy',
            title: 'Khan Academy — Microeconomics (playlist)',
            channel: 'Khan Academy',
            duration: 'variable',
            why: 'Sal Khan\'s free full-length walkthrough of the AP Microeconomics curriculum. Paced for first-time learners; the best on-ramp if MRU feels fast.',
          },
        ],
        books: [
          {
            title: 'An Inquiry into the Nature and Causes of the Wealth of Nations',
            author: 'Adam Smith',
            year: 1776,
            url: 'https://www.gutenberg.org/ebooks/3300',
            why: 'The founding text. Read Book I, Chapters 1–3 (division of labor) and Chapter 7 (natural and market price). More readable than its reputation.',
          },
          {
            title: 'Principles of Economics',
            author: 'Alfred Marshall',
            year: 1890,
            url: 'https://archive.org/details/principlesecono00marsgoog',
            why: 'The Victorian textbook that gave the field its modern shape — and its supply-and-demand diagram. A clear window into how the classical project became the neoclassical one.',
          },
          {
            title: 'On the Principles of Political Economy and Taxation',
            author: 'David Ricardo',
            year: 1817,
            url: 'https://www.gutenberg.org/ebooks/33310',
            why: 'Ricardo on rent, wages, profit, and — crucially — comparative advantage. The case for specialized trade made once, cleanly.',
          },
          {
            title: 'The Worldly Philosophers',
            author: 'Robert Heilbroner',
            year: 1953,
            url: '',
            why: 'The best introduction in English to the great economists — Smith, Ricardo, Marx, Veblen, Keynes, Schumpeter — written for a general reader and still in print after seventy years.',
          },
          {
            title: 'The Undercover Economist',
            author: 'Tim Harford',
            year: 2005,
            url: '',
            why: 'Harford applies elementary microeconomics to coffee, traffic, and everyday life. The friendliest entry on this list; a gift book for a non-economist.',
          },
          {
            title: 'Principles of Economics',
            author: 'N. Gregory Mankiw',
            year: 1997,
            url: '',
            why: 'The dominant American undergraduate textbook across many editions. Not beloved by heterodox economists; still the one you will find in most first-year classrooms.',
          },
          {
            title: 'Good Economics for Hard Times',
            author: 'Abhijit V. Banerjee and Esther Duflo',
            year: 2019,
            url: '',
            why: 'Two MIT Nobel laureates on what economics can and cannot say about immigration, trade, inequality, and growth. The humane, contemporary version of the textbook.',
          },
        ],
        articles: [
          {
            title: 'Microeconomics',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Microeconomics',
            why: 'Broad, well-cited overview with a good section on market failures.',
            year: null,
          },
          {
            title: 'Philosophy of Economics',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/economics/',
            why: 'Daniel Hausman\'s long survey of what economists are doing when they model — the methodological questions every working economist eventually faces.',
            year: 2018,
          },
          {
            title: 'The Wealth of Nations (full text, Econlib)',
            source: 'Library of Economics and Liberty',
            url: 'https://www.econlib.org/library/Smith/smWN.html',
            why: 'Cannan\'s 1904 edition with a paragraph-level citation system. The scholar\'s copy.',
            year: null,
          },
          {
            title: 'Economics',
            source: 'Encyclopædia Britannica',
            url: 'https://www.britannica.com/topic/economics',
            why: 'Editorial overview of the whole field, useful for locating micro inside the bigger discipline.',
            year: null,
          },
          {
            title: 'Marginal utility',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Marginal_utility',
            why: 'The cleanest short reference on the idea that broke classical economics and made neoclassical economics possible.',
            year: null,
          },
          {
            title: 'Our World in Data — Economic growth',
            source: 'Our World in Data',
            url: 'https://ourworldindata.org/economic-growth',
            why: 'Max Roser\'s Oxford team keeps the best public dashboard of the empirical record. Every chart sourced and downloadable.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'MIT 14.01SC — Principles of Microeconomics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/14-01sc-principles-of-microeconomics-fall-2011/',
            free: true,
            why: 'Full Jonathan Gruber lecture series with problem sets, exams, and an open textbook.',
          },
          {
            title: 'Principles of Economics: Microeconomics (MRU)',
            provider: 'Marginal Revolution University',
            url: 'https://mru.org/principles-economics-microeconomics',
            free: true,
            why: 'Cowen–Tabarrok course, video-first, with exercises and a final exam. A friendlier on-ramp than MIT.',
          },
        ],
        podcasts: [
          {
            title: 'Planet Money',
            show: 'Planet Money (NPR)',
            url: 'https://www.npr.org/podcasts/510289/planet-money',
            duration: '≈30:00 per episode',
            why: 'Twenty-minute stories about how the economy works. The best general-audience economics podcast in English.',
          },
          {
            title: 'Conversations with Tyler',
            show: 'Mercatus Center / Tyler Cowen',
            url: 'https://conversationswithtyler.com/',
            duration: '≈60:00 per episode',
            why: 'Tyler Cowen\'s long conversations with economists, historians, and scientists. The interview with Raj Chetty is a particularly good intro to modern empirical micro.',
          },
          {
            title: 'Freakonomics Radio',
            show: 'Freakonomics Radio',
            url: 'https://freakonomics.com/archive/',
            duration: '≈45:00 per episode',
            why: 'Stephen Dubner\'s long-running show. Uneven at the edges; reliably good when the guest is a working economist.',
          },
        ],
        tools: [
          {
            title: 'FRED — Federal Reserve Economic Data',
            url: 'https://fred.stlouisfed.org/',
            why: 'The St. Louis Fed\'s database of over 800,000 economic time series, free, with interactive graphing. Every working economist uses it.',
          },
          {
            title: 'Our World in Data',
            url: 'https://ourworldindata.org/',
            why: 'Max Roser\'s chart-first public database. The best single starting place to see what the numbers actually say.',
          },
        ],
        primarySources: [
          {
            title: 'The Theory of Moral Sentiments (Smith, 1759)',
            url: 'https://www.econlib.org/library/Smith/smMS.html',
            why: 'Smith\'s first book, which he considered his better one. A necessary corrective to the caricature of Smith as a prophet of self-interest.',
          },
        ],
      },

      seeAlso: ['macro', 'behavioral_econ', 'class', 'stats'],
      prereqs: [],
      leadsTo: ['macro', 'behavioral_econ'],

      chapterActivity: 'A monthly market walk — a morning at the Union Square Greenmarket with a clipboard, tracking what the price of the same tomato does between 8 a.m. and closing, and what happens when rain breaks out at 10. Once a quarter, a field trip to the NYSE visitor gallery or to the NY Fed, and an evening over beers arguing about whether the data match the textbook.',

      sources: [
        'https://en.wikipedia.org/wiki/Microeconomics',
        'https://plato.stanford.edu/entries/economics/',
        'https://www.econlib.org/library/Smith/smWN.html',
        'https://en.wikipedia.org/wiki/Marginal_utility',
        'https://ourworldindata.org/economic-growth',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— MACROECONOMICS ———
    macro: {
      id: 'macro',
      name: 'Macroeconomics',
      level: 'Intermediate',
      dek: 'The economics of whole economies — unemployment, inflation, growth, and the arguments over what a government should do about them.',
      readTime: '20 min',

      sections: ['Keynes in 1936', 'The three headline numbers', 'What a central bank does', 'The long argument between schools', 'Growth, which eventually dominates', 'The open economy'],
      body: [
        { type: 'lead', text: 'In 1936, in the teeth of the Great Depression, John Maynard Keynes published a book whose opening sentence was a quiet piece of academic cheek: "I shall argue that the postulates of the classical theory are applicable to a special case only." The classical theory said economies return to full employment on their own. Cambridge and Washington had been watching this fail for seven years. The General Theory invented macroeconomics so that what was happening could be talked about at all.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Keynes_1933.jpg?width=900', caption: 'John Maynard Keynes (1883–1946), photographed in 1933. His 1936 General Theory created macroeconomics as a separate discipline and gave the mid-twentieth-century state its economic toolkit.', credit: 'Public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'The three numbers every economy reports' },
        { type: 'p', text: 'Macroeconomics organizes itself around three headline statistics. GDP — gross domestic product — measures the total market value of goods and services produced in a year. Unemployment measures the share of the labor force actively seeking work but not finding it. Inflation measures the rate at which the general level of prices is rising. Almost every policy argument in the news is ultimately about the trade-offs between these three.' },
        { type: 'p', text: 'Each number is a compromise. GDP misses the unpaid work that keeps households running (Marilyn Waring made the feminist case in the 1980s); it does not distinguish between productive and destructive output (a pipeline and a hurricane cleanup both count as growth); it does not capture distribution. But it is the best we have for a single-number summary of an economy\'s size, and its movements, watched quarterly, are genuinely informative.' },
        { type: 'h2', text: 'The central-bank toolkit' },
        { type: 'p', text: 'A central bank sets short-term interest rates and manages the money supply; through those two levers, it tries to keep inflation near a target (usually two percent) and unemployment as low as it can without setting inflation off. The Federal Reserve has been doing this since 1913, the Bank of England since 1694. The techniques have changed — open-market operations, quantitative easing, forward guidance, standing repo — but the basic job has not.' },
        { type: 'p', text: 'Since 2008, central banks have operated in increasingly exotic territory: zero and even negative interest rates, direct asset purchases in the trillions, coordinated interventions across currencies. The 2020s inflation, the biggest in forty years in most advanced economies, has pushed the same banks back toward the orthodoxy of the 1980s. The vocabulary of modern macro — "hiking cycle," "landing zone," "neutral rate" — is borrowed from aviation on purpose.' },
        { type: 'h2', text: 'The long argument between the schools' },
        { type: 'p', text: 'Macroeconomics is the branch of the field where the disagreements are loudest. Keynesians see a role for active fiscal and monetary policy; monetarists, following Milton Friedman, distrust fiscal intervention and watch the money supply; new classical and real-business-cycle economists treat recessions as optimal responses to real shocks; behavioral and heterodox economists challenge assumptions of rationality from several directions. A careful reader learns to notice which school an argument comes from without being told.' },
        { type: 'p', text: 'The Phillips curve — the empirical trade-off between unemployment and inflation — is the best example of the arguing. Discovered by the New Zealand economist A. W. Phillips in 1958, it suggested that policymakers could pick a point on the curve. Milton Friedman and Edmund Phelps argued in the 1960s that the curve was vertical in the long run: trying to buy lower unemployment with higher inflation would eventually give you both. The subsequent fifty years have produced a dozen "the Phillips curve is dead" and "the Phillips curve is back" op-eds. Both claims have been right at different times, which is the shape of the underlying argument.' },
        { type: 'h2', text: 'Growth, which eventually dominates' },
        { type: 'p', text: 'Over a five-year horizon, unemployment and inflation are the stories that matter. Over a fifty-year horizon, growth dwarfs them. A one-percentage-point difference in annual growth, compounded for a century, is the difference between a poor country and a rich one. Understanding what drives growth — capital, labor, technology, institutions, geography, human capital — is the quiet, slow-moving heart of the subject. Robert Solow\'s 1956 model, for which he won the 1987 Nobel, gave the field its workhorse framework; modern work by Daron Acemoglu and James Robinson on institutions extends it in consequential directions.' },
        { type: 'h2', text: 'The open economy' },
        { type: 'p', text: 'No modern country is a closed economy. Exchange rates, trade balances, capital flows, remittances, and foreign direct investment are all part of the macro picture. Robert Mundell\'s 1963 "impossible trinity" — a country cannot simultaneously fix its exchange rate, allow free capital movement, and run an independent monetary policy — is one of the cleanest and most durable results in the field. The euro crisis of the 2010s was, at root, a slow collision with that result.' },
        { type: 'callout', text: 'The Federal Reserve\'s congressional mandate, set in 1977, is a "dual mandate": maximum employment and stable prices. Most other central banks (the ECB, the Bank of England) are mandated on inflation alone. Which mandate a central bank operates under is not just legal trivia — it changes what the bank will do in a crisis.' },
        { type: 'quote', text: 'The ideas of economists and political philosophers, both when they are right and when they are wrong, are more powerful than is commonly understood.', cite: 'John Maynard Keynes, The General Theory (1936)' },

        { type: 'h2', text: 'Learn it: computing GDP three ways' },
        { type: 'p', text: 'A small economy produces two goods this year: 100 loaves of bread at $3 each, and 50 chairs at $40 each. What is GDP? Work through all three methods. Production (value-added) approach: 100·3 + 50·40 = 300 + 2,000 = $2,300. Expenditure approach: if all of it is bought by households (C), GDP = $2,300. Income approach: the same $2,300 is paid out as wages, rents, interest, and profit. All three methods give the same number by construction; that is the central accounting identity of macro, GDP = C + I + G + NX = total income.' },
        { type: 'p', text: 'Now distinguish nominal from real. Next year, the same economy produces 100 loaves at $4 and 50 chairs at $42. Nominal GDP = 400 + 2,100 = $2,500. Real GDP (using year-one prices as base) = 100·3 + 50·40 = $2,300 — unchanged. The GDP deflator = nominal/real = 2,500/2,300 ≈ 1.087, implying 8.7% inflation. Growth in real terms is 0%. When news headlines say "GDP rose 5%," always ask: real or nominal? What base year? What deflator?' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. An economy has 1,000 working-age adults. 600 are employed, 60 are unemployed (looking for work), 340 are not in the labor force (retired, students, caregivers). What are the labor-force participation rate and the unemployment rate?' },
        { type: 'p', text: 'Answer: Labor force = employed + unemployed = 660. Participation = 660/1,000 = 66%. Unemployment rate = 60/660 ≈ 9.1%. Crucial note: unemployment is measured against the labor force, not the population. A country can have falling unemployment and falling participation at the same time, which is why economists watch both numbers.' },
        { type: 'p', text: 'Problem 2. A central bank raises its policy interest rate from 2% to 4%. Trace through the likely effects on (a) borrowing cost for businesses, (b) the currency\'s exchange rate, (c) the stock market, (d) inflation, and (e) unemployment, assuming a 6-to-18-month lag.' },
        { type: 'p', text: 'Answer: (a) higher — corporate bonds and loans reprice; (b) the currency usually appreciates as higher yields attract foreign capital; (c) stocks typically fall in the short run (higher discount rate on future earnings, weaker outlook); (d) inflation should fall with a lag as demand cools; (e) unemployment typically rises, often peaking 12–18 months after the tightening cycle ends. This is the classic monetary-transmission sequence; 2022–2024 is a textbook case study.' },
        { type: 'p', text: 'Problem 3. In 1923 Germany, prices doubled roughly every 3.7 days at the peak of the hyperinflation. What is the implied annual inflation rate, and what does this tell you about the relationship between the money supply and prices?' },
        { type: 'p', text: 'Answer: Doubling every 3.7 days = about 98 doublings per year = 2^98, which is an annual inflation rate in the trillions of percent. This is what Milton Friedman meant when he said "inflation is always and everywhere a monetary phenomenon" — at the extremes, the relationship is mechanical. At normal low inflation rates, the relationship is much looser; the monetarist story is best at explaining catastrophes, not everyday price drift.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What is the accounting identity GDP = C + I + G + NX actually saying? (2) Why does the Federal Reserve try to move unemployment and inflation in opposite directions? (3) What is the difference between monetary and fiscal policy? (4) Name two things that are produced but not counted in GDP. (5) Draw a Phillips curve. What did Friedman and Phelps claim about its long-run shape? (6) In the Solow model, what happens to growth as an economy approaches its steady state?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Watch MRU\'s macro first-unit videos and one FOMC press conference in full. Read one Fed statement and Jerome Powell\'s opening remarks, then read one piece of news commentary on the same statement. When you can tell which school a commentator is drawing on, you\'ve learned the vocabulary. Once you\'ve got the basics? Read the first two chapters of Mankiw\'s Macroeconomics and the first two of Keynes\'s General Theory, back-to-back. Work through the Solow growth model on paper with sample numbers. To go further? Take Harvard\'s free Big Data course (Chetty), read Reinhart and Rogoff, and — if you\'re serious — sit in on David Romer\'s Berkeley Macro course. The advanced path is Sargent and Ljungqvist or Romer\'s Advanced Macroeconomics.' },
      ],

      keyTerms: ['GDP', 'inflation', 'unemployment', 'monetary policy', 'fiscal policy', 'business cycle', 'central bank', 'Phillips curve', 'recession', 'Solow model', 'impossible trinity', 'quantitative easing'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://mru.org/principles-economics-macroeconomics',
            title: 'Principles of Economics: Macroeconomics',
            channel: 'Marginal Revolution University',
            duration: 'approx. 90 videos',
            why: 'Cowen and Tabarrok\'s free macro course. Particularly good on the quantity theory of money and the mechanics of inflation.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@marginalrevolutionuniversity',
            title: 'MRU — Macro explainers',
            channel: 'Marginal Revolution University',
            duration: 'variable',
            why: 'Short standalone videos on recessions, hyperinflation, and monetary policy. Useful as a second pass on any lecture concept.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheEconomist',
            title: 'The Economist — explainers',
            channel: 'The Economist',
            duration: 'variable',
            why: 'Well-produced short videos on current monetary and fiscal events. Centrist-establishment in its politics; explicit about it; a good antidote to cable news coverage.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@ftvideo',
            title: 'Financial Times — Explained series',
            channel: 'Financial Times',
            duration: 'variable',
            why: 'The FT\'s video explainer channel, with particularly strong coverage of central banking and bond markets.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — macroeconomics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Full-length lectures by Paul Krugman, Mervyn King, Olivier Blanchard, and others. The field\'s senior figures at length.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/nick_hanauer_the_dirty_secret_of_capitalism_and_a_new_way_forward',
            title: 'The dirty secret of capitalism — and a new way forward',
            channel: 'TEDSummit 2019',
            duration: '17:37',
            why: 'Seattle entrepreneur Nick Hanauer on demand-side economics, the myth of trickle-down, and the political implications. Polemical but well-sourced.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/thomas_piketty_new_thoughts_on_capital_in_the_twenty_first_century',
            title: 'New thoughts on capital in the twenty-first century',
            channel: 'TED2014',
            duration: '20:42',
            why: 'Piketty\'s own compressed summary of the r > g argument and its implications for long-run macroeconomic policy.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/mariana_mazzucato_what_is_economic_value_and_who_creates_it',
            title: 'What is economic value, and who creates it?',
            channel: 'TEDSummit 2019',
            duration: '13:24',
            why: 'UCL economist Mariana Mazzucato on the state as innovator, and on the political economy of GDP. The heterodox voice, compressed.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardKennedySchool',
            title: 'Harvard Kennedy School — macro & policy',
            channel: 'Harvard Kennedy School',
            duration: 'variable',
            why: 'Public-policy lectures by Larry Summers, Kenneth Rogoff, and others on current monetary and fiscal debates.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@federalreserve',
            title: 'Federal Reserve — policy briefings & FOMC press conferences',
            channel: 'Federal Reserve',
            duration: 'variable',
            why: 'The chair\'s quarterly FOMC press conferences, posted in full. Learn to read central-bank language by hearing it spoken.',
          },
        ],
        books: [
          {
            title: 'The General Theory of Employment, Interest and Money',
            author: 'John Maynard Keynes',
            year: 1936,
            url: 'https://www.marxists.org/reference/subject/economics/keynes/general-theory/',
            why: 'The book that created macroeconomics. Hard going in places; the first two chapters and the conclusion are the core.',
          },
          {
            title: 'Principles of Political Economy',
            author: 'John Stuart Mill',
            year: 1848,
            url: 'https://www.gutenberg.org/ebooks/30107',
            why: 'The dominant textbook for half a century before Marshall. Mill\'s Book III, on exchange, is where classical macroeconomic reasoning lives.',
          },
          {
            title: 'Capitalism, Socialism and Democracy',
            author: 'Joseph Schumpeter',
            year: 1942,
            url: '',
            why: 'The source of "creative destruction" and still the most provocative defense of capitalism by a critic. Reads like a polemic, teaches like a textbook.',
          },
          {
            title: 'A Monetary History of the United States, 1867–1960',
            author: 'Milton Friedman and Anna Schwartz',
            year: 1963,
            url: '',
            why: 'The canonical monetarist counter to Keynes. Chapter 7, on the Great Contraction, is the single most-cited chapter in American macroeconomic history.',
          },
          {
            title: 'This Time Is Different: Eight Centuries of Financial Folly',
            author: 'Carmen Reinhart and Kenneth Rogoff',
            year: 2009,
            url: '',
            why: 'Eight hundred years of data on sovereign debt, banking crises, and currency collapses. The best modern macroeconomic history in English.',
          },
          {
            title: 'Why Nations Fail',
            author: 'Daron Acemoglu and James A. Robinson',
            year: 2012,
            url: '',
            why: 'The institutional-economics case for why some countries got rich and others did not. Acemoglu won the 2024 Nobel in part for this work; read it with the Solow model in hand.',
          },
          {
            title: 'The Price of Time',
            author: 'Edward Chancellor',
            year: 2022,
            url: '',
            why: 'A modern history of interest rates, from Sumer to the 2020s. Critical of post-2008 central banking; an essential counterweight to establishment macro.',
          },
          {
            title: 'Macroeconomics',
            author: 'N. Gregory Mankiw',
            year: 2000,
            url: '',
            why: 'The dominant undergraduate macro textbook. If you want to read one textbook cover-to-cover, this is it.',
          },
        ],
        articles: [
          {
            title: 'Macroeconomics',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Macroeconomics',
            why: 'Careful overview with a good section on the history of the field and the schools of thought.',
            year: null,
          },
          {
            title: 'Philosophy of Economics',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/economics/',
            why: 'Hausman\'s essay on what economists are doing when they model; indispensable for making sense of the macro schools\' disagreements.',
            year: 2018,
          },
          {
            title: 'Friedrich Hayek',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Friedrich_Hayek',
            why: 'The best short biography in English of Keynes\'s most durable opponent. The "disputes and debates" section covers the macro argument directly.',
            year: null,
          },
          {
            title: 'Phillips curve',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Phillips_curve',
            why: 'Good entry on the single most-argued-about curve in macro, with the Friedman–Phelps critique laid out plainly.',
            year: null,
          },
          {
            title: 'Our World in Data — Economic growth',
            source: 'Our World in Data',
            url: 'https://ourworldindata.org/economic-growth',
            why: 'Clean charts of long-run growth, GDP per capita, and productivity. The empirical base for any serious growth conversation.',
            year: null,
          },
          {
            title: 'Friedrich Hayek — Prices and production',
            source: 'Mises Institute',
            url: 'https://mises.org/library/prices-and-production',
            why: 'Hayek\'s alternative to Keynes. Worth reading in original even if you disagree, to see where the argument actually was.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Principles of Economics: Macroeconomics (MRU)',
            provider: 'Marginal Revolution University',
            url: 'https://mru.org/principles-economics-macroeconomics',
            free: true,
            why: 'Full course with videos, exercises, and a final exam.',
          },
          {
            title: 'Khan Academy — Macroeconomics',
            provider: 'Khan Academy',
            url: 'https://www.khanacademy.org/economics-finance-domain/macroeconomics',
            free: true,
            why: 'Free AP-aligned macro course, paced for first-time learners.',
          },
        ],
        podcasts: [
          {
            title: 'Macro Musings',
            show: 'Macro Musings (Mercatus)',
            url: 'https://www.mercatus.org/macro-musings',
            duration: '≈60:00',
            why: 'David Beckworth\'s monetary-policy podcast. Reliably good conversations with the people inside and around the Fed.',
          },
          {
            title: 'Odd Lots',
            show: 'Odd Lots (Bloomberg)',
            url: 'https://www.bloomberg.com/podcasts/series/odd-lots',
            duration: '≈50:00',
            why: 'Joe Weisenthal and Tracy Alloway\'s long-form financial markets podcast. Macro and micro meet here; the episodes on the 2020 Treasury basis trade are canonical.',
          },
          {
            title: 'Planet Money — macro episodes',
            show: 'Planet Money (NPR)',
            url: 'https://www.npr.org/podcasts/510289/planet-money',
            duration: '≈30:00',
            why: 'The long-running NPR show. Episodes on the Fed\'s birth, on hyperinflation, and on the 2008 crisis are classic explainers.',
          },
        ],
        tools: [
          {
            title: 'FRED — Federal Reserve Economic Data',
            url: 'https://fred.stlouisfed.org/',
            why: 'St. Louis Fed\'s free database of 800,000+ macroeconomic time series. Graph any two series on one chart in thirty seconds.',
          },
          {
            title: 'Trading Economics',
            url: 'https://tradingeconomics.com/',
            why: 'Live dashboards for every major country\'s macroeconomic indicators. Free tier is enough for any non-professional user.',
          },
          {
            title: 'BIS — Bank for International Settlements',
            url: 'https://www.bis.org/statistics/',
            why: 'The central bank of central banks. Their free data on global credit, exchange rates, and banking flows is indispensable.',
          },
        ],
        primarySources: [
          {
            title: 'Keynes, The General Theory (full text)',
            url: 'https://www.marxists.org/reference/subject/economics/keynes/general-theory/',
            why: 'Complete 1936 text, free, hosted at the Marxists Internet Archive.',
          },
        ],
      },

      seeAlso: ['micro', 'behavioral_econ', 'stats', 'institutions', 'geopolitics'],
      prereqs: ['micro'],
      leadsTo: ['behavioral_econ'],

      chapterActivity: 'A quarterly "read the Fed minutes together" evening at a bar in the Financial District, with one working macroeconomist on the bill to translate the jargon. Twice a year, a tour of the New York Fed\'s Museum of American Finance, or a docent walk at the American Numismatic Society in Washington Heights.',

      sources: [
        'https://en.wikipedia.org/wiki/Macroeconomics',
        'https://plato.stanford.edu/entries/economics/',
        'https://www.marxists.org/reference/subject/economics/keynes/general-theory/',
        'https://en.wikipedia.org/wiki/Phillips_curve',
        'https://ourworldindata.org/economic-growth',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— BEHAVIORAL ECONOMICS ———
    behavioral_econ: {
      id: 'behavioral_econ',
      name: 'Behavioral Economics',
      level: 'Intermediate',
      dek: 'The branch of economics that takes psychology seriously — and admits the "rational actor" of the textbook is a convenient fiction.',
      readTime: '18 min',

      sections: ['Kahneman and Tversky', 'The heuristics and the biases', 'Two systems', 'Nudges and the paternalism fight', 'Replication and what survived', 'The limits of the program'],
      body: [
        { type: 'lead', text: 'In the early 1970s, two Israeli psychologists — Daniel Kahneman and Amos Tversky — began a collaboration in a small office in Jerusalem that would eventually win one of them a Nobel Prize in economics. They did not set out to found a subfield. They were trying to explain why experienced statisticians, shown certain kinds of problems, reliably got them wrong.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Daniel_KAHNEMAN.jpg?width=900', caption: 'Daniel Kahneman (1934–2024), who shared the 2002 Nobel in economics. His collaborator Amos Tversky had died in 1996; the prize is not awarded posthumously.', credit: 'nrkbeta, CC BY 2.0, via Wikimedia Commons' },
        { type: 'h2', text: 'The systematic errors' },
        { type: 'p', text: 'Classical economics assumed people were rational: given full information, they would choose what maximized their expected utility. Kahneman and Tversky showed, experiment after experiment, that people are not rational in this sense, and — more importantly — that they are irrational in predictable ways. Anchoring, availability, loss aversion, framing: each is a named, measurable, reproducible deviation from the textbook.' },
        { type: 'p', text: 'Anchoring: show someone a random number before asking them to estimate a quantity, and their estimate shifts toward the number. Availability: ask someone the probability of an event, and they substitute how easily examples come to mind. Loss aversion: people feel the pain of losing $100 roughly twice as intensely as the pleasure of gaining $100. These are not quirks; they are almost universal, and they rewrite a surprising amount of what economics thought it knew.' },
        { type: 'h2', text: 'Two systems' },
        { type: 'p', text: 'Kahneman\'s 2011 book Thinking, Fast and Slow organizes the findings around a metaphor: we have a fast, intuitive, pattern-matching "System 1" and a slow, deliberate, effortful "System 2." Most of our waking decisions run on System 1, which is usually right and occasionally spectacularly wrong. The distinction is more rhetorical than neurological, but it organizes a sprawling literature.' },
        { type: 'h2', text: 'Prospect theory' },
        { type: 'p', text: 'Prospect theory, Kahneman and Tversky\'s 1979 paper, is the canonical formalization. It replaces expected-utility theory with a value function that is concave for gains, convex for losses, and steeper for losses than for gains. That asymmetry — the kink at zero — explains why people are simultaneously risk-averse over gains and risk-seeking over losses, a pattern classical theory could not account for. It is, in citations, one of the most influential economics papers of the late twentieth century.' },
        { type: 'h2', text: 'Nudges, and the debate over them' },
        { type: 'p', text: 'Richard Thaler and Cass Sunstein\'s 2008 book Nudge argued that small changes in how a choice is presented — the default option in a retirement plan, the position of the salad bar — can change behavior without restricting freedom. Governments in the UK, the US, and dozens of other countries now employ "behavioral insights" teams. The British example, the Behavioural Insights Team (founded 2010, spun out of the Cabinet Office in 2014), is the best-documented.' },
        { type: 'p', text: 'Critics on the left call nudges a band-aid that lets politicians avoid structural reform. Critics on the right call them paternalism in polite clothing. The debate is ongoing and worth paying attention to. The practical track record is mixed: some nudges (organ-donor defaults, retirement auto-enrollment) show large and durable effects; others (most text-message interventions) show small and decaying ones.' },
        { type: 'h2', text: 'The replication reckoning' },
        { type: 'p', text: 'Behavioral economics shared the replication crisis that hit social psychology in the 2010s. Some of its famous findings — ego depletion, social priming, power posing — did not replicate at all. Others — loss aversion, anchoring, the endowment effect — have held up robustly across decades and cultures. A careful reader now treats the field the way one would treat any young science: fascinated, curious, and slow to believe the next headline. A living spreadsheet of replication outcomes for behavioral findings is maintained by researchers at Berkeley.' },
        { type: 'h2', text: 'The limits of the program' },
        { type: 'p', text: 'Behavioral economics is strong on diagnosis and uneven on prescription. It has documented dozens of ways humans depart from the rational actor model; it has had a harder time saying what institutions should be redesigned to accommodate the departures. The field has also been criticized, including by Kahneman himself, for focusing on individuals when many of the decisions that matter are made by firms, bureaucracies, and political coalitions. A full sociology of the subject is arguably still to be written.' },
        { type: 'callout', text: 'In 2002, Daniel Kahneman shared the Nobel Memorial Prize in Economic Sciences. Amos Tversky had died in 1996; the Nobel is not awarded posthumously. Kahneman spent a large part of his acceptance lecture talking about him.' },

        { type: 'h2', text: 'Learn it: five biases you can catch yourself committing today' },
        { type: 'p', text: 'Anchoring. Think of the last two digits of your phone number. Now, without looking anything up, guess how many countries are in Africa. Write down both numbers. If you are like most subjects in Tversky and Kahneman\'s classic study, your guess correlates with the arbitrary anchor. (The answer is 54.) The moment the brain is given a number — any number — it uses it as a starting point, and every subsequent adjustment is insufficient.' },
        { type: 'p', text: 'Availability. Which word occurs more often in English text: words starting with "r", or words with "r" as the third letter? Most people say the first, because initial-letter words are easier to recall. The correct answer is the second, by a wide margin. The mind substitutes "how easily can I think of examples?" for "how frequent are the examples?"' },
        { type: 'p', text: 'Loss aversion. Flip a coin: heads you win $150, tails you lose $100. The expected value is positive, and a risk-neutral decision-maker would take the bet every time. Most people refuse. Prospect theory quantifies why: the pain of losing $100 is about twice the pleasure of winning $100. To make the bet attractive on average, the upside typically has to be twice the downside, not equal.' },
        { type: 'p', text: 'Framing. "95% of patients survive this surgery" vs. "5% of patients die from this surgery." Identical information; very different clinical decisions. Surgeons and patients both shift, and the effect survives training.' },
        { type: 'p', text: 'Endowment. Give half a class a mug; give the other half a chance to buy a mug. Let them trade. Classical theory predicts half the mugs change hands. In the actual experiment (Kahneman, Knetsch, and Thaler, 1990), almost none do — sellers want roughly twice what buyers will pay. People value things more once they own them.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. A retirement plan has two possible default options: (A) employees are automatically enrolled at 6% of salary unless they opt out; (B) employees are not enrolled unless they opt in. Classical economics predicts the same participation rate under both. What does behavioral economics predict, and what has the empirical evidence shown? What is the policy name for this intervention?' },
        { type: 'p', text: 'Answer: Classical theory says rational workers know what they want and pick accordingly; defaults should not matter. Behavioral theory predicts massively higher participation under (A) because defaults exploit status-quo bias. The empirical evidence (Madrian and Shea, 2001, and many successors) shows participation roughly doubles. This is the canonical Thaler-Sunstein "nudge." Most U.S. 401(k) plans now use some form of auto-enrollment.' },
        { type: 'p', text: 'Problem 2. You own a stock bought at $50. It is now trading at $30. A similar stock you don\'t own is trading at $30. A rational investor should treat both the same. Most investors, however, refuse to sell at a loss. What bias is at work? Is the sunk cost really "sunk"?' },
        { type: 'p', text: 'Answer: Loss aversion — the disposition effect in finance. Selling at a loss makes the loss psychologically real; holding lets one keep hoping. The sunk cost is genuinely sunk — past prices should not affect forward decisions. Brokers who understand this phenomenon build it into their coaching. The empirical evidence (Shefrin and Statman, 1985) is robust across markets and decades.' },
        { type: 'p', text: 'Problem 3. A cafeteria wants students to eat more fruit. It puts the fruit at eye level at the front of the line, leaves desserts at the back in plainer containers. Consumption of fruit rises 25%. Dessert consumption falls. Is this paternalism? Is it manipulation? Is it ethically distinguishable from a junk-food tax?' },
        { type: 'p', text: 'Answer: There is no single right answer — this is the heart of the Thaler-Sunstein debate. A libertarian-paternalist argues this is acceptable because no option is removed; a harder-line libertarian says shaping defaults is still interference; a critic from the left says real change requires structural reform, not shelf-placement. The question is ethical, not empirical, and you should be able to articulate your own view in plain words.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What is the difference between a heuristic and a bias? (2) Why is loss aversion not the same as risk aversion? (3) What does "System 1 vs System 2" claim, and what is one criticism of the distinction? (4) Name three behavioral findings that have held up under replication, and one that has not. (5) Give a nudge and an equivalent mandate; which would you prefer, and why? (6) What does Kahneman mean by "noise" (as opposed to "bias") in his 2021 book?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Watch Kahneman\'s TED talk and read the first three chapters of Thinking, Fast and Slow. Keep a "bias journal" for a week: every time you catch yourself in one, write down the bias, the context, and how you would have decided differently. This is the single most useful exercise in the field. Once you\'ve got the basics? Read Nudge cover to cover, and the 1979 Prospect Theory paper (freely available through many university libraries). Work through the MIT 14.13 problem sets. To go further? Take a behavioral-economics graduate seminar, or pick one bias and read the last ten years of replication literature on it. The current frontier is heterogeneity — why the same nudge works on some people and not others — and you can read straight into it.' },
      ],

      keyTerms: ['heuristic', 'bias', 'anchoring', 'availability', 'loss aversion', 'framing effect', 'prospect theory', 'nudge', 'bounded rationality', 'System 1', 'System 2', 'endowment effect', 'status quo bias'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/daniel_kahneman_the_riddle_of_experience_vs_memory',
            title: 'The Riddle of Experience vs. Memory',
            channel: 'TED2010',
            duration: '20:34',
            why: 'Kahneman himself on the distinction between the experiencing self and the remembering self. The idea that opens the second half of Thinking, Fast and Slow.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/dan_ariely_are_we_in_control_of_our_own_decisions',
            title: 'Are we in control of our own decisions?',
            channel: 'TEDGlobal 2008',
            duration: '17:22',
            why: 'Dan Ariely, a principal figure in the field, walks through the organ-donor default and a string of other small experiments.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@marginalrevolutionuniversity',
            title: 'MRU — behavioral playlist',
            channel: 'Marginal Revolution University',
            duration: 'variable',
            why: 'Short videos on anchoring, hyperbolic discounting, and status-quo bias. Useful as a bridge from classical to behavioral.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/sendhil_mullainathan_solving_social_problems_with_a_nudge',
            title: 'Solving social problems with a nudge',
            channel: 'TEDIndia 2009',
            duration: '14:20',
            why: 'Sendhil Mullainathan on nudges in development — particularly the behavioral economics of scarcity.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/shlomo_benartzi_saving_for_tomorrow_tomorrow',
            title: 'Saving for tomorrow, tomorrow',
            channel: 'TEDSalon NY 2011',
            duration: '17:45',
            why: 'Shlomo Benartzi on Save More Tomorrow, the Thaler-Benartzi auto-escalation plan that is now a standard feature of US 401(k) design.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/paul_bloom_can_prejudice_ever_be_a_good_thing',
            title: 'Can prejudice ever be a good thing?',
            channel: 'TEDSalon NY 2014',
            duration: '17:45',
            why: 'Yale psychologist Paul Bloom on the cognitive shortcuts that produce stereotype — a careful, uncomfortable, behaviorally informed talk.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — behavioral & development economics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Full lectures by Cass Sunstein, Esther Duflo, and British nudge-unit practitioners.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardUniversity',
            title: 'Harvard — behavioral economics & psychology',
            channel: 'Harvard University',
            duration: 'variable',
            why: 'Lectures by Sendhil Mullainathan, Max Bazerman, and Francesca Gino — the Harvard behavioral ecosystem on camera.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/rory_sutherland_perspective_is_everything',
            title: 'Perspective is everything',
            channel: 'TEDxAthens 2011',
            duration: '18:27',
            why: 'Ogilvy\'s Rory Sutherland on the applied side — why advertising is the oldest behavioral-economics industry. Funny, practical.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@BITCFriends',
            title: 'The Behavioural Insights Team — case studies',
            channel: 'BIT',
            duration: 'variable',
            why: 'The British "nudge unit" posts short case studies and panel discussions. The applied-policy wing of the field, in its own voice.',
          },
        ],
        books: [
          {
            title: 'Thinking, Fast and Slow',
            author: 'Daniel Kahneman',
            year: 2011,
            url: '',
            why: 'The canonical introduction, written by one of the field\'s founders for a general reader. Long, but organized so a reader can stop anywhere.',
          },
          {
            title: 'Nudge: Improving Decisions About Health, Wealth, and Happiness',
            author: 'Richard H. Thaler and Cass R. Sunstein',
            year: 2008,
            url: '',
            why: 'The book that moved the field from academic psychology to policy. Read the first two chapters; the rest is applications.',
          },
          {
            title: 'Misbehaving: The Making of Behavioral Economics',
            author: 'Richard H. Thaler',
            year: 2015,
            url: '',
            why: 'Thaler\'s memoir of the field\'s early years. The best account of how it fought its way into an unwelcoming discipline.',
          },
          {
            title: 'Predictably Irrational',
            author: 'Dan Ariely',
            year: 2008,
            url: '',
            why: 'Ariely\'s popular classic. Each chapter is one experiment. Criticized in light of the replication crisis; still a better first book than a textbook.',
          },
          {
            title: 'Scarcity: The New Science of Having Less and How It Defines Our Lives',
            author: 'Sendhil Mullainathan and Eldar Shafir',
            year: 2013,
            url: '',
            why: 'The cognitive cost of being poor — one of behavioral economics\'s most important recent syntheses.',
          },
          {
            title: 'Noise: A Flaw in Human Judgment',
            author: 'Daniel Kahneman, Olivier Sibony, and Cass R. Sunstein',
            year: 2021,
            url: '',
            why: 'Kahneman\'s late-career follow-up to Thinking, Fast and Slow. About variance in judgment rather than bias — a quieter but possibly more important problem.',
          },
          {
            title: 'The Undoing Project',
            author: 'Michael Lewis',
            year: 2016,
            url: '',
            why: 'A biography of the Kahneman–Tversky friendship, written by the Moneyball author. The human story behind the papers.',
          },
        ],
        articles: [
          {
            title: 'Behavioral economics',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Behavioral_economics',
            why: 'Well-structured overview with honest coverage of the replication issues some findings have faced.',
            year: null,
          },
          {
            title: 'Prospect theory',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Prospect_theory',
            why: 'The 1979 paper\'s successor concept, summarized with the actual value function.',
            year: null,
          },
          {
            title: 'Heuristics (psychology)',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Heuristics_and_biases',
            why: 'The best short summary of the Tversky–Kahneman research program — availability, representativeness, anchoring — with links out to each named bias.',
            year: null,
          },
          {
            title: 'Cognitive bias',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Cognitive_bias',
            why: 'A taxonomic entry listing the named biases, with links to evidence on each. Useful as a reference, not a first read.',
            year: null,
          },
          {
            title: 'Nudge theory',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Nudge_theory',
            why: 'Overview of the policy branch of the field, including its critics.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'MIT 14.13 — Psychology and Economics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/14-13-psychology-and-economics-spring-2020/',
            free: true,
            why: 'Frank Schilbach\'s full MIT undergraduate course on behavioral economics — lectures, slides, problem sets, exams, and readings.',
          },
          {
            title: 'Yale — The Moral Foundations of Politics (PLSC 118)',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science/plsc-118',
            free: true,
            why: 'Shapiro\'s Yale course does not use the phrase "behavioral economics," but its treatment of utilitarianism and rational choice is essential companion reading.',
          },
        ],
        podcasts: [
          {
            title: 'Hidden Brain',
            show: 'Hidden Brain (NPR)',
            url: 'https://hiddenbrain.org/',
            duration: '≈50:00 per episode',
            why: 'Shankar Vedantam\'s flagship show. The cleanest long-running radio program on behavioral and social psychology in English.',
          },
          {
            title: 'Choiceology',
            show: 'Choiceology (Schwab)',
            url: 'https://www.schwab.com/learn/choiceology-podcast',
            duration: '≈35:00 per episode',
            why: 'Hosted by Katy Milkman, a Wharton behavioral scientist. Each episode walks through one bias with a case study. Polished and serious.',
          },
          {
            title: 'No Stupid Questions',
            show: 'Freakonomics Radio Network',
            url: 'https://freakonomics.com/archive/',
            duration: '≈35:00 per episode',
            why: 'Stephen Dubner and Angela Duckworth talking through behavioral-science questions sent in by listeners. Conversational; usually good.',
          },
        ],
        primarySources: [
          {
            title: 'Kahneman\'s Nobel Prize Lecture',
            url: 'https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/lecture/',
            why: '"Maps of Bounded Rationality" — the single best short statement of the research program, delivered in Stockholm.',
          },
          {
            title: 'Judgment under Uncertainty (Tversky & Kahneman, 1974, Science)',
            url: 'https://www.science.org/doi/10.1126/science.185.4157.1124',
            why: 'The founding Science paper. Short, readable, decisive.',
          },
        ],
      },

      seeAlso: ['micro', 'macro', 'cognition', 'clinical'],
      prereqs: ['micro'],
      leadsTo: [],

      chapterActivity: 'A monthly "biases dinner" — each attendee brings a real decision they made badly and diagnoses it with the group, over food. Once a quarter, rent the meeting room at a public library and run a Kahneman-style experiment on ourselves (anchoring, availability, endowment effect) with index cards and ten-dollar stakes.',

      sources: [
        'https://en.wikipedia.org/wiki/Behavioral_economics',
        'https://en.wikipedia.org/wiki/Prospect_theory',
        'https://en.wikipedia.org/wiki/Heuristics_and_biases',
        'https://www.ted.com/talks/daniel_kahneman_the_riddle_of_experience_vs_memory',
        'https://www.nobelprize.org/prizes/economic-sciences/2002/kahneman/lecture/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
