// content/etiquette.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: table, letters
//
// NOTE: Tone here is allowed to be wry (per batch note). Emily Post Institute
// is the durable authority. The 2022 Centennial Edition is the current book.

window.CONTENT = window.CONTENT || {};
window.CONTENT.etiquette = {
  subjectId: 'etiquette',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    table: {
      id: 'table',
      name: 'Table Manners',
      level: 'Beginner',
      dek: 'The silent language every adult is supposed to know — with the small kindnesses that keep a dinner from becoming a performance.',
      readTime: '10 min',

      sections: ['An older rulebook than it looks', 'The three rules most people miss', 'The silverware has a map', 'Conversation is the real meal', 'Host, guest, and the small kindnesses', 'Why manners are still worth learning'],
      body: [
        { type: 'lead', text: 'In 1530, Erasmus of Rotterdam — who was at that point the most famous intellectual in Europe — wrote a small Latin book for children called De civilitate morum puerilium, "On civility in children." It told them not to spit on the floor at dinner, not to lick the common serving spoon, and not to blow their noses in the tablecloth. The book was one of the bestsellers of the sixteenth century, and it is a useful reminder that table manners are not snobbery. They are a thousand-year thread of agreements about how to sit down with other people and share food without making any of them unhappy.' },
        { type: 'h2', text: 'The rulebook, such as it is' },
        { type: 'p', text: 'Emily Post published her first Etiquette in 1922, and her great-great-granddaughter Lizzie Post published the Centennial Edition a century later, in 2022. The book is five hundred pages and still organized around three principles: consideration, respect, and honesty. Almost every specific rule — outside-in with the silverware, napkin in the lap within a minute of sitting, soup spoon moves away from you — is a working specification of those three. When the rule and the principle conflict (the host is eating with her fingers because the meal requires it), go with the principle.' },
        { type: 'h2', text: 'The three rules most people miss' },
        { type: 'p', text: 'One: wait until everyone is served before picking up a fork, unless the host invites you otherwise. In small groups, wait for the host to lift a fork first. Two: the knife and fork are held in opposite hands — American style switches between bites, European style keeps them in the original hands. Either is correct; picking one and being consistent is better than waffling. Three: phone face-down on the table, or off it entirely. The single rule that has done the most to erode modern meals is the tolerance of the unsilenced phone, and the single best correction is a host who says, quietly, "phones away, please" the moment the first person is seated.' },
        { type: 'h2', text: 'The silverware has a map' },
        { type: 'p', text: 'At a formal table, the silverware is arranged in the order the courses will be eaten, from the outside in. The salad fork on the far left goes with the salad that will arrive first; the entree fork nearer the plate goes with the main course; the dessert spoon and fork above the plate go with dessert. Bread-and-butter plate on the upper left, water glass on the upper right, wine glasses (if any) to the right of the water. There is an old mnemonic — BMW, for bread-meal-water, left to right — that has taught a million people whose bread plate is whose. The diagrams on emilypost.com are the most useful single page on the internet the first time you have to set a formal table.' },
        { type: 'h2', text: 'Conversation is the real meal' },
        { type: 'p', text: 'The food is an occasion for the talk. A good guest turns toward the less-included person, asks a real question, listens to the answer, and follows up. She does not monopolize. She does not lecture. She does not deliver an opinion uninvited, and she recognizes that politics, religion, and money — the three old forbidden topics — are forbidden not because they are unimportant but because they tend to produce monologues and ill feeling in almost every group where not everyone agrees on them already. Anna Post, the Centennial Edition\'s co-author, states the rule more generously: "steer toward what the room can share in."' },
        { type: 'callout', text: 'Leave the phone in your pocket. A single glance at a screen during dinner is the clearest signal you can send that the person across from you is less interesting than whatever is not in the room. Do not send it, even inadvertently.' },
        { type: 'h2', text: 'Host and guest' },
        { type: 'p', text: 'A host\'s job is to make the evening possible for the guests. This means the planning — the cooking, the serving, the timing — but also the gentle structural work of introductions, of moving the conversation when a corner of the table has gone quiet, of rescuing the person who has mentioned her divorce by accident. A guest\'s job is to be on time, bring something if asked, eat what is offered, talk with the stranger on her left, and write a thank-you note the next day. The two roles are older than dinner parties. Homer\'s Odyssey calls the guest-host relationship xenia and makes it the central moral principle of the whole poem.' },
        { type: 'h2', text: 'Why manners are still worth learning' },
        { type: 'p', text: 'A hundred years after Emily Post\'s first book, manners are no longer a class marker the way they were, and the old performative rituals — the place cards, the finger bowls, the right address for the dowager countess — have been quietly retired. What remains is the working core: be considerate, be respectful, be honest. The specific rules about the fork exist to spare the person beside you from having to watch you use it awkwardly. That is the only reason any of them have ever existed.' },
      ],

      keyTerms: ['place setting', 'napkin', 'American style (cut and switch)', 'Continental style', 'toast', 'host', 'guest', 'dietary accommodation', 'xenia'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://emilypost.com/advice/table-setting-diagrams',
            title: 'Emily Post — Table Setting Diagrams',
            channel: 'Emily Post Institute', duration: 'on-demand',
            why: 'The reference diagrams — casual, informal, and formal place settings — in one page. The most useful single illustration of the subject in English.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@EmilyPostInst',
            title: 'Emily Post Institute — full channel',
            channel: 'Emily Post Institute', duration: 'variable',
            why: 'The Institute\'s own videos — Lizzie Post and Daniel Post Senning demonstrating place settings, introductions, and the small working pieces of modern table manners.' },
          { id: null, featured: true, source: 'other',
            url: 'https://emilypost.com/podcast/awesome-etiquette-podcast',
            title: 'Awesome Etiquette — podcast',
            channel: 'Emily Post Institute', duration: 'weekly, ~45 min',
            why: 'Lizzie Post and Daniel Post Senning\'s weekly Q&amp;A podcast. The best running, modern-life application of the three principles.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@townandcountrymag',
            title: 'Town &amp; Country — etiquette features',
            channel: 'Town &amp; Country', duration: 'variable',
            why: 'Short features on modern-life etiquette from the magazine that has written about it since 1846.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@DebrettsEngland',
            title: 'Debrett\'s — British etiquette primer',
            channel: 'Debrett\'s', duration: 'variable',
            why: 'The British reference, still operating as it has since 1769. The Debrett\'s video short on place-setting etiquette is the clearest British counterpart to the Emily Post diagrams.' },
        ],
        books: [
          { title: 'Emily Post\'s Etiquette, The Centennial Edition',
            author: 'Lizzie Post and Daniel Post Senning', year: 2022,
            url: 'https://www.penguinrandomhouse.com/books/665502/emily-posts-etiquette-the-centennial-edition-by-lizzie-post-and-daniel-post-senning/',
            why: 'The 2022 hundred-year update of Emily Post\'s 1922 original. Lizzie and Dan are great-great-grandchildren of Emily and co-presidents of the Institute. The single book to own.' },
          { title: 'Etiquette in Society, in Business, in Politics, and at Home',
            author: 'Emily Post', year: 1922,
            url: 'https://www.gutenberg.org/ebooks/14314',
            why: 'The original. Free on Project Gutenberg. Largely dated in its specifics; quietly undated in its principles.' },
          { title: 'Modern Manners: An Etiquette Book for Rude People',
            author: 'P. J. O\'Rourke', year: 1983, url: '',
            why: 'A funny American companion to the earnest ones. O\'Rourke\'s argument is that manners are for the times and places you did not choose to be in — which is most of life.' },
          { title: 'Manners and Rules of Good Society',
            author: 'Debrett\'s', year: 2016, url: '',
            why: 'The British reference, traceable to 1769. Useful for the subtle differences — the calling card, the use of a title, the order of service.' },
          { title: 'Behave Yourself!: The Essential Guide to International Etiquette',
            author: 'Michael Powell', year: 2005, url: '',
            why: 'A country-by-country guide for the traveler. No manners are universal; a Japanese business dinner and an Italian Christmas Eve are different rulebooks.' },
        ],
        articles: [
          { title: 'Etiquette', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Etiquette',
            why: 'A clear, non-preachy history of the norms, from ancient Egypt through the digital age.' },
          { title: 'Emily Post', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Emily_Post',
            why: 'The biography of the American woman who codified modern US table manners. Her 1922 book sold out within weeks of publication.' },
          { title: 'Table Setting Diagrams',
            source: 'Emily Post Institute',
            url: 'https://emilypost.com/advice/table-setting-diagrams',
            why: 'Casual, informal, and formal place-setting diagrams, with the rationale for each position.' },
        ],
        courses: [
          { title: 'Awesome Etiquette — podcast archive',
            provider: 'Emily Post Institute',
            url: 'https://emilypost.com/podcast/',
            free: true,
            why: 'Three hundred and fifty episodes and counting, each answering real listener questions. The modern running curriculum for the subject.' },
          { title: 'Emily Post Institute — free advice articles',
            provider: 'Emily Post Institute',
            url: 'https://emilypost.com/advice',
            free: true,
            why: 'A searchable archive of specific answers on introductions, gift-giving, tipping, and the whole territory of modern interpersonal manners.' },
        ],
        tools: [
          { title: 'Emily Post — Table Setting Diagrams',
            url: 'https://emilypost.com/advice/table-setting-diagrams',
            why: 'The reference diagram every host uses once. Bookmark it.' },
          { title: 'Debrett\'s — advice',
            url: 'https://debretts.com/the-debretts-guide/',
            why: 'The British reference for British situations — royalty, titles, formal dress, and the cases Americans learn the hard way.' },
        ],
        primarySources: [
          { title: 'Desiderius Erasmus, De civilitate morum puerilium (1530)',
            url: 'https://en.wikipedia.org/wiki/De_civilitate_morum_puerilium',
            why: 'The sixteenth-century book on manners for children. Its rules about the tablecloth and the communal spoon are the literary ancestor of every modern etiquette guide.' },
        ],
      },

      interactive: null,
      seeAlso: ['letters', 'negotiation', 'publicspeaking'],
      prereqs: [],
      leadsTo: ['letters'],

      chapterActivity: 'A potluck dinner at a chapter member\'s apartment in Cobble Hill — phones in a basket by the door, one introduction per guest, a handwritten thank-you note the next day.',

      sources: [
        'https://en.wikipedia.org/wiki/Etiquette',
        'https://emilypost.com/',
        'https://emilypost.com/advice/table-setting-diagrams',
      ],
      verifiedAt: '2026-04-23',
    },

    letters: {
      id: 'letters',
      name: 'Correspondence',
      level: 'Beginner',
      dek: 'Thank-you notes still work — and the short handwritten note is the single most underused tool in modern life.',
      readTime: '10 min',

      sections: ['Why the handwritten note still matters', 'The four-line thank-you', 'The structure of a letter', 'Condolence, congratulation, and apology', 'Email is a letter, too', 'Paper, pen, and the small habit'],
      body: [
        { type: 'lead', text: 'In 1775, during the long winter of the Continental Army\'s occupation of Cambridge, Abigail Adams wrote a letter to her husband John that began "I wish you would ever write me a Letter half as long as I write you." Between 1762 and her death in 1818, Abigail wrote more than a thousand surviving letters — to her husband, her children, her sister, her confidantes — and they are now among the most important documents in the American archival record. Nothing she wrote was designed to last. Letters last anyway, in a way that email does not, and one reason an Emily Post Institute in Vermont still teaches the handwritten note is that the medium itself does work.' },
        { type: 'h2', text: 'Why the handwritten note still matters' },
        { type: 'p', text: 'A handwritten note takes five minutes to write, costs less than a dollar, and produces an effect on the recipient wildly out of proportion to the labor. It signals, with no other information necessary, that you thought enough of the person or event to stop what you were doing and make something physical. Emails, texts, and DMs are all read inside a stream. A card is read standing alone at a mailbox, often twice. This is the whole secret of the form: the medium itself, before anything you say in it, is the message.' },
        { type: 'h2', text: 'The four-line thank-you' },
        { type: 'p', text: 'A thank-you note does not have to be long. Four short lines is plenty. Greeting; the gift or occasion named specifically; one sentence of genuine response; close. "Dear Aunt Dorothy — Thank you so much for the copy of Turn Left at Orion. I used the finder charts to find the Andromeda Galaxy on Tuesday night; it was the first time I had ever seen it. Love, Nina." Forty-five seconds to write, fifteen seconds to read, and Aunt Dorothy will remember it for a year. The only absolute rule of the thank-you note is that it be written within a week of the gift or event; past a month it slightly insults the giver by suggesting she did not matter.' },
        { type: 'h2', text: 'The structure of a letter' },
        { type: 'p', text: 'A letter has a salutation, a body, a closing, and a signature. "Dear" is the default salutation in English — there is no warmer or more formal word for the first position — and it can be followed by a first name (close), a full name (professional), or a title and surname (formal). The body is whatever you have to say. The close — "Sincerely," "With love," "Yours," "Best," "Warmly" — signals the temperature of the relationship. "Sincerely" and "Best" are the safe defaults; "Love" is reserved for family and close friends; "Yours" has a faintly British, vaguely literary warmth. The signature is always by hand, even if the letter is typed.' },
        { type: 'h2', text: 'Condolence, congratulation, and apology' },
        { type: 'p', text: 'The three letters most adults will ever write are the letter of condolence, the letter of congratulation, and the letter of apology. Each has a rule. The condolence letter names the person who has died, says one specific thing the writer remembers about her, and offers no advice. The congratulation letter names the achievement specifically and does not compare the recipient to anyone else. The apology letter admits the fault in plain language ("I was wrong to have done that"), does not explain or defend, and proposes a concrete correction. All three should be handwritten, all three should be short, and all three should be sent the week the event occurs. Sending any of them late is worse than sending a brief version on time.' },
        { type: 'callout', text: 'An apology that uses the word "if" — "I\'m sorry if I upset you" — is not an apology. It is an evaluation of the recipient\'s reaction. The word to use is "that": "I\'m sorry that I upset you." One letter changes the sentence from a defense into an admission.' },
        { type: 'h2', text: 'Email is a letter, too' },
        { type: 'p', text: 'Almost everything above applies to email. A salutation, an informative body, a closing with your actual name — these are still the marks of a letter, regardless of the medium. Professional email should have a subject line that actually describes the subject ("Tuesday meeting confirmation" rather than "hi"). The reply-all button is an etiquette hazard. The phone is not always better than an email; an email is not always better than a letter; and the true skill is knowing which medium this message belongs in, then honoring what that medium asks.' },
        { type: 'h2', text: 'Paper, pen, and the small habit' },
        { type: 'p', text: 'Buy a box of plain stationery — Crane\'s, Smythson\'s, or anything you like — keep it in a drawer, keep stamps with it, and keep a working pen nearby. The habit a lifetime of handwritten letters requires is roughly two minutes a week of actual writing and zero minutes of extra planning, because the supplies are in one place. Most people who abandon the habit do so because they ran out of stamps and never replaced them. The small boring infrastructure is the whole barrier, and it takes an afternoon to set up.' },
      ],

      keyTerms: ['salutation', 'closing', 'signature', 'thank-you note', 'condolence', 'apology', 'stationery', 'monogram', 'RSVP'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://emilypost.com/advice/thank-you-notes-rules-to-follow',
            title: 'Emily Post — Thank You Note Rules',
            channel: 'Emily Post Institute', duration: 'on-demand',
            why: 'The Institute\'s own short, specific instructions. The article every first-time thank-you writer should read.' },
          { id: null, featured: true, source: 'other',
            url: 'https://emilypost.com/podcast/awesome-etiquette-podcast',
            title: 'Awesome Etiquette — podcast',
            channel: 'Emily Post Institute', duration: 'weekly, ~45 min',
            why: 'Lizzie Post and Daniel Post Senning\'s weekly podcast. Multiple episodes every year are entirely about letters and notes.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@EmilyPostInst',
            title: 'Emily Post Institute — full channel',
            channel: 'Emily Post Institute', duration: 'variable',
            why: 'The Institute\'s short videos on specific correspondence situations — the condolence note, the hand-addressed envelope, the proper salutation.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@DebrettsEngland',
            title: 'Debrett\'s — British correspondence',
            channel: 'Debrett\'s', duration: 'variable',
            why: 'The British reference for formal correspondence — salutations for titled persons, the thanks after a weekend country visit.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@thearchitectsdaughter',
            title: 'The Paper Letters — calligraphy and letter-writing',
            channel: 'The Paper Letters', duration: 'variable',
            why: 'A slow, thoughtful channel on the mechanics of the hand-addressed envelope and the personal letter. The craft end of the subject.' },
        ],
        books: [
          { title: 'Emily Post\'s Etiquette, The Centennial Edition',
            author: 'Lizzie Post and Daniel Post Senning', year: 2022,
            url: 'https://www.penguinrandomhouse.com/books/665502/emily-posts-etiquette-the-centennial-edition-by-lizzie-post-and-daniel-post-senning/',
            why: 'The working reference. The correspondence chapter is still the standard in English.' },
          { title: 'Etiquette in Society, in Business, in Politics, and at Home',
            author: 'Emily Post', year: 1922,
            url: 'https://www.gutenberg.org/ebooks/14314',
            why: 'Free on Gutenberg. The 1922 original is dated in specific addresses (Senators\' wives, the dowager in her carriage) but timeless on the shape of the letter itself.' },
          { title: 'Letters of Note',
            author: 'Shaun Usher (editor)', year: 2013, url: '',
            why: 'A gallery of famous letters across four centuries. Not an instruction book; the model it provides is better than most instruction.' },
          { title: 'Letters to a Young Poet',
            author: 'Rainer Maria Rilke', year: 1929, url: '',
            why: 'Ten letters from Rilke to a nineteen-year-old cadet. The best demonstration in twentieth-century prose of what a letter can do when it is serious.' },
          { title: 'The Letters of Abigail Adams',
            author: 'Abigail Adams', year: 1848, url: '',
            why: 'The founding-era correspondence that shows a letter is also a working tool of intelligence, affection, and political craft. In multiple print and online editions.' },
        ],
        articles: [
          { title: 'Thank You Note Rules to Follow',
            source: 'Emily Post Institute',
            url: 'https://emilypost.com/advice/thank-you-notes-rules-to-follow',
            why: 'The Institute\'s specific rules — when, what, and how. The most-cited reference in modern American practice.' },
          { title: 'Letter (message)', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Letter_(message)',
            why: 'A broad history of the form, from Egyptian papyri through the modern postal system.' },
          { title: 'Etiquette', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Etiquette',
            why: 'The surrounding history. Correspondence is a subset of manners, and the long-view history helps you know what to keep.' },
        ],
        courses: [
          { title: 'Awesome Etiquette — podcast archive',
            provider: 'Emily Post Institute',
            url: 'https://emilypost.com/podcast/',
            free: true,
            why: 'The running free curriculum. Search the archive by keyword (thank you, condolence, apology) for the specific guidance on your situation.' },
          { title: 'Emily Post Institute — free advice on correspondence',
            provider: 'Emily Post Institute',
            url: 'https://emilypost.com/advice/category/correspondence',
            free: true,
            why: 'Searchable articles on every letter situation — thank-you, condolence, congratulation, apology, holiday card, wedding response.' },
        ],
        tools: [
          { title: 'USPS — First-Class Forever stamps',
            url: 'https://store.usps.com/store/results/stamps',
            why: 'The single piece of infrastructure the habit requires. Buy a book; keep them with your stationery.' },
          { title: 'Crane &amp; Co. — stationery',
            url: 'https://www.crane.com/',
            why: 'The American stationer since 1801. Cotton paper, plain notecards, and the heft that a hand-addressed note should have.' },
        ],
        primarySources: [
          { title: 'Abigail Adams, Letters (1776)',
            url: 'https://www.masshist.org/digitaladams/archive/',
            why: 'The Massachusetts Historical Society\'s free online archive of the Adams family papers — including Abigail\'s thousand surviving letters.' },
        ],
      },

      interactive: null,
      seeAlso: ['table', 'publicspeaking', 'readclose'],
      prereqs: [],
      leadsTo: [],

      chapterActivity: 'A chapter letter-writing night at the Brooklyn Public Library\'s Central branch — boxes of plain cards on the table, stamps in a bowl, and a reading of Abigail Adams or Rilke partway through.',

      sources: [
        'https://emilypost.com/',
        'https://emilypost.com/advice/thank-you-notes-rules-to-follow',
        'https://www.gutenberg.org/ebooks/14314',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
