// content/fishing.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: knots_fish, flyfishing

window.CONTENT = window.CONTENT || {};
window.CONTENT.fishing = {
  subjectId: 'fishing',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    knots_fish: {
      id: 'knots_fish',
      name: 'Essential Knots',
      level: 'Beginner',
      dek: 'Clinch, Palomar, and blood — the three knots that hold almost every fish an angler will ever catch.',
      readTime: '10 min',

      sections: ['The joint where the line ends', 'The improved clinch and the Palomar', 'Joining two lines: blood and uni', 'The one loop that matters', 'Wet the knot before you pull'],
      body: [
        { type: 'lead', text: 'Every failure on a fishing line begins at a knot. When the eight-pound rainbow throws its head at the edge of the pool and the leader goes slack, the tippet almost never broke in the middle; it gave at the hook eye, where the angler tied a careless clinch and did not wet the line before pulling tight. A fisherman\'s whole hardware is a rod, a reel, a length of monofilament, and a lure; three of those are bought and one is tied, and the tied one decides the afternoon.' },
        { type: 'h2', text: 'The clinch, improved' },
        { type: 'p', text: 'The improved clinch knot — five turns around the standing line, pass the tag through the loop at the hook eye, then back through the big loop just formed — is the North American default for attaching a hook, swivel, or lure to monofilament or fluorocarbon up to about fifteen-pound test. Trout anglers have used it for a century; bass anglers, mostly, too. Tied wet and pulled slowly, it tests at about 95 percent of line strength. Tied dry and jerked tight, it cuts itself at the turns and breaks at 60. The improvement over the plain clinch is the final tag-through-the-loop pass, which prevents slippage on thinner line.' },
        { type: 'h2', text: 'The Palomar, the lazy one' },
        { type: 'p', text: 'For anyone with imperfect eyesight or cold hands, the Palomar knot is easier and nearly as strong. Double over six inches of line, pass the loop through the eye, tie a loose overhand, pass the hook through the loop, and pull. Three steps. It tests at 95 percent on braided line and is the braid angler\'s standard. Fly fishermen use it less — they are tying to small tippet eyes and prefer the clinch — but for spin fishing it is the workhorse that forgives fatigue.' },
        { type: 'h2', text: 'Joining two lines: blood and uni' },
        { type: 'p', text: 'The blood knot joins two lines of similar diameter — building a leader that steps down from thick butt to thin tippet — with a symmetrical five-turn-on-each-side arrangement that pulls flat and clean. The double uni knot does the same job with unequal diameters (mono to braid, for instance) and is simpler to tie, which is why saltwater anglers mostly use it now. A good fly leader in 2026 is typically mono blood-knotted to mono, down through four or five steps; a good bass or salmon leader is just a mono shock tippet uni-knotted to a braided main line.' },
        { type: 'callout', text: 'Wet every knot with saliva or water before pulling tight. Monofilament heats as the turns seat, and dry-tied knots lose up to a third of their strength. The half-second of spit is the difference between a landed fish and a story about one.' },
        { type: 'h2', text: 'The loop that matters' },
        { type: 'p', text: 'For streamers, saltwater flies, and any lure whose action you want to preserve, a loop knot — most commonly the non-slip mono loop (Kreh loop), four turns, taught by Lefty Kreh in his casting clinics for forty years — lets the fly swim freely instead of riveted stiffly to the tippet. It is the last knot most fly fishermen learn. It is also the one that most changes what a fly does in the water.' },
        { type: 'h2', text: 'Practice on the couch' },
        { type: 'p', text: 'Animated Knots by Grog — a free website, also an app — shows each knot as a step-by-step animation with the tag end highlighted in color. Ten minutes a night on dry line, from a couch, turns the three knots above into muscle memory by the weekend. A fisherman who has to look at a diagram on the riverbank has lost the bite; one whose hands know the turns ties without thinking, and is already casting again.' },
      ],

      keyTerms: ['improved clinch', 'Palomar', 'blood knot', 'double uni', 'loop knot (Kreh)', 'tag end', 'standing line', 'tippet', 'leader', 'breaking strength'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://www.animatedknots.com/fishing-knots',
            title: 'Animated Knots — fishing knots library',
            channel: 'Animated Knots by Grog', duration: 'on-demand',
            why: '28 fishing knots, each as a step-by-step animation with tag end colored. The internet\'s best knot-teaching resource, free, no sign-in.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/fishingwithrod',
            title: 'Fishing with Rod — full channel',
            channel: 'Fishing with Rod', duration: 'variable',
            why: 'Rodney Hsu\'s British Columbia river-fishing channel. His slow on-water knot-tying sequences are the best demonstrations of technique on YouTube.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@SaltStrong',
            title: 'Salt Strong — knot tutorials',
            channel: 'Salt Strong', duration: 'variable',
            why: 'A saltwater-focused channel whose side-by-side knot strength tests have settled arguments among working charter captains for a decade.' },
          { id: null, source: 'other',
            url: 'https://howtoflyfish.orvis.com/video-lessons',
            title: 'Orvis Fly Fishing Video Lessons',
            channel: 'Orvis Learning Center', duration: 'variable',
            why: 'Tom Rosenbauer\'s free Orvis video series includes a full chapter on knots, tied on camera at beginner pace.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@MonsterMike-Fishing',
            title: 'Monster Mike — knot strength tests',
            channel: 'Monster Mike', duration: 'variable',
            why: 'Line-by-line destructive tests. Watch the knots fail before you trust them on a fish.' },
        ],
        books: [
          { title: 'The MeatEater Fish and Game Cookbook',
            author: 'Steven Rinella', year: 2020,
            url: 'https://www.themeateater.com/cook/cookbook',
            why: 'Rinella\'s book is ostensibly a cookbook, but its opening chapters on handling fish — from knot through filet — are among the clearest in print. The book to give a beginner who catches and cleans his own.' },
          { title: 'The Complete Angler',
            author: 'Izaak Walton', year: 1653,
            url: 'https://www.gutenberg.org/ebooks/9198',
            why: 'The founding text in English on the contemplative fishing life, and the second-most-reprinted book in English after the Bible. Free from Project Gutenberg.' },
          { title: 'The Little Red Book of Fly Fishing',
            author: 'Kirk Deeter and Charlie Meyers', year: 2010, url: '',
            why: '250 numbered tips from two of the best working fishing writers. Terse, practical, reads in an afternoon.' },
          { title: 'Practical Fishing Knots',
            author: 'Mark Sosin and Lefty Kreh', year: 1991, url: '',
            why: 'The working anglers\' reference. Diagrams, strength data, and a lifetime of Kreh\'s saltwater experience.' },
        ],
        articles: [
          { title: 'Fishing', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Fishing',
            why: 'A sober, well-referenced overview of the practice and its industry — the place to learn why line test is measured in pounds.' },
          { title: 'Fishing techniques', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Fishing_techniques',
            why: 'Bait, lure, fly, net, trap, spear — the full catalog, with diagrams.' },
        ],
        courses: [
          { title: 'Take Me Fishing — learn to fish',
            provider: 'Recreational Boating &amp; Fishing Foundation',
            url: 'https://www.takemefishing.org/how-to-fish/',
            free: true,
            why: 'A federally recognized nonprofit\'s free beginner curriculum — knots, tackle, how to read water. Non-commercial, state-specific regulation finder included.' },
          { title: 'Orvis Fly Fishing Learning Center (free)',
            provider: 'Orvis',
            url: 'https://howtoflyfish.orvis.com/',
            free: true,
            why: 'Tom Rosenbauer\'s free thirteen-chapter video course. Despite the retailer behind it, the curriculum is honest and the animated-knot segments are among the best on the internet.' },
        ],
        tools: [
          { title: 'Animated Knots (web + app)',
            url: 'https://www.animatedknots.com/',
            why: 'The reference. Fishing, boating, climbing, and rescue knots, each as a side-by-side animation and photo sequence.' },
          { title: 'Trout Unlimited — Find a Chapter',
            url: 'https://www.tu.org/chapters/',
            why: 'The conservation organization\'s chapter finder. Most chapters run free beginner nights and casting clinics for members.' },
        ],
        primarySources: [
          { title: 'Izaak Walton, The Compleat Angler (1653)',
            url: 'https://www.gutenberg.org/ebooks/9198',
            why: 'The founding document. Public domain, in several editions, on Gutenberg.' },
        ],
      },

      interactive: null,
      seeAlso: ['flyfishing', 'knots', 'survival'],
      prereqs: [],
      leadsTo: ['flyfishing'],

      chapterActivity: 'A Saturday knot-tying night at the Prospect Park Lakeside Angler\'s Club — spools of practice mono on the table, coffee, and a mentor at every seat.',

      sources: [
        'https://www.animatedknots.com/fishing-knots',
        'https://en.wikipedia.org/wiki/Fishing',
        'https://howtoflyfish.orvis.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    flyfishing: {
      id: 'flyfishing',
      name: 'Fly Fishing',
      level: 'Advanced',
      dek: 'The cast and the drift — where angling ceases to be catching and becomes reading the water.',
      readTime: '14 min',

      sections: ['A line you cast, not a lure you throw', 'The cast', 'The drift', 'Matching the hatch', 'A lineage of books', 'The fish and the watershed'],
      body: [
        { type: 'lead', text: 'In Norman Maclean\'s 1976 novella A River Runs Through It, the narrator\'s father — a Presbyterian minister in Missoula, Montana — teaches his two sons to fish by a metronome, four counts back and four counts forward, so that the rod stops at ten o\'clock and at two o\'clock and the line rolls out in a straight line on the Blackfoot. "To him," Maclean writes, "all good things — trout as well as eternal salvation — come by grace and grace comes by art and art does not come easy." No sport in English has been written about more lovingly, or more honestly about its own difficulty.' },
        { type: 'figure', src: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Fly_fishing.jpg',
          alt: 'A fly fisherman casting on a river',
          caption: 'Fly fishing — the line, not the lure, carries the weight.',
          credit: 'Wikimedia Commons · Public domain' },
        { type: 'h2', text: 'A line you cast, not a lure you throw' },
        { type: 'p', text: 'Every other kind of fishing casts by throwing a weighted lure and letting the line follow. Fly fishing reverses the physics: the weight is in the line itself, a tapered length of plastic-coated braid, and the angler propels it with the rod by loading the line in a back-cast and releasing it in a forward stroke. The fly at the end, which imitates a mayfly or caddis or emerger, is virtually weightless — often a hook dressed in hackle and thread, no heavier than a dime. Everything about the equipment follows from this inversion. The rod is long and flexible; the line is heavy for its thickness; the leader steps down in diameter from a thick butt to a hair-thin tippet so that the energy of the cast rolls smoothly to the fly and lays it on the water without a splash.' },
        { type: 'h2', text: 'The cast' },
        { type: 'p', text: 'Lefty Kreh, the Baltimore casting clinician who taught half the country\'s fly fishermen before his death in 2018, reduced the cast to five principles: the rod tip must travel in a straight line; longer strokes for longer casts; the stroke must accelerate to a stop; the back-cast and forward-cast must be 180 degrees apart; the line must be tight at the start of the stroke. Everything past those five is ornament. A beginner who understands them becomes competent in a summer; most fly fishermen never do understand them and cast for forty years anyway.' },
        { type: 'h2', text: 'The drift' },
        { type: 'p', text: 'The whole point of the cast is to deliver a fly so that it drifts on the current at the same speed as the natural flies the trout is eating. Drag — any bow or tension in the line that pulls the fly unnaturally across the current — is the single most common reason a fisherman catches nothing. Mending, a sideways flip of the line to match the water\'s differential speed, is the technique that prevents drag. An angler who can read the seam where fast and slow water meet, and mend her line to float a fly naturally down that seam, will outfish better casters who cannot.' },
        { type: 'h2', text: 'Matching the hatch' },
        { type: 'p', text: 'Wild trout in a good river eat, in a given week, a predictable sequence of aquatic insects — the hatch. Match the size, silhouette, and color of the bug on the water, and the trout treats your imitation as food. Miss any of those three by much, and she treats it as a piece of fluff. The working fly fisherman carries a dozen core patterns (Parachute Adams, Elk Hair Caddis, Pheasant Tail, Hare\'s Ear, Woolly Bugger) in three sizes each. That is enough to cover most North American rivers most of the year. The rest is pattern proliferation for its own sake — though the lifetime project of tying your own flies is one of the old pleasures of the sport, and no dollar in your vest produces more satisfaction than the one you catch a fish on with a fly you tied.' },
        { type: 'callout', text: 'Barbless hooks, crushed with pliers or bought that way, release cleanly and hurt the fish less. Keep a wild trout wet while unhooking; hold it in the current until it swims from your fingers. The fish you let go today is the one someone teaches a child to catch in three years.' },
        { type: 'h2', text: 'The lineage of books' },
        { type: 'p', text: 'The fly-fishing library is older and better than the hobby deserves. Walton\'s Compleat Angler (1653) is the founding text; Dame Juliana Berners\' Treatyse of Fysshynge with an Angle (1496) is older. In English prose of the last century, John Gierach\'s Sex, Death, and Fly-Fishing (1990) is the companion volume for anyone who will read anything well written; Roderick Haig-Brown\'s A River Never Sleeps (1946) is the Pacific Northwest answer to Walton. David James Duncan\'s The River Why (1983) is the great American coming-of-age novel about the subject. Maclean remains the only American who turned fishing into literature.' },
        { type: 'h2', text: 'The fish and the watershed' },
        { type: 'p', text: 'Wild trout are a litmus test for clean cold water. Where they still swim, the watershed is roughly in working order; where they have vanished, something is wrong a hundred miles upstream. Trout Unlimited, the American conservation organization, has spent fifty years restoring streams with volunteer labor — 539 miles reconnected and 830,000 acres protected by 2026. To fish a wild-trout river seriously is to take on some responsibility for it. Most anglers do.' },
      ],

      keyTerms: ['fly line', 'leader', 'tippet', 'hatch', 'drift', 'mending', 'backcast', 'forward stroke', 'dry fly', 'nymph', 'streamer', 'catch and release'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://howtoflyfish.orvis.com/video-lessons',
            title: 'Orvis Fly Fishing Video Lessons — all 13 chapters',
            channel: 'Orvis Learning Center', duration: '~5 hours total',
            why: 'Tom Rosenbauer, the voice of the Orvis Learning Center for two decades, teaches the whole beginner sequence: cast, knot, hatch, and drift. Free, in HD, and honest.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/fishingwithrod',
            title: 'Fishing with Rod — full channel',
            channel: 'Fishing with Rod', duration: 'variable',
            why: 'Rodney Hsu\'s British Columbia river work — equal parts how-to and watershed love letter. A good counterpoint to the Orvis production style.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@OrvisFlyFishing',
            title: 'Orvis Fly Fishing — full channel',
            channel: 'Orvis', duration: 'variable',
            why: 'Tom Rosenbauer\'s shorter tips, the Orvis podcast clips, and the full fly-tying series. The working channel to accompany the Learning Center.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@HuggerIndustries',
            title: 'Hugger Industries — casting clinics',
            channel: 'Hugger Industries', duration: 'variable',
            why: 'Kelly Galloup\'s blunt, specific casting videos. Galloup is one of the country\'s best streamer fishermen and a famously direct teacher.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@timflagler',
            title: 'Tightline Productions — fly tying',
            channel: 'Tim Flagler', duration: 'variable',
            why: 'Tim Flagler\'s vise-mounted tying videos are the gold standard — every step at a patient pace, the camera angle the tyer\'s own.' },
        ],
        books: [
          { title: 'A River Runs Through It and Other Stories',
            author: 'Norman Maclean', year: 1976, url: '',
            why: 'The great American fishing novella. Read it slowly; Robert Redford\'s film is good but the prose is better.' },
          { title: 'The Compleat Angler',
            author: 'Izaak Walton', year: 1653,
            url: 'https://www.gutenberg.org/ebooks/9198',
            why: 'The founding text. Free on Gutenberg in multiple editions.' },
          { title: 'Sex, Death, and Fly-Fishing',
            author: 'John Gierach', year: 1990, url: '',
            why: 'The essayist\'s essayist of contemporary American fly fishing. Thirty books in, Gierach\'s first collection is still the one to start with.' },
          { title: 'A River Never Sleeps',
            author: 'Roderick Haig-Brown', year: 1946, url: '',
            why: 'The Pacific Northwest\'s answer to Walton. Haig-Brown fished the Campbell River on Vancouver Island for forty years and wrote about it month by month.' },
          { title: 'The Orvis Fly-Fishing Guide',
            author: 'Tom Rosenbauer', year: 2017, url: '',
            why: 'The modern standard instructional book. Rosenbauer is the same voice as the video lessons; the book is the reference.' },
          { title: 'The MeatEater Fish and Game Cookbook',
            author: 'Steven Rinella', year: 2020,
            url: 'https://www.themeateater.com/cook/cookbook',
            why: 'Handling, cleaning, and cooking what you catch. Rinella treats fish with the same seriousness as game.' },
        ],
        articles: [
          { title: 'Fly fishing', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Fly_fishing',
            why: 'A clean history from Roman Macedonian anglers through the Catskills school and the graphite-rod revolution.' },
          { title: 'A River Runs Through It', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/A_River_Runs_Through_It_and_Other_Stories',
            why: 'Maclean\'s book — the Pulitzer nomination, the refusal of the University of Chicago Press to edit the novella, and the story of how the book got made.' },
        ],
        courses: [
          { title: 'Orvis Fly Fishing Learning Center',
            provider: 'Orvis',
            url: 'https://howtoflyfish.orvis.com/',
            free: true,
            why: 'The gold-standard free beginner course. Thirteen chapters of video, animated knots, fly-pattern flashcards.' },
          { title: 'Free Fly Fishing 101 classes in-store',
            provider: 'Orvis (US retail locations)',
            url: 'https://www.orvis.com/free-fly-fishing-lessons.html',
            free: true,
            why: 'Free two-hour instructor-led introductory sessions in US Orvis stores. The practical complement to the online course.' },
        ],
        tools: [
          { title: 'Trout Unlimited — Find a Chapter',
            url: 'https://www.tu.org/chapters/',
            why: 'Volunteer conservation and free casting clinics at chapters in most US states and several Canadian provinces.' },
          { title: 'Animated Knots — fishing',
            url: 'https://www.animatedknots.com/fishing-knots',
            why: 'The clinch, Palomar, blood, uni, and loop knots — every step in animation.' },
          { title: 'USGS Current Water Data',
            url: 'https://waterdata.usgs.gov/nwis/rt',
            why: 'Real-time stream gauge data for every major US river. Know the flow before you drive.' },
        ],
        primarySources: [
          { title: 'Dame Juliana Berners, Treatyse of Fysshynge with an Angle (1496)',
            url: 'https://en.wikipedia.org/wiki/A_Treatyse_of_Fysshynge_with_an_Angle',
            why: 'The oldest fishing treatise in English. The Wikipedia article is the most accessible modern doorway.' },
        ],
      },

      interactive: null,
      seeAlso: ['knots_fish', 'ecology', 'knots'],
      prereqs: ['knots_fish'],
      leadsTo: [],

      chapterActivity: 'An April casting clinic on the lawn at the North American Fly Fishers\' Harriman Park outing — bring a 5-weight, or borrow one from a chapter member.',

      sources: [
        'https://en.wikipedia.org/wiki/Fly_fishing',
        'https://howtoflyfish.orvis.com/',
        'https://www.tu.org/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
