// content/foraging.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: safety_forage, mushrooms
//
// NOTE: Foraging is a subject where misidentification can kill. The prose
// enforces the rule of absolute certainty; resources are weighted toward
// careful, named authorities (Sam Thayer, Adam Haritan, Michael Kuo, NAMA).

window.CONTENT = window.CONTENT || {};
window.CONTENT.foraging = {
  subjectId: 'foraging',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    safety_forage: {
      id: 'safety_forage',
      name: 'Safety & Ethics',
      level: 'Beginner',
      dek: 'The rule of absolute certainty, the habit of leaving more than you take, and why one plant a season is enough.',
      readTime: '11 min',

      sections: ['The rule of absolute certainty', 'What a careful forager looks like', 'The ethics of the wild harvest', 'The law, which is not optional', 'Start with the unmistakable'],
      body: [
        { type: 'lead', text: 'In July 2023, a woman in country Victoria, Australia, served a beef Wellington made with what she told police were foraged mushrooms. Three of her four guests were dead within a week; the fourth spent nearly two months in hospital. The fungus was the death cap, Amanita phalloides, which contains amatoxins that destroy the liver silently for a day before the symptoms return. No foraging subject can begin anywhere else. The rule of the harvest is absolute certainty, or you leave it.' },
        { type: 'h2', text: 'The rule of absolute certainty' },
        { type: 'p', text: 'Sam Thayer, the Wisconsin forager who has spent forty years in the field and written three of the best books in English on the subject, states the rule in one line: identify the plant by every one of its features, consistent with published keys, using at least two independent sources, or do not eat it. Eighty percent sure is zero percent. "Looks like" is not identification. A smartphone photo-matching app is a way to generate hypotheses, never a verdict. The error rate that matters is not the app\'s; it is yours in the moment you want the answer to be yes.' },
        { type: 'h2', text: 'What a careful forager looks like' },
        { type: 'p', text: 'She learns one plant a season — spring ramps in the Catskills one year, summer lamb\'s-quarters in the community-garden edges the next. She reads two references before tasting any new species, then a third. She takes tiny first portions and waits a day. She never harvests anything lookalike-rich (morels, chanterelles, milkweed shoots) from the first patch she finds; she confirms the ID from a known patch before she trusts her own eye. She writes down the dates and places in a notebook, because a forager\'s memory is worse than she thinks.' },
        { type: 'h2', text: 'Ethics: take a tenth' },
        { type: 'p', text: 'Wild populations do not exist to feed you. Dig one ramp in ten, or none. Never strip a patch. Do not post the coordinates of rare stands on social media — an online ramp post can wipe out a forty-year colony in a weekend. The old New England woodcraft motto, take what you need and leave more than you take, predates any modern ethic and still governs the field. The Forest Service sets formal quotas on many species on federal land; most states require a commercial permit past a household threshold. Match those rules or tighten them.' },
        { type: 'callout', text: 'If you cannot identify the plant at every stage of its life cycle — flower, leaf, root, seed head — you are not ready to eat it. A safe forager knows what the plant looks like in October and in March, not only on the afternoon it tempts her.' },
        { type: 'h2', text: 'The law and the land' },
        { type: 'p', text: 'Public-land rules vary. National parks almost universally prohibit consumptive foraging; national forests permit it in small amounts; state and local rules are a patchwork. New York City park regulations forbid removing any plant matter — yes, even dandelions — and NYPD Parks Enforcement does in fact write tickets. On private land you need the landowner\'s permission, in writing if you are planning to return. There is no forager\'s exemption in the trespass statute, and a good relationship with a landowner is worth more than any patch.' },
        { type: 'h2', text: 'Start with the unmistakable' },
        { type: 'p', text: 'Samuel Thayer\'s recommended beginner list — dandelion, wild strawberry, nettle, cattail, wood sorrel, and maybe black walnut if you live east of the Mississippi — is what he calls the "forager\'s first year." None of them has a dangerous lookalike. Each teaches one habit: the root dig, the seasonal stalking, the blanch, the crack-and-pick. A year spent on six plants is better than a week spent on sixty, and it is how every serious forager any of us knows actually began.' },
      ],

      keyTerms: ['positive identification', 'lookalike', 'voucher specimen', 'Leave No Trace', 'ethnobotany', 'quota', 'invasive harvest', 'wildcraft'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@LearnYourLand',
            title: 'Learn Your Land — full channel (Adam Haritan)',
            channel: 'Learn Your Land', duration: 'variable',
            why: 'Adam Haritan is the most careful teacher on the internet. His beginner series — starting with "Top 5 Wild Edible Plants for Beginners" — is the right way in.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@thefabulousfoodtrippers',
            title: 'Wild Food Trippers — species walks',
            channel: 'Wild Food Trippers', duration: 'variable',
            why: 'Slow-paced identification walks for common temperate species. Good for the beginner who needs to see the plant in a video before the woods.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@ForagerChef',
            title: 'Forager Chef — Alan Bergo',
            channel: 'Forager Chef', duration: 'variable',
            why: 'A working forager and chef from Minnesota. The cooking is good; the identification cautions are better.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@sergeithepreppy',
            title: 'Sergei Boutenko — Wild Edibles',
            channel: 'Sergei Boutenko', duration: 'variable',
            why: 'A careful Pacific Northwest forager with a large species catalog, each video centered on one unmistakable plant.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@NAMAmushrooms',
            title: 'North American Mycological Association — talks and forays',
            channel: 'NAMA', duration: 'variable',
            why: 'Recorded talks from the premier amateur and professional mushroom organization. The right place to learn the toxicology talks you want in your head before your first chanterelle hunt.' },
        ],
        books: [
          { title: 'The Forager\'s Harvest',
            author: 'Samuel Thayer', year: 2006,
            url: 'https://foragersharvest.com/the-foragers-harvest/',
            why: 'The most careful general foraging book in English. Thirty-two plants, each taught in full — root, shoot, flower, seed — so you know the species at every season.' },
          { title: 'Nature\'s Garden',
            author: 'Samuel Thayer', year: 2010, url: '',
            why: 'The sequel. Forty-one more species, with a much stronger treatment of lookalike risk than any other general guide.' },
          { title: 'Incredible Wild Edibles',
            author: 'Samuel Thayer', year: 2017, url: '',
            why: 'The third volume. Thirty-six more species; Thayer is now the standard reference and his three books together are the working library.' },
          { title: 'A Field Guide to Edible Wild Plants (Peterson)',
            author: 'Lee Allen Peterson', year: 1999, url: '',
            why: 'The classic backpack field guide — Peterson format, familiar illustrations, good bibliography. A second opinion when Thayer is at home on the shelf.' },
          { title: 'Stalking the Wild Asparagus',
            author: 'Euell Gibbons', year: 1962, url: '',
            why: 'The 1962 book that started the American revival. Dated in places, still unmatched as nature writing.' },
        ],
        articles: [
          { title: 'Foraging', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Foraging',
            why: 'A general overview from the behavioral-ecology angle as well as the human-harvest angle — useful background.' },
          { title: 'Mushroom poisoning', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Mushroom_poisoning',
            why: 'The case everyone should read before their first mushroom walk. Mortality data, toxin classes, and the delayed-onset trap of amatoxin syndrome.' },
          { title: 'Leave No Trace — Seven Principles',
            source: 'Leave No Trace Center for Outdoor Ethics',
            url: 'https://lnt.org/why/7-principles/',
            why: 'The standard outdoor-ethics framework. Applies directly to foraging — especially Principles 2, 3, and 6.' },
        ],
        courses: [
          { title: 'Learn Your Land — Online Courses',
            provider: 'Adam Haritan',
            url: 'https://courses.learnyourland.com/',
            free: false,
            why: 'Adam Haritan\'s self-paced courses on plant and mushroom identification. The YouTube channel is the free on-ramp; these are the paid deep dives.' },
          { title: 'NAMA Affiliated Clubs (find a local foray)',
            provider: 'North American Mycological Association',
            url: 'https://www.namyco.org/clubs.php',
            free: true,
            why: 'Most state and metropolitan areas have an affiliated mushroom club running free or low-cost guided forays. The best way to learn is beside someone who already knows.' },
        ],
        tools: [
          { title: 'iNaturalist',
            url: 'https://www.inaturalist.org/',
            why: 'Community-verified identifications — upload a photo, real naturalists weigh in within a day. A generator of hypotheses, never a final word.' },
          { title: 'Go Botany (New England)',
            url: 'https://gobotany.nativeplanttrust.org/',
            why: 'The Native Plant Trust\'s dichotomous-key identification site for New England plants. The model every regional key should follow.' },
        ],
        primarySources: [
          { title: 'USDA PLANTS Database',
            url: 'https://plants.usda.gov/',
            why: 'The authoritative federal database of North American plants — range, taxonomy, invasive status. The first stop for any identification question.' },
        ],
      },

      interactive: null,
      seeAlso: ['mushrooms', 'ecology', 'gardening'],
      prereqs: [],
      leadsTo: ['mushrooms'],

      chapterActivity: 'A late-April ramp walk with a New York Mycological Society guide in Van Cortlandt Park — look only, do not dig; the patch is watched.',

      sources: [
        'https://en.wikipedia.org/wiki/Foraging',
        'https://en.wikipedia.org/wiki/Mushroom_poisoning',
        'https://foragersharvest.com/',
        'https://www.namyco.org/',
      ],
      verifiedAt: '2026-04-23',
    },

    mushrooms: {
      id: 'mushrooms',
      name: 'Mushrooms',
      level: 'Advanced',
      dek: 'High reward, high risk — the kingdom of fungi, and why no serious forager picks a mushroom alone in the first year.',
      readTime: '13 min',

      sections: ['The kingdom below the soil', 'The foolproof four', 'The four that will kill you', 'Spore prints and keys', 'Clubs, not solitudes'],
      body: [
        { type: 'lead', text: 'On a damp October morning in 1881, the French mycologist Lucien Quélet was walking a beech wood in the Jura when he noticed a yellow-orange mushroom with forked ridges running down its stem. He named it Cantharellus cibarius, the chanterelle, and added it to the catalog of safely edible European fungi. A century and a half later, that catalog is longer but not by as much as people think. Of an estimated 2.2 to 3.8 million fungal species on Earth, humans eat fewer than a hundred reliably, and roughly a dozen can kill you from a single bite.' },
        { type: 'figure', src: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Cantharellus_cibarius_02.jpg',
          alt: 'Golden chanterelle, Cantharellus cibarius',
          caption: 'A golden chanterelle — one of the "foolproof four" beginner mushrooms, with forked ridges running down its stem rather than true gills.',
          credit: 'Björn S. · Wikimedia Commons · CC BY-SA 2.0' },
        { type: 'h2', text: 'The kingdom below the soil' },
        { type: 'p', text: 'A mushroom is the fruiting body of a fungus — a small, briefly visible organ attached to a vastly larger organism, the mycelium, which is a branching network of white threads threaded through soil or wood. Most fungi are invisible most of the time. Merlin Sheldrake\'s 2020 book Entangled Life is the best popular introduction to the kingdom in a generation, and makes clear why a forager who thinks of mushrooms as individual objects misses the point. She is harvesting a single week\'s seasonal bloom from a perennial organism that may be older than she is.' },
        { type: 'h2', text: 'The foolproof four' },
        { type: 'p', text: 'Traditional mycological clubs in North America teach a starter list — chanterelle, morel, chicken-of-the-woods, and giant puffball — as the "foolproof four." The phrase is a slight overstatement: chanterelles have a toxic lookalike in the jack-o\'-lantern, morels have the poisonous verpa and the false-morel gyromitra, chicken-of-the-woods on eastern red cedar or eucalyptus can cause gastric upset, and puffballs must be sliced open to confirm the flesh is pure white and featureless (if it is not, it might be a young Amanita). But with those cautions taught carefully, the four will carry a beginner through a first season without a hospital visit.' },
        { type: 'h2', text: 'The four that will kill you' },
        { type: 'p', text: 'Amanita phalloides — the death cap — is responsible for the majority of fatal mushroom poisonings worldwide. It looks benign: pale cap, white gills, smooth stalk, a ring, a cup at the base half-buried in the leaf litter. Its toxins destroy the liver over two to five days after the gastric symptoms have already passed. Amanita virosa, the destroying angel, is its pure-white cousin. Amanita ocreata is the western version. Galerina marginata, a small brown mushroom on rotting wood, contains the same amatoxins and has been mistaken for psilocybin species with predictable outcomes. None of the four has a useful field test. The only reliable defense is not eating any small brown mushroom, any white-gilled mushroom with a ring and cup, or any unknown Amanita, ever.' },
        { type: 'callout', text: 'There is no home test for amatoxins. Boiling does not destroy them. There is no reliable folk-taste test — "edible" and "deadly" mushrooms taste similar. The rule: one species a season, confirmed with a club member or professional. Nothing else is safe.' },
        { type: 'h2', text: 'Spore prints and keys' },
        { type: 'p', text: 'A spore print — cap laid gills-down on paper overnight — gives the color of the spores, a character that distinguishes whole families the eye cannot. Brown-spored Galerina from white-spored Pholiota, white-spored Amanita from pink-spored Pluteus, black-spored Coprinus from everything else. Michael Kuo\'s MushroomExpert.com is the best free resource in English; its keys walk the reader through spore color, cap texture, gill attachment, and habitat in the order a working mycologist asks the questions. David Arora\'s Mushrooms Demystified is the print counterpart — 959 pages, the standard for the Pacific coast but broadly useful.' },
        { type: 'h2', text: 'Clubs, not solitudes' },
        { type: 'p', text: 'The North American Mycological Association keeps a list of affiliated clubs in most metropolitan areas; their guided forays are free or nearly so. Go to a foray before you eat. An experienced member will walk the floor of the woods with you, and a two-hour walk in her company will teach more than a month of books. This is the one subject where apprenticeship, not autodidacticism, is the professional habit. If you skip it, you are gambling with a loaded die.' },
      ],

      keyTerms: ['mycelium', 'fruiting body', 'spore print', 'gill', 'ring (annulus)', 'volva', 'amatoxin', 'false morel', 'mycorrhizal', 'saprotroph'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@LearnYourLand',
            title: 'Learn Your Land — mushroom series',
            channel: 'Adam Haritan', duration: 'variable',
            why: 'Adam Haritan\'s mushroom videos are the most careful identification teaching on YouTube. Always pairs the target species with its dangerous lookalikes in the same video.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@ForagerChef',
            title: 'Forager Chef — Alan Bergo',
            channel: 'Forager Chef', duration: 'variable',
            why: 'A working chef-forager whose mushroom videos are cooking-forward but always follow a rigorous identification pass first.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@NAMAmushrooms',
            title: 'NAMA — talks on toxicology and ID',
            channel: 'North American Mycological Association', duration: 'variable',
            why: 'The national organization\'s own recorded talks. The toxicology talks, in particular, are the ones you want in your head before the first wet fall weekend.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@Mushroaming',
            title: 'Mushroaming — Daniel Winkler',
            channel: 'Mushroaming', duration: 'variable',
            why: 'Daniel Winkler is a professional mycologist and guide; his videos from the Pacific Northwest and the Himalayas are field lessons in what a working mycologist looks at.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@thefungalcanon',
            title: 'The Fungal Canon',
            channel: 'The Fungal Canon', duration: 'variable',
            why: 'Slow, microscopy-inclusive species features. Good for the second-year forager who wants to see what a spore under 400× looks like.' },
        ],
        books: [
          { title: 'Mushrooms Demystified',
            author: 'David Arora', year: 1986, url: '',
            why: 'The 959-page classic. Pacific-coast focus, broad coverage, and the book every serious American forager owns by volume three.' },
          { title: 'All That the Rain Promises, and More',
            author: 'David Arora', year: 1991, url: '',
            why: 'Arora\'s field-portable companion volume. Photographs, keys, and a cover that is somehow a Polish mushroom-hunter with a double bass. The book to carry.' },
          { title: 'Mushrooms of the Northeastern United States and Eastern Canada',
            author: 'Timothy Baroni', year: 2017, url: '',
            why: 'The best modern regional key for the eastern US and Canada. Timothy Baroni is the working authority on the region.' },
          { title: 'Entangled Life',
            author: 'Merlin Sheldrake', year: 2020, url: '',
            why: 'The best popular book on fungi of the last decade. Not an identification guide — a why-mushrooms-matter book that changes what you look at.' },
          { title: 'Mushrooms of the Midwest',
            author: 'Michael Kuo and Andrew Methven', year: 2014, url: '',
            why: 'Michael Kuo\'s regional guide — the print companion to MushroomExpert.com. Strongly keyed and honest about identification ambiguity.' },
        ],
        articles: [
          { title: 'Mushroom poisoning', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Mushroom_poisoning',
            why: 'The essential background. Toxin classes, mortality, treatment. Read before the first foray.' },
          { title: 'Amanita phalloides (death cap)', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Amanita_phalloides',
            why: 'The single most dangerous fungus a North American forager will ever cross paths with. Learn its shape before anything else.' },
          { title: 'MushroomExpert.com',
            source: 'Michael Kuo', url: 'https://www.mushroomexpert.com/',
            why: 'The best free mycology reference in English. Keys, species pages, a running glossary, and an honest tone about the limits of field identification.' },
        ],
        courses: [
          { title: 'Learn Your Land — Foraging Wild Mushrooms',
            provider: 'Adam Haritan',
            url: 'https://courses.learnyourland.com/',
            free: false,
            why: 'The paid course. Haritan\'s free YouTube content is the on-ramp; this is the systematic curriculum.' },
          { title: 'NAMA affiliated clubs — guided forays',
            provider: 'North American Mycological Association',
            url: 'https://www.namyco.org/clubs.php',
            free: true,
            why: 'Find the nearest club. A Saturday foray with an experienced member is the foundational education this subject requires.' },
        ],
        tools: [
          { title: 'iNaturalist',
            url: 'https://www.inaturalist.org/',
            why: 'The best photo-based ID community. Real mycologists weigh in on posts — use it to generate hypotheses, never as final word.' },
          { title: 'MycoKey',
            url: 'https://mycokey.com/',
            why: 'Jens Petersen\'s computer-assisted Nordic key, widely used by serious amateurs worldwide.' },
        ],
        primarySources: [
          { title: 'NAMA Toxicology Committee — annual poisoning reports',
            url: 'https://www.namyco.org/toxicology.php',
            why: 'Year-by-year reports on North American mushroom poisonings. The best data on what actually goes wrong.' },
        ],
        images: [
          { src: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Cantharellus_cibarius_02.jpg',
            alt: 'Chanterelle mushroom, Cantharellus cibarius',
            caption: 'A golden chanterelle — ridges, not gills, run down the stem.',
            credit: 'Björn S. · Wikimedia Commons · CC BY-SA 2.0' },
          { src: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Amanita_phalloides_1.JPG',
            alt: 'Death cap, Amanita phalloides',
            caption: 'Amanita phalloides — the death cap. Pale cap, white gills, ring, and a cup-like volva at the base half-buried in leaf litter.',
            credit: 'Archenzo · Wikimedia Commons · CC BY-SA 3.0' },
        ],
      },

      interactive: null,
      seeAlso: ['safety_forage', 'ecology', 'biochem'],
      prereqs: ['safety_forage'],
      leadsTo: [],

      chapterActivity: 'A wet-October guided foray with the New York Mycological Society in Central Park — bring a basket, a notebook, and an empty afternoon.',

      sources: [
        'https://en.wikipedia.org/wiki/Amanita_phalloides',
        'https://en.wikipedia.org/wiki/Mushroom_poisoning',
        'https://www.namyco.org/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
