// content/gamedev.js
// Owned by batch: B06-tech-and-code
// Last updated: 2026-04-23 by BATCH B06-tech-and-code
//
// Topics this subject covers (from data.js):
//   Core: loop, design_game

window.CONTENT = window.CONTENT || {};
window.CONTENT.gamedev = {
  subjectId: 'gamedev',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B06-tech-and-code',
  topics: {

    loop: {
      id: 'loop',
      name: 'The Game Loop',
      level: 'Intermediate',
      dek: 'The heartbeat of every real-time game — a cycle that reads input, updates the world, and draws it, sixty times a second.',
      readTime: '14 min',

      sections: ['The sixty-times-a-second problem', 'Update, render, repeat', 'Fixed timesteps vs. variable', 'What the engines do for you', 'The rendering pipeline', 'Where to start if you\'re starting'],
      body: [
        { type: 'lead', text: 'If a game is running smoothly at sixty frames per second, it is doing the same set of things every 16.67 milliseconds: reading the controller, moving characters, resolving collisions, playing sounds, and drawing a fresh picture on the screen. The loop that does this has been the skeleton of real-time games since Pong in 1972. Everything interesting in a game engine — physics, animation, networking, AI — hangs off it.' },
        { type: 'figure',
          src: 'content/images/pong_cabinet.jpg',
          alt: 'The original Pong upright arcade cabinet.',
          caption: 'The original Pong cabinet. The game loop inside it ran at 60 Hz, on hardware that predates the microprocessor. Fifty-four years later, the loop you will write does the same three things in the same order.',
          credit: 'Chris Rand, Wikimedia Commons (CC BY-SA 4.0).',
        },
        { type: 'h2', text: 'A real-time program is a fixed budget' },
        { type: 'p', text: 'Film runs at 24 frames per second, television at 30, modern games at 60 or 120. At 60 Hz, the whole loop has to finish in under 17 ms — or the screen skips a frame, and the player feels it as a stutter. Most of game programming is a budget exercise: what can be done in that time, what must be skipped, and what can be amortized across frames. Unlike a web server, which can queue work, a game cannot apologize and serve the next player later. The clock does not wait.' },
        { type: 'p', text: 'The most expensive common operation is drawing. Modern GPUs can push tens of millions of triangles per frame, but only if you organize the work so they can pipeline it — batch similar draw calls, upload geometry once, avoid state changes. The art is in the organization, not the raw capability. John Carmack used to say that id Software\'s secret was that the team understood exactly where each frame\'s 16 ms went. Everything else followed.' },
        { type: 'h2', text: 'The three phases of the loop' },
        { type: 'p', text: 'Input: poll the keyboard, mouse, gamepad, touchscreen for what changed since the last frame. Update: advance the simulation — move entities, run AI, tick timers, resolve physics and collisions. Render: build a list of draw calls and hand it to the GPU. Every modern engine, from Unreal to Unity to Godot, has these three phases under some name. Robert Nystrom\'s Game Programming Patterns, which is free online, devotes a whole chapter to the loop and why you should not write your own from scratch if an engine\'s will do.' },
        { type: 'animation',
          src: 'content/images/pong_gameplay.gif',
          caption: 'Pong, running. The 1972 game loop that invented the genre — and the pattern every modern engine still follows.',
          credit: 'Wikimedia Commons, public domain.',
        },
        { type: 'h2', text: 'Fixed timesteps and the Glenn Fiedler problem' },
        { type: 'p', text: 'The simple loop updates the world by however much real time has passed. The trouble is that variable time produces non-reproducible, non-deterministic physics — a fast machine and a slow machine get different results from the same inputs. Glenn Fiedler\'s 2004 article Fix Your Timestep!, still the most-linked post in game programming, lays out the standard answer: run the physics on a fixed timestep (say, 120 Hz), regardless of frame rate, and interpolate the rendering. That separation — simulation at a fixed rate, rendering at the display\'s rate — is quietly what makes every serious game feel solid.' },
        { type: 'callout', text: 'Decouple simulation from rendering. Run the simulation on a fixed timestep. Interpolate the visuals. If you take one thing from the subject, take that.' },
        { type: 'h2', text: 'What the engines actually buy you' },
        { type: 'p', text: 'You can write a game loop in fifty lines of C and some platform calls — Handmade Hero, Casey Muratori\'s long-running livestream, does exactly that. Most developers use Unity, Unreal, or Godot because writing the loop, the renderer, the audio mixer, the physics, the scripting, and the asset pipeline is a second full-time job. An engine is mostly other people\'s solutions to problems you will otherwise hit in month three.' },
        { type: 'p', text: 'The calculation in 2026 looks something like this: if you are shipping a commercial game in under two years, use an engine. If you are learning, writing a tiny 2D game, or doing something the engines do badly (a rhythm game with strict timing, an unusual input device, a port to obscure hardware), write your own. Almost nobody should write their own on the first project.' },
        { type: 'h2', text: 'The rendering pipeline' },
        { type: 'p', text: 'Under the render phase lives another pipeline entirely. Vertex shader, rasterization, fragment shader, blending — a story with its own decades of literature. The modern state of the art, as of 2026, is Vulkan, Metal, and Direct3D 12, with WebGPU joining as the cross-platform web story. All of them expose the same rough model — you upload data, describe what you want drawn, let the GPU work. The old fixed-function pipeline (OpenGL 1.x, DirectX 9) has been gone long enough that a new programmer may never encounter it, and should not.' },
        { type: 'aside', label: 'Why 60 Hz', text: 'Sixty frames per second is not arbitrary. It matches the 60 Hz refresh rate of North American CRTs, which was chosen because the US electrical grid is 60 Hz, which was chosen by Westinghouse in 1893 after a long argument with Edison. The entire visual language of games inherits from a choice made for generators, not eyeballs.' },
        { type: 'h2', text: 'Where to start if you\'re starting' },
        { type: 'p', text: 'Download Godot, which is free and honest about what it is. Follow the three-hour "Your First 2D Game" tutorial. Ship the tutorial result, verbatim, to itch.io. Then change one thing and ship it again. The loop you will build inside the engine will be boring and five lines long. That is the right amount of boring. The rest of the game is where your design decisions go.' },
      ],

      keyTerms: ['frame', 'tick', 'delta time', 'fixed timestep', 'interpolation', 'render pipeline', 'draw call', 'VSync', 'determinism', 'entity component system'],

      examples: [
        {
          title: 'A minimal game loop, in pseudocode',
          problem: 'while (running) {\n    input = poll_input();\n    update(world, input, dt);\n    render(world);\n}',
          steps: [
            { text: 'Poll input reads controllers, keyboard, mouse — anything that changed since the last frame.' },
            { text: 'Update advances the simulation by dt (delta time) — move things, tick timers, resolve collisions, run AI.' },
            { text: 'Render draws the current state of the world to the screen.' },
            { text: 'The loop runs until running becomes false (user quits). A real engine adds VSync, fixed-step physics, interpolation, but this is the skeleton.' },
          ],
          answer: 'Input → update → render, forever.',
        },
        {
          title: 'The 16 ms budget',
          problem: 'Your game runs at 60 fps. How long does each frame have?',
          steps: [
            { text: '60 frames per second means one frame every 1/60 second.' },
            { text: '1/60 s = 0.0167 s = 16.67 ms.' },
            { text: 'Every update + render must finish in under 17 ms or the screen skips a frame. This is the single most important constraint in real-time programming.' },
          ],
          answer: '16.67 ms per frame at 60 Hz.',
        },
      ],

      practice: [
        { q: 'What article, published in 2004 by Glenn Fiedler, introduced the fixed-timestep pattern?',
          a: 'Fix Your Timestep!', acceptable: ['fix your timestep', 'timestep'],
          difficulty: 'medium', hint: 'The title is an imperative.',
          solution: '"Fix Your Timestep!" on Gaffer on Games. Still the most-linked post in game programming.' },
        { q: 'At 120 fps, how long does each frame have (ms)?',
          a: '8.33', acceptable: ['8', '8.3', '~8', '8ms'],
          difficulty: 'easy', hint: '1/120 in milliseconds.',
          solution: '8.33 ms. Half the 60-fps budget.' },
        { q: 'Which separation keeps a game deterministic regardless of frame rate?',
          a: 'simulation from rendering', acceptable: ['fixed timestep', 'physics from rendering', 'simulation-rendering'],
          difficulty: 'medium', hint: 'Run one at a fixed rate, interpolate the other.',
          solution: 'Separate the simulation (at a fixed rate) from the rendering (at the display\'s rate), and interpolate the visuals.' },
      ],

      subtopics: [
        {
          id: 'loop.fixed_timestep',
          name: 'Fixed timestep and interpolation',
          summary: 'The trick that makes every serious game feel solid.',
          level: 'Intermediate', readTime: '8 min',
          body: [
            { type: 'lead', text: 'If physics runs at whatever frame rate the machine happens to hit, a fast computer and a slow computer will diverge on the same inputs. Glenn Fiedler\'s 2004 answer — run physics at a fixed rate, interpolate rendering to display rate — is the canonical fix, and it is in every serious engine today.' },
            { type: 'p', text: 'The loop looks like this. Accumulate real time into a bucket. While the bucket has more than one fixed-step worth of time, step the simulation once and subtract a step. Render with a fraction t = (bucket remaining) / (step size), interpolating between the previous and current state.' },
          ],
          practice: [
            { q: 'Why does a variable-timestep simulation produce non-reproducible physics?',
              a: 'different dt produces different integration', acceptable: ['different dt', 'different integration', 'floating-point', 'non-determinism'],
              difficulty: 'medium', hint: 'Euler integration with different dt produces different outputs.',
              solution: 'Integration with different dt values produces different trajectories. Two machines stepping with different dt will diverge, even from the same inputs.' },
          ],
          keyTerms: ['dt', 'accumulator', 'interpolation', 'determinism', 'VSync'],
        },
        {
          id: 'loop.ecs',
          name: 'Entity-component-system (ECS)',
          summary: 'Why inheritance hierarchies lose and data-oriented design wins on modern hardware.',
          level: 'Advanced', readTime: '8 min',
          body: [
            { type: 'lead', text: 'Classical OOP game engines put everything in a deep class hierarchy: Entity → Creature → Humanoid → Player. Each entity holds its own data. That is cache-hostile: to update every entity\'s position, you walk a hundred thousand randomly-placed objects.' },
            { type: 'p', text: 'ECS flips the picture. An entity is just an ID. Components are plain data, stored in flat arrays by type. Systems iterate over the arrays and do work. Updating every position is now a tight loop over a contiguous array — cache-friendly, vectorizable, fast.' },
            { type: 'p', text: 'Unity (since 2019), Bevy (the Rust engine), EnTT (the C++ library) are all ECS-forward. The performance gains are real, often an order of magnitude, on the kinds of games that hit the frame budget.' },
          ],
          practice: [
            { q: 'What is an entity in an ECS?',
              a: 'just an ID', acceptable: ['an id', 'identifier', 'number'],
              difficulty: 'easy', hint: 'Stripped of behaviour and data.',
              solution: 'Just an ID — typically a 64-bit integer. All the data lives in components, keyed by that ID.' },
          ],
          keyTerms: ['entity', 'component', 'system', 'archetype', 'data-oriented design', 'cache'],
        },
      ],

      resources: {
        videos: [
          { id: '86lqcCHofCg', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=86lqcCHofCg',
            title: 'How do Video Games Work? — Computerphile',
            channel: 'Computerphile', duration: '7:53',
            why: 'A clean short introduction to the game loop and why frames matter.' },
          { id: 'fdAOPHgW7qM', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=fdAOPHgW7qM',
            title: 'Handmade Hero — Day 1',
            channel: 'Casey Muratori / Molly Rocket', duration: '1:05:00',
            why: 'The first episode of the most complete open source-from-scratch game tutorial ever filmed. Six hundred episodes of C, no engine.' },
          { id: 'DiIoWrOlIRw', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=DiIoWrOlIRw',
            title: 'Why Physics is a Nightmare in Video Games',
            channel: 'Acerola', duration: '16:56',
            why: 'A modern, entertaining deep dive on why fixed timesteps matter.' },
          { id: 'eOCQfxRQ2pY', source: 'youtube', url: 'https://www.youtube.com/watch?v=eOCQfxRQ2pY',
            title: 'What Happens in a Game Engine?',
            channel: 'Acerola', duration: '13:47',
            why: 'A working engine programmer walks through the phases of a modern engine. Clean animations.' },
          { id: 'KpKCdrOzgI8', source: 'youtube', url: 'https://www.youtube.com/watch?v=KpKCdrOzgI8',
            title: 'The Game Loop — Explained',
            channel: 'Unity (YouTube)', duration: '7:00',
            why: 'From the maker of the most-used engine. Short, and useful if Unity is where you plan to land.' },
          { id: 'YwoGWpY6vT8', source: 'youtube', url: 'https://www.youtube.com/watch?v=YwoGWpY6vT8',
            title: 'Jonathan Blow — How to Program Independent Games',
            channel: 'Jonathan Blow (Rice University lecture)', duration: '1:03:00',
            why: 'The maker of Braid and The Witness on how independent games are actually made.' },
          { id: 'drzLRWQaHAY', source: 'youtube', url: 'https://www.youtube.com/watch?v=drzLRWQaHAY',
            title: 'Real-Time Rendering Pipeline',
            channel: 'Cem Yuksel (Utah CS 6610)', duration: '1:10:00',
            why: 'A graduate-level lecture on the modern GPU rendering pipeline. Technical but clear.' },
        ],
        books: [
          { title: 'Game Programming Patterns',
            author: 'Robert Nystrom', year: 2014,
            url: 'https://gameprogrammingpatterns.com/',
            why: 'Free online in full. The practical design-patterns book for games.' },
          { title: 'Game Engine Architecture',
            author: 'Jason Gregory', year: 2018, url: '',
            why: 'The reference. Gregory is a Naughty Dog engineer and the book is a tour of how a production engine actually fits together.' },
          { title: 'Real-Time Collision Detection',
            author: 'Christer Ericson', year: 2005, url: '',
            why: 'The standard text on the hardest part of most game loops.' },
          { title: 'Real-Time Rendering (4th edition)',
            author: 'Akenine-Möller, Haines, Hoffman', year: 2018, url: '',
            why: 'The reference on the render half of the loop. A fixture in every rendering programmer\'s bookshelf.' },
        ],
        articles: [
          { title: 'Fix Your Timestep!',
            source: 'Glenn Fiedler (Gaffer On Games)',
            url: 'https://gafferongames.com/post/fix_your_timestep/',
            why: 'The 2004 post that taught a generation of game programmers how to separate simulation from rendering.', year: 2004 },
          { title: 'Game Programming Patterns — Game Loop chapter',
            source: 'Robert Nystrom',
            url: 'https://gameprogrammingpatterns.com/game-loop.html',
            why: 'A single well-illustrated chapter on the pattern.', year: 2014 },
          { title: 'Game Developers Conference (GDC) Vault',
            source: 'GDC / Informa Tech', url: 'https://www.gdcvault.com/',
            why: 'The industry archive. A growing share of talks is free; the paid talks are often worth it.' },
          { title: 'What Every Programmer Needs To Know About Game Networking',
            source: 'Glenn Fiedler (Gaffer On Games)',
            url: 'https://gafferongames.com/post/what_every_programmer_needs_to_know_about_game_networking/',
            why: 'Once the loop works, your next problem is the network. Fiedler is the canonical resource.' },
        ],
        courses: [
          { title: 'MIT CMS.611J — Creating Video Games',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/cms-611j-creating-video-games-fall-2014/', free: true,
            why: 'A full MIT syllabus with readings, assignments, and studio projects.' },
          { title: 'Your First 2D Game — Godot',
            provider: 'Godot Engine Documentation',
            url: 'https://docs.godotengine.org/en/stable/getting_started/first_2d_game/index.html', free: true,
            why: 'The best free "make your first game in three hours" tutorial on the internet.' },
        ],
        tools: [
          { title: 'Godot Engine', url: 'https://godotengine.org',
            why: 'Free, open source, a real competitor to Unity for 2D and increasingly for 3D. The engine a lot of first-time developers are starting on in 2026.' },
          { title: 'Unity', url: 'https://unity.com',
            why: 'The most widely used commercial engine. C# scripting, huge asset store.' },
          { title: 'Unreal Engine', url: 'https://www.unrealengine.com',
            why: 'The other major commercial engine. Higher-end rendering, C++ and Blueprints.' },
          { title: 'LÖVE2D', url: 'https://love2d.org',
            why: 'A tiny Lua-based 2D framework. The gentlest on-ramp to writing your own engine-ish code.' },
        ],
        primarySources: [
          { title: 'Pong — Wikipedia page with original cabinet photos and schematics',
            url: 'https://en.wikipedia.org/wiki/Pong',
            why: 'The genre\'s founding game, with schematics and history.' },
          { title: 'Doom source code (1997)',
            url: 'https://github.com/id-Software/DOOM',
            why: 'The source to the game that made the 1990s. An education to read.' },
        ],
        images: [
          { src: 'content/images/pong_cabinet.jpg',
            caption: 'The original Pong cabinet, 1972.',
            credit: 'Chris Rand, Wikimedia Commons.' },
          { src: 'content/images/pong_gameplay.gif',
            caption: 'Pong, running. The first game loop most of the industry ever saw.',
            credit: 'Wikimedia Commons, public domain.' },
        ],
        animations: [
          { src: 'content/images/pong_gameplay.gif',
            title: 'Pong gameplay',
            why: 'The game that named the budget: sixty updates per second, two paddles, a ball.' },
          { youtubeId: 'DiIoWrOlIRw',
            title: 'Why Physics is a Nightmare in Video Games',
            channel: 'Acerola',
            why: 'Fixed timestep, explained the modern way.' },
        ],
      },

      interactive: null,
      seeAlso: ['design_game', 'programming', 'datastructures'],
      prereqs: ['programming'],
      leadsTo: ['design_game'],

      chapterActivity: 'A Friday-night game jam at a Brooklyn maker space — four hours, a theme, a working prototype by the end, regardless of engine.',

      sources: [
        'https://gameprogrammingpatterns.com/',
        'https://gafferongames.com/post/fix_your_timestep/',
        'https://ocw.mit.edu/courses/cms-611j-creating-video-games-fall-2014/',
      ],
      verifiedAt: '2026-04-23',
    },

    design_game: {
      id: 'design_game',
      name: 'Game Design',
      level: 'Intermediate',
      dek: 'The craft of arranging rules and feedback so that a player wants to play one more time.',
      readTime: '15 min',

      sections: ['The player does not see the rules', 'MDA, and the gap it names', 'Feel and feedback', 'Loops within loops', 'Playtesting as the only truth', 'A short reading list for the unconvinced'],
      body: [
        { type: 'lead', text: 'In 1980, a twenty-two-year-old at Atari named Ed Logg watched a tester hand the controller back after a few minutes of his half-finished game and say, quite politely, that he had to get back to work. Logg went back and cut two-thirds of the features, added a scoring ramp, and shipped Centipede. It became one of the best-selling arcade games of the decade. Game design is the part of making games that no engine will do for you, and the history is full of moments like that one — where a designer threw away most of what they had built because the player, who saw none of it, was not having fun.' },
        { type: 'h2', text: 'Rules are not the point; the experience is' },
        { type: 'p', text: 'In 2004, Robin Hunicke, Marc LeBlanc, and Robert Zubek published a short paper called MDA: A Formal Approach to Game Design, which has become the field\'s default vocabulary. Mechanics are the rules a designer writes. Dynamics are the behaviour that emerges when players run the rules. Aesthetics are the feelings the dynamics produce — fantasy, challenge, fellowship, discovery. A designer composes mechanics, but a player experiences aesthetics; the path from one to the other is never short and often surprising.' },
        { type: 'animation',
          youtubeId: 'AJdEqssNZ-U',
          caption: 'Mark Brown, "Designing a Game around ONE Mechanic" — Portal, Downwell, Baba Is You, case studies in what happens when one idea is squeezed.',
          credit: 'Game Maker\'s Toolkit.',
        },
        { type: 'h2', text: 'Feel is engineering, not magic' },
        { type: 'p', text: 'Steve Swink\'s Game Feel (2008) is the best book in the field on why two shooters can have identical mechanics and feel completely different. The difference lives in the hundred tiny things under the rules: how quickly a jump responds, how long a hit-flash lasts, how much the camera shakes on impact, how the sound cuts. These are choices a programmer and a designer make together, and they are what separates a game that feels sharp from one that feels mushy.' },
        { type: 'p', text: 'Jan Willem Nijman of Vlambeer — the designer behind Nuclear Throne and Super Crate Box — gave a GDC talk in 2013 called "The Art of Screenshake" that became required viewing in the field. He listed roughly thirty specific tweaks that give a game impact: muzzle flash, knockback, sleep frames, particles, camera shake, sound layering. Any one of them adds nothing. All of them together are why Vlambeer\'s games feel like no one else\'s.' },
        { type: 'h2', text: 'Loops within loops' },
        { type: 'p', text: 'A well-designed game is a set of nested feedback loops: the second-to-second loop (moving, shooting, jumping) inside a minute-to-minute loop (clearing a room, winning a match) inside a session loop (advancing a campaign) inside a meta loop (unlocks, progression). Each layer needs its own pacing and reward. Raph Koster, in A Theory of Fun (2004), argues that fun is mostly the brain noticing it has learned a new pattern — and a good game is a sequence of patterns, served at the rate a human can eat them.' },
        { type: 'callout', text: 'The single cheapest improvement to a game in its first playable week: speed up the time from input to feedback. Shorter menus, fewer splash screens, instant respawns. Players will forgive many things but not a lag on the thing they pressed.' },
        { type: 'h2', text: 'Playtesting is the only truth' },
        { type: 'p', text: 'Every designer, asked how they know a mechanic works, will eventually give the same answer: they watched someone play. Jesse Schell\'s The Art of Game Design organizes its hundred "lenses" — diagnostic questions a designer can ask about a game in progress — around this loop. You can argue in a meeting for a week about whether a level is too hard. Sit a stranger at the controller and you will know in three minutes.' },
        { type: 'p', text: 'The practical discipline is to watch silently. Do not explain the controls. Do not hint. Do not defend. Note every place the player hesitates, every place they do the wrong thing, every place they laugh. At the end, ask one question: what did you think was going to happen? The gap between what they expected and what happened is the design work for the next week.' },
        { type: 'aside', label: 'The tutorial problem', text: 'A surprising amount of design time — sometimes half the budget of the first playable — goes into teaching the player how to play. Portal (2007) is the canonical example of teaching-by-level-design: every new mechanic is introduced in a room that is impossible to fail. The result is the rarest thing in games — a tutorial that is also the best level.' },
        { type: 'h2', text: 'A short reading list for the unconvinced' },
        { type: 'p', text: 'If you do not think design is a real discipline, read the Nijman talk, then Schell\'s book, then Swink\'s book, then subscribe to Mark Brown\'s Game Maker\'s Toolkit. By the third case study you will be arguing about camera shake like a professional. By the tenth you will want to make something. Making something, and watching a stranger play it, is the only education that closes the loop.' },
        { type: 'quote', text: 'Fun from games arises out of mastery. It arises out of comprehension. It is the act of solving puzzles that makes games fun.', cite: 'Raph Koster, A Theory of Fun' },
      ],

      keyTerms: ['mechanic', 'dynamic', 'aesthetic', 'feedback loop', 'game feel', 'playtesting', 'balance', 'onboarding', 'core loop', 'game juice'],

      examples: [
        {
          title: 'MDA, applied to chess',
          problem: 'Mechanics, Dynamics, Aesthetics of chess.',
          steps: [
            { text: 'Mechanics (the rules): how each piece moves, how captures work, check and checkmate, en passant, castling, pawn promotion.' },
            { text: 'Dynamics (what emerges): opening theory, middlegame combinations, endgame technique, the back-rank mate, the rook-and-pawn endgame.' },
            { text: 'Aesthetics (what the player feels): intellectual challenge, competition, mastery, beauty of a well-played combination.' },
            { text: 'The mechanics are simple. The dynamics are vast. The aesthetics are what has made chess survive 1500 years.' },
          ],
          answer: 'Simple mechanics; emergent dynamics; durable aesthetics.',
        },
      ],

      practice: [
        { q: 'Who published the MDA framework, and in what year?',
          a: 'Hunicke, LeBlanc, Zubek in 2004', acceptable: ['hunicke', '2004', 'hunicke leblanc zubek', 'hunicke 2004'],
          difficulty: 'medium', hint: 'Three authors, mid-2000s.',
          solution: 'Robin Hunicke, Marc LeBlanc, and Robert Zubek, in 2004.' },
        { q: 'What 2013 GDC talk by Jan Willem Nijman lists 30 tweaks that give a game "juice"?',
          a: 'The Art of Screenshake', acceptable: ['screenshake', 'art of screenshake'],
          difficulty: 'medium', hint: 'Vlambeer, 2013.',
          solution: '"The Art of Screenshake." Required viewing in the field.' },
        { q: 'What is the only reliable way to know if a design works?',
          a: 'playtesting', acceptable: ['watch someone play', 'user testing', 'play test'],
          difficulty: 'easy', hint: 'Sit a stranger at the controller.',
          solution: 'Playtesting. Every designer, asked the question, gives the same answer.' },
      ],

      subtopics: [
        {
          id: 'design_game.mda',
          name: 'MDA — mechanics, dynamics, aesthetics',
          summary: 'The vocabulary the field has used for twenty years.',
          level: 'Intermediate', readTime: '6 min',
          body: [
            { type: 'lead', text: 'The designer composes mechanics; the player experiences aesthetics. Between them sit dynamics — the run-time behaviour that emerges when real players run the rules. A mechanic that looked good on paper can produce ugly dynamics. A set of mechanics with no emergent dynamics produces a boring game.' },
            { type: 'p', text: 'The eight aesthetics from the MDA paper: sensation, fantasy, narrative, challenge, fellowship, discovery, expression, submission. Most games lean on two or three. A designer asking "what aesthetic am I aiming for?" is usually asking the right question.' },
          ],
          practice: [
            { q: 'In MDA, which layer do designers directly write?',
              a: 'mechanics', difficulty: 'easy',
              hint: 'The rules.',
              solution: 'Mechanics — the rules the designer encodes. Dynamics emerge from them; aesthetics are felt by the player.' },
          ],
          keyTerms: ['mechanic', 'dynamic', 'aesthetic', 'emergence', 'fantasy', 'challenge'],
        },
        {
          id: 'design_game.game_feel',
          name: 'Game feel',
          summary: 'The micro-second polish that separates good games from mushy ones.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'Steve Swink\'s Game Feel is the book-length treatment. Input latency, animation ease, hit-stop, camera shake, sound layering — thirty small choices that no single one matters, but all of them together are why Nuclear Throne feels different from a clone with the same mechanics.' },
            { type: 'p', text: 'The GDC talk "Juice it or Lose it" by Jonasson and Purho is twelve minutes and watching a boring game become a good one in real time. Start there.' },
          ],
          practice: [
            { q: 'Name one of the 30 Vlambeer tweaks that add "juice".',
              a: 'screen shake', acceptable: ['knockback', 'muzzle flash', 'sleep frames', 'particles', 'hit stop', 'sound layering', 'camera shake'],
              difficulty: 'easy', hint: 'One of: screen shake, knockback, muzzle flash, hit stop, particles...',
              solution: 'Any of: screen shake, knockback, muzzle flash, hit stop / sleep frames, particles, sound layering, camera punch, chromatic aberration on impact, and many more.' },
          ],
          keyTerms: ['juice', 'hit-stop', 'screen shake', 'muzzle flash', 'input latency', 'easing'],
        },
        {
          id: 'design_game.playtesting',
          name: 'Playtesting discipline',
          summary: 'Watch silently. Ask "what did you think was going to happen?"',
          level: 'Intermediate', readTime: '6 min',
          body: [
            { type: 'lead', text: 'The professional playtesting move: sit a stranger at the controller. Do not explain the controls. Do not hint. Do not defend. Take notes. At the end, ask one question: what did you think was going to happen? The gap between their expectation and the outcome is the design work for the next week.' },
          ],
          practice: [
            { q: 'What single question gives the most information at the end of a playtest session?',
              a: 'what did you think was going to happen', acceptable: ['what did you expect', 'expectations'],
              difficulty: 'medium', hint: 'About their expectations vs. the outcome.',
              solution: '"What did you think was going to happen?" The gap between expectation and outcome is where the design work lives.' },
          ],
          keyTerms: ['playtest', 'observation', 'expectation', 'friction', 'onboarding'],
        },
      ],

      resources: {
        videos: [
          { id: 'ii4kjr-Ybh0', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=ii4kjr-Ybh0',
            title: 'What Makes a Good Combat System?',
            channel: 'Game Maker\'s Toolkit (Mark Brown)', duration: '19:46',
            why: 'A worked example of mechanics-to-feel analysis.' },
          { id: 'AJdEqssNZ-U', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=AJdEqssNZ-U',
            title: 'Designing a Game around ONE Mechanic',
            channel: 'Game Maker\'s Toolkit', duration: '18:58',
            why: 'Portal, Downwell, Baba Is You — case studies in squeezing one idea.' },
          { id: 'AKlMWkWaoqI', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=AKlMWkWaoqI',
            title: 'The Art of Screenshake',
            channel: 'Jan Willem Nijman / Vlambeer (Indigo Classic 2013)', duration: '40:25',
            why: 'The talk that changed how a generation thinks about game feel.' },
          { id: 'NInNVEHj_G4', source: 'youtube', url: 'https://www.youtube.com/watch?v=NInNVEHj_G4',
            title: 'Jonathan Blow — Designing to Reveal the Nature of the Universe',
            channel: 'Jonathan Blow (Rice)', duration: '1:09:00',
            why: 'The maker of Braid and The Witness on what games can be.' },
          { id: 'UJMHaZF6WVU', source: 'youtube', url: 'https://www.youtube.com/watch?v=UJMHaZF6WVU',
            title: 'Building Games with Juice',
            channel: 'GMTK Game Jam / Martin Jonasson & Petri Purho', duration: '14:30',
            why: 'The famous "Juice it or Lose it" live-coding talk. Watch a boring game become a good one in ten minutes.' },
          { id: 'X18asE5UeV0', source: 'youtube', url: 'https://www.youtube.com/watch?v=X18asE5UeV0',
            title: 'Psychology of Game Design',
            channel: 'Extra Credits', duration: '7:30',
            why: 'A short primer on the motivation psychology designers rely on.' },
          { id: '8Yc3UKjoZoI', source: 'youtube', url: 'https://www.youtube.com/watch?v=8Yc3UKjoZoI',
            title: 'Celeste — Inside Maddy Thorson\'s Design Notes',
            channel: 'Noclip', duration: '18:00',
            why: 'A documentary look at a 2018 indie hit known for precise, kind design. Study how small choices compound.' },
        ],
        books: [
          { title: 'The Art of Game Design: A Book of Lenses',
            author: 'Jesse Schell', year: 2020, url: '',
            why: 'The field\'s closest thing to a standard textbook, organized around 100+ "lenses."' },
          { title: 'A Theory of Fun for Game Design',
            author: 'Raph Koster', year: 2013, url: '',
            why: 'Short, illustrated, quietly influential.' },
          { title: 'Game Feel',
            author: 'Steve Swink', year: 2008, url: '',
            why: 'The only book-length treatment of why good games feel good.' },
          { title: 'Rules of Play',
            author: 'Katie Salen and Eric Zimmerman', year: 2003, url: '',
            why: 'The most academic of the canonical books. Formal, careful, hard.' },
          { title: 'Level Up! The Guide to Great Video Game Design',
            author: 'Scott Rogers', year: 2014, url: '',
            why: 'A professional designer\'s practical companion. Lighter than Schell, heavier than Koster.' },
        ],
        articles: [
          { title: 'MDA: A Formal Approach to Game Design and Game Research',
            source: 'Hunicke, LeBlanc, Zubek (2004)',
            url: 'https://users.cs.northwestern.edu/~hunicke/MDA.pdf',
            why: 'The six-page paper that gave the field its modern vocabulary.', year: 2004 },
          { title: 'MDA framework', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/MDA_framework',
            why: 'A clean summary of the paper and its influence.' },
          { title: 'Game Maker\'s Toolkit — Full archive',
            source: 'Mark Brown', url: 'https://gamemakerstoolkit.com/',
            why: 'The blog side of the YouTube channel. Design essays you can cite.' },
        ],
        courses: [
          { title: 'MIT CMS.611J — Creating Video Games',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/cms-611j-creating-video-games-fall-2014/', free: true,
            why: 'MIT\'s studio course. The design half is stronger than the programming half.' },
          { title: 'Game Design and Development Specialization',
            provider: 'Michigan State (Coursera)',
            url: 'https://www.coursera.org/specializations/game-design-and-development', free: true,
            why: 'A five-course specialization auditable for free. Project-based.' },
        ],
        tools: [
          { title: 'itch.io', url: 'https://itch.io',
            why: 'The platform where most indie and experimental games live. Running a playtest is as easy as uploading a build.' },
          { title: 'Game Design Skills — GDC Vault talks (free)',
            url: 'https://www.gdcvault.com/free',
            why: 'A curated free collection of GDC talks by practitioners.' },
          { title: 'Twine', url: 'https://twinery.org',
            why: 'The simplest way to prototype a narrative mechanic. A text-adventure tool that has launched several real careers.' },
        ],
        primarySources: [
          { title: 'Hunicke, LeBlanc, Zubek — MDA paper (2004)',
            url: 'https://users.cs.northwestern.edu/~hunicke/MDA.pdf',
            why: 'The paper.' },
          { title: 'Double Fine — Psychonauts 2 Documentary (Noclip, free)',
            url: 'https://www.youtube.com/watch?v=4vHO4Qq1hbQ',
            why: 'Thirty-four episodes following a studio making a game. The closest thing to a primary source on modern AAA design.' },
        ],
        images: [
          { src: 'content/images/pong_cabinet.jpg',
            caption: 'Where it started: the 1972 Pong cabinet.',
            credit: 'Chris Rand, Wikimedia Commons.' },
        ],
        animations: [
          { youtubeId: 'AKlMWkWaoqI',
            title: 'The Art of Screenshake',
            channel: 'Jan Willem Nijman / Vlambeer',
            why: 'The forty-minute talk that changed how a generation thought about impact.' },
        ],
      },

      interactive: null,
      seeAlso: ['loop', 'design', 'art'],
      prereqs: ['loop'],
      leadsTo: [],

      chapterActivity: 'A monthly board-game and playtest night at a Clinton Hill café — bring a prototype (digital or paper), everyone plays three, honest feedback only.',

      sources: [
        'https://users.cs.northwestern.edu/~hunicke/MDA.pdf',
        'https://en.wikipedia.org/wiki/MDA_framework',
        'https://ocw.mit.edu/courses/cms-611j-creating-video-games-fall-2014/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
