// content/hunting.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: safety_gun, tracking
//
// NOTE: Hunting is a subject where the law and the ethics are not optional.
// Both topics open with the relevant discipline (safe handling; fair chase)
// before any technique.

window.CONTENT = window.CONTENT || {};
window.CONTENT.hunting = {
  subjectId: 'hunting',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    safety_gun: {
      id: 'safety_gun',
      name: 'Firearms Safety',
      level: 'Beginner',
      dek: 'Four rules first, then everything else — and why every serious shooter has them internalized before loading a magazine.',
      readTime: '11 min',

      sections: ['Jeff Cooper and the four rules', 'What a safe gun handler actually does', 'Hunter education is not optional', 'Storage, transport, and the cable lock', 'Fair chase as a safety ethic'],
      body: [
        { type: 'lead', text: 'In 1960, Jeff Cooper — a Marine officer and firearms instructor who later founded the Gunsite Academy in Paulden, Arizona — reduced the craft of safe shooting to four rules short enough to memorize on the drive to the range. They have been taught, nearly unchanged, to every serious American shooter since. Every hunting-related accident, without exception, is a violation of at least one of them.' },
        { type: 'h2', text: 'The four rules' },
        { type: 'p', text: 'One: treat every firearm as if it is loaded. Two: never let the muzzle cover anything you are not willing to destroy. Three: keep your finger off the trigger until your sights are on the target and you have made the decision to fire. Four: be sure of your target and what is beyond it. The rules overlap on purpose — violate one and the others should catch the error before it becomes a hole in someone. Cooper\'s point was architectural: safety is not a checklist you run through once, it is a layered defense that remains in place regardless of what else is happening in the hunt.' },
        { type: 'h2', text: 'What a safe gun handler actually does' },
        { type: 'p', text: 'The habits are small and constant. She checks the chamber each time the firearm changes hands or comes out of a case. She keeps the action open whenever the gun is not actively in use. She climbs a fence or enters a blind with the action open and the magazine removed. She never walks with the safety as her finger discipline — the safety is a mechanical device that can fail, and the trigger finger is the real safety. She knows what is behind the deer because she scouted the ground that morning, not because she assumed. The National Shooting Sports Foundation\'s Ten Rules of Safe Gun Handling are Cooper\'s four, expanded for hunters and range-goers, and they are the standard curriculum in every state hunter-education class.' },
        { type: 'h2', text: 'Hunter education is not optional' },
        { type: 'p', text: 'Every US state and Canadian province now requires a hunter-education certificate for a first-time hunting license, and the card is recognized in every other state through the IHEA-USA reciprocity program. The course — typically ten to twenty hours, classroom plus field — covers safe handling, state-specific law, ethics, field dressing, and first aid. Hunter-ed.com is the official state-delegated online provider for most of the fifty states; many state wildlife agencies also run free in-person classes. The certificate is for life. The habit of actually practicing what the class taught, starting the weekend after you pass, is what makes you safe.' },
        { type: 'callout', text: 'Blaze orange is not fashion and not optional. Every state that permits firearm hunting for deer or elk requires a minimum area — usually 400 square inches on torso and head — of solid blaze orange or blaze pink during the season. Ninety percent of "mistaken-for-game" shootings are of hunters who were not wearing it.' },
        { type: 'h2', text: 'Storage, transport, and the lock' },
        { type: 'p', text: 'At home, firearms are stored unloaded, in a lockbox or safe, with ammunition stored separately. Every new firearm sold in the United States ships with a cable lock. Use it or replace it with a better one. In transport, long guns are cased and, in most states, unloaded and with the action open; handguns are secured per state law (which varies widely on carry rules). Hunting camp culture in the best places is quietly severe about this — the moment an unloaded, cased firearm becomes a ready one has to be deliberate. If you can\'t state out loud what you are about to do with a gun, do not do it.' },
        { type: 'h2', text: 'Fair chase as a safety ethic' },
        { type: 'p', text: 'The Boone and Crockett Club, founded by Theodore Roosevelt in 1887, defined fair chase as "the ethical, sportsmanlike, and lawful pursuit and taking of any free-ranging wild, native North American big-game animal in a manner that does not give the hunter an improper advantage." The ethic is an upstream safety device. A hunter who respects the animal takes the shot she is sure of, at a range she has practiced, in a situation where she knows the bullet\'s path. A hunter in a hurry to fill a tag violates ethics and safety simultaneously; they are the same discipline seen from two sides.' },
      ],

      keyTerms: ['four rules (Cooper)', 'muzzle discipline', 'trigger discipline', 'backstop', 'safety (mechanical)', 'blaze orange', 'hunter education', 'fair chase', 'chamber check', 'cable lock'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://www.nssf.org/safety/firearms-safety-videos/',
            title: 'NSSF — Firearms Safety Video Library',
            channel: 'NSSF', duration: 'variable',
            why: 'The industry trade association\'s own video library. Short, practical, and the one every state hunter-education course draws from.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@TheHuntingPublic',
            title: 'The Hunting Public — full channel',
            channel: 'The Hunting Public', duration: 'variable',
            why: 'Aaron Warbritton and Zach Ferenbaugh\'s long-form public-land deer-hunting series. The safety and ethics are consistent; the footage is the honest kind, successes and misses alike.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@MeatEater',
            title: 'MeatEater — full channel',
            channel: 'Steven Rinella', duration: 'variable',
            why: 'Rinella\'s television series and podcast clips. The ethic is steady, the technique is careful, and the show has done more to bring non-hunters to fair chase than anything else on the internet.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@rmefofficial',
            title: 'Rocky Mountain Elk Foundation — full channel',
            channel: 'Rocky Mountain Elk Foundation', duration: 'variable',
            why: 'The RMEF\'s conservation and technique videos — solid elk hunting, serious wildlife management.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@nrafamily',
            title: 'NRA Family — Safe Gun Handling series',
            channel: 'NRA', duration: 'variable',
            why: 'The technical firearm-handling videos are clean and useful independent of anyone\'s feelings about the organization itself. Start with the muzzle-discipline series.' },
        ],
        books: [
          { title: 'The MeatEater Guide to Hunting and Butchering: Small Game and Fowl',
            author: 'Steven Rinella', year: 2023, url: '',
            why: 'Volume two of Rinella\'s guide series. The best modern general reference from someone who writes as carefully as he hunts.' },
          { title: 'The MeatEater Guide to Hunting and Butchering: Big Game',
            author: 'Steven Rinella', year: 2018, url: '',
            why: 'The first volume. Planning, safety, field dressing, and butchering — from someone whose own mistakes and their causes are on the page.' },
          { title: 'The MeatEater Fish and Game Cookbook',
            author: 'Steven Rinella', year: 2018,
            url: 'https://www.themeateater.com/cook/cookbook',
            why: 'The cookbook. Cooking is the moral justification for hunting; this is the volume to demonstrate it.' },
          { title: 'Meditations on Hunting',
            author: 'José Ortega y Gasset', year: 1942, url: '',
            why: 'The Spanish philosopher\'s book-length essay. Not instructional; it is what the instructional books are quietly trying to be.' },
          { title: 'A Sand County Almanac',
            author: 'Aldo Leopold', year: 1949, url: '',
            why: 'The founding text of North American hunting ethics. Leopold\'s "land ethic" remains the standard every careful hunter measures herself against.' },
        ],
        articles: [
          { title: 'Firearm Safety — 10 Rules of Safe Gun Handling',
            source: 'NSSF',
            url: 'https://www.nssf.org/safety/rules-firearms-safety/',
            why: 'The industry\'s authoritative statement. The first four are Cooper\'s rules; the rest are practical additions.' },
          { title: 'Gun safety', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Gun_safety',
            why: 'A well-referenced treatment of training, storage, malfunctions, and secondary hazards.' },
          { title: 'Hunting', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Hunting',
            why: 'A balanced, encyclopedic overview — history, ethics, regulation, and the range of practice from subsistence to sport.' },
          { title: 'Fair chase', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Fair_chase',
            why: 'The Boone and Crockett Club\'s founding ethic, traced from Theodore Roosevelt\'s 1887 constitution through current practice.' },
        ],
        courses: [
          { title: 'Hunter-ed.com — state-approved online hunter education',
            provider: 'IHEA-USA / Kalkomey',
            url: 'https://www.hunter-ed.com/',
            free: false,
            why: 'The official online hunter-safety course for most US states. Needed before a first-time license; the card is recognized for life and in every state.' },
          { title: 'IHEA-USA — find a state course',
            provider: 'International Hunter Education Association',
            url: 'https://ihea-usa.org/',
            free: true,
            why: 'The parent association\'s directory of state-specific programs, many of which offer free in-person classes as an alternative to the online course.' },
        ],
        tools: [
          { title: 'NSSF — Ten Rules (printable)',
            url: 'https://www.nssf.org/safety/rules-firearms-safety/',
            why: 'The rules on one page, printable, suitable for the inside of a gun-safe door.' },
          { title: 'Project ChildSafe — free gun locks',
            url: 'https://www.projectchildsafe.org/',
            why: 'An NSSF-supported program distributing free cable locks through more than 15,000 local partners. There is no excuse to leave a firearm unlocked.' },
        ],
        primarySources: [
          { title: 'Aldo Leopold, "The Land Ethic" (from A Sand County Almanac, 1949)',
            url: 'https://en.wikipedia.org/wiki/Land_ethic',
            why: 'The founding essay on our ethical relationship to what we hunt and where we hunt it. Wikipedia has the essay\'s argument and bibliography.' },
        ],
      },

      interactive: null,
      seeAlso: ['tracking', 'survival', 'firstaid'],
      prereqs: [],
      leadsTo: ['tracking'],

      chapterActivity: 'A September classroom session at the NY State DEC hunter-education course in the Bronx — the in-person version is free; the online one is the same material but more expensive and less good.',

      sources: [
        'https://www.nssf.org/safety/rules-firearms-safety/',
        'https://en.wikipedia.org/wiki/Gun_safety',
        'https://en.wikipedia.org/wiki/Fair_chase',
        'https://www.hunter-ed.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    tracking: {
      id: 'tracking',
      name: 'Tracking',
      level: 'Intermediate',
      dek: 'Reading sign — the oldest applied science, and the one a hunter borrows from every culture older than her own.',
      readTime: '12 min',

      sections: ['An older craft than writing', 'The field marks of a print', 'Sign, not just print', 'Wind, weather, and the edge of disturbance', 'Tracking as wildlife science', 'A school, a notebook, and the land'],
      body: [
        { type: 'lead', text: 'The San Bushmen of the Kalahari, whose living tradition of tracking is the oldest continuous intellectual practice on earth, do not separate the verbs "to track" and "to read." A San tracker in the 1970s, studied by the South African zoologist Louis Liebenberg, could look at a print in the sand and tell you the species, sex, approximate age, direction of travel, gait, and time since passage, and — in the Kalahari sun — whether the animal had stopped to drink. This is science of the most careful observational kind, older than writing by forty thousand years, and every working hunter who has ever been good at the craft has drawn from the same well.' },
        { type: 'h2', text: 'Reading a print' },
        { type: 'p', text: 'A whitetail\'s print is a splayed heart; a coyote\'s is oval with four toes and claw marks; a bobcat\'s is round with four toes and no claws; a black bear\'s shows the thumb-like fifth toe mammal scientists call the first digit. Size, gait (walk, trot, bound, gallop, the four clean categories), and substrate together tell most of the story. A wet morning after rain is the tracker\'s gift — the mud takes an imprint as honestly as plaster. By afternoon the edges are blurring; by the next day the print is already shifting into what Paul Rezendes, the Massachusetts tracker, called the "aging signature" you learn to read to the hour.' },
        { type: 'h2', text: 'Sign is more than print' },
        { type: 'p', text: 'A good tracker notices what is bent, what is broken, what is eaten. A rub on a sapling in November is a whitetail buck marking his territory. A scratched patch of forest floor is a turkey dusting. Scat — the polite word for droppings — is itself a species identifier, with whole books written on it. A trail of bent grass pointing one way is a deer\'s passage; pointing the other is a coyote\'s. Tom Brown Jr., who trained generations of American trackers out of his New Jersey school, talked of the "concentric rings of disturbance" that spread around any animal in the landscape. Learn to see the rings and you have the animal without ever seeing the animal.' },
        { type: 'h2', text: 'Wind, weather, and edge' },
        { type: 'p', text: 'A tracking hunt moves crosswind or upwind, because scent is the mammalian sense a deer trusts most. She walks slowly — the rule-of-thumb pace is three steps, stop and look, three steps, stop and look — because the eye needs time to resolve stationary silhouette. She works edges: where field meets wood, where ridge meets bottom, where hardwood meets conifer. The densities of sign shift at edges, because the animals themselves shift at edges. By the third season a tracker begins to see the map of a landscape as a system of edges, and realizes that the woods are not uniform at all.' },
        { type: 'callout', text: 'The best way to learn tracking is to follow a living trail with a teacher correcting your guesses. No book substitutes for a Saturday with someone who already knows. The CyberTracker certification, run by Louis Liebenberg\'s organization, is the most widely respected formal credential.' },
        { type: 'h2', text: 'Tracking as wildlife science' },
        { type: 'p', text: 'State wildlife agencies conduct annual tracking surveys — transects walked in winter to count snow prints — that feed directly into population estimates and harvest regulations. Volunteer programs like the Teton Cougar Project and North American Wolverine surveys depend on tracked data that amateur backcountry skiers file. The skill that feeds the hunter also feeds the biologist, which is why every serious state agency maintains a tracker certification program and every serious hunter considers herself a citizen scientist whether she uses the word or not.' },
        { type: 'h2', text: 'A school, a notebook, and the land' },
        { type: 'p', text: 'Mark Elbroch\'s Mammal Tracks and Sign is the encyclopedic modern reference, nine hundred pages of every North American mammal, its prints, and its sign, with photographs you learn to recognize the way a birder learns plumages. A notebook — date, weather, location, print diagram in pencil — is the second irreducible tool. The third is the land itself: walk a patch weekly for a year and it teaches you more than any book. This is how every good tracker any of us knows actually got good. She walked a patch.' },
      ],

      keyTerms: ['spoor', 'gait', 'stride', 'straddle', 'scat', 'rub', 'scrape', 'aging (of a print)', 'substrate', 'CyberTracker'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@TheHuntingPublic',
            title: 'The Hunting Public — tracking and reading deer sign',
            channel: 'The Hunting Public', duration: 'variable',
            why: 'Aaron Warbritton\'s segments on finding and reading rubs, scrapes, and travel corridors in public-land whitetail country. The practical working application.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@MeatEater',
            title: 'MeatEater — Steven Rinella field segments',
            channel: 'MeatEater', duration: 'variable',
            why: 'Rinella\'s show regularly dwells on tracking and backtracking. Clean camerawork, patient explanation.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@elbrochmark',
            title: 'Mark Elbroch — Panthera Puma Program',
            channel: 'Mark Elbroch', duration: 'variable',
            why: 'Elbroch is the CyberTracker-certified wildlife biologist whose book is the reference. His Panthera videos are a window onto professional tracking.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@cybertracker',
            title: 'CyberTracker Conservation — talks and field notes',
            channel: 'CyberTracker', duration: 'variable',
            why: 'The Liebenberg organization\'s own channel. Features of San trackers in the Kalahari and working professionals in North America.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@KeepingItWild',
            title: 'Keeping It Wild — Casey McFarland',
            channel: 'Casey McFarland', duration: 'variable',
            why: 'Casey McFarland is a CyberTracker evaluator; his videos are patient, field-based, and refuse to simplify the craft.' },
        ],
        books: [
          { title: 'Mammal Tracks &amp; Sign: A Guide to North American Species',
            author: 'Mark Elbroch', year: 2019, url: '',
            why: 'The encyclopedic modern reference. Nine hundred pages; every North American mammal; prints, gaits, sign. Second edition; the book every tracker owns.' },
          { title: 'Tracking and the Art of Seeing',
            author: 'Paul Rezendes', year: 1999, url: '',
            why: 'The best popular tracking book. Rezendes was a New England tracker with a photographer\'s eye. Teaches attention more than techniques.' },
          { title: 'The MeatEater Guide to Hunting and Butchering: Big Game',
            author: 'Steven Rinella', year: 2018, url: '',
            why: 'The book that made Rinella the de facto American hunting author. Has a clean working chapter on tracking in context, which is where it belongs.' },
          { title: 'The Art of Tracking: The Origin of Science',
            author: 'Louis Liebenberg', year: 1990, url: '',
            why: 'The South African zoologist who has worked with the San for thirty years, arguing that hypothesis-testing tracking is the oldest scientific practice. A book that changes how you think about the subject.' },
          { title: 'Peterson Field Guide to Animal Tracks',
            author: 'Olaus Murie and Mark Elbroch', year: 2005, url: '',
            why: 'The pocketable classic, updated by Elbroch in 2005. The book to carry, where the Elbroch encyclopedia stays at camp.' },
        ],
        articles: [
          { title: 'Tracking (hunting)', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Tracking_(hunting)',
            why: 'A careful treatment of sign, gait, and stealth technique. Well-referenced for a subject that mostly lives outside the academic literature.' },
          { title: 'Wildlife management', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Wildlife_management',
            why: 'Context for why the skill feeds state population surveys and why state agencies support tracker certifications.' },
          { title: 'Fair chase', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Fair_chase',
            why: 'The ethical frame for using these skills. Tracking gives the hunter an enormous advantage; fair chase is the deliberate limit placed on that advantage.' },
        ],
        courses: [
          { title: 'CyberTracker evaluations (US)',
            provider: 'CyberTracker Conservation',
            url: 'https://cybertrackerusa.org/',
            free: false,
            why: 'The most widely respected tracker certification. Evaluations are held throughout the year in various US locations.' },
          { title: 'Hunter-ed.com — state-approved hunter education',
            provider: 'IHEA-USA / Kalkomey',
            url: 'https://www.hunter-ed.com/',
            free: false,
            why: 'Every first-time licensed hunter goes through this course; the tracking, sign, and ethics chapters are the state-verified baseline.' },
        ],
        tools: [
          { title: 'US Fish &amp; Wildlife Service',
            url: 'https://www.fws.gov/',
            why: 'Species range maps, regulations, and refuges. The first place to check what lives where you plan to look for sign.' },
          { title: 'iNaturalist — tracks and sign',
            url: 'https://www.inaturalist.org/',
            why: 'A community of amateur and professional naturalists will ID a print photo within a day. Excellent for the second-year tracker still building confidence.' },
        ],
        primarySources: [
          { title: 'Louis Liebenberg, "The Origin of Science" (paper)',
            url: 'https://en.wikipedia.org/wiki/CyberTracker',
            why: 'The Wikipedia article on CyberTracker is the best free entry point to Liebenberg\'s body of work with the San and its theoretical argument.' },
        ],
      },

      interactive: null,
      seeAlso: ['safety_gun', 'survival', 'ecology'],
      prereqs: ['safety_gun'],
      leadsTo: [],

      chapterActivity: 'A January snow-tracking walk in the Catskills with a CyberTracker-certified guide — bring a notebook, a tape measure, and patience; the prints are clearest within an hour of sunrise.',

      sources: [
        'https://en.wikipedia.org/wiki/Tracking_(hunting)',
        'https://en.wikipedia.org/wiki/Wildlife_management',
        'https://www.fws.gov/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
