// content/law.js
// Owned by batch: B05-social-world
// Last updated: 2026-04-23 by BATCH B05-social-world
//
// Topics this subject must cover (from data.js):
//   Core: contract_law, criminal, constitutional

window.CONTENT = window.CONTENT || {};
window.CONTENT.law = {
  subjectId: 'law',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B05-social-world',
  topics: {

    // ——— CONTRACT LAW ———
    contract_law: {
      id: 'contract_law',
      name: 'Contracts',
      level: 'Intermediate',
      dek: 'The law that turns a handshake, or an invoice, or a terms-of-service click, into a promise the state will enforce.',
      readTime: '17 min',

      sections: ['The morning contract', 'The four elements', 'Consideration, the odd requirement', 'When a promise is not a contract', 'Remedies for breach', 'The Uniform Commercial Code'],
      body: [
        { type: 'lead', text: 'Every time someone buys coffee, takes a job, clicks "I agree," or rents an apartment, a contract is formed. Most are never read, most are never disputed, and most are, from the law\'s point of view, entirely valid. Contract law is the quiet machinery that allows strangers to cooperate at scale — and most of the time you only notice it when it is broken.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/P1050771_Louvre_code_Hammurabi_face_rwk.JPG?width=900', caption: 'The Code of Hammurabi (c. 1754 BCE), now in the Louvre. Among its 282 laws are the earliest surviving rules for sales, rentals, and deposits — contract law, in the original.', credit: 'Mbzt, CC BY-SA 3.0, via Wikimedia Commons' },
        { type: 'h2', text: 'The four elements' },
        { type: 'p', text: 'A legally binding contract, in the common-law tradition, requires four things: an offer; an acceptance; consideration (something of value exchanged by each side); and, in most places, legal capacity. A bargain to paint my house for a thousand dollars has all four. A gift promise does not, because only one side is giving anything, and contract law will not enforce it.' },
        { type: 'p', text: 'Offer and acceptance seem simple until a lawyer draws them. A billboard advertising a car is not an offer; it is an invitation to treat. The email reply that says "agreed, except let\'s push closing to Friday" is not an acceptance; it is a counter-offer, which destroys the original offer. First-year law students spend weeks on these small distinctions because millions of dollars turn on them in commercial disputes.' },
        { type: 'h2', text: 'Consideration, the odd requirement' },
        { type: 'p', text: 'The consideration doctrine is the most distinctive feature of common-law contract. Continental civil-law systems (France, Germany, Japan) do not require it; a serious promise intentionally made can be binding on that basis alone. The American rule — that a contract needs bargained-for exchange — is still debated, and courts have invented workarounds like promissory estoppel for the obvious cases it gets wrong. If your employer promises you a bonus and you turn down another job on the strength of the promise, the consideration doctrine technically says you have no contract. Promissory estoppel says you might still win.' },
        { type: 'h2', text: 'When it is not a contract' },
        { type: 'p', text: 'Some agreements are not enforceable no matter how carefully they are drafted. A contract for an illegal purpose (to commit a crime), a contract signed under duress, a contract with a minor, a contract whose performance is impossible from the start, a contract that violates public policy (a covenant not to compete drafted too broadly, an exculpatory clause for gross negligence) — each is void or voidable. The list is shorter than a layperson imagines; the system is biased toward enforcement, and for good reasons.' },
        { type: 'h2', text: 'Remedies for breach' },
        { type: 'p', text: 'When a party breaches, the default remedy in common law is damages — a money payment designed to put the non-breaching party where they would have been if the contract had been performed. Courts are reluctant to order specific performance (making the breaching party actually do the thing they promised); they prefer letting money settle it, except for unique goods like land and art. The "efficient breach" doctrine, championed by law-and-economics scholars like Richard Posner, even argues that breach is sometimes good: if the breaching party gains more than the non-breaching party loses, damages put things right and society is better off.' },
        { type: 'h2', text: 'The Uniform Commercial Code' },
        { type: 'p', text: 'American commercial contract law runs on the Uniform Commercial Code, drafted by Karl Llewellyn in the 1940s and 1950s and adopted (with minor variations) by every U.S. state. Article 2 of the UCC governs sales of goods; its default rules fill in the gaps every time a purchase order is silent on a detail. Even people who have never heard of Llewellyn rely on him every time they buy something on the internet.' },
        { type: 'p', text: 'The UCC is a remarkable intellectual achievement. Llewellyn, a legal realist at Columbia, wanted the Code to reflect how merchants actually behaved, not an idealized theory. Whole passages of Article 2 reflect trade-usage realities — "course of dealing," "usage of trade," good-faith obligations — that older common-law doctrine had under-specified. The international counterpart is the CISG (Contracts for the International Sale of Goods), adopted by most major trading nations except the United Kingdom and India.' },
        { type: 'callout', text: 'A contract does not have to be in writing. In most U.S. states, a verbal agreement to paint a house is just as enforceable as a written one — provided the price is below the Statute of Frauds threshold (typically $500 for goods under Article 2) and both sides can prove what was said.' },

        { type: 'h2', text: 'Learn it: the IRAC method' },
        { type: 'p', text: 'Every first-year law student learns the IRAC framework — Issue, Rule, Application, Conclusion. It is how a lawyer breaks down any legal problem. Practice it here. Facts: On Monday, Alice emails Bob: "I\'ll sell you my 2018 Honda for $9,000. Let me know by Friday." On Wednesday, Bob replies: "I\'ll take it for $8,500." On Thursday, Alice sells the car to Carol for $9,500. Is Alice liable to Bob?' },
        { type: 'p', text: 'Issue: Did Alice and Bob form a binding contract? Rule: A contract requires offer, acceptance, and consideration. A counter-offer (different price) is not an acceptance; it is a new offer that terminates the original. Application: Alice\'s Monday email is an offer. Bob\'s Wednesday reply proposes a different price; that is a counter-offer, which destroys Alice\'s original offer. Alice had no outstanding offer to Bob when she sold to Carol. Conclusion: No contract formed between Alice and Bob. Alice is not liable. This is what IRAC does — it forces the lawyer to name the issue, state the governing rule, apply it carefully, and reach a defensible conclusion. Every case brief you will ever read follows this structure.' },

        { type: 'h2', text: 'Worked example: the Peerless ships' },
        { type: 'p', text: 'Raffles v. Wichelhaus (1864) is the canonical law-school case on mutual mistake. Two English merchants contracted for cotton to be shipped from Bombay on a ship named "Peerless." There were two ships called Peerless in Bombay harbor that year. The seller meant the December Peerless; the buyer meant the October Peerless. When the cotton arrived on the December ship, the buyer refused delivery. The court held there was no contract — the parties had never in fact agreed on the same subject matter. Read this case cold and you will never forget that a "meeting of the minds" means the minds actually have to meet. The practical lesson: if a contract term is ambiguous and both parties understood different things, and neither is more reasonable than the other, there is no enforceable bargain.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. A bakery owner tells a neighbor over coffee: "I\'ll give you 500 dollars to paint the fence." The neighbor says nothing but goes home, buys paint, and paints the fence the next day. Is there a contract? Which elements are or are not met?' },
        { type: 'p', text: 'Answer: Offer: yes. Acceptance: contested — silence is ordinarily not acceptance, but *performance* can be acceptance of a unilateral offer. Consideration: yes (painting for money, each party giving up something). Under modern American common law, the bakery owner is likely bound because the neighbor\'s full performance accepts the offer. The restoration doctrine would reinforce this. If the neighbor had just *started* painting, the question gets trickier — Restatement § 45 protects the offeree against revocation once performance begins.' },
        { type: 'p', text: 'Problem 2. A drafting clause says: "Time is of the essence." A different clause says: "Minor delays shall not constitute material breach." A party delivers three days late. Is the delay a breach? How do you read the contract?' },
        { type: 'p', text: 'Answer: The two clauses conflict. Courts use several interpretive canons: specific provisions control general ones; handwritten and typed terms beat printed form language; ambiguity is construed against the drafter (contra proferentem). The honest answer is that a court will look to the parties\' course of dealing, trade usage, and drafting history to decide which clause dominates. This is why contract drafting matters: every such ambiguity costs somebody money in litigation.' },
        { type: 'p', text: 'Problem 3. A homeowner hires a contractor to build a pool for $50,000. Halfway through, the homeowner loses their job and can no longer pay. They tell the contractor to stop. The contractor has already spent $30,000 on materials and labor. What is the contractor entitled to recover?' },
        { type: 'p', text: 'Answer: The contractor has a claim for expectation damages — the position they would have been in had the contract been performed. That is typically the contract price ($50,000) minus the cost to complete, or equivalently, the cost incurred plus the lost profit. If the contractor\'s expected profit was $10,000 on a $50,000 project with $40,000 of costs, and they have incurred $30,000 so far, they should be made whole at $30,000 + their remaining $10,000 profit = $40,000. The homeowner\'s financial hardship is not a legal defense; changes in a party\'s ability to pay are not grounds to rescind. This is harsh, and it is the rule.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What are the four elements of a common-law contract? (2) What is consideration, and why does civil law not require it? (3) What is promissory estoppel? (4) Name three things that make a contract voidable. (5) What is the Uniform Commercial Code, and which article governs sales of goods? (6) Distinguish expectation, reliance, and restitution damages. (7) What is a "meeting of the minds," and what case is the classic illustration?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read the Cornell LII contract entry and watch three LawShelf contract videos. Try reading a real contract you\'ve signed (a lease, a terms of service) and locate the offer, acceptance, consideration, damages clauses, and severability. Once you\'ve got the basics? Read Fried\'s Contract as Promise cover to cover and do a first-year contracts casebook\'s first chapter (Kessler and Fine, or Farnsworth). Work the IRAC method on ten classic cases. To go further? Take contract law in an LLM or JD program, or read the Restatement (Second) of Contracts cover to cover. The next level is commercial: UCC Article 2, CISG, and the international-arbitration literature (Gary Born, Redfern and Hunter).' },
      ],

      keyTerms: ['offer', 'acceptance', 'consideration', 'capacity', 'breach', 'damages', 'specific performance', 'promissory estoppel', 'UCC', 'statute of frauds', 'unconscionability', 'good faith'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@crashcourse/playlists',
            title: 'Crash Course — Business & Government (contract episodes)',
            channel: 'Crash Course',
            duration: 'variable',
            why: 'Crash Course\'s Business and Government playlists both touch on contracts at the introductory level.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LawShelf',
            title: 'LawShelf — Contract Law series',
            channel: 'LawShelf Educational Media',
            duration: 'variable',
            why: 'National Paralegal College\'s free video series on U.S. law. The contract-law playlist is a coherent first-semester 1L review.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/michael_sandel_the_lost_art_of_democratic_debate',
            title: 'The lost art of democratic debate',
            channel: 'TED2010',
            duration: '19:41',
            why: 'Harvard\'s Michael Sandel on markets and moral limits — the philosophy behind modern doctrines like unconscionability.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardLawSchool',
            title: 'Harvard Law School — public lectures',
            channel: 'Harvard Law School',
            duration: 'variable',
            why: 'HLS\'s channel hosts lectures by contract-law scholars — Daphna Kapeliuk, Ian Ayres (visiting), and others — on current commercial law debates.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheFederalistSociety',
            title: 'Federalist Society — legal conventions',
            channel: 'Federalist Society',
            duration: 'variable',
            why: 'Conservative-leaning legal panels with substantive content. Particularly strong on law-and-economics treatments of contract.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@acslaw',
            title: 'American Constitution Society — legal panels',
            channel: 'American Constitution Society',
            duration: 'variable',
            why: 'Progressive counterpart to the Federalist Society. Good panels on consumer contract, arbitration clauses, and the political economy of contract law.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — commercial law',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'British commercial-law perspective on contract, which diverges from American in ways worth noticing.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/larry_lessig_laws_that_choke_creativity',
            title: 'Laws that choke creativity',
            channel: 'TED2007',
            duration: '18:53',
            why: 'Lessig on copyright licensing — a branch of contract law where the stakes are unusually visible. The founding talk for Creative Commons.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@StanfordLawSchool',
            title: 'Stanford Law School — panels & lectures',
            channel: 'Stanford Law School',
            duration: 'variable',
            why: 'Stanford hosts strong public-facing programming on commercial law, with Robert Cooter and others on law-and-economics.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/glenn_greenwald_why_privacy_matters',
            title: 'Why privacy matters',
            channel: 'TEDGlobal 2014',
            duration: '20:40',
            why: 'A useful intersection: the terms-of-service contract is the operative instrument of digital privacy today, and the talk names the stakes.',
          },
        ],
        books: [
          {
            title: 'The Common Law',
            author: 'Oliver Wendell Holmes, Jr.',
            year: 1881,
            url: 'https://www.gutenberg.org/ebooks/2449',
            why: 'The most famous work of American legal theory, and the source of the line "the life of the law has not been logic; it has been experience." Chapters 7 and 8 treat contract.',
          },
          {
            title: 'Contract as Promise',
            author: 'Charles Fried',
            year: 1981,
            url: '',
            why: 'Fried, a Harvard law professor, argues that contract law is grounded in the morality of promising — not economic efficiency. The cleanest modern philosophical account.',
          },
          {
            title: 'The Death of Contract',
            author: 'Grant Gilmore',
            year: 1974,
            url: '',
            why: 'Gilmore\'s counter-argument: that the classical law of contract was quietly absorbed by tort in the twentieth century. Slim, funny, provocative.',
          },
          {
            title: 'An Introduction to the Law of Contract',
            author: 'P. S. Atiyah',
            year: 1961,
            url: '',
            why: 'The British standard introduction across many editions. For comparative perspective on the American doctrine.',
          },
          {
            title: 'The Economics of Contract Law',
            author: 'Robert Cooter and Thomas Ulen (in Law and Economics)',
            year: 2016,
            url: '',
            why: 'The law-and-economics treatment, in its standard textbook form. Read alongside Fried to see the two main modern frames argued side by side.',
          },
          {
            title: 'Commentaries on the Laws of England',
            author: 'William Blackstone',
            year: 1769,
            url: 'https://avalon.law.yale.edu/subject_menus/blackstone.asp',
            why: 'The eighteenth-century background. Book II covers contract and property; the prose is usable even today.',
          },
          {
            title: 'Principles of European Contract Law',
            author: 'Commission on European Contract Law',
            year: 2000,
            url: '',
            why: 'The civil-law counterpoint. Reading any chapter alongside the analogous Restatement (Second) of Contracts is an education.',
          },
        ],
        articles: [
          {
            title: 'Contract',
            source: 'Cornell Legal Information Institute — Wex',
            url: 'https://www.law.cornell.edu/wex/contract',
            why: 'The best free reference-grade summary of American contract doctrine.',
            year: null,
          },
          {
            title: 'Contract',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Contract',
            why: 'Broad comparative overview — common law, civil law, Sharia, Chinese — with a good bibliography.',
            year: null,
          },
          {
            title: 'Contractarianism',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/contractarianism/',
            why: 'On the philosophical idea that political obligation rests on something like a contract — useful for seeing how the legal doctrine relates to the political one.',
            year: 2025,
          },
          {
            title: 'Legal Obligation and Authority',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/legal-obligation/',
            why: 'The philosophical backdrop to what it means for a contract to impose a duty.',
            year: 2022,
          },
          {
            title: 'Uniform Commercial Code',
            source: 'Cornell Legal Information Institute',
            url: 'https://www.law.cornell.edu/ucc',
            why: 'Full text of the UCC, article by article, free.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Cornell LII — Contract Law reference',
            provider: 'Cornell Law School',
            url: 'https://www.law.cornell.edu/wex/contract',
            free: true,
            why: 'Not a course, but the free primary-source bibliography Cornell maintains is the closest free equivalent of a contracts casebook on the open web.',
          },
        ],
        podcasts: [
          {
            title: 'Strict Scrutiny',
            show: 'Crooked Media',
            url: 'https://crooked.com/podcast-series/strict-scrutiny/',
            duration: '≈60:00 per episode',
            why: 'Three constitutional-law professors — Melissa Murray, Leah Litman, Kate Shaw — on current cases. Progressive in framing; unusually good on the craft details.',
          },
          {
            title: 'The Lawfare Podcast',
            show: 'Lawfare',
            url: 'https://www.lawfaremedia.org/topic/podcasts',
            duration: '≈50:00 per episode',
            why: 'Broad national-security law. Contract-law topics appear in connection with defense procurement and sanctions compliance.',
          },
        ],
        primarySources: [
          {
            title: 'Restatement (Second) of Contracts (Cornell LII summary)',
            url: 'https://www.law.cornell.edu/wex/contract',
            why: 'The Restatement, compiled by the American Law Institute, is the single most-cited non-statutory authority in American contract litigation.',
          },
          {
            title: 'Uniform Commercial Code — full text',
            url: 'https://www.law.cornell.edu/ucc',
            why: 'Free, searchable, with cross-links to Cornell\'s commentary.',
          },
        ],
      },

      seeAlso: ['criminal', 'constitutional', 'micro', 'negotiation'],
      prereqs: [],
      leadsTo: ['constitutional'],

      chapterActivity: 'A quarterly "read-the-fine-print" meetup: bring a terms-of-service from an app you use daily; the group finds the clause most likely to surprise you. Twice a year, a guest lawyer from a local non-profit (Legal Aid, Volunteer Lawyers) walks the group through a real small-claims contract dispute.',

      sources: [
        'https://www.law.cornell.edu/wex/contract',
        'https://www.law.cornell.edu/ucc',
        'https://en.wikipedia.org/wiki/Contract',
        'https://plato.stanford.edu/entries/contractarianism/',
        'https://plato.stanford.edu/entries/legal-obligation/',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— CRIMINAL LAW ———
    criminal: {
      id: 'criminal',
      name: 'Criminal Law',
      level: 'Intermediate',
      dek: 'The branch of law that defines what counts as a public wrong, and what the state is permitted to do in response.',
      readTime: '19 min',

      sections: ['Actus reus, mens rea', 'The Model Penal Code', 'Justifications and excuses', 'The five purposes of punishment', 'Due process and the burden of proof', 'Mass incarceration and reform'],
      body: [
        { type: 'lead', text: 'In English, the phrase "guilty act" sounds tautological. In Latin — actus reus — it is a term of art, and its counterpart mens rea, the "guilty mind," makes the whole difference. A surgeon who performs a fatal operation has committed a guilty act (the killing) without a guilty mind (intent). The law has been drawing that line since at least the twelfth century, and a first-year criminal-law class spends a semester on where, exactly, to put it.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Oliver_Wendell_Holmes_Jr_circa_1930.jpg?width=900', caption: 'Oliver Wendell Holmes, Jr. (1841–1935), associate justice of the U.S. Supreme Court for nearly thirty years. His 1881 book The Common Law set out the actus reus / mens rea framework in plain English.', credit: 'Harris & Ewing, public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'The two elements' },
        { type: 'p', text: 'Almost every crime at common law has the same structure: the act (actus reus) plus the mental state (mens rea). The Model Penal Code, drafted by the American Law Institute in 1962 and adopted in some form by most U.S. states, formalized four levels of mens rea — purposely, knowingly, recklessly, and negligently — and a criminal-law exam will still ask you to distinguish them. Purposely: the defendant wanted the result. Knowingly: the defendant knew the result was virtually certain. Recklessly: the defendant disregarded a substantial and unjustifiable risk. Negligently: the defendant should have been aware of such a risk.' },
        { type: 'h2', text: 'Justifications and excuses' },
        { type: 'p', text: 'A defense is a reason the state\'s case should fail even if both elements are proved. Some are justifications (self-defense, defense of others, necessity, defense of property): the act was not wrongful in the circumstances. Others are excuses (insanity, duress, infancy, involuntary intoxication): the act was wrongful, but blaming this particular defendant would not be just. The distinction is subtle; it matters a great deal in practice, because a justification legalizes the act (others may not interfere with it) while an excuse only exempts this defendant from blame.' },
        { type: 'h2', text: 'Why punish at all' },
        { type: 'p', text: 'Philosophers and criminologists have offered five justifications for punishment: retribution (the offender deserves it), deterrence (others will be discouraged), incapacitation (the offender can\'t do it again from prison), rehabilitation (the offender can be changed), and restoration (the victim, community, and offender can be reconciled). Every sentencing scheme is a weighted mix of these; none of them dominates alone. The argument over the weights is the political debate about criminal justice in miniature.' },
        { type: 'p', text: 'Retributive theory, as articulated by Kant, says wrongdoers must be punished because they deserve to be — regardless of consequences. Consequentialist theory, from Bentham onward, says we punish to reduce future crime, full stop. Most working systems are hybrids: they set sentencing ranges by the retributive gravity of the offense, then adjust within the range for consequentialist reasons (first offense, cooperation, treatment availability).' },
        { type: 'h2', text: 'The procedural backstop' },
        { type: 'p', text: 'In most legal systems today, the state must prove criminal guilt beyond a reasonable doubt; the defendant is presumed innocent; the defendant is entitled to counsel; and a person cannot be tried twice for the same offense. These are not accidents. The package was assembled over centuries in response to actual abuses, and any serious conversation about reform has to specify which of these protections one is willing to weaken, and by how much.' },
        { type: 'h2', text: 'The American peculiarity' },
        { type: 'p', text: 'The United States holds about 5% of the world\'s population and about 20% of the world\'s prisoners. The incarceration rate has roughly quadrupled since the 1970s; it peaked around 2008 and has declined modestly since. A vast literature — Michelle Alexander\'s The New Jim Crow (2010), Bruce Western\'s Punishment and Inequality (2006), John Pfaff\'s Locked In (2017), and Elizabeth Hinton\'s From the War on Poverty to the War on Crime (2016) — argues about why. The immediate causes (longer sentences, more prosecutions, aggressive drug laws, plea bargaining) are easier to agree on than the deeper ones (racial politics, deindustrialization, federalism).' },
        { type: 'p', text: 'The reform argument is now broadly bipartisan but stalls on specifics. Bail reform, cash bail abolition, sentencing reductions for nonviolent drug offenses, Ban the Box, and prosecutorial reform have all made partial progress at the state and local level. What has not been tried at scale, anywhere, is a serious reduction in sentences for violent offenses — which is where most of the incarcerated population actually is.' },
        { type: 'quote', text: 'It is better that ten guilty persons escape than that one innocent suffer.', cite: 'William Blackstone, Commentaries on the Laws of England (1765)' },
        { type: 'callout', text: 'The presumption of innocence is not a direct command of the U.S. Constitution. It was read into the Due Process Clause by the Supreme Court in Coffin v. United States (1895), drawing on Roman and English law going back two millennia. The Court called it "axiomatic and elementary." Its practical force depends entirely on how seriously a given courtroom takes it.' },

        { type: 'h2', text: 'Learn it: reading a criminal statute' },
        { type: 'p', text: 'Pick up any state criminal code and read the homicide section. You will find the same nested structure everywhere. First-degree murder usually requires killing + specific intent + premeditation. Second-degree murder drops premeditation. Voluntary manslaughter drops specific intent (heat of passion). Involuntary manslaughter drops even intent (recklessness or gross negligence). Each rung down the ladder removes one mental-state element; each rung changes the sentence range, often by decades. A defense lawyer\'s job is often not to contest the killing but to argue about which rung of the ladder the facts actually reach. This is why mens rea is called the "guilty mind" in the singular — there are four flavors in the Model Penal Code (purposely, knowingly, recklessly, negligently), and every element of every crime carries its own required flavor. Reading a criminal statute is an act of decomposition.' },

        { type: 'h2', text: 'Worked example: the self-defense analysis' },
        { type: 'p', text: 'Facts: A man is followed home at night by someone he does not recognize. The follower pulls out what turns out to be a wallet. The man, fearing a weapon, shoots and kills the follower. Is this self-defense? Walk through the elements. (1) Imminence — was the threat immediate, not speculative? Yes, the follower is present. (2) Reasonableness — would an ordinary person in that situation have believed they were in danger of great bodily harm? Probably — unknown stranger following at night, reaching into a jacket. (3) Proportionality — was deadly force necessary to meet the threat? Harder — the man had no prior knowledge it was a weapon. (4) Retreat — many but not all jurisdictions require retreat if safely possible before using deadly force. "Stand your ground" states remove this requirement. The same facts can produce acquittal in Florida (no duty to retreat) and conviction in Massachusetts (duty to retreat). Self-defense is not one doctrine; it is a state-by-state patchwork.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. A hunter, aiming at what he believes is a deer in dim light, shoots and kills another hunter. Is this murder, voluntary manslaughter, involuntary manslaughter, or no crime? Which mens rea applies?' },
        { type: 'p', text: 'Answer: Almost certainly involuntary manslaughter — killing by gross negligence or recklessness. The hunter did not intend to kill a person (no purpose), did not know with certainty it was a person (no knowledge), but a reasonable hunter should have identified the target before firing. Some jurisdictions would prosecute as "criminally negligent homicide" instead. In a few states with no negligent-homicide statute, the conduct might result in no criminal charge at all and only civil liability. The same conduct, the same death, three different legal classifications across American jurisdictions.' },
        { type: 'p', text: 'Problem 2. A defendant confesses to a crime after being interrogated for eight hours without being told of her right to remain silent. At trial, the prosecution wants to introduce the confession. What is the governing Supreme Court case? What must the prosecution show to admit the confession? What is the constitutional basis?' },
        { type: 'p', text: 'Answer: Miranda v. Arizona (1966). Before custodial interrogation, police must warn the suspect of the right to remain silent, that anything said can be used against them, the right to counsel, and the right to appointed counsel if indigent. Without the warnings, statements are inadmissible in the prosecution\'s case-in-chief. Constitutional basis: Fifth Amendment privilege against self-incrimination, as incorporated against the states by the Fourteenth. Exceptions exist (public-safety exception, routine booking, spontaneous statements).' },
        { type: 'p', text: 'Problem 3. A defendant is clearly mentally ill but is capable of distinguishing right from wrong. Under the M\'Naghten rule, is the defendant eligible for an insanity defense? Under the Model Penal Code test? What policy trade-off do the two tests reflect?' },
        { type: 'p', text: 'Answer: Under M\'Naghten (1843), the defendant must not know what he was doing or not know it was wrong — a narrow cognitive test. So a defendant who knows right from wrong fails the test. Under the MPC (1962), the defendant is insane if, due to mental disease, he lacks substantial capacity either to appreciate the criminality of his conduct *or* to conform his conduct to the law — a broader test that includes "volitional" incapacity. The MPC approach acknowledges that severely mentally ill defendants may know right from wrong but be unable to resist acting. After the 1982 Hinckley verdict, several states narrowed the test back toward M\'Naghten. The policy trade-off: broader insanity tests acquit defendants who are not morally blameworthy; narrower tests avoid "abuse" of the defense and protect public confidence.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What are the two elements of most crimes? (2) Name the four Model Penal Code mens rea levels in order of severity. (3) Distinguish a justification from an excuse. (4) State the four classic purposes of punishment. (5) Under what circumstances are Miranda warnings required? (6) What is the reasonable-doubt standard, and how does it differ from "preponderance" and "clear and convincing"? (7) Name two recent reforms of American criminal-justice practice and one effect each has had.' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read Blackstone\'s Commentaries Book IV Introduction. Watch five LawShelf criminal-law videos. Read one Supreme Court opinion (Gideon is short and accessible). When you can walk through an arrest-to-appeal flowchart from memory, you have the skeleton. Once you\'ve got the basics? Read Stevenson\'s Just Mercy and Alexander\'s The New Jim Crow, and work the first chapter of a 1L criminal-law casebook (Kadish, Schulhofer, and Steiker). To go further? Take criminal law and criminal procedure in a JD or LLM program. Read Packer\'s "Two Models of the Criminal Process" (1964) and Herbert Packer\'s Limits of the Criminal Sanction. Then dive into contemporary policy literature: Pfaff\'s Locked In, Gottschalk\'s Caught, and the Marshall Project\'s ongoing reporting.' },
      ],

      keyTerms: ['actus reus', 'mens rea', 'felony', 'misdemeanor', 'due process', 'presumption of innocence', 'reasonable doubt', 'self-defense', 'insanity defense', 'Model Penal Code', 'Miranda warning', 'plea bargain'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LawShelf',
            title: 'LawShelf — Criminal Law playlist',
            channel: 'LawShelf Educational Media',
            duration: 'variable',
            why: 'Full introductory series on U.S. criminal law — mens rea, the major offenses, defenses, procedure.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/cases/1962/155',
            title: 'Oyez: Gideon v. Wainwright (1963)',
            channel: 'Oyez',
            duration: '43:12 (oral argument audio)',
            why: 'The case that guaranteed counsel to indigent defendants in state criminal trials. Listen to the oral argument with the case summary open.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/cases/1965/759',
            title: 'Oyez: Miranda v. Arizona (1966)',
            channel: 'Oyez',
            duration: 'oral argument audio + case summary',
            why: 'The case behind "you have the right to remain silent." Listening to the argument is an education in how rights are actually litigated.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardLawSchool',
            title: 'Harvard Law School — public lectures',
            channel: 'Harvard Law School',
            duration: 'variable',
            why: 'Lectures by Carol Steiker, Alan Dershowitz, Randall Kennedy on criminal justice, the death penalty, and mass incarceration.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice',
            title: 'We need to talk about an injustice',
            channel: 'TED2012',
            duration: '23:41',
            why: 'Bryan Stevenson, founder of the Equal Justice Initiative, on the American criminal-justice system. The most-viewed legal talk on TED.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/adam_foss_a_prosecutor_s_vision_for_a_better_justice_system',
            title: 'A prosecutor\'s vision for a better justice system',
            channel: 'TED2016',
            duration: '17:55',
            why: 'Adam Foss on prosecutorial discretion — the point at which labels and charges get applied or withheld.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@StanfordLawSchool',
            title: 'Stanford Law School — criminal justice programming',
            channel: 'Stanford Law School',
            duration: 'variable',
            why: 'Stanford\'s public-facing criminal-justice programs, including the Stanford Criminal Justice Center.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheMarshallProject',
            title: 'The Marshall Project — criminal-justice journalism',
            channel: 'The Marshall Project',
            duration: 'variable',
            why: 'Nonprofit journalism on American criminal justice. Not social theory, but the field reporting any serious sociology of deviance needs.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/eve_abrams_the_human_stories_behind_mass_incarceration',
            title: 'The human stories behind mass incarceration',
            channel: 'TED2018',
            duration: '11:24',
            why: 'Abrams\'s radio-documentary approach to a question that starts with labeling theory and ends in a Louisiana prison.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE lectures — comparative criminology',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'David Garland and others on how different countries punish. A useful antidote to the American-centric framing.',
          },
        ],
        books: [
          {
            title: 'Commentaries on the Laws of England',
            author: 'William Blackstone',
            year: 1769,
            url: 'https://avalon.law.yale.edu/subject_menus/blackstone.asp',
            why: 'The most influential English legal treatise of the eighteenth century. Book IV covers criminal law.',
          },
          {
            title: 'The Common Law',
            author: 'Oliver Wendell Holmes, Jr.',
            year: 1881,
            url: 'https://www.gutenberg.org/ebooks/2449',
            why: 'Holmes on criminal law occupies chapters 2 and 3. A better starting point than any modern textbook for understanding where the doctrines came from.',
          },
          {
            title: 'Discipline and Punish',
            author: 'Michel Foucault',
            year: 1975,
            url: '',
            why: 'The most influential book on punishment and social control of the last fifty years. Hard, slow, indispensable.',
          },
          {
            title: 'The New Jim Crow',
            author: 'Michelle Alexander',
            year: 2010,
            url: '',
            why: 'The most influential modern critique of American criminal justice — argues that mass incarceration is a racial caste system.',
          },
          {
            title: 'Locked In',
            author: 'John Pfaff',
            year: 2017,
            url: '',
            why: 'A criminologist\'s data-first counter-read of the mass-incarceration consensus: prosecutors, not drug laws, did most of the work.',
          },
          {
            title: 'Just Mercy',
            author: 'Bryan Stevenson',
            year: 2014,
            url: '',
            why: 'Stevenson\'s memoir of defending death-row inmates in Alabama. Narrative journalism as legal argument.',
          },
          {
            title: 'Punishment and Inequality in America',
            author: 'Bruce Western',
            year: 2006,
            url: '',
            why: 'The Princeton sociologist\'s quantitative account of the incarceration boom\'s distributional consequences. The empirical backbone of the reform argument.',
          },
          {
            title: 'The Trial',
            author: 'Franz Kafka',
            year: 1925,
            url: 'https://www.gutenberg.org/ebooks/7849',
            why: 'Not jurisprudence, but no serious student of criminal procedure should skip it. Kafka saw the bureaucratic shape of the modern state clearly.',
          },
        ],
        articles: [
          {
            title: 'Legal Punishment',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/legal-punishment/',
            why: 'Antony Duff\'s long, careful survey of the theories of punishment. Revised 2026.',
            year: 2026,
          },
          {
            title: 'Criminal Law',
            source: 'Cornell Legal Information Institute — Wex',
            url: 'https://www.law.cornell.edu/wex/criminal_law',
            why: 'Free, reference-grade summary of American criminal doctrine.',
            year: null,
          },
          {
            title: 'Criminal law',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Criminal_law',
            why: 'Broad comparative overview covering the common-law and civil-law traditions and the five classic purposes of punishment.',
            year: null,
          },
          {
            title: 'Natural Law Theories',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/natural-law-theories/',
            why: 'John Finnis and others on the philosophical frame behind "some things are crimes because they are wrong."',
            year: 2025,
          },
          {
            title: 'Model Penal Code',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Model_Penal_Code',
            why: 'The best short summary of the 1962 ALI code that reorganized American criminal law.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Yale Open — Moral Foundations of Politics (PLSC 118)',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science/plsc-118',
            free: true,
            why: 'Shapiro\'s Yale course devotes a full week to retributive justice and the state\'s moral license to punish.',
          },
          {
            title: 'Cornell LII — Criminal Law reference',
            provider: 'Cornell Law School',
            url: 'https://www.law.cornell.edu/wex/criminal_law',
            free: true,
            why: 'The free primary-source reference for American criminal doctrine.',
          },
        ],
        podcasts: [
          {
            title: 'Serial Season One',
            show: 'Serial Productions / The New York Times',
            url: 'https://serialpodcast.org/season-one',
            duration: '12 episodes',
            why: 'Sarah Koenig\'s 2014 investigation of the Adnan Syed case. Still the best single introduction to how an American criminal case actually moves.',
          },
          {
            title: 'Ear Hustle',
            show: 'Ear Hustle (PRX)',
            url: 'https://www.earhustlesq.com/',
            duration: '≈30:00 per episode',
            why: 'Award-winning podcast produced with incarcerated people at San Quentin. Field sociology with sound.',
          },
          {
            title: 'Criminal',
            show: 'Vox Media',
            url: 'https://thisiscriminal.com/',
            duration: '≈30:00 per episode',
            why: 'Phoebe Judge\'s weekly long-form stories about crime and its edges.',
          },
        ],
        primarySources: [
          {
            title: 'Gideon v. Wainwright, 372 U.S. 335 (1963)',
            url: 'https://www.oyez.org/cases/1962/155',
            why: 'The right-to-counsel case. Opinion text, oral-argument audio, and case summary.',
          },
          {
            title: 'Miranda v. Arizona, 384 U.S. 436 (1966)',
            url: 'https://www.oyez.org/cases/1965/759',
            why: 'The case that produced the warning.',
          },
          {
            title: 'Model Penal Code (1962) — summary',
            url: 'https://en.wikipedia.org/wiki/Model_Penal_Code',
            why: 'The ALI\'s full Code is copyrighted; Wikipedia\'s summary of the mens rea hierarchy is the best free substitute.',
          },
        ],
      },

      seeAlso: ['contract_law', 'constitutional', 'deviance', 'governments'],
      prereqs: [],
      leadsTo: ['constitutional'],

      chapterActivity: 'A monthly "sit in court" night at 100 Centre Street — attend an arraignment session, compare notes afterwards on how the ideal model of due process survives contact with the actual calendar. Once a quarter, a trip to Sing Sing Museum upriver or to the Tenement Museum\'s court-records tour; closing reading aloud from Blackstone on the train back.',

      sources: [
        'https://plato.stanford.edu/entries/legal-punishment/',
        'https://www.law.cornell.edu/wex/criminal_law',
        'https://en.wikipedia.org/wiki/Criminal_law',
        'https://plato.stanford.edu/entries/natural-law-theories/',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— CONSTITUTIONAL LAW ———
    constitutional: {
      id: 'constitutional',
      name: 'Constitutional Law',
      level: 'Advanced',
      dek: 'The law about the law — the rules that govern how the government itself may act, and the rights that the government may not take away.',
      readTime: '20 min',

      sections: ['Marbury and the power to strike down', 'Rights against the state', 'Interpretive methods', 'The great cases', 'Comparative perspective', 'The current moment'],
      body: [
        { type: 'lead', text: 'On February 24, 1803, Chief Justice John Marshall handed down an opinion that was, on its face, a procedural defeat for the plaintiff. William Marbury did not get his commission. But the reason he did not get it — that the statute under which he sued was unconstitutional — gave the Supreme Court the power it has exercised ever since: to strike down an act of Congress. Nothing in the Constitution says the Court may do this. Marshall simply said it could, and every subsequent justice has agreed.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/US_Supreme_Court_Building.jpg?width=1200', caption: 'The U.S. Supreme Court building in Washington, completed in 1935. Before that, the Court sat for 146 years in rooms borrowed from Congress. "Equal Justice Under Law" is carved above the west entrance.', credit: 'dbking, CC BY 2.0, via Wikimedia Commons' },
        { type: 'h2', text: 'The doctrine of judicial review' },
        { type: 'p', text: 'Marbury v. Madison is the most consequential case in American constitutional law, and the one that is most arguably made up from whole cloth. Marshall\'s reasoning — that the Constitution is law, that courts interpret law, and therefore that courts must decide what the Constitution means when it conflicts with a statute — is plausible but not inevitable. Most other constitutional democracies have since adopted some version of judicial review, but some (the United Kingdom, New Zealand, the Nordic countries) have deliberately stopped short of giving courts the power to strike down legislation.' },
        { type: 'h2', text: 'Individual rights' },
        { type: 'p', text: 'Much of modern constitutional law is about the rights of individuals against the state: freedom of speech, freedom of religion, due process, equal protection, the protection against unreasonable searches. In the U.S., most of these were written in the first ten amendments in 1791; the Fourteenth Amendment in 1868 extended most of them to restrain state governments, not just the federal one. The application to each new technology and circumstance — wiretapping, abortion, same-sex marriage, thermal imaging of houses, GPS tracking, cell-tower data — is the running project of the field.' },
        { type: 'p', text: 'Incorporation — the doctrine that the Bill of Rights applies against state governments through the Fourteenth Amendment — was a slow twentieth-century project. Not every clause has been incorporated; the Seventh Amendment\'s civil-jury right, the Grand Jury Clause, and the Third Amendment\'s anti-quartering clause have not. The doctrinal history of "selective incorporation" is essentially the history of the Supreme Court between 1897 and 2010.' },
        { type: 'h2', text: 'How judges decide' },
        { type: 'p', text: 'Constitutional interpretation is fought along several lines at once. Originalists (Scalia, Thomas, Barrett) argue that the meaning of a clause is fixed at the time of ratification. Living-constitutionalists (Brennan, Ginsburg, Breyer) argue that the document\'s broad language adapts to changing circumstance. Textualists focus on the words; purposivists on the intent; structuralists on the whole architecture. Any serious constitutional-law course spends at least as much time on method as on outcomes, because the method is usually doing the real work.' },
        { type: 'h2', text: 'The great cases' },
        { type: 'p', text: 'Certain cases are load-bearing for the American constitutional architecture. McCulloch v. Maryland (1819) established broad implied federal powers. Brown v. Board (1954) desegregated public schools. Gideon v. Wainwright (1963) guaranteed counsel to indigent defendants. New York Times v. Sullivan (1964) protected the press. Roe v. Wade (1973), and its 2022 reversal in Dobbs v. Jackson Women\'s Health, shaped the abortion right and its withdrawal. Obergefell v. Hodges (2015) recognized same-sex marriage. Reading any one of these with the majority, concurrence, and dissent together is more useful than reading any single textbook chapter.' },
        { type: 'h2', text: 'Looking outward' },
        { type: 'p', text: 'The German Federal Constitutional Court, the Indian Supreme Court, the South African Constitutional Court, and the European Court of Human Rights all do comparable work on different documents. A comparative glance is humbling: some systems handle rights-protection, federalism, and judicial legitimacy better than the U.S. in some respects, worse in others. The German court\'s proportionality analysis, for example, is a more structured way of weighing rights against state interests than the American "tiers of scrutiny" — and much of the world has adopted it.' },
        { type: 'h2', text: 'The current moment' },
        { type: 'p', text: 'American constitutional law is in a period of unusual visible contestation. The Supreme Court\'s current majority has overturned Roe, Chevron (administrative deference), and Loper Bright (administrative deference again); has substantially expanded the scope of Second Amendment protection; and has narrowed the Voting Rights Act. Whether this represents a durable constitutional realignment or an eventually reversed moment is one of the open questions of the decade. A reader trying to understand the field in 2026 needs to be comfortable reading fresh 5-4 and 6-3 opinions, not just canonical cases.' },
        { type: 'callout', text: 'The Supreme Court hears about 70 cases per year out of roughly 7,000 petitions. The Justices vote on cert in private conference; four votes are required to grant review (the "rule of four"). Most constitutional law in practice is made by the lower federal courts, whose opinions are final unless the Supreme Court intervenes.' },

        { type: 'h2', text: 'Learn it: the tiers of scrutiny' },
        { type: 'p', text: 'American constitutional law runs on three "tiers" of judicial scrutiny. Learn them and you have a large fraction of Equal Protection and Due Process doctrine in your head. Rational basis (the lowest tier): the law is valid if it is rationally related to a legitimate government interest. Almost any law survives this; the government usually wins. Intermediate scrutiny: the law must be substantially related to an important government interest. Used for sex-based classifications and some First Amendment cases. Strict scrutiny (the highest): the law must be narrowly tailored to a compelling government interest. Used for race-based classifications, fundamental rights, and content-based speech restrictions. Strict scrutiny is, in practice, usually fatal to the law in question, which is why the Court\'s *choice of tier* often determines the outcome before any facts are weighed.' },

        { type: 'h2', text: 'Worked example: reading Brown v. Board' },
        { type: 'p', text: 'Brown v. Board of Education (1954) is the most important American judicial decision of the twentieth century, and it is short — about nine pages. Read it with three questions. (1) What precedent was overruled? (Plessy v. Ferguson, 1896, which had held "separate but equal" constitutional.) (2) On what ground? (Not on original intent — the Fourteenth Amendment\'s drafters ratified segregated schools. Instead, Chief Justice Warren relies on the *social reality* of education\'s role and the demonstrated psychological harm of segregation.) (3) What does this tell you about originalism vs. living constitutionalism? (Brown is hard to justify on purely originalist grounds. Justice Scalia, a committed originalist, eventually argued Brown was correct on a "faithless" reading of the Fourteenth — showing that originalism and result can diverge.) Brown is the case that makes the interpretive debate real.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. A city passes an ordinance requiring all licensed taxi drivers to be at least 21 years old. A 19-year-old with a commercial driver\'s license sues, arguing the rule violates Equal Protection. Which tier of scrutiny applies, and who is likely to win?' },
        { type: 'p', text: 'Answer: Age is not a suspect classification under current doctrine; rational-basis review applies. The city need only show the age rule is rationally related to a legitimate interest (public safety, insurance risk). It will almost certainly win. A very different result would follow if the ordinance targeted race, national origin, or alienage.' },
        { type: 'p', text: 'Problem 2. A state enacts a law forbidding abortion after six weeks. Before Dobbs v. Jackson Women\'s Health (2022), which Supreme Court case controlled? What standard did it impose? After Dobbs, what standard applies?' },
        { type: 'p', text: 'Answer: Before Dobbs, Planned Parenthood v. Casey (1992) controlled, applying an "undue burden" standard — laws placing a substantial obstacle in the path of a pre-viability abortion were unconstitutional. Dobbs overturned Roe and Casey; abortion regulation now receives rational-basis review. States may largely restrict or permit abortion as they choose, subject only to the very weak constraint that the regulation be rationally related to a legitimate state interest. Within 18 months of Dobbs, 14 states had enacted near-total bans; others expanded protections. This is the clearest recent example of how a shift in doctrine transfers questions from courts to politics — as living-constitutionalists feared and originalists intended.' },
        { type: 'p', text: 'Problem 3. A public university\'s admissions policy gives explicit numerical weight to race in order to increase diversity. What is the governing case? What tier applies? What arguments do both sides make?' },
        { type: 'p', text: 'Answer: SFFA v. Harvard (2023) is the governing case. Race-based classifications trigger strict scrutiny. The university must show a compelling interest (diversity was accepted in Grutter) and narrow tailoring. In SFFA, the Court held that Harvard\'s and UNC\'s race-conscious admissions failed narrow tailoring and effectively ended race-conscious admissions in American higher education. The university argues diversity benefits pedagogy and democracy; opponents argue race-based classifications are unconstitutional on their face. Both frames have textual, historical, and prudential support. The answer in any given term depends on who is on the Court.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What did Marbury v. Madison establish and on what reasoning? (2) Name the three tiers of scrutiny and when each applies. (3) What is incorporation, and what Amendment does it work through? (4) Distinguish originalism, textualism, and living constitutionalism. (5) Name three landmark cases that shaped twentieth-century individual-rights doctrine. (6) What is the "political question" doctrine, and why does it exist? (7) How does the German Basic Law\'s proportionality framework differ from American tiers of scrutiny?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read the U.S. Constitution front to back. Read Marbury v. Madison and Brown v. Board. Watch one National Constitution Center "We the People" debate. Once you\'ve got the basics? Read Amar\'s America\'s Constitution: A Biography and Scalia-Gutmann\'s A Matter of Interpretation back to back. Watch five Supreme Court oral arguments on Oyez. To go further? Take constitutional law in JD or LLM. Read Tribe\'s American Constitutional Law (3 volumes — not cover to cover) as a reference. Read Dworkin\'s Freedom\'s Law and Whittington\'s Constitutional Interpretation. For comparative depth, read David Landau and Rosalind Dixon on abusive constitutionalism — the current scholarly frontier.' },
      ],

      keyTerms: ['judicial review', 'due process', 'equal protection', 'incorporation', 'originalism', 'living constitution', 'separation of powers', 'strict scrutiny', 'federalism', 'Marbury v. Madison', 'Commerce Clause', 'proportionality'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/cases/1803/5',
            title: 'Oyez: Marbury v. Madison (1803)',
            channel: 'Oyez',
            duration: 'case summary + text',
            why: 'The opinion that invented judicial review. Oyez has the full text and summary.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/cases/1953/1',
            title: 'Oyez: Brown v. Board of Education (1954)',
            channel: 'Oyez',
            duration: 'case summary + oral argument audio',
            why: 'Thurgood Marshall\'s oral argument and the unanimous Warren opinion. The audio is a landmark document in American history.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/cases/2014/14-556',
            title: 'Oyez: Obergefell v. Hodges (2015)',
            channel: 'Oyez',
            duration: 'case summary + oral argument audio',
            why: 'The same-sex marriage case. Listen to both the majority and the dissents for the cleanest recent example of an originalist–living-constitutionalist argument.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardLawSchool',
            title: 'Harvard Law School — constitutional lectures',
            channel: 'Harvard Law School',
            duration: 'variable',
            why: 'Laurence Tribe, Cass Sunstein, Noah Feldman, and Jack Goldsmith on constitutional interpretation.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@StanfordLawSchool',
            title: 'Stanford Law School — Constitutional Law programming',
            channel: 'Stanford Law School',
            duration: 'variable',
            why: 'Pam Karlan, Michael McConnell, and visitors on constitutional interpretation and current doctrine.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@NationalConstitutionCenter',
            title: 'National Constitution Center (Philadelphia)',
            channel: 'National Constitution Center',
            duration: 'variable',
            why: 'The best public programming on the U.S. Constitution in the country. Jeffrey Rosen\'s "We the People" podcast is posted here in video form.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheFederalistSociety',
            title: 'Federalist Society — constitutional panels',
            channel: 'Federalist Society',
            duration: 'variable',
            why: 'The originalist/textualist side of the debate, as conducted by scholars and judges who have shaped the current Court.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@acslaw',
            title: 'American Constitution Society',
            channel: 'American Constitution Society',
            duration: 'variable',
            why: 'Progressive counterpart to the Federalist Society — Pam Karlan, Jeff Sutton, Kate Shaw. Strong on current doctrine.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/jeffrey_rosen_the_constitution_belongs_to_you',
            title: 'Jeffrey Rosen on constitutional interpretation (search TED.com)',
            channel: 'TED',
            duration: 'variable',
            why: 'Rosen runs the National Constitution Center; his short talks are the cleanest popular-level introduction.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@C-SPAN',
            title: 'C-SPAN — Supreme Court programming',
            channel: 'C-SPAN',
            duration: 'variable',
            why: 'Unedited footage of confirmation hearings, Supreme Court press conferences, and Book TV interviews with constitutional scholars.',
          },
        ],
        books: [
          {
            title: 'The Federalist Papers',
            author: 'Alexander Hamilton, James Madison, and John Jay',
            year: 1788,
            url: 'https://www.gutenberg.org/ebooks/1404',
            why: 'The founding generation explaining the design. Federalist 10, 51, and 78 are the essential reading for constitutional law.',
          },
          {
            title: 'A Matter of Interpretation',
            author: 'Antonin Scalia',
            year: 1997,
            url: '',
            why: 'Scalia\'s defense of originalism, followed by critical responses from Amy Gutmann, Gordon Wood, Laurence Tribe, and Ronald Dworkin.',
          },
          {
            title: 'Active Liberty',
            author: 'Stephen Breyer',
            year: 2005,
            url: '',
            why: 'Justice Breyer\'s counter-argument: constitutional interpretation should look to consequences for democratic participation.',
          },
          {
            title: 'America\'s Constitution: A Biography',
            author: 'Akhil Reed Amar',
            year: 2005,
            url: '',
            why: 'Amar\'s clause-by-clause reading. The one-volume reference for serious readers.',
          },
          {
            title: 'Taking Rights Seriously',
            author: 'Ronald Dworkin',
            year: 1977,
            url: '',
            why: 'The most important liberal constitutional theorist of the late twentieth century. Dworkin\'s "law as integrity" frame is the main rival to originalism among academics.',
          },
          {
            title: 'The Bill of Rights: The Politics of the Living Constitution',
            author: 'Akhil Reed Amar',
            year: 1998,
            url: '',
            why: 'Amar on the Bill of Rights as a coherent document, not a list of unrelated protections. Essential for understanding incorporation.',
          },
          {
            title: 'The Nine',
            author: 'Jeffrey Toobin',
            year: 2007,
            url: '',
            why: 'The most readable history of the modern Supreme Court, ending in the mid-2000s. Pairs well with Linda Greenhouse\'s work for the 2010s.',
          },
          {
            title: 'How Democracies Die',
            author: 'Steven Levitsky and Daniel Ziblatt',
            year: 2018,
            url: '',
            why: 'Not about constitutional law per se, but about the political culture that lets constitutional protections hold.',
          },
        ],
        articles: [
          {
            title: 'Constitutionalism',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/constitutionalism/',
            why: 'Wil Waluchow on the idea that power may be subject to higher law.',
            year: 2023,
          },
          {
            title: 'Legal Rights',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/legal-rights/',
            why: 'Leif Wenar\'s entry on what a legal right is, how it differs from a moral right, and how it interacts with the state.',
            year: 2023,
          },
          {
            title: 'Natural Law Theories',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/natural-law-theories/',
            why: 'John Finnis and the natural-law tradition — the philosophical alternative to positivist constitutional theory.',
            year: 2025,
          },
          {
            title: 'Constitutional law',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Constitutional_law',
            why: 'Comparative overview with good international material.',
            year: null,
          },
          {
            title: 'Constitutional Law',
            source: 'Cornell Legal Information Institute — Wex',
            url: 'https://www.law.cornell.edu/wex/constitutional_law',
            why: 'Cornell\'s reference-grade entry linking to the Constitution and to annotations of every major doctrine.',
            year: null,
          },
          {
            title: 'SCOTUSblog — case analysis',
            source: 'SCOTUSblog',
            url: 'https://www.scotusblog.com/',
            why: 'The best free source of analysis of current Supreme Court cases, with case files, argument previews, and symposium essays.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Harvard Law School — academics portal',
            provider: 'Harvard Law School',
            url: 'https://hls.harvard.edu/academics/',
            free: true,
            why: 'HLS publishes substantial course materials and lecture videos.',
          },
          {
            title: 'Cornell LII — Supreme Court opinions',
            provider: 'Cornell Law School',
            url: 'https://www.law.cornell.edu/supremecourt/text/home',
            free: true,
            why: 'The single best free portal to current and historic Supreme Court opinions, with search and cross-linking.',
          },
        ],
        podcasts: [
          {
            title: 'We the People',
            show: 'National Constitution Center',
            url: 'https://constitutioncenter.org/news-debate/podcasts/we-the-people',
            duration: '≈60:00 per episode',
            why: 'Jeffrey Rosen hosts weekly debates between constitutional scholars with opposing views.',
          },
          {
            title: 'Amicus',
            show: 'Slate',
            url: 'https://slate.com/podcasts/amicus',
            duration: '≈50:00 per episode',
            why: 'Dahlia Lithwick\'s long-running Supreme Court podcast.',
          },
          {
            title: 'Advisory Opinions',
            show: 'The Dispatch',
            url: 'https://thedispatch.com/podcast/advisory-opinions/',
            duration: '≈60:00 per episode',
            why: 'David French and Sarah Isgur on constitutional law and the Supreme Court. Conservative-leaning counterweight to Amicus.',
          },
          {
            title: 'Strict Scrutiny',
            show: 'Crooked Media',
            url: 'https://crooked.com/podcast-series/strict-scrutiny/',
            duration: '≈60:00 per episode',
            why: 'Melissa Murray, Leah Litman, and Kate Shaw on current cases. Progressive in framing; strong on doctrine.',
          },
        ],
        primarySources: [
          {
            title: 'The U.S. Constitution, annotated',
            url: 'https://www.law.cornell.edu/constitution',
            why: 'Cornell LII\'s annotated text with commentary from the Congressional Research Service.',
          },
          {
            title: 'Marbury v. Madison (full opinion)',
            url: 'https://www.oyez.org/cases/1803/5',
            why: 'The case on Oyez, with the opinion, summary, and background.',
          },
          {
            title: 'The Federalist Papers (Yale Avalon)',
            url: 'https://avalon.law.yale.edu/subject_menus/fed.asp',
            why: 'Full 1787–88 ratification debate.',
          },
        ],
      },

      seeAlso: ['contract_law', 'criminal', 'constitutions', 'governments'],
      prereqs: ['constitutions', 'contract_law'],
      leadsTo: [],

      chapterActivity: 'A monthly case-of-the-month reading — one Supreme Court decision per session, read cold, argued over drinks; everyone must pick a side. Twice a year, a day in Washington for a Supreme Court argument (first-come line) and a reading aloud of Federalist 78 on the Amtrak home.',

      sources: [
        'https://plato.stanford.edu/entries/constitutionalism/',
        'https://plato.stanford.edu/entries/legal-rights/',
        'https://plato.stanford.edu/entries/natural-law-theories/',
        'https://en.wikipedia.org/wiki/Constitutional_law',
        'https://www.law.cornell.edu/wex/constitutional_law',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
