// content/linguistics.js
// Owned by batch: B05-social-world
// Last updated: 2026-04-23 by BATCH B05-social-world
//
// Topics this subject must cover (from data.js):
//   Core: phonetics, syntax, etymology

window.CONTENT = window.CONTENT || {};
window.CONTENT.linguistics = {
  subjectId: 'linguistics',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B05-social-world',
  topics: {

    // ——— PHONETICS ———
    phonetics: {
      id: 'phonetics',
      name: 'Phonetics',
      level: 'Beginner',
      dek: 'The physics and physiology of speech — the sounds themselves, before any language chops them into meaning.',
      readTime: '16 min',

      sections: ['The unpromising instrument', 'The articulators', 'Vowels are harder', 'The IPA', 'Phonology, its companion', 'Why machines got so good so slowly'],
      body: [
        { type: 'lead', text: 'The human mouth is an unpromising musical instrument: a fleshy tube, a floppy tongue, a pair of gates at the back of the throat. Nevertheless, by moving those parts in rapid coordination, a speaker produces several dozen distinct sounds per second, and a listener across the room can reconstruct them with almost perfect fidelity. Phonetics is the scientific study of that minor miracle.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/IPA_chart_2020.svg?width=1400', caption: 'The International Phonetic Alphabet (2020 revision). A single symbol for every speech sound in every language — the working toolkit of phoneticians, lexicographers, speech therapists, and opera singers.', credit: 'International Phonetic Association, CC BY-SA 3.0, via Wikimedia Commons' },
        { type: 'h2', text: 'The articulators' },
        { type: 'p', text: 'Almost every speech sound in every language is described by what the speaker is doing with three things: the place of articulation (lips, teeth, alveolar ridge, palate, velum, glottis), the manner (stop, fricative, nasal, approximant), and the voicing (vocal folds vibrating or not). The difference between p and b is voicing. The difference between b and v is manner. The difference between v and z is place. That three-dimensional space is the body of the subject.' },
        { type: 'p', text: 'The vocal tract from glottis to lips is roughly 17 centimeters long in an average adult. That length, and the shapes the tract can take, determine the frequency spectrum of each vowel. Phoneticians call these shaping frequencies formants; F1 and F2 together uniquely identify most English vowels. A spectrogram of speech, which plots frequency against time, shows these formants as dark bands, sweeping and pooling as the tract moves.' },
        { type: 'h2', text: 'Vowels are harder' },
        { type: 'p', text: 'Consonants are modulated by obstruction; vowels are modulated by shape. The tongue can be high, mid, or low; front, central, or back; the lips can be rounded or spread. A chart of English vowels looks nothing like a chart of French vowels, because the same mouth draws slightly different boundaries around the same continuous space. This is why it takes an adult so long to learn a new vowel system.' },
        { type: 'p', text: 'The classic vowel trapezoid — front to back along the x-axis, close to open along the y-axis — was refined by Daniel Jones in the early twentieth century. Every IPA chart still uses it, and every descriptive linguistics grammar of a new language begins by locating its vowels in this space. The cardinal vowels [i, e, ɛ, a, ɑ, ɔ, o, u] are the reference points; actual languages place their vowels among them.' },
        { type: 'h2', text: 'The International Phonetic Alphabet' },
        { type: 'p', text: 'In 1888, a group of language teachers in Paris proposed a single alphabet that could represent every speech sound in every language with a single symbol each. The result, the IPA, has been refined and expanded ever since. Linguists use it; dictionaries use it (the Oxford English Dictionary switched to it decades ago); opera singers learn it in conservatory. A few hours with the chart is enough to change how you hear your own voice.' },
        { type: 'h2', text: 'Phonology, its companion' },
        { type: 'p', text: 'Phonetics tells you what sounds a person is making. Phonology tells you which differences count in a given language. English speakers distinguish [p] from [b]; Mandarin distinguishes aspirated [pʰ] from unaspirated [p] but treats [b] as the same as [p]. The phoneme is the mental unit a speaker perceives as "the same sound"; the allophone is the physical variant that depends on context. Phonetics and phonology are different disciplines studying the same signal at different levels — like optics and vision science.' },
        { type: 'h2', text: 'Why computers got so good so slowly' },
        { type: 'p', text: 'Automatic speech recognition is hard because there is no reliable silence between words; because every speaker\'s vowel space is slightly different; because coarticulation (each sound shaped by its neighbors) smears the boundaries; because noise is ubiquitous. Human listeners handle all of this unconsciously. Modern systems, trained on millions of hours of speech, finally approach human performance in ideal conditions and still fall apart in noisy ones. The gap is smaller than it was but not yet gone.' },
        { type: 'callout', text: 'The "McGurk effect," named for the perception psychologist Harry McGurk who discovered it in 1976, shows that speech perception is partly visual. Video of lips saying "ga" dubbed with audio saying "ba" is perceived as "da" by most viewers. Close your eyes and it switches back. Phonetics is not purely about the ear.' },

        { type: 'h2', text: 'Learn it: describe a sound in three coordinates' },
        { type: 'p', text: 'Every consonant can be described by place + manner + voicing. Say /p/ out loud. Place: lips come together (bilabial). Manner: airflow is completely stopped and released (stop, also called "plosive"). Voicing: vocal folds not vibrating (voiceless). So /p/ is a voiceless bilabial stop. Now /b/: same place, same manner, but add voicing — voiced bilabial stop. Now /v/: teeth-on-lip (labiodental), air squeezed through a narrow gap (fricative), voiced. So /v/ is a voiced labiodental fricative. Practice on ten consonants in your own speech: put your fingers on your throat to feel voicing, look in a mirror for place, hold a tissue in front of your mouth for manner. In an hour you will have the basic articulatory vocabulary of the field.' },

        { type: 'h2', text: 'Worked example: narrow IPA transcription of a short English phrase' },
        { type: 'p', text: 'Transcribe "cats and dogs" in narrow IPA. First, identify each sound. "cats" is /kæts/ — four segments, no trick. "and" has a schwa in connected speech — /ənd/ or even /ən/ when relaxed. "dogs" is /dɒɡz/ in RP, /dɑːɡz/ in General American. Now narrow transcription: mark aspiration on voiceless stops — /kʰæts ənd dɒɡz/. Notice that the /t/ in "cats" is not aspirated because it is final; the /k/ in "cats" *is* aspirated because it is initial and followed by a stressed vowel. These allophonic details are invisible to a naive speaker, which is precisely why phonetics is a technical subject. The same letter "t" is a different sound in "top" (aspirated), "stop" (unaspirated), "cat" (unreleased), and "butter" (flapped). Same phoneme, four allophones, one transcription system that can show them all.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. Describe the following consonants in place + manner + voicing: /t/, /s/, /m/, /ʃ/ (as in "ship"), /ŋ/ (as in "sing").' },
        { type: 'p', text: 'Answer: /t/ voiceless alveolar stop. /s/ voiceless alveolar fricative. /m/ voiced bilabial nasal. /ʃ/ voiceless postalveolar fricative. /ŋ/ voiced velar nasal. Note that "nasal" replaces "voicing" in the usual three-coordinate description only because nasals are always voiced in the world\'s languages; some traditions still list voicing explicitly.' },
        { type: 'p', text: 'Problem 2. Transcribe "phonetics" in broad IPA for a General American speaker.' },
        { type: 'p', text: 'Answer: /fəˈnɛtɪks/. The first syllable has a reduced schwa because the stress is on the second syllable; the vowel in "net" is the open-mid front /ɛ/; the vowel in "tics" is the near-close /ɪ/; the final consonant cluster is /ks/, with /s/ voiceless because it follows a voiceless stop. Stress mark ˈ before the stressed syllable. If you got within one vowel of this, you have the hang of the system.' },
        { type: 'p', text: 'Problem 3. The word "butter" is often pronounced [ˈbʌɾɚ] in General American English, with a flap [ɾ] in the middle and an r-colored schwa at the end. In British RP it is [ˈbʌtə]. What does this pair reveal about phonemes vs. allophones? Is the American [ɾ] a separate phoneme or an allophone of /t/?' },
        { type: 'p', text: 'Answer: In American English, [ɾ] is an allophone of /t/ (and of /d/) — it appears only in a specific environment (between a stressed vowel and a following unstressed vowel or syllabic liquid) and is predictable. The underlying phoneme is still /t/. Speakers who write "butter" with a "t" are correct; the flap is a phonetic, not phonemic, phenomenon. If two words differed only by having [ɾ] vs. [t] and had different meanings, [ɾ] would be phonemic. They don\'t, so it isn\'t.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What are the three dimensions used to describe a consonant? (2) How do vowels differ from consonants articulatorily? (3) What is the difference between a phoneme and an allophone? (4) Why is English spelling a poor guide to English pronunciation? (5) Name three world languages with sounds not found in English, and the IPA symbols for them. (6) What is a formant, and how do F1 and F2 relate to tongue position?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Use the Interactive IPA Chart to hear all the consonants and practice saying them. Transcribe your name, your city, and one sentence you say often. Watch the first three Ling Space phonetics videos. Once you\'ve got the basics? Get Ladefoged\'s A Course in Phonetics with the accompanying audio CD and work through the exercises. Install Praat and record yourself saying the vowels; look at your spectrograms. To go further? Take a linguistics department phonetics course, or the free MIT 24.900. Read Sounds of the World\'s Languages (Ladefoged & Maddieson). The serious path then goes into laboratory phonology, speech processing, or experimental phonetics.' },
      ],

      keyTerms: ['place of articulation', 'manner of articulation', 'voicing', 'vowel', 'consonant', 'IPA', 'coarticulation', 'phoneme', 'allophone', 'formant', 'spectrogram', 'aspiration'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@thelingspace',
            title: 'The Ling Space (channel)',
            channel: 'The Ling Space',
            duration: 'variable',
            why: 'Moti Lieberman\'s short, well-made videos explaining core concepts in linguistics. Best free introduction on YouTube.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            title: 'Crash Course Linguistics (16 episodes)',
            channel: 'Crash Course',
            duration: 'approx. 3 hours total',
            why: 'Taylor Behnke and Gretchen McCulloch\'s sixteen-episode course, written by working linguists. Episodes 6–8 are the phonetics core.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://lingthusiasm.com/',
            title: 'Lingthusiasm (podcast)',
            channel: 'Gretchen McCulloch & Lauren Gawne',
            duration: 'variable',
            why: 'The most listenable podcast in the field. The episodes on the IPA, on mouth diagrams, and on tongue twisters are the best audio introduction to the subject.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@nativlang',
            title: 'NativLang (channel)',
            channel: 'NativLang',
            duration: 'variable',
            why: 'Well-researched short films on historical and comparative linguistics, with careful attention to sound. The "how European languages sound to outsiders" videos are phonetics in applied form.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@polyMATHY_Luke',
            title: 'polýMATHY (Luke Ranieri)',
            channel: 'polýMATHY',
            duration: 'variable',
            why: 'Ranieri\'s videos on reconstructed ancient pronunciations (Latin, Greek, Old English) are a working-phonetics lab in public.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LangfocusChannel',
            title: 'Langfocus',
            channel: 'Langfocus',
            duration: 'variable',
            why: 'Paul Jorgensen\'s comparative language channel — a profile of a language each episode, with accurate IPA and good audio examples.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@mitopencourseware',
            title: 'MIT OpenCourseWare — 24.900 Introduction to Linguistics',
            channel: 'MIT OpenCourseWare',
            duration: 'variable',
            why: 'MIT\'s undergraduate introduction to linguistics, with the phonetics lectures covering articulation, the IPA, and acoustic analysis.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/patricia_kuhl_the_linguistic_genius_of_babies',
            title: 'The linguistic genius of babies',
            channel: 'TEDxRainier 2010',
            duration: '10:17',
            why: 'Patricia Kuhl on how infants learn phoneme categories before their first birthday. A window into why adult L2 pronunciation is so hard.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/john_mcwhorter_4_reasons_to_learn_a_new_language',
            title: '4 reasons to learn a new language',
            channel: 'TED2016',
            duration: '9:52',
            why: 'John McWhorter, Columbia linguist, on the phonetic and cognitive stakes of second-language learning.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — language & linguistics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Occasional lectures by David Crystal, Deborah Cameron, and other senior British linguists.',
          },
        ],
        books: [
          {
            title: 'A Course in Phonetics',
            author: 'Peter Ladefoged and Keith Johnson',
            year: 2014,
            url: '',
            why: 'The standard introductory textbook, continuously in print since 1975. Ladefoged\'s audio examples (available on the companion site) are what make it work.',
          },
          {
            title: 'Vowels and Consonants',
            author: 'Peter Ladefoged',
            year: 2001,
            url: '',
            why: 'Ladefoged\'s trade-book version of the textbook — half the length, twice the wit.',
          },
          {
            title: 'Because Internet',
            author: 'Gretchen McCulloch',
            year: 2019,
            url: '',
            why: 'A modern popular book on how language works, with careful sections on how writing and speech diverge in the age of texting.',
          },
          {
            title: 'The Language Instinct',
            author: 'Steven Pinker',
            year: 1994,
            url: '',
            why: 'Pinker\'s popular classic on language as a biological adaptation. Chapter 6 is the accessible phonetics.',
          },
          {
            title: 'Language Files',
            author: 'Department of Linguistics, Ohio State University',
            year: 2016,
            url: '',
            why: 'The undergraduate linguistics textbook across many editions. The phonetics file is among the clearest short introductions in any textbook in print.',
          },
          {
            title: 'Sounds of the World\'s Languages',
            author: 'Peter Ladefoged and Ian Maddieson',
            year: 1996,
            url: '',
            why: 'The encyclopedic reference for the phonetic inventories of the world\'s languages. Not a read-through; an indispensable shelf.',
          },
          {
            title: 'The Stuff of Thought',
            author: 'Steven Pinker',
            year: 2007,
            url: '',
            why: 'Pinker on the semantic side; chapters 2 and 3 are good companions to any phonetics course because they locate phonetics inside the larger language system.',
          },
        ],
        articles: [
          {
            title: 'Phonetics',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Phonetics',
            why: 'Comprehensive overview with clear anatomical diagrams and a good section on the acoustic side of the subject.',
            year: null,
          },
          {
            title: 'International Phonetic Alphabet',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/International_Phonetic_Alphabet',
            why: 'The place to start for learning the symbols, with audio files for most of them.',
            year: null,
          },
          {
            title: 'The IPA Chart (official)',
            source: 'International Phonetic Association',
            url: 'https://www.internationalphoneticassociation.org/content/ipa-chart',
            why: 'The authoritative chart, with downloadable PDFs and interactive versions. Bookmark this.',
            year: null,
          },
          {
            title: 'Phonology',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Phonology',
            why: 'The sister entry; read alongside the phonetics one to see the two disciplines separate.',
            year: null,
          },
          {
            title: 'Linguistics',
            source: 'Encyclopædia Britannica',
            url: 'https://www.britannica.com/science/linguistics',
            why: 'Editorial overview of the whole field, useful for locating phonetics inside the larger discipline.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Crash Course Linguistics',
            provider: 'Crash Course / PBS',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            free: true,
            why: 'Sixteen episodes, about three hours total.',
          },
          {
            title: 'MIT 24.900 — Introduction to Linguistics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-fall-2022/',
            free: true,
            why: 'Full MIT undergraduate introduction with problem sets and lecture notes. More technical than Crash Course.',
          },
        ],
        podcasts: [
          {
            title: 'Lingthusiasm',
            show: 'Gretchen McCulloch & Lauren Gawne',
            url: 'https://lingthusiasm.com/',
            duration: '≈45:00 per episode',
            why: 'Monthly episodes on the weird and delightful bits of language, with transcripts.',
          },
          {
            title: 'The Allusionist',
            show: 'Helen Zaltzman',
            url: 'https://www.theallusionist.org/',
            duration: '≈25:00 per episode',
            why: 'Short-form etymology and word-history episodes. Charming, well-reported.',
          },
          {
            title: 'A Way with Words',
            show: 'Wayword, Inc. (public radio)',
            url: 'https://www.waywordradio.org/',
            duration: '≈50:00 per episode',
            why: 'Grant Barrett and Martha Barnette\'s long-running public-radio show on language questions from callers. Affectionate and accurate.',
          },
        ],
        tools: [
          {
            title: 'Interactive IPA Chart',
            url: 'https://www.ipachart.com/',
            why: 'Click any IPA symbol and hear the sound. The best single interactive resource for learning the alphabet.',
          },
          {
            title: 'Praat — phonetics software',
            url: 'https://www.fon.hum.uva.nl/praat/',
            why: 'Paul Boersma and David Weenink\'s free acoustic-analysis software. The tool every phonetics PhD student uses.',
          },
          {
            title: 'SIL Global',
            url: 'https://global.sil.org/',
            why: 'SIL International maintains language-documentation resources, including phonetic inventories for over a thousand languages.',
          },
        ],
      },

      seeAlso: ['syntax', 'etymology', 'cognition'],
      prereqs: [],
      leadsTo: ['syntax'],

      chapterActivity: 'A monthly accent-mapping night — each attendee records the same short paragraph, the group transcribes the vowels in IPA and argues about the New York diphthongs. Twice a year, a fieldwork exercise: ride the 7 train end to end, listen, try to pick up one new phoneme your own idiolect does not have.',

      sources: [
        'https://en.wikipedia.org/wiki/Phonetics',
        'https://en.wikipedia.org/wiki/International_Phonetic_Alphabet',
        'https://www.internationalphoneticassociation.org/content/ipa-chart',
        'https://en.wikipedia.org/wiki/Phonology',
        'https://www.britannica.com/science/linguistics',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— SYNTAX ———
    syntax: {
      id: 'syntax',
      name: 'Syntax',
      level: 'Intermediate',
      dek: 'The rules that turn a bag of words into a sentence — and the long argument about where those rules come from.',
      readTime: '17 min',

      sections: ['A young Chomsky', 'Constituency, not order', 'Universal grammar and its critics', 'Recursion', 'Typology — the other side of the argument', 'Why it matters outside linguistics'],
      body: [
        { type: 'lead', text: 'In 1957, a twenty-eight-year-old assistant professor at MIT published a slim book with a dull title — Syntactic Structures — and ignited a revolution. Noam Chomsky\'s opening move was to observe that "colorless green ideas sleep furiously" is grammatical nonsense; it is nonsense, but it is grammatical. The rules that distinguish the two, he argued, are not learned by imitation. A child\'s mind, he thought, comes pre-wired to learn them.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Noam_Chomsky_portrait_2017_retouched.png?width=900', caption: 'Noam Chomsky (b. 1928). His 1957 Syntactic Structures rewrote the field; his subsequent work on universal grammar has been argued about in every linguistics department for seven decades.', credit: 'Duncan Rawlinson, CC BY 2.0, via Wikimedia Commons' },
        { type: 'h2', text: 'Constituency' },
        { type: 'p', text: 'The central discovery of modern syntax is that a sentence is not a flat sequence of words; it is a hierarchical structure of nested groups (constituents). "The old man in the brown hat" is a single unit within a sentence, and you know it because you can replace the whole thing with a pronoun ("he"), move it as a block, or leave it out. The rules for forming these units differ across languages, but the fact that languages are constituent-structured seems to be nearly universal.' },
        { type: 'p', text: 'The diagram of these constituents is the tree. An introductory syntax course spends weeks teaching students to draw them, because the tree makes visible what an intuition only hints at: that the same sequence of words can have two different structures and therefore two different meanings. "I saw the man with the telescope" has two trees, and either one resolves the ambiguity.' },
        { type: 'h2', text: 'Universal grammar' },
        { type: 'p', text: 'Chomsky\'s stronger claim — universal grammar — is that the core architecture of syntax is innate. Children learn language too fast, from too little data, with too few errors, to be doing it by general-purpose induction. Critics including Geoffrey Pullum, Daniel Everett, and a generation of usage-based linguists have pushed back hard, arguing that the evidence for a dedicated language module is thinner than Chomsky claims. The debate is still open, and still lively.' },
        { type: 'p', text: 'Michael Tomasello\'s usage-based theory (from Constructing a Language, 2003) is the main alternative inside cognitive science. In Tomasello\'s account, children learn language by extracting patterns from interaction, using general pattern-learning mechanisms shared with other cognitive domains. The evidence comes from longitudinal studies of child language and from primate cognition. A fair reading is that both sides are seeing something real; the synthesis is not yet written.' },
        { type: 'h2', text: 'Recursion' },
        { type: 'p', text: 'A key feature of every known human language is recursion: a sentence can contain another sentence, which can contain another, indefinitely. This is how finite rules produce infinite expression. Daniel Everett\'s 2005 report on the Amazonian language Pirahã — which, he claimed, does not have recursion — remains one of the great contested cases in the field. Whether one example is enough to refute a universal is a question that looks smaller than it is.' },
        { type: 'h2', text: 'Typology' },
        { type: 'p', text: 'The World Atlas of Language Structures, a database maintained by Martin Haspelmath and colleagues, catalogs how the world\'s roughly 7,000 languages vary on 192 structural features. Languages can be subject-verb-object (English, Mandarin), subject-object-verb (Japanese, Turkish, Hindi), verb-subject-object (Classical Arabic, Welsh), or a handful of other orders. They can pack morphology tightly (Finnish, Inuktitut) or barely at all (Vietnamese, Mandarin). The typological evidence complicates universal-grammar claims and sharpens them both.' },
        { type: 'h2', text: 'Why syntax matters outside linguistics' },
        { type: 'p', text: 'Every programming language has a syntax (a set of formal rules for well-formed strings) and a parser (a program that checks them). The machinery was borrowed wholesale from linguistic syntax in the 1960s and built out in computer science. Modern large language models learn syntactic regularities from data rather than from a built-in grammar — which, depending on your view of the Chomsky program, is either a vindication or an embarrassment. The empirical facts are consistent with several theoretical stories; the reading public mostly does not know this.' },
        { type: 'callout', text: 'Colorless green ideas sleep furiously. One of the most famous sentences in twentieth-century scholarship. It is syntactically well-formed and semantically hopeless. The pair — this sentence against any word salad — is the argument for treating syntax and semantics as separable.' },

        { type: 'h2', text: 'Learn it: drawing your first tree' },
        { type: 'p', text: 'Take the sentence "The old dog chased the cat." Identify the constituents by running the replacement test — substitute a pronoun and see what survives as a unit. "He chased it" works, so "the old dog" and "the cat" are each single constituents (noun phrases, NPs). "The old dog" contains a determiner ("the"), an adjective ("old"), and a noun ("dog"). "Chased the cat" is a verb phrase (VP) — you can substitute "did so" for the whole phrase. Now draw the tree. S at the top splits into NP (subject) and VP (predicate). NP splits into Det + AdjP + N. VP splits into V + NP (object). NP splits again into Det + N. That is phrase-structure grammar at its simplest. Every sentence in every human language can be given such a tree, though the specific labels and combinatorial rules differ.' },

        { type: 'h2', text: 'Worked example: ambiguity through structure' },
        { type: 'p', text: 'Consider "I saw the man with the telescope." This sentence is genuinely ambiguous — and the ambiguity is structural, not merely lexical. Tree 1: "with the telescope" attaches to the VP ("saw with the telescope"). Tree 2: "with the telescope" attaches to the NP ("the man with the telescope"). Tree 1 says I used the telescope; Tree 2 says the man had the telescope. The same word sequence produces two different meanings by virtue of two different phrase structures. This is why syntax is not the same as word order. A parser (human or machine) has to decide which tree the speaker intended, usually by using context, prosody, or probability. The failure modes of early machine translation were almost all of this form.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. Are the following sentences grammatical? Explain any that are not. (a) "The girl who lives next door sings." (b) "The girl who lives sings next door." (c) "Who do you think that sings?" (d) "Who do you think sings?"' },
        { type: 'p', text: 'Answer: (a) grammatical. (b) grammatical but means something different (relative clause is shorter). (c) ungrammatical in standard English — the "that-trace effect" forbids "that" immediately before a gap where the subject was extracted. (d) grammatical without "that." This is one of the classic English syntax puzzles. It appears in no other grammatical form; native speakers reject (c) without knowing why. The rule is part of universal grammar\'s evidence base.' },
        { type: 'p', text: 'Problem 2. English is subject-verb-object (SVO). Japanese is subject-object-verb (SOV). Translate "The dog chases the cat" into Japanese word order (gloss the English words in the right order, you don\'t need the Japanese).' },
        { type: 'p', text: 'Answer: "Dog-SUBJECT cat-OBJECT chases." That is: "Dog cat chases" with grammatical particles marking roles. Japanese relies on case particles (wa/ga for subject, o for object) rather than word order to indicate grammatical relations. About 45% of the world\'s languages are SOV, 40% SVO, and 10% VSO; other orders are rare. Word order is one of the most systematic typological variables.' },
        { type: 'p', text: 'Problem 3. "The student who the teacher the principal likes praised graduated." Is this grammatical? Can you parse it?' },
        { type: 'p', text: 'Answer: Technically grammatical; effectively unreadable. It has three relative clauses nested in the center: the student graduated; the teacher praised the student; the principal likes the teacher. English speakers reject multi-center-embedded sentences at about three levels of nesting, not because the rules forbid them but because working memory cannot hold them. This is the "center-embedding" phenomenon Chomsky highlighted — a limit on human parsing, not on the underlying grammar. Right-branching equivalents ("The principal likes the teacher who praised the student who graduated") are effortless.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What does the replacement test do? (2) Draw a tree for "The tall boy quickly finished his homework." (3) What is the difference between a noun and a noun phrase? (4) What does Chomsky mean by "universal grammar"? (5) Name three major theoretical frameworks in syntax besides generative grammar. (6) Why are programming-language parsers usually much simpler than human-language parsers?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Watch the Ling Space syntax playlist. Practice drawing trees for ten simple sentences from a novel you like. Work the first chapter of Language Files or of Carnie\'s Syntax: A Generative Introduction. Once you\'ve got the basics? Read Pinker\'s The Language Instinct, then tackle Chomsky\'s Syntactic Structures (it\'s short). Work through Carnie\'s textbook cover to cover. To go further? Take a graduate syntax seminar. The Minimalist Program (1995) is Chomsky\'s current framework; read Adger\'s Core Syntax for a textbook treatment. Read at least one paper in the usage-based tradition (Tomasello, Goldberg) to hear the other side of the field.' },
      ],

      keyTerms: ['constituent', 'phrase structure', 'transformational grammar', 'universal grammar', 'recursion', 'grammaticality', 'parse tree', 'minimalism', 'movement', 'typology', 'construction grammar', 'dependency'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@thelingspace',
            title: 'The Ling Space — Syntax playlist',
            channel: 'The Ling Space',
            duration: 'variable',
            why: 'Moti Lieberman\'s syntax series — tree diagrams, X-bar theory, movement — taught cleanly.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            title: 'Crash Course Linguistics: Syntax (eps. 3–5)',
            channel: 'Crash Course',
            duration: 'approx. 30 min',
            why: 'Three connected episodes on how sentences are assembled.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://lingthusiasm.com/',
            title: 'Lingthusiasm — syntax episodes',
            channel: 'Gretchen McCulloch & Lauren Gawne',
            duration: 'variable',
            why: 'The episodes on tree diagrams, long-distance dependencies, and the "does this sentence sound okay?" test.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@mitopencourseware',
            title: 'MIT OCW — 24.900 Introduction to Linguistics',
            channel: 'MIT OpenCourseWare',
            duration: 'variable',
            why: 'MIT\'s undergraduate introduction, with syntax lectures by working Chomskyan linguists.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/steven_pinker_what_our_language_habits_reveal',
            title: 'What our language habits reveal',
            channel: 'TED2005',
            duration: '17:28',
            why: 'Pinker on how everyday grammar encodes a theory of mind. Language of Thought theory in popular form.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/anne_curzan_what_makes_a_word_real',
            title: 'What makes a word real?',
            channel: 'TEDxUofM',
            duration: '17:04',
            why: 'Michigan linguist Anne Curzan on grammaticality and descriptivism. A friendly entry to the debate about what it means to be "grammatical."',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@nativlang',
            title: 'NativLang — syntax and typology videos',
            channel: 'NativLang',
            duration: 'variable',
            why: 'NativLang\'s animated explainers on word order and grammatical structure in the world\'s languages.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LangfocusChannel',
            title: 'Langfocus — language profiles',
            channel: 'Langfocus',
            duration: 'variable',
            why: 'Each episode profiles a language, showing its syntactic structures with examples and comparisons.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — linguistic science',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Occasional lectures on comparative syntax, sociolinguistics, and the Chomskyan program from non-American voices.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/lera_boroditsky_how_language_shapes_the_way_we_think',
            title: 'How language shapes the way we think',
            channel: 'TEDWomen 2017',
            duration: '14:14',
            why: 'Stanford cognitive scientist Lera Boroditsky on the Whorfian side of linguistics — how grammatical categories influence cognition. Contested; worth watching critically.',
          },
        ],
        books: [
          {
            title: 'The Language Instinct',
            author: 'Steven Pinker',
            year: 1994,
            url: '',
            why: 'The most influential popular defense of the Chomskyan view of language. Clear, combative, sometimes overconfident.',
          },
          {
            title: 'Syntactic Structures',
            author: 'Noam Chomsky',
            year: 1957,
            url: '',
            why: 'The short book that changed the field. Technical, but a good reader can get the gist of the first three chapters without prior training.',
          },
          {
            title: 'The Cambridge Grammar of the English Language',
            author: 'Rodney Huddleston and Geoffrey K. Pullum',
            year: 2002,
            url: '',
            why: 'The reference grammar. Massive, authoritative, and the antidote to fuzzy thinking about English sentence structure.',
          },
          {
            title: 'Constructing a Language',
            author: 'Michael Tomasello',
            year: 2003,
            url: '',
            why: 'The main usage-based counter to universal grammar. A cognitive-scientist\'s account of how children actually acquire language.',
          },
          {
            title: 'Don\'t Sleep, There Are Snakes',
            author: 'Daniel Everett',
            year: 2008,
            url: '',
            why: 'Everett\'s memoir of thirty years with the Pirahã, and the fieldwork that produced his anti-Chomsky argument. Gripping.',
          },
          {
            title: 'Through the Language Glass',
            author: 'Guy Deutscher',
            year: 2010,
            url: '',
            why: 'Deutscher on the Whorfian hypothesis — does grammar shape thought? The best modern popular book on the question.',
          },
          {
            title: 'Language: Its Nature, Development and Origin',
            author: 'Otto Jespersen',
            year: 1922,
            url: 'https://archive.org/details/languageitsnatur00jesp',
            why: 'The Danish linguist\'s classic. Pre-Chomskyan in method, it still contains some of the clearest writing on syntax ever put in English.',
          },
        ],
        articles: [
          {
            title: 'Syntax',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Syntax',
            why: 'Well-structured overview with good coverage of the major frameworks (generative, dependency, categorial, construction grammar).',
            year: null,
          },
          {
            title: 'Philosophy of Linguistics',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/linguistics/',
            why: 'Barbara Scholz, Francis Jeffry Pelletier, and Geoffrey Pullum\'s long entry is the best philosophical introduction to what linguists are doing when they write a grammar.',
            year: 2024,
          },
          {
            title: 'Syntactic Structures',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Syntactic_Structures',
            why: 'Summary of the 1957 book\'s argument, with a good reception section.',
            year: null,
          },
          {
            title: 'Universal grammar',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Universal_grammar',
            why: 'Good overview of the claim and its critics, with recent references.',
            year: null,
          },
          {
            title: 'WALS — World Atlas of Language Structures',
            source: 'Max Planck Institute for Evolutionary Anthropology',
            url: 'https://wals.info/',
            why: 'The authoritative typological database. Every language-structure claim about world linguistic diversity should be checked against it.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'MIT 24.900 — Introduction to Linguistics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-fall-2022/',
            free: true,
            why: 'Full undergraduate introduction, with problem sets and lecture notes. The Chomskyan side, from the institution that built it.',
          },
          {
            title: 'Crash Course Linguistics',
            provider: 'Crash Course / PBS',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            free: true,
            why: 'The friendlier alternative.',
          },
        ],
        podcasts: [
          {
            title: 'Lingthusiasm',
            show: 'Gretchen McCulloch & Lauren Gawne',
            url: 'https://lingthusiasm.com/',
            duration: '≈45:00 per episode',
            why: 'Reliably good; the syntax episodes are particularly accessible.',
          },
        ],
        tools: [
          {
            title: 'World Atlas of Language Structures',
            url: 'https://wals.info/',
            why: 'Interactive typological database. Click any feature; see a map of how the world\'s languages distribute.',
          },
        ],
      },

      seeAlso: ['phonetics', 'etymology', 'cognition', 'cs'],
      prereqs: ['phonetics'],
      leadsTo: [],

      chapterActivity: 'A monthly "draw the tree" night — bring a sentence from a book or a headline, draw its constituency tree on butcher paper, defend your choices. Twice a year, take a sentence in a language nobody in the room speaks (get the group pronouncing it first) and try to reverse-engineer its structure from glosses.',

      sources: [
        'https://en.wikipedia.org/wiki/Syntax',
        'https://plato.stanford.edu/entries/linguistics/',
        'https://en.wikipedia.org/wiki/Syntactic_Structures',
        'https://en.wikipedia.org/wiki/Universal_grammar',
        'https://wals.info/',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— ETYMOLOGY ———
    etymology: {
      id: 'etymology',
      name: 'Etymology',
      level: 'Beginner',
      dek: 'Where words come from — a discipline that treats the language you already speak as an archaeological dig.',
      readTime: '15 min',

      sections: ['Jones in Calcutta, 1786', 'The comparative method', 'The Indo-European family', 'Loans, borrowings, and detours', 'Semantic drift', 'What etymology cannot tell you'],
      body: [
        { type: 'lead', text: 'In 1786, an English judge named William Jones, serving in Calcutta, gave a lecture in which he observed that Sanskrit, Latin, and Greek "bear to each other a stronger affinity than could possibly have been produced by accident." The claim seems obvious now; it was electric then. Jones had noticed, without quite saying so, that half the languages from Iceland to India came from a single lost ancestor. The modern science of historical linguistics started with that sentence.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/IndoEuropeanTree.svg?width=1200', caption: 'The Indo-European language family tree. About half the living languages from Iceland to India — and half the world\'s speakers — descend from a single reconstructed ancestor spoken north of the Black Sea around 4500 BCE.', credit: 'Hayden120, CC BY-SA 3.0, via Wikimedia Commons' },
        { type: 'h2', text: 'The comparative method' },
        { type: 'p', text: 'Etymologists do not work by intuition. They assemble tables of cognates — words with the same meaning in related languages — and look for regular sound correspondences. Latin pater, Sanskrit pitṛ, Greek patēr, English father: the p-to-f shift is not a coincidence but a law (Grimm\'s Law, formalized by Jacob Grimm in 1822), and it applies across the whole Germanic vocabulary. By the 1870s, the Neogrammarians had formalized the method, and the family trees of the world\'s languages began to fill in.' },
        { type: 'p', text: 'The Neogrammarian hypothesis — that sound changes are exceptionless within a speech community — is still the working assumption, though modern sociolinguistics (William Labov\'s work especially) has complicated it. The comparative method produces reliable results anyway, because apparent exceptions almost always turn out to be borrowings, analogies, or conditioned by factors the linguist had not yet controlled for.' },
        { type: 'h2', text: 'The Indo-European family' },
        { type: 'p', text: 'English, German, Russian, Persian, Hindi, Greek, Latin, Irish, and dozens of others descend from a single language — Proto-Indo-European — spoken somewhere north of the Black Sea around 4500 BCE. Nobody wrote it down; nobody heard it in the modern era; everything we know about it is reconstructed from its daughters by the comparative method. The reconstructed forms are marked with an asterisk (*kwon- for "dog") and the whole apparatus is one of the great intellectual achievements of the nineteenth century.' },
        { type: 'p', text: 'Indo-European is not the only language family, just the best-studied. Afro-Asiatic (Arabic, Hebrew, Amharic, ancient Egyptian), Sino-Tibetan (Mandarin, Burmese, Tibetan), Niger-Congo (Swahili, Yoruba, Zulu), Austronesian (Malay, Tagalog, Māori), Uralic (Finnish, Hungarian, Estonian), and perhaps a hundred others each have their own family trees and their own comparative reconstruction. Modern historical linguistics aims at all of them.' },
        { type: 'h2', text: 'Borrowing, the messier half' },
        { type: 'p', text: 'A lot of English is not Germanic at all. After the Norman Conquest, French flooded the vocabulary of law, cuisine, and administration; Latin came through the Church and the universities; Greek through science; and colonial contact brought in shampoo, pajamas, ketchup, avocado, and thousands more. A word\'s etymology is often a short cultural history of who was talking to whom.' },
        { type: 'p', text: 'About 60% of the English vocabulary is ultimately of French or Latin origin. Only about 25% is Germanic. The functional core — the most frequent thousand words — is heavily Germanic; the specialized, literary, and technical vocabulary is mostly Romance and Greek. The doublet is a tell: "cow" (Germanic, the animal in the field) versus "beef" (French, the meat on the table) reflects the Norman conquest of England\'s aristocracy while peasants kept tending the animals. The class history is in the vocabulary.' },
        { type: 'h2', text: 'Semantic drift' },
        { type: 'p', text: 'Words do not only change in sound; they change in meaning. "Nice" once meant "foolish"; "silly" once meant "blessed"; "awful" once meant "worthy of awe"; "meat" once meant "food in general." "Terrific" in the nineteenth century meant "causing terror"; now it means "excellent." These shifts are not random. Linguists track pejoration (a word becomes negative), amelioration (a word becomes positive), narrowing, broadening, metaphor, metonymy, and several other mechanisms.' },
        { type: 'h2', text: 'The etymological fallacy' },
        { type: 'p', text: 'A word\'s oldest meaning is not its true meaning. Appealing to a word\'s etymology to dictate its present use — what linguists call the etymological fallacy — is a rhetorical trick, not a linguistic argument. Etymology tells you where a word has been. What it now means is decided by how people now use it.' },
        { type: 'callout', text: 'The word "etymology" itself is Greek: etymos, "true," plus -logia, "study of." The word is also a little embarrassment: the Greeks thought etymology would reveal the true meaning of words, and it does not.' },

        { type: 'h2', text: 'Learn it: apply the comparative method' },
        { type: 'p', text: 'Suppose you notice that English "father", German "Vater", Dutch "vader", Swedish "fader", and Gothic "fadar" all mean the same thing and start with a labiodental fricative or a /v/. Are these cognates? Apply the comparative method. Step 1: list the forms. Step 2: look for regular correspondences — do *all* of these words pattern the same way across other Germanic pairs (English "foot" / German "Fuß" / Dutch "voet"; English "fish" / German "Fisch" / Dutch "vis")? Yes — f and v alternate across Germanic languages in a predictable way. Step 3: compare to the Latin and Sanskrit forms — pater, pitṛ. The p-to-f shift is exactly what Grimm\'s Law predicts. Conclusion: these are cognates descended from Proto-Indo-European *ph₂tḗr. The asterisk marks a reconstructed form. No one ever spoke it in the recorded era; it is the mathematically reconstructed ancestor.' },

        { type: 'h2', text: 'Worked example: the history of "salary"' },
        { type: 'p', text: 'Trace "salary" back. Modern English salary → Middle English salarie → Old French salarie → Latin salarium ("salt money," from sal = salt). The Latin word referred to an allowance paid to Roman soldiers, possibly originally to purchase salt, possibly already metaphorical by the first century. Related words in English: salt, salad (from Vulgar Latin *salata, "salted"), sauce (salsa), salami, salsa. Now the comparative angle: Greek hals "salt," Welsh halen, all from the same Proto-Indo-European root *sal- "salt." The salt root shows up in many daughter languages because salt was one of the first widely traded commodities; its word traveled with the trade. An afternoon on Etymonline with a good sauce of patience and you can run this tree for ten words before dinner.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. The English word "decimate" originally meant "to kill one in ten" (from Latin decimus, "tenth" — a Roman military punishment). Today most speakers use it to mean "to destroy a large proportion of." Is the modern usage "wrong"? What linguistic phenomenon is at work?' },
        { type: 'p', text: 'Answer: Semantic broadening, or more specifically generalization. The original narrow meaning has broadened to include any massive reduction. Arguing the "wrong" usage is wrong is the etymological fallacy — the belief that a word\'s original meaning dictates its true meaning. Languages change; broadening is one of the most common change types. The prescriptivist position is defensible as a style preference ("use \'decimate\' precisely for emphasis"), not as a linguistic fact.' },
        { type: 'p', text: 'Problem 2. The word "nice" meant "foolish" in the 14th century, "fastidious" in the 16th, "precise" in the 18th, and "pleasant" in the modern period. What is this phenomenon, and how does it fit into a general pattern?' },
        { type: 'p', text: 'Answer: Semantic drift through amelioration (a word becomes more positive over time). Its opposite is pejoration ("silly" moved from "blessed" to "foolish"). Other common semantic changes include broadening (dog, originally one breed, now all dogs), narrowing (meat, originally all food, now only flesh), and metaphorical extension (bright as in "intelligent"). Semantic shift is systematic enough that historical linguists can often predict which direction a word will move given its cultural role.' },
        { type: 'p', text: 'Problem 3. English has two words for most cattle products: cow/beef, pig/pork, sheep/mutton, deer/venison, chicken/poultry. Why?' },
        { type: 'p', text: 'Answer: Norman Conquest (1066). The Anglo-Saxon peasants who tended the animals used Germanic words; the Norman-French aristocracy who ate them used Romance words. The lexical doublet is a fossil of the class structure of post-conquest England. It persists a thousand years later, long after the class distinction has faded, because vocabulary is more durable than the institutions that produced it.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What is Grimm\'s Law? Give three sound correspondences. (2) What does an asterisk before a word signify in historical linguistics? (3) Name three language families besides Indo-European. (4) What is the etymological fallacy? (5) Distinguish a cognate from a loanword; give one example of each in English. (6) Why did the Neogrammarians think sound change was exceptionless, and was it a simplification or an insight?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read John McWhorter\'s Power of Babel. Spend 15 minutes a day on Etymonline looking up common words and tracing them back. Watch NativLang\'s Indo-European videos. Once you\'ve got the basics? Read Guy Deutscher\'s Unfolding of Language and Nicholas Ostler\'s Empires of the Word. Learn the first 50 Grimm\'s Law correspondences. To go further? Take a historical-linguistics course (Campbell\'s textbook is the standard). Learn an ancient language — Latin, Old English, or Sanskrit — and read the primary sources the comparative method was built on. Serious students read Meillet and Brugmann in German, and the current Proto-Indo-European reconstruction debates in papers from the Journal of Indo-European Studies.' },
      ],

      keyTerms: ['cognate', 'sound change', 'Grimm\'s Law', 'Proto-Indo-European', 'loanword', 'folk etymology', 'comparative method', 'semantic shift', 'pejoration', 'amelioration', 'Neogrammarian', 'language family'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@thelingspace',
            title: 'The Ling Space — Historical & Etymology playlists',
            channel: 'The Ling Space',
            duration: 'variable',
            why: 'Lieberman\'s videos on sound change, language families, and the comparative method.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            title: 'Crash Course Linguistics: Historical (eps. 14–15)',
            channel: 'Crash Course',
            duration: 'approx. 25 min',
            why: 'Two episodes on language families and how languages change.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://lingthusiasm.com/',
            title: 'Lingthusiasm — Etymology episodes',
            channel: 'Gretchen McCulloch & Lauren Gawne',
            duration: 'variable',
            why: 'Multiple episodes on word origins, taboo-word replacement, and the etymology of emoji.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@nativlang',
            title: 'NativLang (channel)',
            channel: 'NativLang',
            duration: 'variable',
            why: 'Careful, animated short films on historical linguistics. The videos on the Indo-European family, on Grimm\'s Law, and on the history of scripts are all excellent.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@polyMATHY_Luke',
            title: 'polýMATHY',
            channel: 'Luke Ranieri',
            duration: 'variable',
            why: 'Ranieri on reconstructed ancient-world pronunciations — Latin, Greek, Old English, Gothic. Practical etymology in audio form.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LangfocusChannel',
            title: 'Langfocus',
            channel: 'Paul Jorgensen',
            duration: 'variable',
            why: 'Comparative language-family videos, each half an hour. The Indo-European family videos are a great way to see the tree in motion.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/anne_curzan_what_makes_a_word_real',
            title: 'What makes a word real?',
            channel: 'TEDxUofM',
            duration: '17:04',
            why: 'University of Michigan\'s Anne Curzan on how new words enter a language. Practical, friendly.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/john_mcwhorter_txtng_is_killing_language_jk',
            title: 'Txtng is killing language. JK!',
            channel: 'TED2013',
            duration: '13:48',
            why: 'John McWhorter, Columbia linguist, on how modern texting is adding a new register to English, not destroying it.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@simonroper9218',
            title: 'Simon Roper',
            channel: 'Simon Roper',
            duration: 'variable',
            why: 'Simon Roper speaks Old and Middle English aloud with analysis, and walks through sound changes on camera. Etymology as audible history.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@AlliterativeEtymology',
            title: 'Alliterative — etymology & history',
            channel: 'Alliterative',
            duration: 'variable',
            why: 'Mark Sundaram on word histories in their cultural context. Dense but welcoming.',
          },
        ],
        books: [
          {
            title: 'The Power of Babel: A Natural History of Language',
            author: 'John McWhorter',
            year: 2001,
            url: '',
            why: 'A popular survey of how languages split, borrow, simplify, and die. The clearest introduction to historical linguistics for a general reader.',
          },
          {
            title: 'The Unfolding of Language',
            author: 'Guy Deutscher',
            year: 2005,
            url: '',
            why: 'Deutscher on how grammar itself erodes and rebuilds over time. The best recent popular book on historical linguistics.',
          },
          {
            title: 'Our Magnificent Bastard Tongue',
            author: 'John McWhorter',
            year: 2008,
            url: '',
            why: 'A focused history of English — why it is so simple grammatically and so weird lexically.',
          },
          {
            title: 'The Stories of English',
            author: 'David Crystal',
            year: 2004,
            url: '',
            why: 'The British linguist\'s single-volume history of English, told through the people who used it. Long, rich, eminently readable.',
          },
          {
            title: 'Empires of the Word',
            author: 'Nicholas Ostler',
            year: 2005,
            url: '',
            why: 'A history of the world told through the languages of empire: Aramaic, Greek, Latin, Arabic, Sanskrit, Chinese, Spanish, English.',
          },
          {
            title: 'Word Origins',
            author: 'John Ayto',
            year: 1990,
            url: '',
            why: 'A dictionary of 8,000 English word histories, organized as prose rather than as entries. A browseable shelf reference.',
          },
          {
            title: 'The Oxford History of English',
            author: 'Lynda Mugglestone (ed.)',
            year: 2006,
            url: '',
            why: 'The academic standard. Eleven chapters by different scholars, covering Old English through the twenty-first century.',
          },
        ],
        articles: [
          {
            title: 'Etymology',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Etymology',
            why: 'Broad, well-cited overview with a good section on the comparative method.',
            year: null,
          },
          {
            title: 'Linguistics',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Linguistics',
            why: 'Context for etymology inside the larger field.',
            year: null,
          },
          {
            title: 'Philosophy of Linguistics',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/linguistics/',
            why: 'Useful for understanding what kind of claim an etymological one is — historical, probabilistic, reconstructive.',
            year: 2024,
          },
          {
            title: 'Indo-European languages',
            source: 'Encyclopædia Britannica',
            url: 'https://www.britannica.com/topic/Indo-European-languages',
            why: 'The long Britannica entry on the family. Still the best single overview.',
            year: null,
          },
          {
            title: 'Grimm\'s Law',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Grimm%27s_law',
            why: 'Good short entry on the 1822 formulation that made comparative linguistics a science.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Crash Course Linguistics',
            provider: 'Crash Course / PBS',
            url: 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP5mp25nStsuDzk2blncJDW',
            free: true,
            why: 'Full sixteen-episode course; the historical-linguistics block is episodes 14–15.',
          },
          {
            title: 'MIT 24.900 — Introduction to Linguistics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-fall-2022/',
            free: true,
            why: 'The historical linguistics block covers sound change and the comparative method.',
          },
        ],
        podcasts: [
          {
            title: 'The Allusionist',
            show: 'Helen Zaltzman',
            url: 'https://www.theallusionist.org/',
            duration: '≈25:00 per episode',
            why: 'Short etymology episodes — the single best podcast on English word history.',
          },
          {
            title: 'Lingthusiasm',
            show: 'McCulloch & Gawne',
            url: 'https://lingthusiasm.com/',
            duration: '≈45:00 per episode',
            why: 'Monthly episodes that regularly turn to etymology.',
          },
          {
            title: 'A Way with Words',
            show: 'Wayword, Inc.',
            url: 'https://www.waywordradio.org/',
            duration: '≈50:00 per episode',
            why: 'Grant Barrett and Martha Barnette on listener word-history questions.',
          },
        ],
        tools: [
          {
            title: 'Online Etymology Dictionary',
            url: 'https://www.etymonline.com/',
            why: 'Douglas Harper\'s twenty-plus-year project. Not peer-reviewed, but exhaustively sourced and the best single free reference for English word histories.',
          },
          {
            title: 'OED (Oxford English Dictionary)',
            url: 'https://www.oed.com/',
            why: 'The authoritative historical dictionary of English. Subscription-only for most features; many public libraries give free access with a library card.',
          },
        ],
      },

      seeAlso: ['phonetics', 'syntax', 'literature', 'history'],
      prereqs: [],
      leadsTo: ['syntax'],

      chapterActivity: 'A "word origins" evening at a bar — each attendee brings three odd words, the group guesses their etymologies cold, then we look them up together. Twice a year, a longer session with photocopies from the OED and a bottle of something appropriate: everyone picks a modern slang word and tries to reconstruct where it came from before checking Etymonline.',

      sources: [
        'https://en.wikipedia.org/wiki/Etymology',
        'https://en.wikipedia.org/wiki/Linguistics',
        'https://plato.stanford.edu/entries/linguistics/',
        'https://www.etymonline.com/',
        'https://en.wikipedia.org/wiki/Grimm%27s_law',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
