// content/meteorology.js
// Owned by batch: B15-nature-and-games
// Last updated: 2026-04-23 by BATCH B15-nature-and-games
//
// Topics this subject covers (from data.js):
//   Core: clouds, fronts

window.CONTENT = window.CONTENT || {};
window.CONTENT.meteorology = {
  subjectId: 'meteorology',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B15-nature-and-games',
  topics: {

    clouds: {
      id: 'clouds',
      name: 'Cloud Types',
      level: 'Beginner',
      dek: 'Cumulus, stratus, cirrus — the three forms named by a nineteenth-century Quaker pharmacist, and the ones meteorologists still use.',
      readTime: '11 min',

      sections: ['Luke Howard and the Linnaeus of clouds', 'The ten genera', 'Height and what it means', 'What a cloud actually is', 'Reading the sky'],
      body: [
        { type: 'lead', text: 'In December 1802, a twenty-nine-year-old Quaker pharmacist named Luke Howard read a paper to a London debating society called the Askesian. It was called "On the Modifications of Clouds," and in it he proposed three Latin names — cumulus, stratus, cirrus — and a few compound forms for the clouds between. Johann Wolfgang von Goethe, reading the paper in Weimar, wrote four short poems in praise of Howard. Two centuries later every meteorology class on Earth still uses the names Howard proposed in London that winter.' },
        { type: 'figure', src: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/CloudTypes-en.svg',
          alt: 'Diagram of cloud types arranged by altitude',
          caption: 'The ten cloud genera, arranged by altitude — cirrus and cirrostratus high, altocumulus and altostratus middle, stratus and cumulus low.',
          credit: 'Valentin de Bruyn · Wikimedia Commons · CC BY-SA 3.0' },
        { type: 'h2', text: 'The ten genera' },
        { type: 'p', text: 'The World Meteorological Organization, which inherited the classification from Howard through the nineteenth-century cloud atlases, now recognizes ten genera, arranged in three height tiers. High (above 20,000 feet): cirrus, cirrocumulus, cirrostratus. Middle (6,500 to 20,000 feet): altocumulus, altostratus, nimbostratus. Low (below 6,500 feet): stratus, stratocumulus, cumulus. And the two that span the tiers because they grow vertically: cumulonimbus (the thunderhead) and the uppermost anvil-topped version of cumulus. The genus names combine Howard\'s three root words the way any Linnaean system does: alto- is Latin for "high," nimbus is "rain," so nimbostratus is a layered raincloud.' },
        { type: 'h2', text: 'Height tells you physics' },
        { type: 'p', text: 'The three tiers are not arbitrary. High clouds are made of ice crystals because the air is below freezing; they diffract sunlight into the thin feathery shapes that give cirrus its name. Middle clouds are mostly water droplets at or near freezing and are the dappled, buttermilk layers that fill overcast days. Low clouds are water droplets at warmer temperatures and the ones children point at. A thunderhead, cumulonimbus, is the single thing in the troposphere tall enough to reach all three levels at once, and that vertical extent is what makes it the most dangerous cloud on the list.' },
        { type: 'h2', text: 'What a cloud actually is' },
        { type: 'p', text: 'A cloud is a visible mass of tiny water droplets or ice crystals suspended in air. The droplets are a hundredth of a millimeter across, about the weight of a mote of dust, and they stay aloft because they fall more slowly than the updrafts pushing them up. A cumulus cloud on a warm afternoon contains hundreds of tons of water, held up by what is essentially the gentle rising of a hot parking lot. When droplets grow past about a fiftieth of a millimeter they begin to fall faster than the updraft can support, collide and merge on the way down, and become rain. Rain is a cloud that has given up.' },
        { type: 'callout', text: 'A cirrus cloud is ice; an altocumulus is droplets; a cumulus is the condensing rising warm air off your own neighborhood. Three clouds, three physical regimes, each with its own behavior and forecast.' },
        { type: 'h2', text: 'Reading the sky' },
        { type: 'p', text: 'The sky forecasts itself. Cirrus thickening to cirrostratus — the halo-producing thin sheet around the sun or moon — is the front edge of a warm front, and the barometer is usually already falling. Altocumulus lenticularis, the saucer-shaped clouds that form over mountain ridges, means strong winds aloft. Cumulus humilis ("fair-weather cumulus") keeps its summer afternoon. Cumulus congestus — tall towers with hard, cauliflower tops — is two hours from being a thunderstorm. Learn these six shapes and you have the working vocabulary of every experienced sailor, pilot, and farmer since 1802.' },
      ],

      keyTerms: ['cumulus', 'stratus', 'cirrus', 'nimbostratus', 'cumulonimbus', 'altocumulus', 'troposphere', 'condensation', 'updraft', 'lenticular'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'other',
            url: 'https://weather.metoffice.gov.uk/learn-about/weather',
            title: 'UK Met Office — Learn About Weather',
            channel: 'Met Office', duration: 'on-demand',
            why: 'The UK\'s national weather service\'s own learning portal. Clean explanations of clouds, fronts, and forecasting, free.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@MetOffice',
            title: 'Met Office — Learn About Weather (YouTube)',
            channel: 'UK Met Office', duration: 'variable',
            why: 'The Met Office\'s YouTube channel, with short explanatory videos on each cloud type and on how forecasts actually work.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@crashcourse',
            title: 'Crash Course — Meteorology episodes',
            channel: 'Crash Course', duration: 'variable',
            why: 'The Crash Course Climate &amp; Energy series covers the cloud-classification and atmospheric-physics episodes at a good first-principles level.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@RyanHallYall',
            title: 'Ryan Hall, Y\'all — weather storytelling',
            channel: 'Ryan Hall', duration: 'variable',
            why: 'A young American meteorologist whose live severe-weather coverage, with honest forecasting reasoning, has become the model for how to explain clouds and fronts in real time.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@NOAAnws',
            title: 'NOAA / National Weather Service',
            channel: 'NOAA NWS', duration: 'variable',
            why: 'The US federal service\'s own videos — short, authoritative, and free.' },
        ],
        books: [
          { title: 'The Cloudspotter\'s Guide',
            author: 'Gavin Pretor-Pinney', year: 2006, url: '',
            why: 'The founder of the Cloud Appreciation Society on the pleasure of looking up. Sold a million copies and revived amateur cloud-watching.' },
          { title: 'The Cloud Collector\'s Handbook',
            author: 'Gavin Pretor-Pinney', year: 2011, url: '',
            why: 'The pocket-sized companion — a field guide with a running point system, in the spirit of a birding life list.' },
          { title: 'Meteorology Today',
            author: 'C. Donald Ahrens and Robert Henson', year: 2024, url: '',
            why: 'The undergraduate textbook almost every atmospheric-science program uses. Thirteenth edition. The reference for anyone who wants to go past the field guide.' },
          { title: 'The Weather Book',
            author: 'Jack Williams', year: 2009, url: '',
            why: 'USA Today\'s longtime weather editor wrote the general-reader book. Well-illustrated, readable, honest about what forecasts cannot do.' },
          { title: 'Instant Weather Forecasting',
            author: 'Alan Watts', year: 2012, url: '',
            why: 'A laminated booklet-sized guide for sailors and pilots. Twenty-five sky photographs with the forecast beside each. The most useful thirty-page book in this genre.' },
        ],
        articles: [
          { title: 'Cloud', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Cloud',
            why: 'A careful treatment of physics, classification, and cloud species — referenced and well-illustrated.' },
          { title: 'International Cloud Atlas (WMO)',
            source: 'World Meteorological Organization',
            url: 'https://cloudatlas.wmo.int/',
            why: 'The official reference. Every genus, species, variety, and feature, with authoritative photographs.' },
          { title: 'Luke Howard', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Luke_Howard',
            why: 'The Quaker pharmacist who named the clouds, in a paragraph you can read with breakfast.' },
        ],
        courses: [
          { title: 'NOAA JetStream — online weather school',
            provider: 'NOAA / NWS',
            url: 'https://www.noaa.gov/jetstream',
            free: true,
            why: 'The National Weather Service\'s free self-paced curriculum for non-meteorologists. The right next step after the field guide.' },
          { title: 'MetEd (UCAR) — free atmospheric science modules',
            provider: 'University Corporation for Atmospheric Research',
            url: 'https://www.meted.ucar.edu/',
            free: true,
            why: 'The professional training site, free after a no-cost registration. The modules are what NWS forecasters actually use.' },
        ],
        tools: [
          { title: 'National Weather Service',
            url: 'https://www.weather.gov/',
            why: 'The free US forecast — not commercialized, not gamified. The source everyone else is repackaging.' },
          { title: 'Windy.com',
            url: 'https://www.windy.com/',
            why: 'The best free interactive weather map — multiple models, overlays for cloud cover, wind, precipitation, and lightning.' },
          { title: 'Earth.nullschool.net',
            url: 'https://earth.nullschool.net/',
            why: 'Cameron Beccario\'s global wind and weather visualization. Indispensable for seeing the structure of a storm or jet stream.' },
          { title: 'Cloud Appreciation Society',
            url: 'https://cloudappreciationsociety.org/',
            why: 'Pretor-Pinney\'s community. Daily user photographs, a cloud-of-the-day gallery, and a slow, persistent campaign for the pleasures of looking up.' },
        ],
        primarySources: [
          { title: 'Luke Howard, "On the Modifications of Clouds" (1802)',
            url: 'https://archive.org/details/onmodificationso00howa',
            why: 'Howard\'s original paper, public domain, scanned by the Internet Archive. The twenty pages that named the clouds.' },
        ],
        images: [
          { src: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/CloudTypes-en.svg',
            alt: 'Cloud types by altitude',
            caption: 'The ten WMO cloud genera arranged by altitude tier.',
            credit: 'Valentin de Bruyn · Wikimedia Commons · CC BY-SA 3.0' },
        ],
      },

      interactive: null,
      seeAlso: ['fronts', 'biomes', 'geography'],
      prereqs: [],
      leadsTo: ['fronts'],

      chapterActivity: 'A Sunday morning cloudspotting walk on the Brooklyn Heights Promenade — bring a pocket field guide, leave the phone in your bag until the end.',

      sources: [
        'https://en.wikipedia.org/wiki/Cloud',
        'https://cloudatlas.wmo.int/',
        'https://weather.metoffice.gov.uk/learn-about/weather',
      ],
      verifiedAt: '2026-04-23',
    },

    fronts: {
      id: 'fronts',
      name: 'Fronts',
      level: 'Intermediate',
      dek: 'Warm, cold, stationary — the boundaries where air masses collide and where almost every interesting weather you will ever have comes from.',
      readTime: '12 min',

      sections: ['The Bergen school', 'Cold fronts, fast and loud', 'Warm fronts, slow and gray', 'The occlusion', 'The barometer and the ache in your knee', 'Reading a weather map'],
      body: [
        { type: 'lead', text: 'In the last winter of the First World War, a small group of Norwegian meteorologists at the Bergen Geophysical Institute — led by Vilhelm Bjerknes and his son Jacob — were trying to forecast weather for a country that had just lost its transatlantic radio contact with the rest of Europe. What they worked out, drawing on military-style frontal metaphors, became the single most important idea in twentieth-century meteorology: that most weather in the middle latitudes happens at the boundaries between masses of air with different temperatures and humidities. They called these boundaries fronts, and the language of warm, cold, and occluded fronts has barely changed in a hundred years.' },
        { type: 'h2', text: 'The Bergen school\'s idea' },
        { type: 'p', text: 'Temperature-equal, pressure-equal air is stable. Unequal air is a battle waiting to happen. A cold front is the leading edge of a cold, dense air mass plowing under a warmer one; a warm front is the leading edge of a warm, less dense air mass climbing over a colder one. Because cold air is dense it moves faster, and cold fronts produce sharp, narrow bands of weather — squalls, strong winds, a sudden temperature drop. Warm fronts, which must lift the retreating cold air, move more slowly and produce broad, layered weather — hours of steady rain from a thick gray nimbostratus before the front itself arrives.' },
        { type: 'h2', text: 'Cold front: the Hollywood weather' },
        { type: 'p', text: 'The cloud signature of a cold front is theatrical. Out of a blue morning sky, a line of cumulus towers grows in the west, darkening through the afternoon into a wall of cumulonimbus. Wind picks up. The temperature drops ten or fifteen degrees in an hour. Heavy rain begins, often with lightning. Thirty minutes later the rain stops, the sky clears behind the front, and the air is suddenly cooler and drier. On a weather map a cold front is drawn as a blue line with triangles pointing in the direction of movement — the teeth of the advancing cold air, in the Bergen-school metaphor.' },
        { type: 'h2', text: 'Warm front: the slow drench' },
        { type: 'p', text: 'The warm front\'s signature is subtler and older-feeling. Cirrus thickening over twelve to twenty-four hours to cirrostratus (the halo layer) to altostratus (the dimming that makes the sun look like a ground-glass disc) to nimbostratus (the sheet from which the steady rain falls). The rain is not heavy but it lasts — a gray twelve-hour drench, the kind you remember from rural English novels. When the front finally passes, the temperature rises, the rain stops, and the sky often stays overcast with stratocumulus. On the weather map it is a red line with semicircles on its advancing edge.' },
        { type: 'h2', text: 'The occlusion' },
        { type: 'p', text: 'A midlatitude cyclone — the shorthand name for the counter-clockwise-spinning low-pressure system that drives most North American and European weather — has a warm front ahead of a cold front, both pivoting around a common center. Because the cold front moves faster, it catches up with the warm front and lifts the warm air wedge off the ground. The resulting combined boundary is called an occluded front and is drawn purple on the map. Occluded fronts are the mature, late-life form of the cyclone, with weather that resembles a slightly more dramatic warm front.' },
        { type: 'callout', text: 'Barometric pressure falls before a front arrives and rises behind it. An old sailor\'s or farmer\'s trick: tap the barometer twice. If the needle jumps downward between taps, a storm is coming inside twenty-four hours. The ache in grandparents\' knees is the same signal — joint capsules responding to the pressure change.' },
        { type: 'h2', text: 'Reading a weather map' },
        { type: 'p', text: 'Every modern surface weather map carries the same vocabulary: an H for high-pressure, an L for low; cold and warm fronts in their blue-with-triangles and red-with-semicircles drawings; isobars (lines of equal pressure) spiraling into the low. The Weather Service\'s National Centers for Environmental Prediction post analyzed maps every six hours. A half hour studying them through a week of your own weather turns the maps from abstraction into something you can read the way a farmer reads the field. Matthew Cappucci and other working broadcast meteorologists post twice-daily map breakdowns on social platforms now; any of them is a better teacher than most textbooks.' },
      ],

      keyTerms: ['air mass', 'cold front', 'warm front', 'occluded front', 'stationary front', 'isobar', 'midlatitude cyclone', 'dew point', 'barometric pressure', 'polar front'],

      resources: {
        videos: [
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@MetOffice',
            title: 'Met Office — Learn About Weather (YouTube)',
            channel: 'UK Met Office', duration: 'variable',
            why: 'The UK national weather service\'s own YouTube channel. The "How fronts work" and "Types of clouds" series are the best free introductory video explainers.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@RyanHallYall',
            title: 'Ryan Hall, Y\'all — severe-weather coverage',
            channel: 'Ryan Hall', duration: 'variable',
            why: 'Ryan Hall\'s real-time frontal-storm coverage treats viewers like adults and narrates the meteorology as events unfold. Essential for translating book weather into living weather.' },
          { id: null, featured: true, source: 'youtube',
            url: 'https://www.youtube.com/@NOAAnws',
            title: 'National Weather Service (NOAA)',
            channel: 'NOAA NWS', duration: 'variable',
            why: 'NOAA\'s short forecast discussions and weather-of-the-week explainers. The authoritative US source.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@MesoMatt',
            title: 'Matthew / MesoMattWX — live severe-weather',
            channel: 'Matthew', duration: 'variable',
            why: 'A young Kentucky-based meteorology student whose live severe-weather coverage and map breakdowns are excellent training in pattern recognition.' },
          { id: null, source: 'youtube',
            url: 'https://www.youtube.com/@thisisrealscience',
            title: 'Tamitha Skov / Space Weather Woman',
            channel: 'Tamitha Skov', duration: 'variable',
            why: 'A working space-weather scientist, whose terrestrial-weather crossover videos are among the clearest scientific explainers on YouTube.' },
        ],
        books: [
          { title: 'Meteorology Today',
            author: 'C. Donald Ahrens and Robert Henson', year: 2024, url: '',
            why: 'The standard undergraduate textbook. Thirteenth edition. The serious first book for someone who wants to understand fronts past the hand-waving.' },
          { title: 'The Cloudspotter\'s Guide',
            author: 'Gavin Pretor-Pinney', year: 2006, url: '',
            why: 'Not a fronts book, but the best way to learn the sky before asking what is moving through it.' },
          { title: 'The Weather Book',
            author: 'Jack Williams', year: 2009, url: '',
            why: 'A veteran weather journalist\'s general-reader overview. Clear on cyclones, fronts, and what forecasts actually predict.' },
          { title: 'Weather for Dummies',
            author: 'John D. Cox', year: 2000, url: '',
            why: 'More serious than the title suggests. A clean, readable introduction written by a former Knight-Ridder science reporter.' },
          { title: 'Air Apparent: How Meteorologists Learned to Map, Predict, and Dramatize Weather',
            author: 'Mark Monmonier', year: 1999, url: '',
            why: 'The cultural and cartographic history. Monmonier is the country\'s best writer on maps; this is his weather book.' },
        ],
        articles: [
          { title: 'Weather front', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Weather_front',
            why: 'A clean, well-referenced treatment of every front type and the Bergen-school origins.' },
          { title: 'Meteorology', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Meteorology',
            why: 'The broader field — history, subdisciplines, and the principal tools.' },
          { title: 'Cyclogenesis', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Cyclogenesis',
            why: 'How midlatitude storms form — the Norwegian cyclone model in detail.' },
        ],
        courses: [
          { title: 'NOAA JetStream — online weather school',
            provider: 'NOAA National Weather Service',
            url: 'https://www.noaa.gov/jetstream',
            free: true,
            why: 'The most comprehensive free weather curriculum in English, written by and for the agency that makes the forecasts.' },
          { title: 'MetEd — free atmospheric science modules',
            provider: 'UCAR',
            url: 'https://www.meted.ucar.edu/',
            free: true,
            why: 'Professional-grade online training, free. The "Introduction to Fronts" module is the best single explanation online.' },
        ],
        tools: [
          { title: 'NWS Surface Analysis (WPC)',
            url: 'https://www.wpc.ncep.noaa.gov/html/sfc2.shtml',
            why: 'The National Weather Service Weather Prediction Center\'s updated surface frontal analysis every few hours. The map meteorologists actually use.' },
          { title: 'Windy.com',
            url: 'https://www.windy.com/',
            why: 'Global weather map with multiple models — ECMWF, GFS, ICON — overlaid with wind, pressure, and cloud cover. Free.' },
          { title: 'Earth.nullschool.net',
            url: 'https://earth.nullschool.net/',
            why: 'Real-time global wind and temperature. Watch a cold front advance from space.' },
          { title: 'Pivotal Weather',
            url: 'https://www.pivotalweather.com/',
            why: 'Free high-resolution model output (HRRR, GFS, ECMWF). What local forecasters actually look at.' },
        ],
        primarySources: [
          { title: 'Vilhelm Bjerknes, "The problem of weather prediction, considered from the viewpoints of mechanics and physics" (1904)',
            url: 'https://en.wikipedia.org/wiki/Vilhelm_Bjerknes',
            why: 'The Wikipedia article on Bjerknes, with references to his founding papers. The original idea that weather prediction is an initial-value problem in fluid dynamics.' },
        ],
      },

      interactive: null,
      seeAlso: ['clouds', 'climate', 'geography'],
      prereqs: ['clouds'],
      leadsTo: [],

      chapterActivity: 'A Saturday afternoon at the New York Public Library Science, Industry & Business Library tracking a moving front on a printout of the NWS surface analysis — coffee, pencils, and a radar loop on a laptop.',

      sources: [
        'https://en.wikipedia.org/wiki/Weather_front',
        'https://www.weather.gov/',
        'https://www.noaa.gov/jetstream',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
