// content/photography.js
// Batch: B13-arts-performing
// Last updated: 2026-04-23 by BATCH B13+B14
//
// Topics this subject must cover (from data.js):
//   Core: exposure, composition_photo, light

window.CONTENT = window.CONTENT || {};
window.CONTENT.photography = {
  subjectId: 'photography',
  version: 1,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B13+B14',
  topics: {

    exposure: {
      id: 'exposure',
      name: 'The Exposure Triangle',
      level: 'Beginner',
      dek: 'Aperture, shutter, ISO — three dials in a hundred-and-eighty-year-old argument about how much light is enough.',
      readTime: '12 min',

      sections: ['Three dials, one exposure', 'Aperture and the shape of focus', 'Shutter and the shape of time', 'ISO and the cost of darkness', 'Reading the histogram'],
      body: [
        { type: 'lead', text: 'In 1826, a French inventor named Nicéphore Niépce pointed a camera obscura out the upper window of his house in Burgundy and left the shutter open for eight hours. What came back on a pewter plate coated with bitumen of Judea was the first photograph ever made. The exposure was impossibly long by any modern standard, but the principle is the same one every photographer still wrestles with — a sensitive surface, a finite amount of light, and a decision about how long and how wide to let the light in.' },
        { type: 'h2', text: 'Three dials, one exposure' },
        { type: 'p', text: 'Every modern camera — phone, mirrorless, medium-format — exposes a sensor with three controls. Aperture is the diameter of the hole in the lens, measured in f-stops. Shutter speed is how long the sensor is uncovered, measured in seconds or fractions. ISO is the sensor\'s amplification of the signal, measured on an old film-speed scale. Double any one of them, halve another, and the total exposure stays the same. Photographers call this set of three the exposure triangle, and mastery of photography is, in one sense, learning what each corner costs.' },
        { type: 'h2', text: 'Aperture and the shape of focus' },
        { type: 'p', text: 'A wide aperture — f/1.4, f/2.8 — lets in a lot of light and throws the background out of focus. A narrow aperture — f/11, f/16 — lets in less light and keeps the whole scene sharp. Portrait photographers favor wide apertures because a blurred background isolates the face. Landscape photographers favor narrow ones because a sharp foreground rock and a sharp distant mountain are both what the picture is about. The same f-stop scale has been on lenses since the 1880s because the physics of light through a hole has not changed.' },
        { type: 'h2', text: 'Shutter and the shape of time' },
        { type: 'p', text: 'Shutter speed decides whether motion is frozen or blurred. A thousandth of a second stops a hummingbird\'s wing; a quarter of a second turns a running river into silk. Sports photographers shoot at 1/2000 or faster; a photojournalist on the street runs around 1/250 to keep hands sharp; a night photographer on a tripod can leave the shutter open for thirty seconds and collect the stars\' slow rotation. The handheld rule of thumb is that the shutter speed should be at least one over the focal length of the lens — a fifty-millimeter lens handheld at 1/60, a two-hundred-millimeter lens at 1/250, and so on.' },
        { type: 'h2', text: 'ISO and the cost of darkness' },
        { type: 'p', text: 'ISO is the insurance policy. When aperture and shutter together cannot gather enough light, ISO amplifies what the sensor collects. The cost is noise — a grainy speckling across the shadows that looks like static on an old television. A 2026 full-frame camera can shoot at ISO 6400 without meaningful penalty; a phone can shoot at ISO 12,800 and have its computational pipeline clean the noise afterward. For a working photographer the rule is simple: raise ISO until the shot is sharp, no further. A slightly grainy picture beats a blurred one every time.' },
        { type: 'h2', text: 'Reading the histogram' },
        { type: 'p', text: 'The one indicator more useful than the picture itself is the histogram — the small graph on the back of the camera showing how many pixels fall at each brightness level, from pure black on the left to pure white on the right. A well-exposed frame spreads across the graph without piling against either edge. A picture bunched against the right wall has "blown highlights" — white with no recoverable detail. One bunched against the left is "crushed shadows." Photographers shoot by the histogram, not by the tiny LCD, because an LCD on a bright day lies and the histogram never does.' },
        { type: 'callout', text: 'The Sunny 16 rule — f/16, shutter at one over the ISO, in daylight — still works. Set ISO 100, f/16, 1/125, and point a camera at a sunlit subject anywhere on earth. The exposure will be within a stop. It is the oldest photographer\'s trick and the best sanity check when the meter misbehaves.' },
      ],

      keyTerms: ['aperture', 'shutter speed', 'ISO', 'f-stop', 'histogram', 'stop', 'depth of field', 'reciprocity', 'exposure value', 'Sunny 16'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheSlantedLens',
            title: 'The Slanted Lens — Jay P. Morgan\'s lighting and exposure tutorials',
            channel: 'The Slanted Lens',
            duration: 'variable',
            featured: true,
            why: 'Thirty years of commercial experience in a patient weekly tutorial. Jay P. Morgan teaches exposure the way a working studio photographer thinks about it.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TonyAndChelsea',
            title: 'Tony & Chelsea Northrup — exposure fundamentals',
            channel: 'Tony & Chelsea Northrup',
            duration: 'variable',
            featured: true,
            why: 'The Northrups have taught a generation of beginners through their free YouTube course and best-selling photography book. Dense, accurate, welcoming.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@mangoStreet',
            title: 'Mango Street — exposure triangle, in under ten minutes',
            channel: 'Mango Street',
            duration: 'variable',
            featured: true,
            why: 'Rachel Gulotta and Daniel Inskeep built their channel on short, visually disciplined lessons for newer photographers. Best short-form introduction on the internet.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@BandH',
            title: 'B&H Photo Video — exposure and metering masterclass',
            channel: 'B&H Photo Video',
            duration: 'variable',
            featured: false,
            why: 'The New York camera store\'s YouTube education channel runs hour-long free seminars with working professionals. The old B&H Event Space, now online.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@KelbyOneOfficial',
            title: 'KelbyOne — Scott Kelby\'s photography training',
            channel: 'KelbyOne',
            duration: 'variable',
            featured: false,
            why: 'Scott Kelby has sold more photography books than anyone alive. His free channel samples the paid KelbyOne curriculum, and the free bits are still excellent.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@DPReviewTV',
            title: 'DPReview TV — technical fundamentals',
            channel: 'DPReview',
            duration: 'variable',
            featured: false,
            why: 'The camera industry\'s long-running technical review team, now on YouTube. Chris Niccolls and Jordan Drake explain sensor behavior, dynamic range, and noise without jargon.',
          },
        ],
        books: [
          {
            title: 'The Camera',
            author: 'Ansel Adams',
            year: 1980,
            url: 'https://www.worldcat.org/title/camera/oclc/6630639',
            why: 'Book one of Adams\'s three-volume technical series. Still the clearest careful treatment of how a camera sees — written by the photographer who convinced America that a negative was a score and the print its performance.',
          },
          {
            title: 'The Negative',
            author: 'Ansel Adams',
            year: 1981,
            url: 'https://www.worldcat.org/title/negative/oclc/7834139',
            why: 'Book two. The Zone System — Adams\'s framework for previsualizing exposure and development — is still the most disciplined way to think about the exposure triangle, even on a digital sensor.',
          },
          {
            title: 'Understanding Exposure',
            author: 'Bryan Peterson',
            year: 1990,
            url: 'https://www.penguinrandomhouse.com/books/91712/understanding-exposure-fourth-edition-by-bryan-peterson/',
            why: 'The standard modern reference. Now in its fourth edition, this is the book every photography student buys in their first week.',
          },
          {
            title: 'Stunning Digital Photography',
            author: 'Tony Northrup',
            year: 2014,
            url: 'https://www.tonynorthrup.com/stunning-digital-photography/',
            why: 'The genuinely excellent modern entry. Exhaustive, searchable, bundled with eighteen hours of companion video — the one beginner reference that respects the reader\'s time.',
          },
          {
            title: 'On Photography',
            author: 'Susan Sontag',
            year: 1977,
            url: 'https://archive.org/details/onphotography0000sont_m8j0',
            why: 'Not a technical book. The essays that taught a generation what it means to take a picture and keep one. Every photographer should own a copy.',
          },
        ],
        articles: [
          {
            title: 'Exposure (photography)',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Exposure_(photography)',
            why: 'Thorough, diagrammed, well-cited. The reference entry on reciprocity, latitude, and the optimum-exposure problem.',
            year: null,
          },
          {
            title: 'F-number',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/F-number',
            why: 'Why the f-stop scale goes 1.4, 2, 2.8, 4… and why doubling the number means half the light. The math of aperture, briefly and clearly.',
            year: null,
          },
          {
            title: 'Film speed',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Film_speed',
            why: 'The history of ISO, DIN, and ASA — the sensitivity scales that pre-date digital sensors and still govern how cameras think about light.',
            year: null,
          },
          {
            title: 'A History of Photography',
            source: 'The Metropolitan Museum of Art, Heilbrunn Timeline',
            url: 'https://www.metmuseum.org/toah/hd/phot/hd_phot.htm',
            why: 'The Met\'s short curatorial survey from Niépce to the present. Context for the technology and the art in the same breath.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Photography Basics and Beyond',
            provider: 'Coursera / Michigan State University',
            url: 'https://www.coursera.org/specializations/photography-basics',
            free: true,
            why: 'Peter Glendinning\'s free specialization from Michigan State. The most complete free photography course online, exposure through editing.',
          },
          {
            title: 'Stunning Digital Photography (free video companion)',
            provider: 'Tony Northrup',
            url: 'https://www.youtube.com/@TonyAndChelsea',
            free: true,
            why: 'Tony and Chelsea Northrup\'s bundled video course for their book. Eighteen hours, free on YouTube, still the best structured beginner sequence in the medium.',
          },
        ],
        podcasts: [
          {
            title: 'The Candid Frame',
            show: 'Ibarionex Perello',
            url: 'https://thecandidframe.com/',
            duration: 'variable',
            why: 'Long-form interviews with photographers, fifteen years deep. Technical and philosophical — exposure talk inside larger conversations about seeing.',
          },
        ],
        tools: [
          {
            title: 'PhotoPills',
            url: 'https://www.photopills.com/',
            why: 'Mobile planning app used by landscape and astrophotographers. Sunrise, moon phase, star-tracker, and the calculators for long exposures.',
          },
          {
            title: 'DxOMark camera database',
            url: 'https://www.dxomark.com/cameras/',
            why: 'Independent measurement of dynamic range, ISO, and color depth across every current sensor. The standard technical reference.',
          },
        ],
        primarySources: [
          {
            title: 'Niépce\'s "View from the Window at Le Gras" (1826)',
            url: 'https://en.wikipedia.org/wiki/View_from_the_Window_at_Le_Gras',
            why: 'The earliest surviving photograph. An eight-hour exposure on a pewter plate — the reference point for everything that followed.',
          },
        ],
        images: [
          {
            src: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/View_from_the_Window_at_Le_Gras%2C_Joseph_Nic%C3%A9phore_Ni%C3%A9pce.jpg',
            alt: 'View from the Window at Le Gras by Nicéphore Niépce, 1826',
            caption: 'Niépce\'s View from the Window at Le Gras, 1826 — the earliest surviving photograph, made with an eight-hour exposure on a pewter plate coated in bitumen.',
            credit: 'Harry Ransom Center, University of Texas · Wikimedia Commons · Public domain',
          },
          {
            src: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Lenses_with_different_apertures.jpg',
            alt: 'Lens apertures at different f-stops',
            caption: 'A lens opened at different f-stops. Each full stop halves or doubles the area of the opening.',
            credit: 'Wikimedia Commons',
          },
        ],
      },

      seeAlso: ['composition_photo', 'light', 'shots'],
      prereqs: [],
      leadsTo: ['composition_photo', 'light'],

      chapterActivity: 'A monthly "shoot the same block" meetup in Greenpoint — everyone photographs the same corner at the same hour, then prints small and pins to a cork board to compare decisions about exposure.',

      sources: [
        'https://en.wikipedia.org/wiki/Exposure_(photography)',
        'https://en.wikipedia.org/wiki/F-number',
        'https://en.wikipedia.org/wiki/Film_speed',
        'https://www.metmuseum.org/toah/hd/phot/hd_phot.htm',
      ],
      verifiedAt: '2026-04-23',
    },

    composition_photo: {
      id: 'composition_photo',
      name: 'Composition',
      level: 'Intermediate',
      dek: 'A rectangle, a subject, and every decision about what to leave out.',
      readTime: '12 min',

      sections: ['The frame is the decision', 'The rule of thirds, and when to break it', 'Leading lines and the eye\'s path', 'Negative space', 'The decisive moment'],
      body: [
        { type: 'lead', text: 'Henri Cartier-Bresson photographed with a Leica and a single fifty-millimeter lens for fifty years. He never cropped a frame in the darkroom; he considered the moment of the shutter the moment of the composition, and a later crop a failure of nerve. The standard for composition in photography — the standard still taught at the International Center of Photography in New York — is Cartier-Bresson\'s: see the geometry, wait for the subject to enter it, and press the shutter once.' },
        { type: 'h2', text: 'The frame is the decision' },
        { type: 'p', text: 'Painting builds up; photography subtracts. The painter starts with a blank canvas and decides what to put in; the photographer starts with a world and decides what to leave out. The frame of the camera — the 3:2 rectangle inherited from 35mm film, or the 4:3 of a phone, or the square of a Hasselblad — is the most important compositional tool in the medium. Where its four edges fall is not a detail. It is the composition itself.' },
        { type: 'h2', text: 'The rule of thirds, and when to break it' },
        { type: 'p', text: 'Divide the frame into thirds, horizontally and vertically; the four intersections are the strongest places to put a subject. This is the rule of thirds, and it works because the human eye is more interested in asymmetry than symmetry. Beginners center every subject; the rule of thirds, applied once, is the fastest way to make beginner photographs look intentional. Later, photographers break the rule on purpose — a dead-center face at an Irving Penn formality, a subject pushed all the way to the edge for a sense of unease. The rule is a starting place, not a law.' },
        { type: 'h2', text: 'Leading lines and the eye\'s path' },
        { type: 'p', text: 'The eye follows lines into a picture. A road receding, a railing, a stripe on a wall, the edge of a shadow — any line that runs from near to far pulls the viewer\'s eye through the frame toward the subject. Photojournalists use leading lines because they place the subject in a world; portrait photographers use them because they add depth to an otherwise flat face. A single diagonal line can change an ordinary scene into a photograph.' },
        { type: 'h2', text: 'Negative space' },
        { type: 'p', text: 'The space around the subject is not empty; it is part of the subject. A small figure in a large white sky is a different picture than the same figure cropped tight. Japanese woodblock printers called this principle ma — the meaningful pause between objects — and photographers who studied Hiroshige and Hokusai in the nineteenth century brought it into the medium. Negative space is a compositional tool as powerful as any line or thirds-intersection. It gives the subject room to breathe.' },
        { type: 'h2', text: 'The decisive moment' },
        { type: 'p', text: 'Cartier-Bresson coined the phrase in the title of his 1952 book: the decisive moment is the instant when the geometry of a scene and the significance of its subject coincide. A puddle with a man leaping over it, a child running past a torn poster, a cyclist turning a corner at the precise instant the shadow of a railing falls across his face. The photograph cannot be made a second earlier or a second later. The photographer\'s job is to stand in the right place long enough to see it coming.' },
        { type: 'quote', text: 'To me, photography is the simultaneous recognition, in a fraction of a second, of the significance of an event as well as of a precise organization of forms which give that event its proper expression.', cite: 'Henri Cartier-Bresson, The Decisive Moment (1952)' },
      ],

      keyTerms: ['rule of thirds', 'leading lines', 'negative space', 'frame within a frame', 'golden ratio', 'decisive moment', 'aspect ratio', 'foreground-midground-background', 'figure-ground', 'ma'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@SeanTucker',
            title: 'Sean Tucker — quiet essays on composition and seeing',
            channel: 'Sean Tucker',
            duration: 'variable',
            featured: true,
            why: 'Sean Tucker\'s channel sounds like a photography monograph read aloud. The finest video essays on composition and photographic seeing being made today.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheArtofPhotography',
            title: 'The Art of Photography — Ted Forbes on composition',
            channel: 'The Art of Photography',
            duration: 'variable',
            featured: true,
            why: 'Ted Forbes has been publishing a free photography show since 2009. His historical-composition episodes — on Kertész, Evans, Winogrand — are the best free college course on the medium.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@mangoStreet',
            title: 'Mango Street — composition tricks in under five minutes',
            channel: 'Mango Street',
            duration: 'variable',
            featured: true,
            why: 'Rachel Gulotta and Daniel Inskeep distill one compositional idea into one quick visual tutorial. High-density instruction without filler.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheSlantedLens',
            title: 'The Slanted Lens — composition for commercial photography',
            channel: 'The Slanted Lens',
            duration: 'variable',
            featured: false,
            why: 'Jay P. Morgan teaches composition from inside a working studio. Client briefs, storyboards, and how to compose for a paid assignment.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@ThomasHeatonPhoto',
            title: 'Thomas Heaton — composition in the field',
            channel: 'Thomas Heaton',
            duration: 'variable',
            featured: false,
            why: 'Landscape photographer filmed while he works. Watch him walk the same hillside three times looking for the frame. The most honest composition practice on YouTube.',
          },
        ],
        books: [
          {
            title: 'The Decisive Moment (Images à la sauvette)',
            author: 'Henri Cartier-Bresson',
            year: 1952,
            url: 'https://www.worldcat.org/title/decisive-moment-photography-by-henri-cartier-bresson/oclc/7272419',
            why: 'The founding book of modern photographic composition. Every photograph in it is a lesson. Long out of print, reissued by Steidl in 2014.',
          },
          {
            title: 'The Photographer\'s Eye',
            author: 'John Szarkowski',
            year: 1966,
            url: 'https://www.moma.org/collection/works/146923',
            why: 'MoMA\'s definitive essay on how photographs are made and seen. Szarkowski\'s five compositional categories — the thing itself, the detail, the frame, time, vantage point — are still the framework curators use.',
          },
          {
            title: 'On Photography',
            author: 'Susan Sontag',
            year: 1977,
            url: 'https://archive.org/details/onphotography0000sont_m8j0',
            why: 'The great essays on what a photograph does in the world. Composition, Sontag argues, is always moral as well as visual.',
          },
          {
            title: 'The Photographer\'s Eye: Composition and Design for Better Digital Photos',
            author: 'Michael Freeman',
            year: 2007,
            url: 'https://www.worldcat.org/title/photographers-eye-composition-and-design-for-better-digital-photos/oclc/144330168',
            why: 'The best modern textbook on composition. Organized like a design-school course, with annotated images on every page.',
          },
          {
            title: 'Looking at Photographs',
            author: 'John Szarkowski',
            year: 1973,
            url: 'https://www.moma.org/collection/works/134918',
            why: 'One hundred photographs from MoMA\'s collection, each with a short Szarkowski essay. The shortest and best crash course in reading a photograph.',
          },
        ],
        articles: [
          {
            title: 'Composition (visual arts)',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Composition_(visual_arts)',
            why: 'Broad survey of compositional principles — rule of thirds, golden ratio, leading lines — across painting and photography.',
            year: null,
          },
          {
            title: 'Henri Cartier-Bresson',
            source: 'The Metropolitan Museum of Art, Heilbrunn Timeline',
            url: 'https://www.metmuseum.org/toah/hd/cabr/hd_cabr.htm',
            why: 'The Met\'s curatorial essay on Cartier-Bresson\'s work and the decisive-moment idea. Better than Wikipedia for a first reading.',
          },
          {
            title: 'Rule of thirds',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Rule_of_thirds',
            why: 'History of the rule, traced to John Thomas Smith\'s 1797 essay Remarks on Rural Scenery. Older than photography itself.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Seeing Through Photographs',
            provider: 'Coursera / Museum of Modern Art',
            url: 'https://www.coursera.org/learn/photography',
            free: true,
            why: 'MoMA\'s free course with Sarah Meister, the museum\'s former photography curator. The single best free education in looking at photographs online.',
          },
          {
            title: 'Photography Basics and Beyond (composition module)',
            provider: 'Coursera / Michigan State University',
            url: 'https://www.coursera.org/specializations/photography-basics',
            free: true,
            why: 'Peter Glendinning\'s Michigan State specialization. The composition module is sixty percent of how a first-year photography student learns to see.',
          },
        ],
        tools: [
          {
            title: 'Magnum Photos archive',
            url: 'https://www.magnumphotos.com/photographers/',
            why: 'Seventy-five years of photographs by the cooperative Cartier-Bresson co-founded. The most concentrated archive of great compositional work on the internet.',
          },
        ],
        primarySources: [
          {
            title: 'Henri Cartier-Bresson at the Magnum Photos archive',
            url: 'https://www.magnumphotos.com/photographer/henri-cartier-bresson/',
            why: 'The photographer\'s canonical archive. Browse by decade and watch the decisive-moment principle at work frame by frame.',
          },
        ],
      },

      seeAlso: ['exposure', 'light', 'drawing', 'composition'],
      prereqs: ['exposure'],
      leadsTo: ['light'],

      chapterActivity: 'A printed-photograph swap at the Howl! Happening gallery on the Lower East Side — everyone brings three of their recent frames, four by six inches, and the room reshuffles them into a silent critique.',

      sources: [
        'https://en.wikipedia.org/wiki/Composition_(visual_arts)',
        'https://en.wikipedia.org/wiki/Rule_of_thirds',
        'https://www.metmuseum.org/toah/hd/cabr/hd_cabr.htm',
      ],
      verifiedAt: '2026-04-23',
    },

    light: {
      id: 'light',
      name: 'Light',
      level: 'Intermediate',
      dek: 'Quality, direction, color — the material photography is actually made of.',
      readTime: '12 min',

      sections: ['Quality: hard, soft, the size of the source', 'Direction: where the shadow falls', 'Color: the temperature of white', 'The golden and blue hours', 'Learning to see light'],
      body: [
        { type: 'lead', text: 'In 1943, a nineteen-year-old American named Saul Leiter moved to New York and began photographing from inside the glass of coffee shops, through rain and through steam, in available light. His pictures, rediscovered in the 1990s, taught a generation of street photographers something every painter has always known: the subject of a photograph is not the thing photographed but the light that lands on it. Change the light and the same corner is a different picture.' },
        { type: 'h2', text: 'Quality: hard, soft, the size of the source' },
        { type: 'p', text: 'The quality of light is set almost entirely by the apparent size of its source. A bare bulb across a room is a small source and throws hard, sharp-edged shadows. The same bulb bounced into a three-foot softbox is a large source and wraps its light gently around the subject. The sun, ninety-three million miles away, is a hard source on a clear day at noon; push an overcast cloud between the sun and the subject and that same sun becomes a softbox the size of the sky. This one principle — source size relative to subject — underlies everything a lighting technician does.' },
        { type: 'h2', text: 'Direction: where the shadow falls' },
        { type: 'p', text: 'Front light flattens. Side light sculpts. Back light silhouettes. The direction of light relative to the subject determines what the photograph is about as much as any other decision. Rembrandt lighting — the triangle of light under the eye on the shadow side of a portrait — is named for the Dutch master who understood, four centuries before photography, that a forty-five-degree angle high and to one side of the face is the flattering human light. Every studio portrait since is a variation on that observation.' },
        { type: 'h2', text: 'Color: the temperature of white' },
        { type: 'p', text: 'White is not a color but a negotiation. Daylight at noon is around 5500 Kelvin — cool, with a blue cast. A tungsten bulb is around 3200 Kelvin — warm, with an orange cast. A candle is 1800 Kelvin — nearly red. The human eye adapts and reads them all as white; a camera does not. The white-balance setting on a camera tells the sensor what temperature to call white. Modern cameras set it automatically; a photographer who cares sets it by hand, or shoots RAW and decides later. The cinematographer Roger Deakins has said that the single greatest advance in digital cameras is the ability to choose your white balance in post.' },
        { type: 'h2', text: 'The golden and blue hours' },
        { type: 'p', text: 'The hour after sunrise and the hour before sunset — the golden hour — gives photographers long shadows, warm color, and a low sun that sidelights everything. The hour before sunrise and after sunset — the blue hour — gives an even, cool, twilight glow. Both are brief and both are famous in the craft for good reason. A street scene photographed at noon and at seven p.m. is two different pictures. The difference is not the subject. The difference is the light.' },
        { type: 'h2', text: 'Learning to see light' },
        { type: 'p', text: 'The single discipline a beginning photographer should cultivate is noticing light. Sit on a bench for twenty minutes with no camera and watch a sunlit wall. See where the shadows fall. See how the color shifts as a cloud crosses the sun. The skill that separates working photographers from everyone else is not knowing their gear; it is a trained attention to the moment-by-moment behavior of available light. Every great photographer, asked what they do, describes some version of the same answer. They wait. They watch. They are in the right place when the light is right.' },
        { type: 'callout', text: 'The inverse square law — light falls off with the square of distance — is the single most useful physics a photographer knows. Move a light twice as far from the subject and it becomes a quarter as bright. This is why a window is a beautiful portrait light: the subject standing near it is far brighter than the background behind them.' },
      ],

      keyTerms: ['hard light', 'soft light', 'key light', 'fill light', 'rim light', 'color temperature', 'white balance', 'Kelvin', 'golden hour', 'inverse square law', 'Rembrandt lighting'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@TheSlantedLens',
            title: 'The Slanted Lens — Jay P. Morgan\'s lighting tutorials',
            channel: 'The Slanted Lens',
            duration: 'variable',
            featured: true,
            why: 'Jay P. Morgan is a commercial lighting veteran; his free tutorials are the single most generous lighting curriculum online. Start with his "five-minute portrait" series.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@karltaylor',
            title: 'Karl Taylor — studio lighting fundamentals',
            channel: 'Karl Taylor',
            duration: 'variable',
            featured: true,
            why: 'Karl Taylor\'s Visual Education channel — now the best free lighting-school archive on YouTube. His discussions of softbox size and distance are essential.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@SeanTucker',
            title: 'Sean Tucker — essays on natural light',
            channel: 'Sean Tucker',
            duration: 'variable',
            featured: true,
            why: 'Tucker\'s videos on window light, golden hour, and rainy-day color are the finest available-light essays on the internet.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@profotoglobal',
            title: 'Profoto — lighting behind the image',
            channel: 'Profoto',
            duration: 'variable',
            featured: false,
            why: 'The Swedish strobe-manufacturer\'s educational channel. Behind-the-scenes on real commercial shoots with big-name photographers — Joey L, Annie Leibovitz, Gregory Heisler.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@BandH',
            title: 'B&H Photo Video — lighting seminars with working photographers',
            channel: 'B&H Photo Video',
            duration: 'variable',
            featured: false,
            why: 'Hour-long free seminars from the Event Space era of B&H. Joe McNally, David Hobby, Gregory Heisler — all free on the store\'s channel.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@strobist',
            title: 'Strobist — David Hobby\'s small-flash blog archive',
            channel: 'Strobist',
            duration: 'variable',
            featured: false,
            why: 'David Hobby invented the modern small-flash movement with his Strobist blog in 2006. His free Lighting 101 course is the other half of a working photographer\'s education.',
          },
        ],
        books: [
          {
            title: 'The Print',
            author: 'Ansel Adams',
            year: 1983,
            url: 'https://www.worldcat.org/title/print/oclc/9393927',
            why: 'Book three of Adams\'s technical trilogy. Adams understood light as physics and music simultaneously; nothing in the printing literature has surpassed him.',
          },
          {
            title: 'Light — Science and Magic',
            author: 'Fil Hunter, Steven Biver, Paul Fuqua',
            year: 1990,
            url: 'https://www.taylorfrancis.com/books/mono/10.4324/9780367822248/light-science-magic-fil-hunter-steven-biver-paul-fuqua',
            why: 'The reference used in every photography school in the country. A theory-first treatment that explains why lighting setups work, not just how to copy them.',
          },
          {
            title: 'Photographing Shadow and Light',
            author: 'Tim Wallace',
            year: 2011,
            url: 'https://www.worldcat.org/title/photographing-shadow-and-light-inside-the-dramatic-lighting-techniques-and-creative-vision-of-portrait-photographer-tim-wallace/oclc/701027541',
            why: 'Commercial portrait photographer Tim Wallace walks through twenty-five real jobs. Modern lighting thinking applied to paying clients.',
          },
          {
            title: 'Annie Leibovitz at Work',
            author: 'Annie Leibovitz',
            year: 2008,
            url: 'https://www.penguinrandomhouse.com/books/105213/annie-leibovitz-at-work-by-annie-leibovitz/',
            why: 'The notes of the most influential magazine photographer of the late twentieth century. Her assignments are the portfolio; her lighting language is the lesson.',
          },
          {
            title: 'Saul Leiter: Early Color',
            author: 'Saul Leiter, edited by Martin Harrison',
            year: 2006,
            url: 'https://www.steidl.de/Books/Early-Color-1729292921.html',
            why: 'Leiter\'s 1950s New York color work was ignored for forty years and then revolutionized photography in the 2000s. Study it for what light can do to a rainy street.',
          },
        ],
        articles: [
          {
            title: 'Color temperature',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Color_temperature',
            why: 'The physics of Kelvin, the Planckian locus, and why daylight is bluer than a lamp. The reference article for white balance.',
            year: null,
          },
          {
            title: 'Inverse-square law',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Inverse-square_law',
            why: 'The one piece of physics every portrait photographer uses without thinking. Intensity falls off with the square of distance.',
            year: null,
          },
          {
            title: 'Three-point lighting',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Three-point_lighting',
            why: 'Key, fill, rim — the foundation of all studio and film lighting, briefly and correctly explained.',
            year: null,
          },
          {
            title: 'Saul Leiter',
            source: 'The Metropolitan Museum of Art',
            url: 'https://www.metmuseum.org/art/collection/search/283168',
            why: 'The Met\'s Leiter holdings and a short curatorial essay. A first encounter with a photographer whose subject was always light itself.',
          },
        ],
        courses: [
          {
            title: 'Lighting 101',
            provider: 'Strobist (David Hobby)',
            url: 'https://strobist.blogspot.com/2006/03/lighting-101.html',
            free: true,
            why: 'The original free off-camera-flash curriculum. Two decades later, still the best introduction to small-flash lighting ever written.',
          },
          {
            title: 'Photography Basics and Beyond',
            provider: 'Coursera / Michigan State University',
            url: 'https://www.coursera.org/specializations/photography-basics',
            free: true,
            why: 'The lighting modules are paced and technical without losing the craft side.',
          },
        ],
        tools: [
          {
            title: 'PhotoPills (golden-hour and sun-position calculator)',
            url: 'https://www.photopills.com/',
            why: 'Tells you where the sun will be and what time the golden hour hits. The standard planning tool for outdoor photographers.',
          },
          {
            title: 'SunCalc',
            url: 'https://www.suncalc.org/',
            why: 'Free browser tool for sun-path, azimuth, and shadow length on any date at any address. Useful before any shoot dependent on daylight.',
          },
        ],
        primarySources: [
          {
            title: 'Saul Leiter Foundation',
            url: 'https://saulleiterfoundation.org/',
            why: 'The painter-photographer\'s archive, maintained by his estate. Slow color images that still teach better than any textbook can.',
          },
        ],
      },

      seeAlso: ['exposure', 'composition_photo', 'color'],
      prereqs: ['exposure'],
      leadsTo: [],

      chapterActivity: 'A winter evening "chasing the blue hour" walk along the West Side piers — everyone meets at the 23rd Street ferry landing twenty minutes before sunset and shoots until full dark.',

      sources: [
        'https://en.wikipedia.org/wiki/Color_temperature',
        'https://en.wikipedia.org/wiki/Inverse-square_law',
        'https://en.wikipedia.org/wiki/Three-point_lighting',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
