// content/politics.js
// Owned by batch: B05-social-world
// Last updated: 2026-04-23 by BATCH B05-social-world
//
// Topics this subject must cover (from data.js):
//   Core: governments, constitutions, ir

window.CONTENT = window.CONTENT || {};
window.CONTENT.politics = {
  subjectId: 'politics',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B05-social-world',
  topics: {

    // ——— GOVERNMENTS ———
    governments: {
      id: 'governments',
      name: 'Forms of Government',
      level: 'Beginner',
      dek: 'The same problem solved in a dozen different ways, from Athenian assembly to modern parliamentary democracy.',
      readTime: '17 min',

      sections: ['Aristotle\'s six regimes', 'The democratic family', 'Autocracies, ancient and new', 'The hybrid middle', 'Federalism and its cousins', 'Why the form matters'],
      body: [
        { type: 'lead', text: 'Around 350 BCE, in a grove outside Athens, Aristotle gave his students a handout. There were six kinds of government, he said, and they came in pairs: rule by one, by a few, or by many, each in a healthy and a corrupted form. Monarchy and tyranny, aristocracy and oligarchy, polity and democracy. The scheme was not complete, and Aristotle knew it was not. It is still, two millennia later, the place any course on comparative politics begins.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aristotle_Altemps_Inv8575.jpg?width=900', caption: 'A Roman copy of a Greek bronze bust of Aristotle (384–322 BCE), Palazzo Altemps, Rome. His Politics catalogued 158 Greek constitutions and classified them by who ruled.', credit: 'Jastrow, public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'The modern democratic family' },
        { type: 'p', text: 'Most of what we call democracy today is representative rather than direct. Citizens elect officials who legislate on their behalf, and the institutions that constrain those officials — courts, free press, independent bureaucracies, civil society — do more of the work than the ballot. Within this family there are substantial differences. A parliamentary system, like the United Kingdom\'s, fuses the executive and the legislature. A presidential system, like the United States\', separates them. A semi-presidential system, like France\'s Fifth Republic, does some of both. Each has characteristic strengths and pathologies.' },
        { type: 'p', text: 'Juan Linz\'s 1990 essay "The Perils of Presidentialism" argued that presidential systems are more prone to breakdown than parliamentary ones, because an elected president and an elected legislature can both claim democratic legitimacy when they disagree. The empirical record — Latin America through the twentieth century, parts of Africa after 1990 — has been kind to his argument. The American case, where the system has held for 235 years, is the interesting outlier.' },
        { type: 'h2', text: 'Autocracy, old and new' },
        { type: 'p', text: 'An autocracy concentrates political power in one person or one small group. Pre-modern monarchies relied on dynastic legitimacy; modern authoritarian regimes lean on some mix of nationalism, economic performance, repression, and managed elections. Political scientists — Steven Levitsky and Lucan Way, among others — now classify many twenty-first-century regimes as "competitive authoritarian": elections happen, but the playing field is so unequal that the outcome is rarely in doubt. Russia under Putin, Hungary under Orbán, Turkey under Erdoğan, and Venezuela under Chávez and Maduro have all been assigned to this category at some point in the last two decades.' },
        { type: 'h2', text: 'The hybrid middle' },
        { type: 'p', text: 'Pure democracies and pure autocracies are the extremes of a spectrum; most governments live somewhere between. Theocracies mix religious and political authority (Iran); constitutional monarchies keep a royal head of state while devolving power to an elected parliament (Japan, Sweden, Spain, the United Kingdom); one-party states combine meritocratic bureaucracy with tight political control (China, Vietnam, Singapore); military juntas hold power with a civilian face (several in West Africa in the 2020s). The classification schemes — Freedom House, Polity, V-Dem, the Economist Intelligence Unit — each draw the lines differently and argue with each other about where specific countries sit.' },
        { type: 'h2', text: 'Federalism, confederation, unitary' },
        { type: 'p', text: 'Cutting across the democracy/autocracy axis is a separate question: how is power divided vertically? A federal system (the United States, Germany, India, Australia) constitutionally reserves powers for subnational units. A unitary system (France, Japan, most African states) concentrates them in the center, even where it devolves administratively. A confederation (the historical United States under the Articles of Confederation, or the modern European Union on some readings) gives more power to the parts than to the whole. Which a country has shapes everything from tax policy to how quickly a pandemic response can be mounted.' },
        { type: 'h2', text: 'Why the form matters' },
        { type: 'p', text: 'Amartya Sen observed in 1999 that no functioning democracy has ever suffered a serious famine. The claim oversimplifies, but it points at something real: the form of government shapes which information reaches decision-makers, which decisions are reversible, and whose interests get protected in a crunch. A regime is not an ornament. It is the software on which everything else runs.' },
        { type: 'p', text: 'The late-twentieth-century story was that democracy was slowly winning. Larry Diamond, Samuel Huntington, and others called it "the third wave." The 2010s and 2020s have complicated the story. V-Dem\'s annual Democracy Report records a decade-long decline in the average level of liberal democracy worldwide. Whether this is a durable reversal or a temporary pause is one of the live questions of contemporary political science.' },
        { type: 'quote', text: 'Democracy is the worst form of government, except for all those other forms that have been tried from time to time.', cite: 'Winston Churchill, House of Commons, 11 November 1947' },
        { type: 'callout', text: 'The United Nations has 193 member states. Freedom House rates about 83 of them "free" in its 2024 report, 56 "partly free," and 54 "not free." The share of the world\'s population living in "free" countries has fallen below 20% for the first time in the survey\'s half-century.' },

        { type: 'h2', text: 'Learn it: diagnosing a real regime' },
        { type: 'p', text: 'Pick an unfamiliar country — Senegal, say, or Moldova. Work through Levitsky and Way\'s four diagnostic questions in order. (1) Are national elections free and fair in the sense that the outcome is not a foregone conclusion? (2) Do opposition parties have meaningful access to media, to state resources, and to public spaces? (3) Is the judiciary independent enough to strike down executive overreach when it occurs? (4) Can civil society — journalists, unions, NGOs — operate without fear of state retaliation? Four yeses means liberal democracy. Four noes means consolidated authoritarianism. Any mixed pattern puts the regime in the "hybrid" middle, where most of the world\'s population now lives.' },
        { type: 'p', text: 'Run the exercise on the United States in 1855 (answer: electoral democracy for white men, authoritarian in the South for Black residents; hybrid). Run it on Singapore today (dominant party, reasonably free elections, limited press freedom, independent judiciary in commercial matters). Run it on China (single-party state, no national contested elections, but substantial local experimentation and meritocratic bureaucracy). The point of the four questions is not to produce a label but to notice which features of a regime are present and which are not — so that any subsequent conversation is about specific mechanisms, not about slogans.' },

        { type: 'h2', text: 'Worked example: reading Federalist 10' },
        { type: 'p', text: 'Madison\'s Federalist 10 (1787) is the single most important 3,000 words in American political thought. The argument has four steps, and you can reconstruct them cold. Step 1: the greatest threat to popular government is "faction" — a group united by interest adverse to the common good. Step 2: faction has two cures — remove its causes (impossible without destroying liberty) or control its effects. Step 3: control of effects works better in a large republic than a small one, because a large territory contains more competing factions and no single one can dominate. Step 4: representation ("filter") purifies the popular will through elected representatives. Every criticism and defense of the American system since has been an argument with one of those four steps.' },
        { type: 'p', text: 'Now practice the method: pick another Federalist (51 on checks and balances, 78 on the judiciary) and try to state its argument in four steps without looking. When you can do that for all three, you have read the constitutional founding.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. Country X has a parliamentary system with proportional representation, a ceremonial monarch, and a single-chamber legislature. Country Y has a presidential system with first-past-the-post districts, a written constitution with an entrenched bill of rights, and a bicameral legislature. Which system is more likely to produce gridlock between the executive and the legislature, and why? Which is more likely to produce frequent changes of government?' },
        { type: 'p', text: 'Answer: Y (presidential, separate elections for executive and legislature) is more likely to produce gridlock, because both branches can claim a democratic mandate and neither can force the other to act. X (parliamentary) is more likely to produce changes of government, because the prime minister falls whenever the coalition breaks. Linz (1990) is the classic argument; the empirical pattern holds.' },
        { type: 'p', text: 'Problem 2. Use the Freedom House 2024 map. Pick two countries with similar GDP per capita but very different Freedom House scores (e.g., Singapore and Costa Rica, or Saudi Arabia and Chile). What does this pairing tell you about the relationship between wealth and democracy? What is the name of the thesis — Seymour Martin Lipset\'s — that predicts wealth causes democracy, and what are the main empirical challenges to it?' },
        { type: 'p', text: 'Answer: Lipset\'s "modernization thesis" (1959) argued that economic development leads to democratization. Cases like Singapore and Saudi Arabia show rich autocracies persist; cases like India and Costa Rica show poor democracies work. The current empirical view (Przeworski and others) is that wealth helps *sustain* existing democracies but does not reliably *cause* transitions. It is useful for any political conversation to know both what Lipset claimed and what the revised view says.' },
        { type: 'p', text: 'Problem 3. A hybrid regime holds national elections that the incumbent party always wins with 55–65% of the vote. Independent observers report no fraud on election day, but state media gives the opposition little coverage, the judiciary declines to hear opposition complaints, and large public-sector employers circulate "guidance" about voting. Using Levitsky and Way\'s term, what is this regime? What is the single most important variable for predicting whether it will liberalize or consolidate into authoritarianism?' },
        { type: 'p', text: 'Answer: Competitive authoritarianism. Levitsky and Way\'s 2010 book argues the single most important variable is "linkage" to Western democracies (trade, education, diaspora, institutional ties). High-linkage regimes tend to liberalize; low-linkage ones tend to consolidate. Hungary and Serbia are high-linkage cases (both inside the EU\'s orbit); Belarus and Zimbabwe are low-linkage. The predicted outcomes have largely held since 2010.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What are Aristotle\'s six regime types? (2) Why did Juan Linz argue presidential systems break down more often? (3) Name three non-electoral features a liberal democracy requires. (4) What is "competitive authoritarianism," and name two current examples. (5) Draw the Levitsky-Ziblatt "democratic guardrails" — mutual toleration and institutional forbearance — and give a recent American example of each eroding. (6) What does Sen\'s famine claim assume, and what is one serious counter-example?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Watch Smith\'s first six Yale PLSC 114 lectures and read Federalist 10, 51, and 78. Then pick a country not your own and write a one-page diagnosis of its regime using Freedom House\'s checklist. When you can do that in an hour, you have the working vocabulary. Once you\'ve got the basics? Read How Democracies Die and Why Nations Fail, and follow Francis Fukuyama\'s Substack for one month — you will see the live arguments as they are made. To go further? Take a graduate comparative-politics field course (Shapiro, Mainwaring, Levitsky all teach public-accessible versions). The serious readers then read Tocqueville in French, Weber\'s Politics as a Vocation, and Huntington\'s Political Order in Changing Societies in order.' },
      ],

      keyTerms: ['democracy', 'autocracy', 'parliamentary system', 'presidential system', 'semi-presidential system', 'separation of powers', 'federalism', 'unitary state', 'legitimacy', 'competitive authoritarianism', 'theocracy', 'constitutional monarchy'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@crashcourse/playlists',
            title: 'Crash Course U.S. Government & Politics',
            channel: 'Crash Course',
            duration: '50 episodes',
            why: 'Craig Benzine\'s full high-school-and-up course on the U.S. system, framed in comparison with others.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://oyc.yale.edu/political-science/plsc-114',
            title: 'Introduction to Political Philosophy (Yale PLSC 114)',
            channel: 'Yale Open Courses',
            duration: '24 lectures',
            why: 'Steven B. Smith\'s full Yale course on Plato, Aristotle, Hobbes, Locke, Rousseau, Tocqueville. The best free undergraduate introduction to the tradition.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://oyc.yale.edu/political-science/plsc-118',
            title: 'The Moral Foundations of Politics (Yale PLSC 118)',
            channel: 'Yale Open Courses',
            duration: '26 lectures',
            why: 'Ian Shapiro\'s companion course on utilitarianism, Marxism, social contract, and democratic theory. Pairs directly with Smith\'s.',
          },
          {
            id: 'fNjsPjqzl3k',
            source: 'youtube',
            url: 'https://www.youtube.com/watch?v=fNjsPjqzl3k',
            title: 'The People vs. Democracy',
            channel: 'Talks at Google',
            duration: '56:48',
            why: 'Johns Hopkins political scientist Yascha Mounk presenting his 2018 book on how liberal democracies erode. Careful, comparative, non-partisan.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — comparative politics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Lectures by Larry Diamond, Francis Fukuyama, Steven Levitsky, Anne Applebaum, and many others. The live argument, in real time.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardUniversity',
            title: 'Harvard — political science & Kennedy School',
            channel: 'Harvard University',
            duration: 'variable',
            why: 'Harvard\'s public lectures by Daniel Ziblatt, Ryan Enos, and Kennedy School visitors on American democracy and comparative regimes.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/larry_diamond_why_democracies_in_the_west_are_struggling',
            title: 'Larry Diamond — on democratic recession (see TED.com)',
            channel: 'TED',
            duration: 'variable',
            why: 'Diamond coined "democratic recession"; his talks and lectures are the central framing of the post-2010 backsliding debate.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/francis_fukuyama_on_political_order_and_decay',
            title: 'Francis Fukuyama on Political Order (recorded lecture)',
            channel: 'TED / Stanford',
            duration: 'variable',
            why: 'Fukuyama in his own voice on the long-run argument of Political Order and Political Decay — state capacity, rule of law, accountability.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@CarnegieEndowment',
            title: 'Carnegie Endowment — public events',
            channel: 'Carnegie Endowment for International Peace',
            duration: 'variable',
            why: 'Think-tank lectures on current regime dynamics — particularly strong on Russia, China, and Middle Eastern politics.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/steven_pinker_is_the_world_getting_better_or_worse_a_look_at_the_numbers',
            title: 'Is the world getting better or worse? A look at the numbers',
            channel: 'TED2018',
            duration: '18:18',
            why: 'Pinker on long-run trends in violence, prosperity, and (by implication) the correlation with democratic governance. Disputed; worth the argument.',
          },
        ],
        books: [
          {
            title: 'Politics',
            author: 'Aristotle',
            year: -350,
            url: 'https://www.gutenberg.org/ebooks/6762',
            why: 'The founding text of the field. Books III and IV contain the typology of regimes that still anchors every introductory course.',
          },
          {
            title: 'Leviathan',
            author: 'Thomas Hobbes',
            year: 1651,
            url: 'https://www.gutenberg.org/ebooks/3207',
            why: 'The founding text of modern sovereignty. Chapters 13–17 contain the state-of-nature argument; read those before anything else.',
          },
          {
            title: 'Second Treatise of Government',
            author: 'John Locke',
            year: 1689,
            url: 'https://www.gutenberg.org/ebooks/7370',
            why: 'The counter-statement to Hobbes, and the most direct ancestor of modern liberal-democratic thought.',
          },
          {
            title: 'The Social Contract',
            author: 'Jean-Jacques Rousseau',
            year: 1762,
            url: 'https://www.gutenberg.org/ebooks/46333',
            why: 'Rousseau\'s short, radical answer to Hobbes and Locke. The source of "general will," and of most modern trouble about majority tyranny.',
          },
          {
            title: 'Democracy in America',
            author: 'Alexis de Tocqueville',
            year: 1835,
            url: 'https://www.gutenberg.org/ebooks/815',
            why: 'The best book ever written about American democracy, by a French aristocrat visiting in 1831. Volume I covers the institutional machinery; volume II, the social habits. Both are still current.',
          },
          {
            title: 'How Democracies Die',
            author: 'Steven Levitsky and Daniel Ziblatt',
            year: 2018,
            url: '',
            why: 'Two Harvard political scientists on how regimes erode from within. Drawn from comparative data on twentieth-century breakdowns; written for a general reader.',
          },
          {
            title: 'Political Order and Political Decay',
            author: 'Francis Fukuyama',
            year: 2014,
            url: '',
            why: 'The long-run companion to The Origins of Political Order. Fukuyama\'s three-leg stool — state, rule of law, accountability — is still the cleanest frame for comparative regime analysis.',
          },
          {
            title: 'Why Nations Fail',
            author: 'Daron Acemoglu and James A. Robinson',
            year: 2012,
            url: '',
            why: 'The "inclusive vs. extractive institutions" argument. Acemoglu won the 2024 Nobel in part for this work.',
          },
        ],
        articles: [
          {
            title: 'Democracy',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/democracy/',
            why: 'Tom Christiano\'s long survey of democratic theory — aggregative, deliberative, epistemic — updated in 2024.',
            year: 2024,
          },
          {
            title: 'Hobbes\'s Moral and Political Philosophy',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/hobbes-moral/',
            why: 'The best companion for reading Leviathan. Frames Hobbes against the modern social-contract tradition.',
            year: null,
          },
          {
            title: 'John Locke',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/locke/',
            why: 'The scholarly companion to Locke\'s political thought. Revised 2022.',
            year: 2022,
          },
          {
            title: 'Government',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Forms_of_government',
            why: 'Comprehensive overview of the main classification systems with maps and a good bibliography.',
            year: null,
          },
          {
            title: 'Freedom House — Freedom in the World',
            source: 'Freedom House',
            url: 'https://freedomhouse.org/report/freedom-world',
            why: 'The authoritative annual ranking of political and civil liberties. Data going back to 1972; interactive map.',
            year: null,
          },
          {
            title: 'V-Dem — Democracy Report',
            source: 'Varieties of Democracy Institute, University of Gothenburg',
            url: 'https://v-dem.net/',
            why: 'The most granular public dataset on regime characteristics worldwide. Annual report plus interactive data dashboards.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Introduction to Political Philosophy (PLSC 114)',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science/plsc-114',
            free: true,
            why: 'Steven Smith\'s twenty-four lectures with full transcripts and reading list.',
          },
          {
            title: 'The Moral Foundations of Politics (PLSC 118)',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science/plsc-118',
            free: true,
            why: 'Ian Shapiro\'s companion Yale course on utilitarianism, Marxism, and the democratic tradition.',
          },
        ],
        podcasts: [
          {
            title: 'Talking Politics — History of Ideas',
            show: 'Talking Politics (CUP)',
            url: 'https://www.talkingpoliticspodcast.com/history-of-ideas',
            duration: '≈50:00 per episode',
            why: 'David Runciman\'s solo series: twelve lectures on twelve great political thinkers. The best short audio introduction in English.',
          },
          {
            title: 'The Ezra Klein Show',
            show: 'The New York Times',
            url: 'https://www.nytimes.com/column/ezra-klein-podcast',
            duration: '≈75:00 per episode',
            why: 'Long interviews with political scientists and theorists. The episodes with Francis Fukuyama, Larry Diamond, and Steven Levitsky are directly relevant.',
          },
          {
            title: 'Democracy in Danger',
            show: 'University of Virginia / Miller Center',
            url: 'https://democracyindanger.as.virginia.edu/',
            duration: '≈45:00 per episode',
            why: 'Two UVA historians on American democratic institutions and their current stresses. Well-sourced, measured.',
          },
        ],
        tools: [
          {
            title: 'Our World in Data — Democracy',
            url: 'https://ourworldindata.org/democracy',
            why: 'Clean, sourced long-run charts of democratic indicators worldwide. Every figure downloadable.',
          },
          {
            title: 'V-Dem Dataset',
            url: 'https://v-dem.net/data/the-v-dem-dataset/',
            why: 'The Varieties of Democracy Institute\'s full dataset, free for download. The empirical foundation of most current comparative-politics research.',
          },
        ],
      },

      seeAlso: ['constitutions', 'ir', 'institutions', 'history', 'geopolitics'],
      prereqs: [],
      leadsTo: ['constitutions', 'ir'],

      chapterActivity: 'A once-a-session "form of government" trivia night — each attendee draws a country at random, has five minutes to explain how it is governed, from memory, before the group fact-checks. Once a quarter, a field trip to the United Nations headquarters on First Avenue, or an afternoon at the Roosevelt House on East 65th Street.',

      sources: [
        'https://plato.stanford.edu/entries/democracy/',
        'https://plato.stanford.edu/entries/hobbes-moral/',
        'https://plato.stanford.edu/entries/locke/',
        'https://en.wikipedia.org/wiki/Forms_of_government',
        'https://freedomhouse.org/report/freedom-world',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— CONSTITUTIONS ———
    constitutions: {
      id: 'constitutions',
      name: 'Constitutions',
      level: 'Intermediate',
      dek: 'The rulebook — the document or practice that constrains the people who run the government.',
      readTime: '18 min',

      sections: ['Philadelphia, 1787', 'What a constitution is for', 'Written, unwritten, and mixed', 'Judicial review and its discontents', 'Amendment and its difficulty', 'When constitutions fail'],
      body: [
        { type: 'lead', text: 'In the summer of 1787, fifty-five men met in a sweltering room in Philadelphia with the windows nailed shut against eavesdroppers. They had come to fix the Articles of Confederation; by September they had written something else. The Constitution of the United States is four pages long, it is the oldest still in use, and it was the product of a bad-tempered compromise between people who disagreed almost as much as they agreed.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Scene_at_the_Signing_of_the_Constitution_of_the_United_States.jpg?width=1200', caption: 'Howard Chandler Christy\'s 1940 painting Scene at the Signing of the Constitution of the United States, hanging in the U.S. Capitol. Thirty-nine of the fifty-five Philadelphia delegates signed on 17 September 1787.', credit: 'Howard Chandler Christy, public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'What a constitution is for' },
        { type: 'p', text: 'A constitution does two jobs. It organizes the government — who does what, how power is shared, how officials are chosen — and it constrains the government, by putting some things off-limits even to a majority. The second job is harder. A bill of rights that can be suspended by a simple vote is not much of a constraint. Most modern constitutions make amendment deliberately difficult for this reason.' },
        { type: 'p', text: 'John Rawls, in A Theory of Justice (1971), argued that a well-designed constitution should be the kind of thing rational people would agree to behind a "veil of ignorance" about their own place in the resulting society. Whether you like his answer or not, the question he asked — what would fair rules look like if you did not know who you were going to be? — is the right one to hold in mind while reading any constitution.' },
        { type: 'h2', text: 'Written, unwritten, and mixed' },
        { type: 'p', text: 'The United States, India, Germany, and Japan have written constitutions in a single document. The United Kingdom, Israel, New Zealand, and San Marino have no single document and rely on a collection of statutes, court decisions, and unwritten conventions. A third group (Canada, South Africa) has a central written text plus a tradition of unwritten constitutional conventions alongside it. The interesting comparative question is not whether a constitution is written but whether it is actually followed: written paper tigers exist, and so do unwritten but durable restraints.' },
        { type: 'h2', text: 'Judicial review and its discontents' },
        { type: 'p', text: 'In 1803, in Marbury v. Madison, the U.S. Supreme Court claimed the power to strike down federal laws as unconstitutional. Nothing in the document itself says it may. Chief Justice John Marshall\'s reasoning was that the Constitution is law, that courts interpret law, and therefore courts must decide what the Constitution means when it conflicts with a statute. The argument is plausible but not inevitable; most other constitutional democracies have adopted some version of judicial review, but several (the United Kingdom, New Zealand, the Nordic countries in various ways) have deliberately stopped short of giving courts the power to strike down legislation.' },
        { type: 'p', text: 'The critique from the left of judicial review is that unelected judges overturn democratic majorities; the critique from the right is the same critique about different cases. Both are right more often than either wants to admit. Jeremy Waldron\'s 2006 article "The Core of the Case Against Judicial Review" is the cleanest statement of the democratic worry. Its defenders — including the German and South African constitutional courts in practice — argue that precisely the point of a constitution is to constrain majorities. The argument has no final answer and is not supposed to.' },
        { type: 'h2', text: 'Amendment' },
        { type: 'p', text: 'A constitution\'s amendment rule is, in some ways, its most important article. The United States has amended its constitution 27 times since 1789, 15 of those before 1870. The difficulty of amendment — two-thirds of both houses of Congress plus three-quarters of the states — is famously high. The Indian constitution, by contrast, has been amended over 100 times; the German Basic Law 60-plus times; some parts of the Australian constitution require a national referendum and have rarely passed. Comparative constitutional law asks whether an easier or a harder amendment rule is better, and the honest answer is "it depends on everything else."' },
        { type: 'h2', text: 'When constitutions fail' },
        { type: 'p', text: 'A constitution is a coordination device: it works only if the powerful people in a society agree to keep playing by it when the stakes are high. The 1936 Stalin Constitution of the USSR was a model of liberal protections on paper; it protected no one. Weimar Germany had one of the most carefully drafted constitutions of its day and collapsed in a decade. The lesson is that constitutional text is a necessary condition, not a sufficient one. What finally holds a constitution in place is a political culture of acceptance — and that culture, once lost, is very hard to rebuild.' },
        { type: 'callout', text: 'The United States Constitution, at about 7,600 words, is among the shortest national constitutions in active use. The Indian Constitution, with over 146,000 words, is the longest. Neither length predicts durability or democratic quality.' },

        { type: 'h2', text: 'Learn it: the three-step anatomy of any written constitution' },
        { type: 'p', text: 'Pick up any national constitution and answer three questions in order. (A) How is power organized? Find the articles on the executive, legislature, and judiciary; note how each is selected, how long it serves, and who can dismiss it. (B) What is entrenched against majority change? Find the amendment clause; find the bill of rights (or its absence); find any unamendable clauses ("eternity clauses" like Germany\'s Article 79(3) on human dignity). (C) Who resolves disputes about the document itself? Find the judicial-review mechanism, its personnel, and its selection. Do this for the U.S. Constitution, then for Germany\'s Basic Law, then for South Africa\'s 1996 constitution, and you will have the comparative-law toolkit in an afternoon.' },

        { type: 'h2', text: 'Worked example: Marbury, the move' },
        { type: 'p', text: 'Read Marshall\'s opinion in Marbury v. Madison (1803) with three questions in hand. First: what is the actual legal holding? (Answer: §13 of the Judiciary Act of 1789 is unconstitutional; the Court cannot issue the writ Marbury asked for.) Second: what does Marshall have to establish to reach that holding? (Answer: that the Constitution is law, that courts say what the law is, and therefore that courts can refuse to apply statutes that conflict with the Constitution.) Third: what does Marshall *not* say that a less-clever opinion might have? (Answer: he does not say the Court can order the president to do anything. The procedural defeat for Marbury is the price of the institutional victory for the Court.) This is the single most artfully constructed opinion in American legal history. Read it slowly.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. Country A\'s constitution can be amended by a simple parliamentary majority. Country B requires two-thirds of the legislature plus three-quarters of the sub-national units. Which constitution is more likely to function as an actual constraint on the government? What are the likely failure modes of each?' },
        { type: 'p', text: 'Answer: B is the stronger constraint — an amendment rule too easy to use makes the constitution effectively just a statute. But B can also ossify (the U.S. has not passed a substantive amendment since 1971, arguably 1791). Very-hard-to-amend constitutions can produce "judicial amendment" as courts reinterpret to cope with changed circumstances. Neither extreme is clearly better; the design question is context-dependent.' },
        { type: 'p', text: 'Problem 2. A president signs an executive order that clearly contradicts a statute passed by Congress. A district court rules the order unlawful. The president ignores the court\'s injunction and continues to enforce the order. What is the constitutional crisis, and what institutions are supposed to resolve it?' },
        { type: 'p', text: 'Answer: This is the classic "who will enforce the court\'s order" problem, famously raised by Andrew Jackson ("John Marshall has made his decision; now let him enforce it"). The formal answer is Congress (impeachment) and ultimately the electorate. The deeper answer, from Levitsky and Ziblatt, is that constitutional democracy runs on norms of compliance that no document can self-enforce. This is why the question is a recurring one.' },
        { type: 'p', text: 'Problem 3. Germany\'s Basic Law has an "eternity clause" (Article 79(3)) protecting human dignity and the federal structure from any amendment. The U.S. Constitution has only one entrenched clause — the guarantee of equal Senate representation per state. Which approach do you think handles the tension between democracy and constitutionalism better, and why?' },
        { type: 'p', text: 'Answer: There is no settled answer — this is one of the live debates in comparative constitutional law. The German approach says some values are so foundational that even a supermajority should not be able to amend them. The American approach trusts the political process more and the text less. Your answer should identify the trade-off, not just pick a side. Reading Bruce Ackerman\'s We the People and Dieter Grimm\'s Constitutionalism: Past, Present, and Future together is the best way to see both.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) What two jobs does every constitution do? (2) What is judicial review, and where does it come from in the U.S. text? (3) Name three countries with no single-document constitution. (4) What does "incorporation" mean in U.S. constitutional law? (5) Contrast originalism and living constitutionalism in one sentence each. (6) Name the three Federalist essays most often cited, and what each claims.' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read the U.S. Constitution front to back (it is about 45 minutes) with the Cornell LII annotations open. Then read Federalist 10, 51, and 78. Then watch Smith\'s Yale lectures on the constitutional founding. Once you\'ve got the basics? Read Akhil Amar\'s America\'s Constitution: A Biography and take the National Constitution Center\'s free online course with Jeffrey Rosen. To go further? Pick one comparative constitution (Germany\'s Basic Law, the 1996 South African Constitution, India\'s 1950 Constitution) and read it with its contemporary scholarly commentary; then compare it to the American document clause by clause. Serious readers take Ackerman\'s Yale seminar or its recorded equivalents, and read Dworkin\'s Taking Rights Seriously alongside Scalia\'s A Matter of Interpretation.' },
      ],

      keyTerms: ['separation of powers', 'bill of rights', 'judicial review', 'amendment', 'federalism', 'originalism', 'living constitution', 'checks and balances', 'entrenchment', 'Marbury v. Madison', 'constitutional convention'],

      resources: {
        videos: [
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@crashcourse/playlists',
            title: 'Crash Course U.S. Government — Constitution episodes',
            channel: 'Crash Course',
            duration: 'approx. 50 min across 5 eps',
            why: 'Craig Benzine walks through the Constitution, the Bill of Rights, and the separation of powers.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://oyc.yale.edu/political-science/plsc-114',
            title: 'Yale PLSC 114 — Federalist & constitutional design',
            channel: 'Yale Open Courses',
            duration: '24 lectures',
            why: 'Steven Smith\'s Yale course contains a full sequence on the Federalist and the constitutional design.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.oyez.org/',
            title: 'Oyez — Supreme Court oral arguments and opinions',
            channel: 'Oyez (Chicago-Kent College of Law)',
            duration: 'variable',
            why: 'Searchable oral-argument audio for most important constitutional cases since 1955, paired with the written opinions.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardLawSchool',
            title: 'Harvard Law School — constitutional lectures',
            channel: 'Harvard Law School',
            duration: 'variable',
            why: 'HLS\'s channel hosts lectures by Laurence Tribe, Cass Sunstein, Jack Goldsmith, and Noah Feldman on constitutional interpretation.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@NationalConstitutionCenter',
            title: 'National Constitution Center (Philadelphia)',
            channel: 'National Constitution Center',
            duration: 'variable',
            why: 'The best public programming on the U.S. Constitution in the country. "We the People" interviews and full Town Hall programs.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/jeffrey_rosen_the_constitutionally_correct_way_to_handle_the_supreme_court',
            title: 'Jeffrey Rosen on the Supreme Court (search TED.com)',
            channel: 'TED',
            duration: 'variable',
            why: 'Jeffrey Rosen runs the National Constitution Center and teaches constitutional law at GW. His TED talks are short and accessible.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures — comparative constitutions',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'Lectures by Conor Gearty, Vernon Bogdanor, and comparative constitutional scholars — the non-American angle.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/larry_lessig_we_the_people_and_the_republic_we_must_reclaim',
            title: 'We the People, and the Republic we must reclaim',
            channel: 'TED2013',
            duration: '18:20',
            why: 'Harvard Law\'s Larry Lessig on campaign finance and the Constitution — a specific, contested application of constitutional analysis.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@C-SPAN',
            title: 'C-SPAN — Supreme Court and constitutional programming',
            channel: 'C-SPAN',
            duration: 'variable',
            why: 'C-SPAN\'s Book TV and Washington Journal regularly host constitutional scholars at length. Unedited footage of congressional hearings, too.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/sarah_t_roberts_the_people_you_re_paying_to_be_in_abusive_relationships_on_the_internet',
            title: 'Digital speech and the First Amendment (search TED.com)',
            channel: 'TED',
            duration: 'variable',
            why: 'The open problem of how to apply a document written in 1791 to speech on the modern internet. See also the TED talks by Jonathan Haidt and Jonathan Rauch.',
          },
        ],
        books: [
          {
            title: 'The Federalist Papers',
            author: 'Alexander Hamilton, James Madison, and John Jay',
            year: 1788,
            url: 'https://www.gutenberg.org/ebooks/1404',
            why: 'Eighty-five essays arguing for ratification of the U.S. Constitution. Federalist 10 (factions), 51 (checks and balances), and 78 (judicial review) are the three to read first.',
          },
          {
            title: 'Second Treatise of Government',
            author: 'John Locke',
            year: 1689,
            url: 'https://www.gutenberg.org/ebooks/7370',
            why: 'The intellectual engine behind the American founders\' constitutionalism. Read chapters 2 and 19.',
          },
          {
            title: 'Democracy in America',
            author: 'Alexis de Tocqueville',
            year: 1835,
            url: 'https://www.gutenberg.org/ebooks/815',
            why: 'Volume I is, in large part, a commentary on the U.S. Constitution from the outside. Still one of the most astute analyses of American constitutional practice in any language.',
          },
          {
            title: 'How Democracies Die',
            author: 'Steven Levitsky and Daniel Ziblatt',
            year: 2018,
            url: '',
            why: 'The clearest modern book on what makes constitutional democracies resilient — and what causes them to come apart — drawn from comparative twentieth-century data.',
          },
          {
            title: 'A People\'s History of the Supreme Court',
            author: 'Peter Irons',
            year: 1999,
            url: '',
            why: 'Irons tells constitutional history through the lives of the litigants, not just the justices. Reads like good narrative journalism.',
          },
          {
            title: 'America\'s Constitution: A Biography',
            author: 'Akhil Reed Amar',
            year: 2005,
            url: '',
            why: 'Amar\'s clause-by-clause reading of the U.S. Constitution. Opinionated, encyclopedic, the one-volume reference for serious readers.',
          },
          {
            title: 'The Anti-Federalist Papers',
            author: 'Various (Herbert Storing, ed.)',
            year: 1788,
            url: '',
            why: 'The losing side of the 1787 ratification argument, and a reminder that the framers did not agree with themselves. Melancton Smith and Brutus are the essential authors.',
          },
        ],
        articles: [
          {
            title: 'Constitutionalism',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/constitutionalism/',
            why: 'Wil Waluchow\'s long, careful entry on what it means for power to be constrained by a constitution. Revised 2023.',
            year: 2023,
          },
          {
            title: 'The U.S. Constitution, annotated',
            source: 'Cornell Legal Information Institute',
            url: 'https://www.law.cornell.edu/constitution',
            why: 'Cornell LII\'s free annotated text, with each clause linked to explanatory commentary from the Congressional Research Service.',
            year: null,
          },
          {
            title: 'Constitution',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Constitution',
            why: 'Good short comparative overview, with coverage of the written/unwritten distinction.',
            year: null,
          },
          {
            title: 'Legal Rights',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/legal-rights/',
            why: 'The philosophical companion to any discussion of a bill of rights. 2023 revision.',
            year: 2023,
          },
          {
            title: 'Federalist Papers (Yale Avalon Project)',
            source: 'Yale Avalon Project',
            url: 'https://avalon.law.yale.edu/subject_menus/fed.asp',
            why: 'The complete Federalist with each essay on its own page, maintained by the Lillian Goldman Law Library at Yale.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Introduction to Political Philosophy (PLSC 114)',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science/plsc-114',
            free: true,
            why: 'Smith\'s Yale course covers constitutional design directly in its late weeks (Federalist, Tocqueville).',
          },
          {
            title: 'Constitutional Interpretation — Cornell LII',
            provider: 'Cornell Law School',
            url: 'https://www.law.cornell.edu/constitution-conan',
            free: true,
            why: 'The Constitution Annotated, a clause-by-clause Congressional Research Service treatment. The scholar\'s edition.',
          },
        ],
        podcasts: [
          {
            title: 'We the People',
            show: 'National Constitution Center',
            url: 'https://constitutioncenter.org/news-debate/podcasts/we-the-people',
            duration: '≈60:00 per episode',
            why: 'Jeffrey Rosen hosts weekly debates between constitutional scholars with opposing views. Careful, nonpartisan, and the best podcast in the field.',
          },
          {
            title: 'Amicus',
            show: 'Slate',
            url: 'https://slate.com/podcasts/amicus',
            duration: '≈50:00 per episode',
            why: 'Dahlia Lithwick\'s long-running Supreme Court podcast. Progressive in framing; reliably good on the cases.',
          },
          {
            title: 'Advisory Opinions',
            show: 'The Dispatch',
            url: 'https://thedispatch.com/podcast/advisory-opinions/',
            duration: '≈60:00 per episode',
            why: 'David French and Sarah Isgur on constitutional law and the Supreme Court. Conservative-leaning; a useful counterweight to Amicus.',
          },
        ],
        primarySources: [
          {
            title: 'The Federalist Papers (Yale Avalon Project)',
            url: 'https://avalon.law.yale.edu/subject_menus/fed.asp',
            why: 'Complete hyperlinked 1787–88 text, by essay.',
          },
          {
            title: 'U.S. Constitution — Annotated (Cornell LII)',
            url: 'https://www.law.cornell.edu/constitution',
            why: 'Full annotated text with clause-level commentary.',
          },
        ],
      },

      seeAlso: ['governments', 'constitutional', 'institutions', 'law'],
      prereqs: ['governments'],
      leadsTo: ['constitutional', 'ir'],

      chapterActivity: 'A one-night "constitution-writing" workshop at the Brooklyn Public Library, in which small groups draft a governing charter for a fictional thirty-person co-op and then argue about the amendment clause. Twice a year, a Saturday trip to Federal Hall on Wall Street (where Washington took the oath in 1789) and afterward a seminar-style discussion of Federalist 10.',

      sources: [
        'https://plato.stanford.edu/entries/constitutionalism/',
        'https://plato.stanford.edu/entries/legal-rights/',
        'https://www.law.cornell.edu/constitution',
        'https://en.wikipedia.org/wiki/Constitution',
        'https://avalon.law.yale.edu/subject_menus/fed.asp',
      ],
      verifiedAt: '2026-04-23',
    },

    // ——— INTERNATIONAL RELATIONS ———
    ir: {
      id: 'ir',
      name: 'International Relations',
      level: 'Advanced',
      dek: 'The study of what happens between states — and of why a world of many rulers has never quite settled down.',
      readTime: '19 min',

      sections: ['Thucydides and the long argument', 'The three schools', 'Anarchy, and what it implies', 'Deterrence and the nuclear question', 'Beyond the state', 'The problem of climate'],
      body: [
        { type: 'lead', text: 'Around 400 BCE, an Athenian general named Thucydides wrote the history of a war he had fought in and lost, and in a short aside he offered a theory. The Peloponnesian War, he said, had one cause that mattered: "the rise of Athens and the fear that this inspired in Sparta." Twenty-five centuries of international relations scholarship is, in one sense, a footnote to that sentence.' },
        { type: 'figure', src: 'https://commons.wikimedia.org/wiki/Special:FilePath/Thucydides_pushkin02.jpg?width=900', caption: 'A Roman copy of a Greek bust of Thucydides (c. 460 – c. 400 BCE). His History of the Peloponnesian War remains the founding text of international relations as a realist discipline.', credit: 'Shakko, public domain, via Wikimedia Commons' },
        { type: 'h2', text: 'The three schools, briefly' },
        { type: 'p', text: 'Modern IR organizes itself around a small number of traditions. Realism (Morgenthau, Waltz, Mearsheimer) sees states pursuing power in a self-help world. Liberalism (Keohane, Nye) argues that institutions, trade, and democratic peace soften anarchy. Constructivism (Wendt, Finnemore) treats interests and identities as socially constructed, not fixed. Marxism and post-colonial scholarship add a class and a power-over-the-global-South lens. A careful reader listens for which tradition an argument is drawing on.' },
        { type: 'h2', text: 'Anarchy, and what it implies' },
        { type: 'p', text: 'The key structural feature of international politics, for most theorists, is anarchy — not chaos, but the absence of a global government above sovereign states. There is no international police to call when a neighbor invades. This simple fact, realists argue, forces even peaceful states to worry about their own security, arm themselves, and watch their rivals. The result is the security dilemma: one state\'s defensive preparations are another state\'s offensive threat. Liberals respond that institutions like the UN, the WTO, and the EU partially substitute for a world government. Both claims contain truth; which matters more varies by issue.' },
        { type: 'h2', text: 'Deterrence, alliances, and the nuclear question' },
        { type: 'p', text: 'In 1945, the United States ended a war by incinerating two cities. The weapons have not been used in anger since. Deterrence theory — most of it worked out by Thomas Schelling in the 1950s and 1960s — is the uncomfortable body of knowledge about why. Schelling\'s The Strategy of Conflict (1960) and Arms and Influence (1966) remain in print; the current reappearance of nuclear threats around the Ukraine war has brought both books back into university reading lists they had briefly left.' },
        { type: 'p', text: 'Nine countries currently possess nuclear weapons. The nonproliferation regime built around the 1968 Nuclear Non-Proliferation Treaty has had mixed success: it has not prevented India, Pakistan, Israel, or North Korea from acquiring weapons, but it has slowed the spread from the 15 to 20 states that once seemed likely to go nuclear to the 9 we actually have. The regime\'s central argument — nuclear-armed states will reduce arsenals if non-nuclear states forgo acquisition — is under visible strain as of 2026.' },
        { type: 'h2', text: 'Non-state actors, now more than ever' },
        { type: 'p', text: 'Twentieth-century IR was largely about states. Twenty-first-century IR is also about transnational corporations, non-governmental organizations, terrorist networks, and — more recently — a small number of very large technology companies with the effective reach of middle powers. No single theory has absorbed this shift cleanly. The field is in an interesting moment.' },
        { type: 'h2', text: 'Climate and other commons' },
        { type: 'p', text: 'Climate change is the hardest case IR currently faces: a problem that cannot be solved unilaterally, in a system with no enforceable global authority. The Paris Agreement (2015) is a voluntary regime of nationally determined commitments; Elinor Ostrom\'s earlier work on polycentric governance is increasingly cited as the theoretical scaffold. Whether this approach can actually produce outcomes adequate to the physical problem is one of the defining open questions of the century.' },
        { type: 'p', text: 'The emerging subfields — cyber conflict, pandemic preparedness, AI governance, space policy — are each, in effect, new tests of the same structural question: can sovereign states coordinate in the absence of a sovereign above them? The history of international relations is the answer, still being written.' },
        { type: 'callout', text: 'The "democratic peace" is one of the most-discussed empirical regularities in international relations: established liberal democracies almost never fight each other. Michael Doyle formalized the observation in 1983; it has held up reasonably well to challenge. Whether the pattern reflects democracy itself, or something else correlated with democracy, is the live argument.' },

        { type: 'h2', text: 'Learn it: reading an international crisis in four theories' },
        { type: 'p', text: 'Take Russia\'s 2022 invasion of Ukraine. Write one paragraph explaining why it happened in the voice of each theoretical tradition. A *realist* (Mearsheimer) says NATO expansion created a security dilemma Russia could not tolerate; structure produced the war. A *liberal* (Ikenberry) says the war shows the fragility of the rules-based order when a revisionist great power no longer accepts it; institutions matter but can be broken. A *constructivist* (Wendt) says the Russian elite\'s identity and its narratives about Ukraine — not material interests alone — are doing the work; you cannot predict the war from capabilities alone. A *Marxist* (David Harvey) says the invasion is the latest round in the contest for energy resources and pipeline routes; accumulation logic remains central. Each paragraph catches something real. No paragraph is the whole story. Getting fluent means being able to write all four.' },

        { type: 'h2', text: 'Worked example: the Cuban Missile Crisis as game theory' },
        { type: 'p', text: 'In October 1962, the United States discovered Soviet missiles in Cuba. Kennedy\'s advisers proposed three options: (A) diplomatic negotiation, (B) naval quarantine (blockade), (C) air strike. Each choice affected the Soviet reaction. Schelling\'s framework — reciprocal fear of surprise attack — predicted that both sides would look for moves that demonstrated resolve without forcing the other side to escalate. The quarantine was exactly that: visible enough to commit the U.S. publicly, slow enough to give Khrushchev time to back down. The secret deal (U.S. missiles in Turkey traded for Soviet missiles in Cuba) preserved both leaders\' face. Read Allison\'s Essence of Decision (1971) for three different theoretical lenses on the same thirteen days; it is the single best case study in the IR teaching canon.' },

        { type: 'h2', text: 'Practice problems' },
        { type: 'p', text: 'Problem 1. Two states share a border and a history of conflict. State A builds up its military "for defense." State B, unable to distinguish defensive from offensive preparations, builds up in response. Both end up more vulnerable and more paranoid than before. What is this phenomenon called? What is the standard realist remedy, and what is a liberal alternative?' },
        { type: 'p', text: 'Answer: The security dilemma (Herz, 1951). Realist remedies: balance of power, clear alliance structures, deterrence. Liberal alternatives: arms-control treaties with verification, economic interdependence, confidence-building measures. The U.S.-Soviet strategic-arms treaties (SALT, START) are the canonical example of successful liberal mitigation of a severe security dilemma.' },
        { type: 'p', text: 'Problem 2. A rising power\'s GDP growth outpaces the incumbent hegemon\'s for two decades. Graham Allison surveyed 16 historical cases of a rising power challenging an incumbent over 500 years. In how many did war follow? What variables best predicted when it didn\'t?' },
        { type: 'p', text: 'Answer: 12 of 16 resulted in war; 4 did not. The non-war cases (Portugal-Spain in the late 15th century, UK-US handoff 1894–1918, USSR-US cold war, UK-France 20th century) share common features: cultural/institutional similarity, presence of a shared threat, or nuclear deterrence. Allison\'s argument for US-China is that the pattern is alarming but not destiny; careful statecraft has mattered in the 4 successful cases.' },
        { type: 'p', text: 'Problem 3. A small state cannot credibly threaten a large state militarily. What non-military levers of power are available to it? Name three real-world examples of small states exerting disproportionate global influence.' },
        { type: 'p', text: 'Answer: Soft power (Nye) — attraction via culture, values, legitimacy. Smart power — combining hard and soft levers. Niche specialization — Switzerland in banking and mediation; Ireland in corporate taxation; Qatar in media (Al Jazeera) and aviation; Singapore in finance and shipping; the Vatican in moral authority. The lesson: power in the international system is multi-dimensional, and states that play to their structural position outperform those that chase great-power symbols.' },

        { type: 'h2', text: 'Self-check' },
        { type: 'callout', text: 'Check yourself. (1) State the central claim of realism in one sentence. (2) What is the security dilemma, and why is it harder than an arms race? (3) What did Thucydides mean by "the real cause" of the Peloponnesian War? (4) Name three international institutions and what problem each solves. (5) What does soft power rely on that hard power does not? (6) What is the "nuclear taboo," and why might AI and cyber be eroding it?' },

        { type: 'h2', text: 'The learning progression' },
        { type: 'p', text: 'Brand new? Read the Melian Dialogue (Thucydides, Book V.84–116), then watch Graham Allison\'s TED talk and one LSE lecture by Mearsheimer. Write a one-page comparison of realist and liberal explanations of a current event. Once you\'ve got the basics? Read Waltz\'s Theory of International Politics (chapters 5–6) and Keohane\'s After Hegemony (first two chapters). Follow Foreign Affairs for three months and notice which authors come from which tradition. To go further? Take a graduate IR seminar or read Jervis, Schelling, and Wendt back to back. For the current moment, read the weekly War on the Rocks essays and Tom Friedman with equal skepticism; notice the prose conventions.' },
      ],

      keyTerms: ['anarchy', 'realism', 'liberalism', 'constructivism', 'balance of power', 'deterrence', 'hegemony', 'sovereignty', 'soft power', 'security dilemma', 'nonproliferation', 'democratic peace'],

      resources: {
        videos: [
          {
            id: null,
            source: 'other',
            url: 'https://oyc.yale.edu/political-science',
            title: 'Yale Open Political Science (lecture series)',
            channel: 'Yale Open Courses',
            duration: 'variable',
            why: 'The Yale Open index lists several IR-adjacent full courses, including capitalism and political philosophy.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@LSE',
            title: 'LSE public lectures on international politics',
            channel: 'London School of Economics',
            duration: 'variable',
            why: 'The LSE\'s public lecture channel regularly posts full-length talks by the leading figures in the field (Mearsheimer, Walt, Rachman, Chin).',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/joseph_nye_global_power_shifts',
            title: 'Joseph Nye — Global Power Shifts',
            channel: 'TEDGlobal 2010',
            duration: '17:55',
            why: 'Nye coined the term "soft power." This is the short version of his argument.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@CarnegieEndowment',
            title: 'Carnegie Endowment for International Peace',
            channel: 'Carnegie Endowment',
            duration: 'variable',
            why: 'Public-facing think-tank programming with current policy scholars — particularly strong on Russia, China, and the Middle East.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@CFR_org',
            title: 'Council on Foreign Relations',
            channel: 'CFR',
            duration: 'variable',
            why: 'The CFR\'s public meetings are posted in full. Every living U.S. Secretary of State has been interviewed here.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@CaspianReport',
            title: 'Caspian Report (channel)',
            channel: 'Caspian Report',
            duration: 'variable',
            why: 'Shirvan Neftchi\'s long-running geopolitics explainer. Careful, measured, with sources.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/graham_allison_is_china_destined_to_go_to_war_with_the_us',
            title: 'Is China destined to go to war with the US?',
            channel: 'TEDWomen 2018',
            duration: '13:49',
            why: 'Harvard\'s Graham Allison on the Thucydides Trap — his argument that rising powers and incumbents tend to fight. The most-viewed IR talk in the TED library.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@chathamhouse',
            title: 'Chatham House — Royal Institute of International Affairs',
            channel: 'Chatham House',
            duration: 'variable',
            why: 'Britain\'s senior foreign-policy think tank. The panel events are unusually good at getting practitioners on camera alongside scholars.',
          },
          {
            id: null,
            source: 'youtube',
            url: 'https://www.youtube.com/@HarvardKennedySchool',
            title: 'Harvard Kennedy School — Belfer Center',
            channel: 'Harvard Kennedy School',
            duration: 'variable',
            why: 'Lectures by Stephen Walt, Graham Allison, Ash Carter (before his death), and Samantha Power. The American IR establishment, on camera.',
          },
          {
            id: null,
            source: 'other',
            url: 'https://www.ted.com/talks/rose_gottemoeller_nuclear_weapons_s_powerful_purpose',
            title: 'Rose Gottemoeller on nuclear deterrence (search TED.com)',
            channel: 'TED / NATO',
            duration: 'variable',
            why: 'Rose Gottemoeller, former NATO deputy secretary-general and U.S. State Department arms-control negotiator. The real-world practice of deterrence, explained.',
          },
        ],
        books: [
          {
            title: 'The History of the Peloponnesian War',
            author: 'Thucydides',
            year: -400,
            url: 'https://www.gutenberg.org/ebooks/7142',
            why: 'The founding work. Read the Melian Dialogue (Book V.84–116); it is the single most discussed passage in IR.',
          },
          {
            title: 'Theory of International Politics',
            author: 'Kenneth N. Waltz',
            year: 1979,
            url: '',
            why: 'The definitive statement of structural realism. Hard going, but short; chapters 5 and 6 are the core.',
          },
          {
            title: 'The Tragedy of Great Power Politics',
            author: 'John J. Mearsheimer',
            year: 2001,
            url: '',
            why: 'The offensive-realist case, updated after the Cold War. Mearsheimer\'s predictions about post-Soviet Europe are now testable and, depending on your reading, mostly borne out.',
          },
          {
            title: 'After Hegemony',
            author: 'Robert O. Keohane',
            year: 1984,
            url: '',
            why: 'The liberal institutionalist reply to Waltz. Why, despite anarchy, states cooperate — because institutions reduce transaction costs.',
          },
          {
            title: 'Social Theory of International Politics',
            author: 'Alexander Wendt',
            year: 1999,
            url: '',
            why: 'The constructivist counter: "anarchy is what states make of it." Hard going; the first chapter repays the time.',
          },
          {
            title: 'Why Nations Fight',
            author: 'Richard Ned Lebow',
            year: 2010,
            url: '',
            why: 'Lebow looks at 94 great-power wars since 1648 and argues that most had less to do with security than with status, revenge, and ideology.',
          },
          {
            title: 'The Strategy of Conflict',
            author: 'Thomas C. Schelling',
            year: 1960,
            url: '',
            why: 'The founding text of modern deterrence theory. Schelling won the 2005 Nobel in economics for this work, strange as that sounds.',
          },
          {
            title: 'Destined for War: Can America and China Escape Thucydides\'s Trap?',
            author: 'Graham Allison',
            year: 2017,
            url: '',
            why: 'The most-cited recent book on U.S.–China relations. Allison\'s 16-case historical dataset is worth the price of admission.',
          },
        ],
        articles: [
          {
            title: 'Political Realism in International Relations',
            source: 'Stanford Encyclopedia of Philosophy',
            url: 'https://plato.stanford.edu/entries/realism-intl-relations/',
            why: 'W. Julian Korab-Karpowicz\'s long essay. The best single treatment of realism in one place.',
            year: null,
          },
          {
            title: 'International relations',
            source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/International_relations',
            why: 'A broad overview with good coverage of the theoretical schools and the major historical turning points.',
            year: null,
          },
          {
            title: 'International relations',
            source: 'Encyclopædia Britannica',
            url: 'https://www.britannica.com/topic/international-relations',
            why: 'Editorial entry with a careful history of the field.',
            year: null,
          },
          {
            title: 'Foreign Affairs',
            source: 'Council on Foreign Relations',
            url: 'https://www.foreignaffairs.com/',
            why: 'The flagship American IR journal. Paywalled, but the best single source of current working-professional writing on world politics.',
            year: null,
          },
          {
            title: 'War on the Rocks — essays',
            source: 'War on the Rocks',
            url: 'https://warontherocks.com/',
            why: 'Long-form essays by working strategists and academics. Particularly strong on military and strategic questions.',
            year: null,
          },
        ],
        courses: [
          {
            title: 'Yale Open Political Science',
            provider: 'Yale Open Courses',
            url: 'https://oyc.yale.edu/political-science',
            free: true,
            why: 'Complete course pages, with video, transcripts, and reading lists.',
          },
        ],
        podcasts: [
          {
            title: 'The Rachman Review',
            show: 'Financial Times',
            url: 'https://www.ft.com/rachman-review',
            duration: '≈30:00 per episode',
            why: 'Gideon Rachman, FT chief foreign-affairs columnist, interviews policy scholars and practitioners. Steady and serious.',
          },
          {
            title: 'Pod Save the World',
            show: 'Crooked Media',
            url: 'https://crooked.com/podcast-series/pod-save-the-world/',
            duration: '≈60:00 per episode',
            why: 'Former Obama NSC aide Tommy Vietor on foreign policy. Politically committed — he says so — with serious guests.',
          },
          {
            title: 'The Lawfare Podcast',
            show: 'Lawfare',
            url: 'https://www.lawfaremedia.org/topic/podcasts',
            duration: '≈50:00 per episode',
            why: 'National-security law, policy, and ethics, with a strong IR component. Good on cyber, counterterrorism, and the laws of war.',
          },
        ],
        tools: [
          {
            title: 'Correlates of War',
            url: 'https://correlatesofwar.org/',
            why: 'The canonical historical dataset on interstate conflict, maintained at Ohio State. Free to download; the empirical backbone of the quantitative side of the field.',
          },
          {
            title: 'UCDP — Uppsala Conflict Data Program',
            url: 'https://ucdp.uu.se/',
            why: 'Sweden\'s Uppsala University maintains the best open dataset on armed conflict since 1946.',
          },
        ],
      },

      seeAlso: ['governments', 'constitutions', 'geopolitics', 'history', 'macro'],
      prereqs: ['governments'],
      leadsTo: ['geopolitics'],

      chapterActivity: 'A monthly foreign-policy reading night — one member picks a current Foreign Affairs essay, everyone reads it, the debate runs as long as the drinks. Twice a year, a trip to the UN visitor center on First Avenue and then a joint read-aloud of UN Charter Article 2 at a diner afterward.',

      sources: [
        'https://plato.stanford.edu/entries/realism-intl-relations/',
        'https://en.wikipedia.org/wiki/International_relations',
        'https://www.britannica.com/topic/international-relations',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
