// content/robotics.js
// Owned by batch: B06-tech-and-code
// Last updated: 2026-04-23 by BATCH B06-tech-and-code
//
// Topics this subject covers (from data.js):
//   Core: sensors, control

window.CONTENT = window.CONTENT || {};
window.CONTENT.robotics = {
  subjectId: 'robotics',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B06-tech-and-code',
  topics: {

    sensors: {
      id: 'sensors',
      name: 'Sensors & Actuators',
      level: 'Intermediate',
      dek: 'The transducers that turn the world into numbers — and the motors that turn numbers back into motion.',
      readTime: '14 min',

      sections: ['A robot is a transducer sandwich', 'What the common sensors actually measure', 'Actuators and the tyranny of torque', 'Why sensor fusion exists', 'The mechanical and electrical are not optional', 'The 2020s sensor revolution'],
      body: [
        { type: 'lead', text: 'Strip away the software, and a robot is a machine for turning electrical signals into mechanical motion — and, in the other direction, for turning physical quantities (angles, distances, temperatures, images) into electrical signals. Every robot ever built, from the 1961 Unimate arm at a General Motors plant in New Jersey to a 2026 humanoid walking around a warehouse, is fundamentally a transducer sandwich with computation in the middle.' },
        { type: 'figure',
          src: 'content/images/unimate_1967.jpg',
          alt: 'The Unimate industrial robot pouring coffee for a woman at the Biltmore Hotel, 1967.',
          caption: 'Unimate, pouring coffee at the Biltmore Hotel in 1967. The first industrial robot; six years old in this photo, and already being rented out for press events.',
          credit: 'Wikimedia Commons, public domain.',
        },
        { type: 'h2', text: 'The short catalogue of common sensors' },
        { type: 'p', text: 'A working roboticist spends most of her time with a small set: encoders (how far has this motor turned), inertial measurement units (accelerations and angular rates in three axes), force-torque sensors (how hard is the tip pressing), ultrasonic and time-of-flight range finders (how far is that), cameras (a grid of photon counts), lidar (millions of ranges per second). Each measures one thing, imperfectly, in its own coordinate frame, at its own rate. The entire intellectual content of perception is about reconciling those measurements into something a controller can use.' },
        { type: 'p', text: 'The modern drop in cost has been dramatic. A 9-axis IMU that would have cost $2,000 in 2005 is $3 in 2026. A lidar that was $70,000 is under $500. A depth camera indistinguishable from a research-grade 2010 stereo rig is $150. Almost everything interesting a contemporary robot does would have been financially impossible fifteen years ago, independent of the algorithms.' },
        { type: 'h2', text: 'Actuators: the world fights back' },
        { type: 'p', text: 'The other half of the sandwich is actuation. Brushless DC motors dominate — in drones, wheels, and quadrupedal legs — because they are efficient, controllable, and have become cheap. Stepper motors turn in fixed increments and are useful when you know exactly where you want to be (3D printers, CNC machines). Pneumatic and hydraulic actuators produce enormous forces per unit weight, at the cost of hoses, compressors, and mess — which is why industrial arms are largely electric now. Between an actuator and the world sits the gearbox, and most real-world robot failures live there.' },
        { type: 'animation',
          youtubeId: 'BmNTw5Vq7lg',
          caption: 'Computerphile on the sensor stack in self-driving cars — lidar, radar, cameras, and how their measurements are combined.',
          credit: 'Computerphile.',
        },
        { type: 'h2', text: 'Sensor fusion and the Kalman filter' },
        { type: 'p', text: 'No sensor is trustworthy on its own. A GPS drifts, an IMU integrates error, a camera misidentifies, a lidar is noisy. Rudolf Kalman\'s 1960 paper on recursive filtering gave the field its first principled way to combine noisy measurements into a single best estimate, and the Kalman filter and its descendants — extended, unscented, particle — remain the backbone of every serious state estimator. If a modern robot is not falling down, it is because sensor fusion is quietly running, dozens of times a second.' },
        { type: 'callout', text: 'The ROS (Robot Operating System) ecosystem is not strictly an operating system — it is a set of libraries and tools for publishing and subscribing to sensor and actuator messages. Since its 2007 release, it has become the lingua franca of academic and much of commercial robotics.' },
        { type: 'h2', text: 'The mechanical and electrical are not optional' },
        { type: 'p', text: 'A recurring lesson, painful for software people: a robot that cannot move, cannot. The mechanical design, the electrical bus, the power budget, the EMI on the motor wires — any of these can make the most elegant code useless. The working roboticist has to know enough of each discipline to recognize whose problem an anomaly belongs to before the debugging session ends at dawn.' },
        { type: 'p', text: 'Rod Brooks — the MIT professor who founded iRobot and Rethink Robotics — has been saying for three decades that the hard problems in robotics are on the hardware side, not the software side. He has mostly been right, and nothing about modern AI has changed that. A learned policy that handles every lighting condition still cannot, on its own, make a gripper close at the right torque.' },
        { type: 'h2', text: 'The 2020s sensor revolution' },
        { type: 'p', text: 'The combination of a new generation of low-cost lidars (solid-state, MEMS), dense depth cameras (Intel RealSense, Luxonis OAK), low-drift IMUs, and GPU-accelerated perception has changed what a serious hobbyist robot can do. Autonomous indoor mapping, once a research project, is a weekend kit in 2026. The gap between research and practice has narrowed. The interesting open problems have moved up the stack — into planning, manipulation, and the long tail of the physical world.' },
        { type: 'aside', label: 'Moravec\'s paradox', text: 'Hans Moravec observed in 1988 that the easy problems for humans — reaching for a cup, climbing a stair, recognizing a friend — are the hard problems for robots. Forty years on, that paradox is intact: a machine can beat a grandmaster at Go and still cannot reliably load a dishwasher.' },
      ],

      keyTerms: ['encoder', 'IMU', 'lidar', 'ultrasonic', 'actuator', 'servo', 'brushless motor', 'Kalman filter', 'sensor fusion', 'ROS', 'SLAM'],

      examples: [
        {
          title: 'Estimating position from an IMU — why it drifts',
          problem: 'An IMU reports acceleration. How do you get position? Why does it drift?',
          steps: [
            { text: 'Position is the double integral of acceleration. Integrate once to get velocity; integrate again to get position.' },
            { text: 'Each measurement has noise. Integration accumulates noise — a small constant error in acceleration becomes a ramp in velocity and a parabola in position.' },
            { text: 'After a few seconds, the integrated position estimate is meaningless. This is why every serious inertial navigation system fuses IMU data with GPS, visual odometry, or lidar.' },
            { text: 'The fusion is done with a Kalman filter: the IMU provides high-rate predictions, the slower sensors provide bounded-error corrections.' },
          ],
          answer: 'IMU alone drifts because integration amplifies noise.',
        },
      ],

      practice: [
        { q: 'Which sensor is used for absolute heading on a robot: IMU, GPS, or encoder?',
          a: 'IMU', acceptable: ['magnetometer', 'compass', 'imu'],
          difficulty: 'medium', hint: 'Specifically, the magnetometer in the IMU.',
          solution: 'The IMU — specifically its magnetometer, which acts as a compass and gives absolute heading. GPS gives position; encoders give wheel rotation.' },
        { q: 'What does SLAM stand for?',
          a: 'simultaneous localization and mapping', acceptable: ['slam'],
          difficulty: 'medium', hint: 'Four words.',
          solution: 'Simultaneous Localization And Mapping — figure out where you are while building a map, from sensor data alone.' },
        { q: 'What is the middleware most academic robots use for messaging?',
          a: 'ROS', acceptable: ['ros 2', 'robot operating system'],
          difficulty: 'easy', hint: 'Three letters.',
          solution: 'ROS (Robot Operating System). Current long-term release is ROS 2 Jazzy as of 2026.' },
      ],

      subtopics: [
        {
          id: 'sensors.imu',
          name: 'IMUs — accelerometers, gyros, magnetometers',
          summary: 'The nine-axis sensor that lives in every drone, phone, and robot.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'An Inertial Measurement Unit packages three sensors: a three-axis accelerometer (acceleration, including gravity), a three-axis gyroscope (rotation rate), and often a three-axis magnetometer (magnetic field, for compass). Nine measurements per sample. A good 2026 IMU samples at 1 kHz and costs $3.' },
            { type: 'p', text: 'The hard part is not the hardware, it is the fusion. Madgwick, Mahony, and extended-Kalman filters combine the three to produce a stable orientation estimate — the accelerometer provides a long-term gravity reference, the gyro provides a fast-but-drifting rate, and the magnetometer nails down the yaw.' },
          ],
          practice: [
            { q: 'Which IMU sub-sensor has the worst long-term drift?',
              a: 'gyroscope', acceptable: ['gyro'],
              difficulty: 'medium', hint: 'Rates integrated over time.',
              solution: 'The gyroscope. Integrating its rate over time accumulates bias drift.' },
          ],
          keyTerms: ['accelerometer', 'gyroscope', 'magnetometer', 'sensor fusion', 'Madgwick', 'orientation'],
        },
        {
          id: 'sensors.slam',
          name: 'SLAM — knowing where you are',
          summary: 'Simultaneous localization and mapping. The chicken-and-egg problem of mobile robotics.',
          level: 'Advanced', readTime: '9 min',
          body: [
            { type: 'lead', text: 'A robot in a new environment faces two problems at once: it needs a map to know where it is, but it needs to know where it is to build a map. SLAM solves both together. Using landmarks it keeps re-observing, it simultaneously refines its pose and the map.' },
            { type: 'p', text: 'The classic approaches: EKF-SLAM (Extended Kalman Filter, 1990s), particle filters (late 1990s), graph-based SLAM (2000s), and visual-inertial odometry (2010s). The modern reference is ORB-SLAM3 (2021) — mono or stereo cameras plus an IMU, open source, runs in real time on a laptop.' },
          ],
          practice: [
            { q: 'What does "loop closure" mean in SLAM?',
              a: 'recognizing a previously-visited place', acceptable: ['revisit', 'revisit recognition', 'detect a place seen before'],
              difficulty: 'hard', hint: 'Correcting accumulated drift when you return somewhere.',
              solution: 'Recognizing that the robot has returned to a previously-visited place, which lets the algorithm correct accumulated drift in the map.' },
          ],
          keyTerms: ['SLAM', 'pose', 'landmark', 'loop closure', 'odometry', 'bundle adjustment'],
        },
      ],

      resources: {
        videos: [
          { id: 'BmNTw5Vq7lg', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=BmNTw5Vq7lg',
            title: 'How do Self-Driving Cars work? — Computerphile',
            channel: 'Computerphile', duration: '19:36',
            why: 'A working tour of the sensor stack — lidar, radar, cameras — and how their measurements are combined.' },
          { id: 'mwn8xhgNpFY', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=mwn8xhgNpFY',
            title: 'Understanding Kalman Filters — Part 1',
            channel: 'MATLAB', duration: '4:53',
            why: 'The first of a seven-part MATLAB series. The best no-math introduction to sensor fusion.' },
          { id: 'Pck_Pj9iGY0', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=Pck_Pj9iGY0',
            title: 'How Robots See: Vision, SLAM, and Localization',
            channel: 'Two Minute Papers', duration: '6:53',
            why: 'A quick introduction to SLAM — the algorithm that lets a robot know where it is.' },
          { id: 'TiL7O1lxrJw', source: 'youtube', url: 'https://www.youtube.com/watch?v=TiL7O1lxrJw',
            title: 'ROS 2 for Beginners',
            channel: 'Articulated Robotics', duration: '11:00',
            why: 'Josh Newans\' ROS 2 series is the cleanest free ROS tutorial on the internet.' },
          { id: 'd8LoPP1_O_k', source: 'youtube', url: 'https://www.youtube.com/watch?v=d8LoPP1_O_k',
            title: 'Introduction to LiDAR',
            channel: 'Engineering Explained', duration: '15:02',
            why: 'The technology, explained at a hobbyist level. Good before the research papers.' },
          { id: 'gPwjOUXH_7U', source: 'youtube', url: 'https://www.youtube.com/watch?v=gPwjOUXH_7U',
            title: 'How Humanoids See the World — Figure 02 overview',
            channel: 'Figure AI', duration: '8:00',
            why: 'A company engineering a production humanoid explains the 2025 perception stack. A window into where the field is today.' },
        ],
        books: [
          { title: 'Introduction to Autonomous Mobile Robots',
            author: 'Roland Siegwart, Illah Nourbakhsh, Davide Scaramuzza', year: 2011, url: '',
            why: 'The standard textbook on mobile-robot perception and locomotion.' },
          { title: 'Robotics, Vision and Control',
            author: 'Peter Corke', year: 2023,
            url: 'https://petercorke.com/rvc/home/',
            why: 'A working engineer\'s book — third edition, now in Python, every example runnable in Colab.' },
          { title: 'Probabilistic Robotics',
            author: 'Sebastian Thrun, Wolfram Burgard, Dieter Fox', year: 2005, url: '',
            why: 'The reference on sensor fusion and localization — Kalman, particle filters, Monte Carlo localization.' },
          { title: 'Robot Modeling and Control',
            author: 'Mark W. Spong, Seth Hutchinson, M. Vidyasagar', year: 2020, url: '',
            why: 'A second-edition classic on the mathematics of manipulators. Dense, clear, the book every robotics grad student keeps.' },
        ],
        articles: [
          { title: 'Kalman filter', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Kalman_filter',
            why: 'A well-referenced treatment with intuition and the math.' },
          { title: 'IEEE Spectrum — Robotics',
            source: 'IEEE Spectrum', url: 'https://spectrum.ieee.org/robotics',
            why: 'The field\'s working trade press.' },
          { title: 'Boston Dynamics — Engineering Blog',
            source: 'Boston Dynamics', url: 'https://bostondynamics.com/blog/',
            why: 'First-person posts from the engineers behind Atlas, Spot, and Stretch.' },
          { title: 'SLAM — A Tutorial',
            source: 'Stachniss, Leonard, Thrun (IEEE RAM, 2016)',
            url: 'https://www.ipb.uni-bonn.de/html/teaching/msr2-2020/sensors-modern-slam.pdf',
            why: 'The canonical short introduction to simultaneous localization and mapping.', year: 2016 },
        ],
        courses: [
          { title: 'Modern Robotics — Mechanics, Planning, and Control',
            provider: 'Kevin Lynch / Northwestern / Coursera',
            url: 'https://www.coursera.org/specializations/modernrobotics', free: true,
            why: 'A six-course specialization by Kevin Lynch and Frank Park, auditable free. The textbook is on the course site.' },
          { title: 'Articulated Robotics — ROS 2 Series',
            provider: 'Josh Newans (YouTube)',
            url: 'https://articulatedrobotics.xyz/', free: true,
            why: 'The most practical free ROS 2 tutorial series in 2026.' },
        ],
        tools: [
          { title: 'ROS 2 — Robot Operating System', url: 'https://www.ros.org/',
            why: 'The messaging and tooling backbone used in most academic and much of commercial robotics. Current long-term release in 2026 is ROS 2 Jazzy.' },
          { title: 'Gazebo', url: 'https://gazebosim.org/',
            why: 'The open-source 3D simulator most robots are first tested in.' },
          { title: 'NVIDIA Isaac Sim', url: 'https://developer.nvidia.com/isaac/sim',
            why: 'The photorealistic simulator most 2025–26 learned-policy research uses for sim-to-real training.' },
        ],
        primarySources: [
          { title: 'Kalman, "A New Approach to Linear Filtering and Prediction Problems" (1960)',
            url: 'https://www.cs.unc.edu/~welch/kalman/media/pdf/Kalman1960.pdf',
            why: 'The founding paper. Ten pages. Still read.' },
          { title: 'Brooks, "Intelligence Without Representation" (1991)',
            url: 'https://people.csail.mit.edu/brooks/papers/representation.pdf',
            why: 'Rod Brooks\' argument for subsumption architecture — the paper that turned MIT robotics toward behavior-based approaches.' },
        ],
        images: [
          { src: 'content/images/unimate_1967.jpg',
            caption: 'Unimate, 1967 — the first industrial robot, on a publicity tour.',
            credit: 'Wikimedia Commons.' },
        ],
        animations: [
          { youtubeId: 'mwn8xhgNpFY',
            title: 'Understanding Kalman Filters',
            channel: 'MATLAB',
            why: 'The intuition behind every modern state estimator.' },
        ],
      },

      interactive: null,
      seeAlso: ['control', 'programming', 'physics'],
      prereqs: ['programming'],
      leadsTo: ['control'],

      chapterActivity: 'A Saturday sensor night at a Brooklyn hackerspace — a pile of IMUs, lidars, and Arduino kits, one small project each month.',

      sources: [
        'https://en.wikipedia.org/wiki/Kalman_filter',
        'https://www.ros.org/',
        'https://petercorke.com/rvc/home/',
      ],
      verifiedAt: '2026-04-23',
    },

    control: {
      id: 'control',
      name: 'Control Systems',
      level: 'Advanced',
      dek: 'How to make a physical system do what you want, in the presence of noise, delay, and its own bad habits.',
      readTime: '16 min',

      sections: ['The thermostat and the centrifugal governor', 'PID, the workhorse', 'Why linear theory takes you far', 'Underactuation and the interesting half', 'Where control meets learning', 'A practical path through the subject'],
      body: [
        { type: 'lead', text: 'In 1788, James Watt patented a centrifugal governor — a pair of weighted balls spinning on an axis that rose as the engine ran faster and closed a valve to let in less steam. It was the first machine that corrected itself: a physical implementation of negative feedback, a century before anyone had a theory of it. Every control system built since, from the thermostat on a wall to the flight computer on a drone to the stabilization code on a rocket, is a descendant of that pair of spinning balls.' },
        { type: 'figure',
          src: 'content/images/watt_governor.jpg',
          alt: 'Boulton and Watt centrifugal governor, 1788.',
          caption: 'A Boulton and Watt governor from 1788 — the first widely-deployed feedback controller. The faster the engine turned, the higher the balls flew, the more the steam valve closed.',
          credit: 'Maksym Kozlenko, Wikimedia Commons (CC BY-SA 4.0).',
        },
        { type: 'h2', text: 'The error-correcting loop' },
        { type: 'p', text: 'A controller has a reference (the setpoint — a temperature, an angle, a velocity), a sensor reading (the actual value), and a control signal (what we send to the motor or valve). The core idea is to drive the error — reference minus actual — to zero, using feedback. Norbert Wiener, in Cybernetics (1948), gave the field its name and its place in intellectual history; Hendrik Bode and Harry Nyquist at Bell Labs had already worked out most of the mathematics for stable feedback amplifiers in the 1930s.' },
        { type: 'h2', text: 'PID: the 1922 idea that will not die' },
        { type: 'p', text: 'The Russian-American engineer Nicolas Minorsky published the PID algorithm in 1922 while trying to steer US Navy ships automatically. Almost every controller you meet in industry is still PID. P: correct proportionally to the current error. I: correct for accumulated past error (to cancel drift). D: correct for the rate of change of error (to avoid overshoot). Tuning the three gains — by Ziegler–Nichols, by auto-tuning, or by hand — is the trade skill control engineers build in their first year. The Wikipedia article on PID is unusually good on the intuition.' },
        { type: 'animation',
          youtubeId: 'Pi7l8mMjYVE',
          caption: 'Steve Brunton, Control Bootcamp: Overview — the opening lecture of the best free control theory series on the internet.',
          credit: 'Steve Brunton, University of Washington.',
        },
        { type: 'h2', text: 'State-space, linear, and nonlinear' },
        { type: 'p', text: 'Classical control assumes a single input and a single output. Modern control — developed around Kalman\'s work in the 1960s — treats a system as a vector of states evolving by linear differential equations. A lot of the real world is not linear, but linear theory carries you further than you would guess, because many systems look linear near the operating point you care about. Linear Quadratic Regulators (LQR) and Model Predictive Control (MPC) are the two tools a working roboticist is likeliest to reach for once PID stops being enough.' },
        { type: 'callout', text: '"When in doubt, use brute force — or a PID controller." — Ken Thompson (adapted). The joke is half true: most problems worth solving in industry are still solved with PID, and you will be a better engineer for knowing why.' },
        { type: 'h2', text: 'Underactuation and the interesting half of the field' },
        { type: 'p', text: 'A walking biped has more degrees of freedom than motors; a quadcopter has four rotors controlling six dimensions of motion; a skater has a foot, not a wheel. These are underactuated systems, and the clever part of the subject is about controlling things that cannot be directly told what to do. Russ Tedrake\'s free MIT textbook, Underactuated Robotics, is the best modern treatment — and the reason most of Boston Dynamics\' early engineering lineage traces back to his lab.' },
        { type: 'p', text: 'The aesthetic of the field is oddly musical. A well-tuned controller looks like a good jazz soloist: it does not fight the instrument, it does not over-commit, it corrects when the instrument corrects. Watch a high-quality quadcopter recover from a kick, or an Atlas humanoid catch itself after a stumble, and you are watching nonlinear control at a level that was a research frontier five years ago.' },
        { type: 'h2', text: 'Control, meet learning' },
        { type: 'p', text: 'The most active frontier in 2026 is the marriage of classical control with reinforcement learning — training neural-network policies in simulation and transferring them to hardware. It works, dramatically, for tasks (quadruped locomotion, dexterous manipulation) where writing an analytical controller is brutal. It fails, also dramatically, when the simulator is not honest about what the real world will do. The working attitude: learn what you cannot easily derive; derive what you want to trust.' },
        { type: 'aside', label: 'Sim-to-real', text: 'A whole subfield has grown up around making a policy trained in simulation work when transferred to a real robot. The techniques — domain randomization, system identification, online adaptation — are still art more than science. Boston Dynamics, ETH Zurich, and a dozen startups have spent the 2020s quietly solving sub-problems that, a decade ago, would have been whole PhD theses.' },
        { type: 'h2', text: 'A practical path through the subject' },
        { type: 'p', text: 'For a working engineer in 2026: Steve Brunton\'s Control Bootcamp playlist on YouTube gets you intuition for classical and modern control, end to end, for free. Åström and Murray\'s Feedback Systems is the clean textbook companion. Tune a PID on a 3D-printer extruder, then on an inverted pendulum in simulation, then on a small quadruped. At each step you will learn more than a semester of lectures could teach. The subject rewards practice.' },
        { type: 'quote', text: 'A controller that works on paper and not on hardware has, in the end, taught you only what is wrong with your paper.', cite: 'control engineer\'s proverb' },
      ],

      keyTerms: ['feedback', 'setpoint', 'PID', 'state space', 'transfer function', 'stability', 'LQR', 'MPC', 'underactuation', 'observability'],

      examples: [
        {
          title: 'PID, computed by hand',
          problem: 'error = setpoint - measured\nintegral += error * dt\nderivative = (error - last_error) / dt\noutput = Kp*error + Ki*integral + Kd*derivative\nlast_error = error',
          steps: [
            { text: 'Error is setpoint minus actual — how far off we are.' },
            { text: 'Proportional term (Kp·error): respond in proportion to the current error. Like driving: if you are far from the centre, steer harder.' },
            { text: 'Integral term (Ki·integral): respond to accumulated past error. Cancels steady-state offsets, at the cost of slower response.' },
            { text: 'Derivative term (Kd·derivative): respond to the rate of change of error. Damps overshoot by anticipating where the error is heading.' },
            { text: 'Tuning the three gains by Ziegler-Nichols, auto-tune, or by hand is the skill a control engineer builds in their first year.' },
          ],
          answer: 'PID = respond now + respond to past + anticipate the future.',
        },
      ],

      practice: [
        { q: 'Which term in PID cancels steady-state offsets?',
          a: 'integral', acceptable: ['I', 'integral term', 'ki'],
          difficulty: 'medium', hint: 'It accumulates past error.',
          solution: 'The integral term. Ongoing bias accumulates in the integral until it produces enough control output to cancel the offset.' },
        { q: 'Who patented the first widely-deployed feedback controller, and in what year?',
          a: 'James Watt in 1788', acceptable: ['watt', '1788', 'watt 1788'],
          difficulty: 'hard', hint: 'He also gave us the steam engine.',
          solution: 'James Watt, 1788. The centrifugal governor.' },
        { q: 'Which technique is used for optimal control of a linear system with quadratic cost?',
          a: 'LQR', acceptable: ['linear quadratic regulator'],
          difficulty: 'medium', hint: 'Three letters.',
          solution: 'LQR — Linear Quadratic Regulator. Gives the optimal linear controller for a linear system with a quadratic cost function.' },
      ],

      subtopics: [
        {
          id: 'control.pid',
          name: 'PID — the 1922 algorithm that still runs the world',
          summary: 'Proportional, integral, derivative. Most controllers you will ever meet.',
          level: 'Advanced', readTime: '8 min',
          body: [
            { type: 'lead', text: 'Almost every thermostat, process controller, autopilot, and motor driver you have ever interacted with is PID. Nicolas Minorsky wrote it up in 1922 for US Navy ship autopilots and no one has replaced it because it does not need replacing.' },
            { type: 'p', text: 'The three constants: Kp (proportional gain), Ki (integral gain), Kd (derivative gain). Too much Kp: oscillation. Too much Ki: slow wind-up. Too much Kd: noise amplification. Tuning is the craft.' },
            { type: 'callout', text: 'Ziegler–Nichols method: crank Kp until the loop oscillates steadily, note the period, set the three gains by lookup. Used every day in industrial practice. Not optimal, but fast and good enough.' },
          ],
          practice: [
            { q: 'What happens if you set Kp too high in a PID loop?',
              a: 'oscillation', acceptable: ['oscillates', 'unstable', 'overshoot'],
              difficulty: 'medium', hint: 'The controller overreacts.',
              solution: 'Oscillation — the controller overreacts to small errors, overshoots, corrects, overshoots the other way.' },
          ],
          keyTerms: ['Kp', 'Ki', 'Kd', 'setpoint', 'steady-state error', 'overshoot', 'Ziegler-Nichols'],
        },
        {
          id: 'control.modern',
          name: 'Modern control — LQR, MPC',
          summary: 'What you reach for when PID is not enough.',
          level: 'Advanced', readTime: '9 min',
          body: [
            { type: 'lead', text: 'PID is a single-input single-output tool. When you have many sensors and many actuators coupled together (a quadcopter, a robot arm, a process plant), you want something that thinks in state-space vectors.' },
            { type: 'p', text: 'LQR (Linear Quadratic Regulator) gives the provably optimal linear controller for a linear system with quadratic costs. You give it a dynamics matrix, cost matrices; it gives you gains. Used in everything from rocket landings to legged locomotion.' },
            { type: 'p', text: 'MPC (Model Predictive Control) looks ahead. At each timestep, it simulates the system\'s likely future, picks the control action that optimizes a cost over the next N steps, applies the first action, then repeats. Handles constraints natively. The cost: you are re-solving an optimization problem every control cycle, 50-100 times a second.' },
          ],
          practice: [
            { q: 'Which modern control method can natively handle actuator constraints?',
              a: 'MPC', acceptable: ['model predictive control'],
              difficulty: 'hard', hint: 'It builds constraints into the optimization problem.',
              solution: 'MPC. Because it solves an optimization problem at each step, constraints (motor limits, joint angles, safety bounds) can be added directly.' },
          ],
          keyTerms: ['LQR', 'MPC', 'state space', 'Riccati equation', 'horizon', 'optimization'],
        },
      ],

      resources: {
        videos: [
          { id: 'Pi7l8mMjYVE', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=Pi7l8mMjYVE',
            title: 'Control Bootcamp: Overview',
            channel: 'Steve Brunton (University of Washington)', duration: '24:00',
            why: 'The opening lecture of Brunton\'s free Control Bootcamp playlist. The best self-paced control theory course on the internet.' },
          { id: '4Y7zG48uHRo', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=4Y7zG48uHRo',
            title: 'What is a PID Controller?',
            channel: 'MATLAB', duration: '5:29',
            why: 'A clean, short visual walkthrough of how the three terms work together.' },
          { id: 'Y6D4xrYmmcs', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=Y6D4xrYmmcs',
            title: 'Atlas | Partners in Parkour',
            channel: 'Boston Dynamics', duration: '0:58',
            why: 'A minute-long demonstration of what modern control, combined with planning and perception, can do.' },
          { id: 'XFZRolLXZbA', source: 'youtube', url: 'https://www.youtube.com/watch?v=XFZRolLXZbA',
            title: 'PID Tuning — a Working Method',
            channel: 'Brian Douglas (MATLAB Tech Talks)', duration: '13:11',
            why: 'The Ziegler–Nichols and manual-tuning methods, drawn on a whiteboard.' },
          { id: 'w5mENVTHD3g', source: 'youtube', url: 'https://www.youtube.com/watch?v=w5mENVTHD3g',
            title: 'Model Predictive Control',
            channel: 'Brian Douglas', duration: '15:14',
            why: 'The tool you reach for after PID. Brian Douglas is the patron saint of YouTube control theory.' },
          { id: 'vE3Vyr5lG3k', source: 'youtube', url: 'https://www.youtube.com/watch?v=vE3Vyr5lG3k',
            title: 'Underactuated Robotics — Introduction',
            channel: 'Russ Tedrake / MIT 6.832', duration: '1:20:00',
            why: 'The textbook\'s opening lecture, recorded and free. Watch it before the readings.' },
          { id: 'Kf9KjCKmDcU', source: 'youtube', url: 'https://www.youtube.com/watch?v=Kf9KjCKmDcU',
            title: 'ANYmal learns to walk in the mountains',
            channel: 'ETH Zurich / Robotic Systems Lab', duration: '2:15',
            why: 'Learned-controller locomotion on hardware. The 2022 milestone that changed expectations.' },
        ],
        books: [
          { title: 'Feedback Systems: An Introduction for Scientists and Engineers',
            author: 'Karl J. Åström and Richard M. Murray', year: 2020,
            url: 'http://fbswiki.org/wiki/index.php/Main_Page',
            why: 'A classic introductory textbook, free PDF from the authors.' },
          { title: 'Modern Control Engineering',
            author: 'Katsuhiko Ogata', year: 2010, url: '',
            why: 'The standard undergraduate textbook, fifth edition.' },
          { title: 'Underactuated Robotics: Algorithms for Walking, Running, Swimming, Flying, and Manipulation',
            author: 'Russ Tedrake', year: 2024,
            url: 'https://underactuated.mit.edu/',
            why: 'The free MIT course notes, actively maintained. The modern reference.' },
          { title: 'Applied Nonlinear Control',
            author: 'Jean-Jacques Slotine and Weiping Li', year: 1991, url: '',
            why: 'The classic text on nonlinear control. Dated in specifics, still read for the insight.' },
        ],
        articles: [
          { title: 'PID controller', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/PID_controller',
            why: 'An unusually good Wikipedia article. Clear math, good intuition, a whole section on tuning methods.' },
          { title: 'Control theory', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Control_theory',
            why: 'A broad, well-referenced map of the territory.' },
          { title: 'Cybernetics: or Control and Communication in the Animal and the Machine (excerpt)',
            source: 'Norbert Wiener, 1948',
            url: 'https://en.wikipedia.org/wiki/Cybernetics_(book)',
            why: 'Wikipedia\'s page on the book that named the field.' },
        ],
        courses: [
          { title: 'MIT 6.832 — Underactuated Robotics',
            provider: 'MIT OpenCourseWare',
            url: 'https://ocw.mit.edu/courses/6-832-underactuated-robotics-spring-2009/', free: true,
            why: 'Russ Tedrake\'s MIT course — lectures, problem sets, the textbook.' },
          { title: 'Control Bootcamp',
            provider: 'Steve Brunton (YouTube playlist)',
            url: 'https://www.youtube.com/playlist?list=PLMrJAkhIeNNR20Mz-VpzgfQs5zrYi085m', free: true,
            why: 'A 30+ episode free playlist. The fastest self-paced path to modern control theory.' },
        ],
        tools: [
          { title: 'Python Control Systems Library',
            url: 'https://python-control.readthedocs.io/',
            why: 'A Python package that implements most of the standard classical-control operations.' },
          { title: 'Drake',
            url: 'https://drake.mit.edu/',
            why: 'The open-source robotics toolbox from the Tedrake lab.' },
          { title: 'Simulink',
            url: 'https://www.mathworks.com/products/simulink.html',
            why: 'The industry-standard block-diagram control simulation tool. Dominant in automotive, aerospace, and process control in 2026.' },
        ],
        primarySources: [
          { title: 'Minorsky, "Directional Stability of Automatically Steered Bodies" (1922)',
            url: 'https://en.wikipedia.org/wiki/Nicolas_Minorsky',
            why: 'The Wikipedia article — the paper itself is hard to find online but it is the founding document of PID.' },
          { title: 'Bode, "Feedback — The History of an Idea" (1960)',
            url: 'https://www.rle.mit.edu/acoustics/bode.pdf',
            why: 'Hendrik Bode\'s first-person history of the development of feedback theory at Bell Labs.' },
        ],
        images: [
          { src: 'content/images/watt_governor.jpg',
            caption: 'Watt\'s centrifugal governor — the first feedback controller in widespread use.',
            credit: 'Maksym Kozlenko, Wikimedia Commons.' },
        ],
        animations: [
          { youtubeId: 'Pi7l8mMjYVE',
            title: 'Control Bootcamp: Overview',
            channel: 'Steve Brunton',
            why: 'The opening door to the whole subject.' },
          { youtubeId: 'Y6D4xrYmmcs',
            title: 'Atlas | Partners in Parkour',
            channel: 'Boston Dynamics',
            why: 'A minute of what modern control, in the best hands, looks like.' },
        ],
      },

      interactive: null,
      seeAlso: ['sensors', 'diffeq', 'physics'],
      prereqs: ['sensors', 'diffeq', 'linalg'],
      leadsTo: [],

      chapterActivity: 'A monthly controls meet-up at a Long Island City maker space — one participant brings a physical system, everyone tunes a PID on it by hand.',

      sources: [
        'https://en.wikipedia.org/wiki/PID_controller',
        'https://underactuated.mit.edu/',
        'https://ocw.mit.edu/courses/6-832-underactuated-robotics-spring-2009/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
