// content/security.js
// Owned by batch: B06-tech-and-code
// Last updated: 2026-04-23 by BATCH B06-tech-and-code
//
// Topics this subject covers (from data.js):
//   Core: passwords, threats

window.CONTENT = window.CONTENT || {};
window.CONTENT.security = {
  subjectId: 'security',
  version: 2,
  lastUpdated: '2026-04-23',
  curator: 'BATCH B06-tech-and-code',
  topics: {

    passwords: {
      id: 'passwords',
      name: 'Passwords & 2FA',
      level: 'Beginner',
      dek: 'The oldest authentication mechanism in computing — and the one most often done badly.',
      readTime: '13 min',

      sections: ['A 1961 invention', 'Why length beats complexity', 'The three factors', 'Password managers, the boring answer that works', 'Passkeys, the grown-up replacement', 'What to do this weekend'],
      body: [
        { type: 'lead', text: 'The computer password was invented by Fernando Corbató at MIT in 1961, when he split the shared IBM 7094 into private user accounts on what became the Compatible Time-Sharing System. The following year, a grad student named Allan Scherr printed the password file and used other people\'s time-shares to exceed his quota. The first password breach happened within months of the first password. Sixty-five years later, the particulars change and the basic lesson does not.' },
        { type: 'figure',
          src: 'content/images/enigma_machine.jpg',
          alt: 'An Enigma machine on display.',
          caption: 'Before passwords there were passphrases, code books, and cipher machines. The Enigma, above, was broken in 1940. A modern password defeated by the same kind of effort would be broken in seconds.',
          credit: 'Alessandro Nassiri, Wikimedia Commons.',
        },
        { type: 'h2', text: 'Length and entropy, not asterisks' },
        { type: 'p', text: 'For a long time, websites demanded mixed cases, numbers, and symbols — rules that pushed everyone to write P@ssw0rd1 on a sticky note. NIST dropped those rules from its 2017 Digital Identity Guidelines and most serious security teams have followed. The current guidance is simpler: favor length over composition, ban known-breached passwords, and never force arbitrary rotation. A long passphrase of common words, chosen randomly, is harder to crack than a nine-character mix of gibberish and far easier to type. The XKCD strip about correct-horse-battery-staple was right; NIST eventually agreed.' },
        { type: 'p', text: 'Underneath, the measure is entropy — roughly, the log of the number of possible passwords you could have chosen. A ten-character password chosen from printable ASCII has about 66 bits of entropy; a four-word passphrase from a 7,776-word dictionary has about 51. The second is slightly weaker mathematically but enormously harder to mistype, remember, or lock yourself out of. The UX wins.' },
        { type: 'h2', text: 'The three factors, and why two is the floor' },
        { type: 'p', text: 'Authentication uses some mixture of three things: something you know (a password), something you have (a phone, a hardware key), and something you are (a fingerprint, a face). Any one of them, used alone, is a single point of failure. Two-factor authentication — a password plus a second factor — is the largest reduction in practical risk most users can make in an evening. Among the second factors, a FIDO2 hardware key (YubiKey, Titan) is the strongest; a phone authenticator app is a clear second; SMS codes are a distant third, because phone numbers can be stolen through SIM-swap attacks that are now routine.' },
        { type: 'animation',
          youtubeId: '8ZtInClXe1Q',
          caption: 'Mike Pound, "How NOT to Store Passwords!" on Computerphile — plaintext, hashing, salting, bcrypt.',
          credit: 'Computerphile.',
        },
        { type: 'h2', text: 'Password managers, the boring answer that works' },
        { type: 'p', text: 'No one can remember a unique random twenty-character password for every site. The only honest answer is a password manager. A good manager generates long random passwords, fills them in automatically, and syncs across devices behind one strong master passphrase (and, ideally, a hardware-key second factor). The tradeoff — a single vault that is catastrophic if breached — is a good one for almost everyone, because the alternative is reuse and reuse is how most real compromises start.' },
        { type: 'p', text: 'The LastPass breach of 2022 — in which an attacker eventually got copies of customers\' encrypted vaults — is the canonical cautionary tale. The important takeaway is not that managers are unsafe (the vaults whose masters were strong have held up; the vaults whose masters were weak have been cracked) but that your master passphrase deserves the same care as a cryptographic key. Twenty characters, random, and a hardware-key second factor.' },
        { type: 'callout', text: 'The best password in the world is still catastrophic if you reuse it and one of the sites where you used it gets breached. A password manager turns reuse from a temptation into an inconvenience.' },
        { type: 'h2', text: 'Passkeys, the grown-up replacement' },
        { type: 'p', text: 'The next step is not a better password; it is no password. Passkeys, standardized by the FIDO Alliance and built on the WebAuthn protocol, replace a shared secret with a public-private key pair stored on your device. The server never sees anything that can be stolen and replayed. Apple, Google, and Microsoft have shipped passkey support across their operating systems through 2023–2025, and major sites are rolling out support. The transition will take years, but for new accounts in 2026 a passkey is the right default.' },
        { type: 'p', text: 'The experience of using a passkey, once you are over the unfamiliarity, is much better than a password. You touch a fingerprint sensor or Face-ID; the operating system finds the right key; you are in. There is no sharing, no typing, no breach exposure. The only serious hesitation — what happens if you lose all your devices at once — is answered by the cloud-sync providers (iCloud Keychain, Google Password Manager, 1Password) offering passkey recovery. The UX has finally grown up.' },
        { type: 'aside', label: 'The math behind a passkey', text: 'A passkey is a public-key keypair. When you register with a site, your device generates a new private key and sends only the public key to the server. When you log in, the server sends a challenge; your device signs it with the private key; the server verifies the signature with the public key it already has. Nothing shared, nothing reusable, nothing phishable. The same cryptography behind TLS now protects your login.' },
        { type: 'h2', text: 'What to do this weekend' },
        { type: 'p', text: 'Install a password manager. Let it generate a strong passphrase for your email. Use the manager to generate long random passwords for the ten accounts you use most. Turn on two-factor authentication on your email, bank, and any account that holds real money — hardware key if possible, authenticator app if not. Check Have I Been Pwned for addresses you use. If any account offers a passkey, set one up. You will have reduced your risk by more than any other forty-minute task in computing will.' },
      ],

      keyTerms: ['password', 'passphrase', 'entropy', 'two-factor authentication', 'hardware key', 'passkey', 'SIM swap', 'credential stuffing', 'bcrypt', 'salt'],

      examples: [
        {
          title: 'Entropy of a passphrase',
          problem: 'Four words, each picked randomly from a dictionary of 7,776 words. How much entropy?',
          steps: [
            { text: 'Each word is independently chosen from 7,776 options — that is 2^12.92, or about 12.9 bits of entropy per word.' },
            { text: 'Four independent words multiply: 4 × 12.9 ≈ 51.7 bits of entropy.' },
            { text: 'Compare to an 8-character random ASCII password: 8 × log₂(94) ≈ 52.4 bits. Roughly equivalent.' },
            { text: 'The passphrase has the same strength but is enormously easier to type, remember, and enter on a phone. This is why NIST now prefers length over composition rules.' },
          ],
          answer: '~52 bits of entropy — equivalent to an 8-char random ASCII password.',
        },
      ],

      practice: [
        { q: 'What is the single biggest risk-reduction step for most users in an evening?',
          a: 'enable two-factor authentication', acceptable: ['2fa', 'two-factor', 'turn on 2fa', 'mfa'],
          difficulty: 'easy', hint: 'Add a second factor on top of your password.',
          solution: 'Enable 2FA, preferably a hardware key, on email and banking first.' },
        { q: 'Which second factor is most resistant to phishing?',
          a: 'hardware key', acceptable: ['fido2', 'yubikey', 'security key', 'hardware security key'],
          difficulty: 'medium', hint: 'It signs only the real domain.',
          solution: 'A FIDO2 hardware key. It binds to the site\'s actual origin, so a phishing clone cannot use it.' },
        { q: 'True or false: NIST 2017 guidelines require quarterly password rotation for all users.',
          a: 'false', acceptable: ['f', 'no'],
          difficulty: 'medium', hint: 'NIST changed its mind on this.',
          solution: 'False. NIST explicitly recommends against arbitrary password rotation; it produces worse passwords, not safer ones.' },
      ],

      subtopics: [
        {
          id: 'passwords.entropy',
          name: 'Entropy and the end of composition rules',
          summary: 'Why length beats complexity, and why NIST changed its mind in 2017.',
          level: 'Beginner', readTime: '6 min',
          body: [
            { type: 'lead', text: 'The 2000s doctrine of "must contain uppercase, lowercase, number, symbol" came from a good intuition and a bad measurement. The good intuition: more character classes = more possibilities. The bad measurement: users respond to the rule by writing P@ssw0rd1, which has about as much entropy as a shoe.' },
            { type: 'p', text: 'NIST SP 800-63B (2017) dropped composition rules and rotation rules in favour of length minimums and breach-password blacklisting. The research supports both moves.' },
          ],
          practice: [
            { q: 'Which has more entropy: "Password123!" or "correct horse battery staple"?',
              a: 'correct horse battery staple', acceptable: ['the horse one', 'passphrase', 'second'],
              difficulty: 'easy', hint: 'The first is a cliché in password databases.',
              solution: 'The passphrase. "Password123!" is a well-known dictionary entry; four truly-random words have dramatically more entropy.' },
          ],
          keyTerms: ['entropy', 'bit', 'passphrase', 'breach blacklist', 'composition rule'],
        },
        {
          id: 'passwords.mfa',
          name: 'Multi-factor authentication',
          summary: 'Something you know + something you have + something you are. Two is the floor.',
          level: 'Beginner', readTime: '6 min',
          body: [
            { type: 'lead', text: 'A password is one factor. A phone is another. A fingerprint is a third. Modern authentication demands at least two — ideally from different categories — because losing one should not be catastrophic.' },
            { type: 'p', text: 'The ranking, in 2026: hardware keys (FIDO2) > authenticator apps (TOTP) > push notifications > SMS. SMS is the worst because SIM swaps are now commoditized — the number can be stolen in an hour by anyone with a bribe to a mobile-store employee.' },
          ],
          practice: [
            { q: 'Why is SMS the weakest second factor?',
              a: 'sim swap', acceptable: ['sim-swap', 'sim swapping', 'phone number can be stolen'],
              difficulty: 'medium', hint: 'The phone number can be transferred.',
              solution: 'SIM swapping. An attacker convinces your carrier to move your phone number to their SIM, then receives your SMS codes.' },
          ],
          keyTerms: ['2FA', 'MFA', 'TOTP', 'FIDO2', 'SMS', 'SIM swap'],
        },
        {
          id: 'passwords.passkeys',
          name: 'Passkeys — the replacement',
          summary: 'Public-key authentication instead of shared secrets. The end game.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'A passkey replaces "here is a secret you and I both know" with "here is a signature only I can produce." The server never holds anything that can be stolen and replayed. Phishing becomes nearly impossible, because the key refuses to sign for the wrong domain.' },
            { type: 'p', text: 'Apple, Google, and Microsoft shipped passkey sync through their OS password managers in 2023–2025. A new account in 2026 should prefer passkeys; an old account should add one alongside its password as a second factor.' },
          ],
          practice: [
            { q: 'What does a passkey replace with a keypair?',
              a: 'password', difficulty: 'easy',
              hint: 'The shared secret.',
              solution: 'The password — a shared secret — is replaced with a private key only the user has, and a public key the server keeps.' },
          ],
          keyTerms: ['passkey', 'WebAuthn', 'FIDO2', 'public key', 'challenge-response'],
        },
      ],

      resources: {
        videos: [
          { id: '8ZtInClXe1Q', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=8ZtInClXe1Q',
            title: 'How NOT to Store Passwords!',
            channel: 'Computerphile', duration: '9:24',
            why: 'Mike Pound walks through plaintext, hashing, salting, and bcrypt. Ten minutes on what the server is doing with your password, and why it matters.' },
          { id: '7U-RbOKanYs', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=7U-RbOKanYs',
            title: 'Password Cracking — Computerphile',
            channel: 'Computerphile', duration: '20:20',
            why: 'The adversary\'s view — how hashcat and rockyou.txt actually work on a gaming GPU. Seeing this changes how you think about your own passwords.' },
          { id: 'VFns39RXPrU', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=VFns39RXPrU',
            title: 'Hacking Into the Bank — The Social Engineering Story',
            channel: 'Veritasium', duration: '30:02',
            why: 'A professional penetration tester demonstrates how a human-shaped attack beats any password policy.' },
          { id: 'qGO9Tn6BZu0', source: 'youtube', url: 'https://www.youtube.com/watch?v=qGO9Tn6BZu0',
            title: 'Multi-Factor Authentication',
            channel: 'IBM Technology', duration: '6:21',
            why: 'A clean current primer on why two factors is the floor, not the ceiling.' },
          { id: '2hK-U3l_JXo', source: 'youtube', url: 'https://www.youtube.com/watch?v=2hK-U3l_JXo',
            title: 'What Are Passkeys?',
            channel: 'Google', duration: '2:11',
            why: 'Google\'s short explainer. A good overview before you commit to one.' },
          { id: 'IivuPHvR10Y', source: 'youtube', url: 'https://www.youtube.com/watch?v=IivuPHvR10Y',
            title: 'YubiKey 5 FIDO2 — How It Actually Works',
            channel: 'Yubico', duration: '7:00',
            why: 'A walkthrough of the hardware token that defeats phishing. Educational even if you are not buying.' },
        ],
        books: [
          { title: 'Secrets and Lies: Digital Security in a Networked World',
            author: 'Bruce Schneier', year: 2000,
            url: 'https://www.schneier.com/books/secrets-and-lies/',
            why: 'The book that taught a generation of engineers to think systemically about security — that the weakest link is almost never the cipher.' },
          { title: 'The Art of Deception',
            author: 'Kevin Mitnick', year: 2002, url: '',
            why: 'Social engineering, by the person who was, for a while, the FBI\'s most-wanted hacker.' },
          { title: 'Click Here to Kill Everybody',
            author: 'Bruce Schneier', year: 2018, url: '',
            why: 'The modern follow-up. Passwords and 2FA in the context of a world where the things being authenticated include pacemakers and cars.' },
          { title: 'Permanent Record',
            author: 'Edward Snowden', year: 2019, url: '',
            why: 'A memoir that doubles as a practical argument for taking operational security seriously.' },
        ],
        articles: [
          { title: 'NIST SP 800-63B — Digital Identity Guidelines (HTML)',
            source: 'NIST',
            url: 'https://pages.nist.gov/800-63-3/sp800-63b.html',
            why: 'The authoritative US government guidance on password policy.', year: 2017 },
          { title: 'Password strength', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Password_strength',
            why: 'Good treatment of entropy calculations and why modern dictionary attacks work.' },
          { title: 'About passkeys',
            source: 'FIDO Alliance', url: 'https://fidoalliance.org/passkeys/',
            why: 'The standards body\'s explainer. The place to understand what a passkey actually is before following a vendor\'s version.' },
          { title: 'Password Requirements — The Sensible Rules',
            source: 'Troy Hunt', url: 'https://www.troyhunt.com/passwords-evolved-authentication-guidance-for-the-modern-era/',
            why: 'Troy Hunt\'s long-form post aligning the NIST guidance with real-world product decisions.' },
        ],
        courses: [
          { title: 'Web Security Academy — Authentication',
            provider: 'PortSwigger',
            url: 'https://portswigger.net/web-security/authentication', free: true,
            why: 'Free, hands-on labs on authentication flaws. The best way to learn how password systems fail is to break a few, safely, in a sandbox.' },
        ],
        tools: [
          { title: 'Have I Been Pwned', url: 'https://haveibeenpwned.com/',
            why: 'Troy Hunt\'s free service. Type an email address; find out which of the 700+ known breaches have leaked your credentials.' },
          { title: 'Bitwarden', url: 'https://bitwarden.com',
            why: 'A free, open-source, audited password manager. The boring right answer in 2026 for individuals and small teams.' },
          { title: '1Password', url: 'https://1password.com',
            why: 'The widely-used commercial alternative, with strong family and team plans and audited cryptography.' },
          { title: 'YubiKey', url: 'https://www.yubico.com',
            why: 'The hardware key most organizations standardize on. Phishing-proof by construction.' },
        ],
        primarySources: [
          { title: 'Corbató, "A Time-Sharing System" (1962)',
            url: 'https://multicians.org/thvv/6094.html',
            why: 'The Multicians archive of the original CTSS material — the system where the password was invented.' },
          { title: 'FIDO2 / WebAuthn specification',
            url: 'https://www.w3.org/TR/webauthn-2/',
            why: 'The W3C recommendation that defines passkeys. Technical, current, essential for anyone implementing them.' },
        ],
        images: [],
        animations: [
          { youtubeId: '8ZtInClXe1Q',
            title: 'How NOT to Store Passwords',
            channel: 'Computerphile',
            why: 'The hashing-and-salting explanation that finally makes it click.' },
        ],
      },

      interactive: null,
      seeAlso: ['threats', 'crypto', 'networks'],
      prereqs: [],
      leadsTo: ['threats'],

      chapterActivity: 'A quarterly "password hygiene" clinic at a Queens public library — bring a laptop, set up a password manager, enroll a hardware key, leave with a passkey.',

      sources: [
        'https://pages.nist.gov/800-63-3/sp800-63b.html',
        'https://fidoalliance.org/passkeys/',
        'https://haveibeenpwned.com/',
      ],
      verifiedAt: '2026-04-23',
    },

    threats: {
      id: 'threats',
      name: 'Common Threats',
      level: 'Intermediate',
      dek: 'The short list of attacks that account for most of what actually goes wrong — and the threat-modeling habit that catches them.',
      readTime: '14 min',

      sections: ['The attacker is bored', 'Phishing, still #1', 'Malware in the modern era', 'Ransomware as a business', 'Thinking in threat models', 'What actually works'],
      body: [
        { type: 'lead', text: 'Every year, Verizon publishes a Data Breach Investigations Report — the most widely-cited empirical survey of how real organizations actually get compromised. The 2025 edition, like every edition before it, puts the same two culprits at the top of the list: humans tricked into giving up credentials, and long-unpatched software. The spectacular zero-day exploits in the press are a small share of the total. The mundane categories are where the damage lives.' },
        { type: 'h2', text: 'Attackers are patient, not magical' },
        { type: 'p', text: 'The mental image of hacking is a hooded person typing quickly. The real pattern is far less dramatic: reconnaissance, phishing, a foothold on one laptop, lateral movement, escalation, and eventually ransomware or data theft. Lockheed Martin called this the "kill chain" in 2011, and the MITRE ATT&CK framework has since catalogued every documented step at every stage. Reading ATT&CK is the closest thing a new practitioner has to an encyclopedia of what is actually being done.' },
        { type: 'h2', text: 'Phishing is a design problem' },
        { type: 'p', text: 'Most breaches still begin with an email. A message arrives that looks like the right sender, with a link that looks like the right domain, leading to a page that looks like the right login. The user types their password. Defences are layered: DMARC on the mail server, URL rewriting at the gateway, a second factor at the login, user training for the gap. Hardware-key second factors are the only countermeasure that meaningfully defeats a well-crafted phishing site, because the key signs only the real domain and refuses the lookalike.' },
        { type: 'animation',
          youtubeId: 'Ju7yE8WyRXI',
          caption: 'IBM Technology on modern phishing — spear, whaling, smishing, quishing.',
          credit: 'IBM Technology, YouTube.',
        },
        { type: 'h2', text: 'Malware, and the economy behind it' },
        { type: 'p', text: 'Modern malware is not a lone teenager\'s project. Ransomware-as-a-service lets criminal affiliates rent the tooling and take a cut of the payout; initial-access brokers sell footholds; cryptocurrency makes the final payment plausible. Kim Zetter\'s Countdown to Zero Day (2014) remains the best long-form account of the escalation — the Stuxnet attack on Iran\'s centrifuges marked the moment nation-state malware became public knowledge. The lesson for a working developer is not to write antivirus code, but to assume the host is compromised and design accordingly.' },
        { type: 'h2', text: 'Ransomware as a business' },
        { type: 'p', text: 'From roughly 2017 onward, ransomware has been the single most impactful category of cybercrime by dollar volume. Colonial Pipeline in 2021 shut down the US eastern seaboard\'s gasoline supply for days. The UK NHS WannaCry outbreak in 2017 postponed surgeries. Chainalysis estimates global ransomware payments topped $1 billion in 2024. The crime works because the payoff is large, the risk of prosecution is small (the operators are typically in jurisdictions that will not extradite), and most victims have not tested their backups recently enough to know if they can refuse.' },
        { type: 'p', text: 'The defensive lessons are old and dull: maintained offline backups, tested restores, least-privilege network segmentation, endpoint monitoring, a retainer with a DFIR firm before you need one. None of them scale the way everyone wishes they did. All of them work.' },
        { type: 'callout', text: 'A 2025 rule of thumb: if your system relies on users noticing a suspicious email, you have a system that will fail. Build as if a motivated attacker has already reached the login page.' },
        { type: 'h2', text: 'Threat modeling is the habit that catches the rest' },
        { type: 'p', text: 'The most durable security skill is the question: what are we protecting, from whom, under what assumptions? Adam Shostack\'s four questions — what are we working on, what can go wrong, what are we going to do about it, did we do a good job — organize a practice that does not need a specialist. Threat models are cheapest at the whiteboard stage of a design and most expensive at the post-mortem stage of an incident. Make them a habit at the first.' },
        { type: 'aside', label: 'STRIDE', text: 'Microsoft\'s STRIDE framework — spoofing, tampering, repudiation, information disclosure, denial of service, elevation of privilege — is the oldest and still most-used threat-model taxonomy. Walk through each of the six for any new feature. Most of the real threats will show up in one of the first three.' },
        { type: 'h2', text: 'What actually works' },
        { type: 'p', text: 'The security controls that pay off disproportionately: hardware-key 2FA on every identity, a password manager, automatic operating-system updates, browser-based isolation for high-risk work, backups you have actually restored once, and the NIST Cybersecurity Framework as a scaffolding for the first year of any serious program. Everything else — the acronyms, the vendors, the annual RSA keynotes — is a detail. Most organizations that get compromised do so because they skipped one of the first three.' },
      ],

      keyTerms: ['phishing', 'ransomware', 'malware', 'social engineering', 'zero-day', 'threat model', 'kill chain', 'lateral movement', 'MFA bypass', 'STRIDE'],

      examples: [
        {
          title: 'Spot the phishing email',
          problem: 'From: security@paypa1.com — Subject: Your account will be locked — Body: "Click here to verify your identity within 24 hours."',
          steps: [
            { text: 'Sender address: paypa1.com (digit 1, not letter l). Real PayPal is paypal.com. Misleading domain is a classic phishing tell.' },
            { text: 'Urgency ("24 hours") is standard social-engineering pressure — meant to bypass careful thinking.' },
            { text: 'Link in the email, not a URL you typed. Hover to reveal the real destination — usually some unrelated domain.' },
            { text: 'What to do: type paypal.com manually into the browser. If there is a real issue, it will be visible when you log in.' },
          ],
          answer: 'Classic phishing — misspelled domain, urgency, embedded link.',
        },
      ],

      practice: [
        { q: 'What framework catalogues adversary tactics and techniques from real incidents?',
          a: 'MITRE ATT&CK', acceptable: ['att&ck', 'attack', 'mitre', 'mitre attack'],
          difficulty: 'medium', hint: 'Maintained by a non-profit research corporation.',
          solution: 'MITRE ATT&CK — a free, actively-maintained matrix of what adversaries actually do at each stage of an intrusion.' },
        { q: 'What does DMARC verify?',
          a: 'email authenticity', acceptable: ['sender authenticity', 'email sender', 'sender domain'],
          difficulty: 'hard', hint: 'Defence against spoofed email senders.',
          solution: 'DMARC (Domain-based Message Authentication, Reporting, and Conformance) verifies that an email claiming to be from your domain actually came from an authorized sender.' },
        { q: 'Why do ransomware operators prefer cryptocurrency for payments?',
          a: 'hard to trace', acceptable: ['anonymous', 'pseudonymous', 'traceability', 'difficult to trace'],
          difficulty: 'medium', hint: 'Not about convenience.',
          solution: 'Harder to trace and harder to reverse than wire transfers. Most ransomware business models were economically marginal before Bitcoin.' },
      ],

      subtopics: [
        {
          id: 'threats.phishing',
          name: 'Phishing, still #1',
          summary: 'Most breaches still begin with an email. Layered defences, hardware-key second factors.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'Verizon\'s DBIR keeps confirming what every working security team already knows: most breaches start with someone typing a password into a page that looked like the real thing. The technology to stop this is 2020s-mature (hardware keys, DMARC, URL rewriting, passkeys). The operational challenge is getting organizations to deploy it.' },
            { type: 'p', text: 'The only second factor that robustly defeats phishing is a hardware key. Authenticator codes, SMS, and push notifications can all be intercepted or relayed. A FIDO2 key binds to the real domain and refuses the lookalike.' },
          ],
          practice: [
            { q: 'Why does a FIDO2 hardware key prevent phishing?',
              a: 'binds to the real domain', acceptable: ['domain binding', 'signs only real origin', 'origin binding', 'real domain'],
              difficulty: 'medium', hint: 'Origin-binding.',
              solution: 'The key signs only for the real origin (domain). A phishing clone has a different origin, and the key refuses.' },
          ],
          keyTerms: ['phishing', 'DMARC', 'SPF', 'DKIM', 'FIDO2', 'origin binding', 'MFA bypass'],
        },
        {
          id: 'threats.ransomware',
          name: 'Ransomware as a business',
          summary: 'Crime-as-a-service, cryptocurrency, and why backups are the answer.',
          level: 'Intermediate', readTime: '7 min',
          body: [
            { type: 'lead', text: 'Modern ransomware is an industry with affiliates, access brokers, and cryptocurrency payment rails. The only reliable defence is assume-breach: segment your network, maintain offline backups, test your restore procedure, and have a DFIR retainer ready before you need it.' },
            { type: 'p', text: 'The 2021 Colonial Pipeline incident and the 2017 NotPetya catastrophe both teach the same lesson: the damage is in the downtime, not the ransom. The best-prepared organizations pay nothing because their backups work.' },
          ],
          practice: [
            { q: 'What single non-technical control would prevent most ransomware damage?',
              a: 'tested offline backups', acceptable: ['offline backups', 'backups', 'tested backups'],
              difficulty: 'easy', hint: 'Something you restore from.',
              solution: 'Offline backups that are actually tested by doing a restore drill. An untested backup is a wish.' },
          ],
          keyTerms: ['ransomware', 'initial access', 'lateral movement', 'DFIR', 'backup', 'segmentation'],
        },
        {
          id: 'threats.threat_modeling',
          name: 'Threat modeling — the habit',
          summary: 'Four questions you can ask at any whiteboard.',
          level: 'Intermediate', readTime: '6 min',
          body: [
            { type: 'lead', text: 'Adam Shostack\'s four questions: What are we working on? What can go wrong? What are we going to do about it? Did we do a good job? They do not require a specialist. They are much cheaper at the whiteboard stage than at the post-mortem stage.' },
            { type: 'p', text: 'STRIDE — spoofing, tampering, repudiation, information disclosure, denial of service, elevation of privilege — is the classic taxonomy to walk through as you ask "what can go wrong."' },
          ],
          practice: [
            { q: 'What does the "S" in STRIDE stand for?',
              a: 'spoofing', difficulty: 'easy',
              hint: 'Pretending to be someone else.',
              solution: 'Spoofing — an attacker pretending to be a legitimate user, server, or process.' },
          ],
          keyTerms: ['STRIDE', 'threat model', 'asset', 'mitigation', 'risk'],
        },
      ],

      resources: {
        videos: [
          { id: 'Ju7yE8WyRXI', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=Ju7yE8WyRXI',
            title: 'Phishing Explained In 6 Minutes',
            channel: 'IBM Technology', duration: '6:23',
            why: 'A clean, current rundown of modern phishing variants — spear, whaling, smishing, quishing.' },
          { id: '4gR562GW7TI', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=4gR562GW7TI',
            title: 'What is Malware? — Computerphile',
            channel: 'Computerphile', duration: '10:42',
            why: 'The taxonomy — viruses, worms, trojans, ransomware — explained clearly enough for a non-specialist to follow.' },
          { id: 'MXDAJuRlbK8', featured: true, source: 'youtube', url: 'https://www.youtube.com/watch?v=MXDAJuRlbK8',
            title: 'Ransomware — Computerphile',
            channel: 'Computerphile', duration: '16:03',
            why: 'Why ransomware works: the combination of asymmetric cryptography, cryptocurrency, and the fact that backups are often bad.' },
          { id: 'nG_-00q0AzY', source: 'youtube', url: 'https://www.youtube.com/watch?v=nG_-00q0AzY',
            title: 'MITRE ATT&CK Framework Explained',
            channel: 'SANS Institute', duration: '15:00',
            why: 'The encyclopedia of attack techniques, walked through by SANS.' },
          { id: 'GxNCHYsdEPQ', source: 'youtube', url: 'https://www.youtube.com/watch?v=GxNCHYsdEPQ',
            title: 'Stuxnet — Countdown to Zero Day',
            channel: 'Scott Manley', duration: '21:46',
            why: 'A clear narrative of the Stuxnet attack on Iran\'s centrifuges — the moment nation-state malware went public.' },
          { id: 'lkiwiwRlbDA', source: 'youtube', url: 'https://www.youtube.com/watch?v=lkiwiwRlbDA',
            title: 'The Social-Engineer Toolkit Demo',
            channel: 'LiveOverflow', duration: '18:17',
            why: 'A careful demonstration of how an attack is actually structured. Use it to understand defences.' },
          { id: 'mJfCbIkDNuE', source: 'youtube', url: 'https://www.youtube.com/watch?v=mJfCbIkDNuE',
            title: 'How the NotPetya Attack Happened',
            channel: 'CyberNews', duration: '11:00',
            why: 'The most destructive cyberattack on record, told as a case study.' },
        ],
        books: [
          { title: 'Countdown to Zero Day',
            author: 'Kim Zetter', year: 2014, url: '',
            why: 'The deep history of the Stuxnet attack on Iran\'s nuclear program. The defining long-form account of nation-state malware.' },
          { title: 'Threat Modeling: Designing for Security',
            author: 'Adam Shostack', year: 2014, url: '',
            why: 'The standard reference. The STRIDE framework originated here.' },
          { title: 'Sandworm',
            author: 'Andy Greenberg', year: 2019, url: '',
            why: 'A journalistic history of the Russian military unit behind NotPetya, the most destructive cyberattack on record.' },
          { title: 'The Cuckoo\'s Egg',
            author: 'Cliff Stoll', year: 1989, url: '',
            why: 'The 1989 memoir that invented the modern genre — a Berkeley astronomer catches a KGB hacker by noticing a 75-cent accounting error.' },
        ],
        articles: [
          { title: 'Verizon Data Breach Investigations Report',
            source: 'Verizon',
            url: 'https://www.verizon.com/business/resources/reports/dbir/',
            why: 'The most widely-cited annual empirical survey of real-world breaches.', year: 2025 },
          { title: 'MITRE ATT&CK',
            source: 'MITRE Corporation', url: 'https://attack.mitre.org/',
            why: 'A free, actively-maintained matrix of adversary tactics and techniques, compiled from real incidents.' },
          { title: 'OWASP Top 10',
            source: 'OWASP', url: 'https://owasp.org/www-project-top-ten/',
            why: 'The standard awareness document for web application security risks. The 2025 list is current as of this writing.', year: 2025 },
          { title: 'Phishing', source: 'Wikipedia',
            url: 'https://en.wikipedia.org/wiki/Phishing',
            why: 'A broad, well-referenced overview of the single most common attack category.' },
          { title: 'Krebs on Security',
            source: 'Brian Krebs', url: 'https://krebsonsecurity.com',
            why: 'The single most respected long-running security blog. Reads like a trade paper for the industry.' },
        ],
        courses: [
          { title: 'PortSwigger Web Security Academy',
            provider: 'PortSwigger', url: 'https://portswigger.net/web-security', free: true,
            why: 'The free, industry-standard training on web application attacks.' },
          { title: 'Cybersecurity Fundamentals',
            provider: 'The Open University (OpenLearn)',
            url: 'https://www.open.edu/openlearn/digital-computing/introduction-cyber-security-stay-safe-online/content-section-overview-0', free: true,
            why: 'A free non-specialist overview from the Open University.' },
        ],
        tools: [
          { title: 'Have I Been Pwned', url: 'https://haveibeenpwned.com/',
            why: 'Free, reputable breach notification service.' },
          { title: 'VirusTotal', url: 'https://www.virustotal.com/',
            why: 'Upload a file or URL; get a verdict from dozens of antivirus engines at once. Owned by Google, free for non-commercial use.' },
          { title: 'Shodan', url: 'https://www.shodan.io',
            why: 'A search engine for internet-connected devices. Sobering to run against your own IP.' },
        ],
        primarySources: [
          { title: 'NIST Cybersecurity Framework',
            url: 'https://www.nist.gov/cyberframework',
            why: 'The reference control scaffolding most organizations use as the backbone of their program.' },
        ],
        images: [],
        animations: [
          { youtubeId: 'Ju7yE8WyRXI',
            title: 'Phishing Explained in 6 Minutes',
            channel: 'IBM Technology',
            why: 'Current taxonomy, short and clear.' },
          { youtubeId: 'MXDAJuRlbK8',
            title: 'Ransomware — Computerphile',
            channel: 'Computerphile',
            why: 'The mechanics that make ransomware work.' },
        ],
      },

      interactive: null,
      seeAlso: ['passwords', 'crypto', 'networks'],
      prereqs: ['passwords'],
      leadsTo: [],

      chapterActivity: 'A monthly security book club at a Manhattan library — one book a quarter (Zetter, Greenberg, Shostack), one news story per month, whiteboards out.',

      sources: [
        'https://www.verizon.com/business/resources/reports/dbir/',
        'https://attack.mitre.org/',
        'https://owasp.org/www-project-top-ten/',
      ],
      verifiedAt: '2026-04-23',
    },

  },
};
